#
#
obj-$(CONFIG_MACH_TTC_DKB) += lcd_tpo.o lcd_truly.o lcd_sharp.o
obj-$(CONFIG_UIO_HDMI) += lcd_hdmi.o
obj-$(CONFIG_MACH_YELLOWSTONE) += lcd_mipi.o
obj-$(CONFIG_MACH_EMEIDKB) += lcd_mipi.o
obj-$(CONFIG_MACH_ARUBA_TD) += lcd_hx8369_mipi.o
obj-$(CONFIG_MACH_WARUBA) += lcd_hx8369_mipi.o
obj-$(CONFIG_MACH_HELANDKB) += lcd_mipi.o
obj-$(CONFIG_MACH_HELANDELOS) += lcd_hx8369_mipi.o
obj-$(CONFIG_MACH_EDEN_FPGA) += lcd_mipi.o
obj-$(CONFIG_MACH_HARRISON) += lcd_tc35876x_boeot_wsvga_mipi.o
obj-$(CONFIG_MACH_LT02) += lcd_tc35876x_boeot_wsvga_mipi.o
obj-$(CONFIG_MACH_WILCOX) += board-wilcox-display.o lcd_hx8389b_mipi.o lcd_s6d78a0x_mipi.o
obj-$(CONFIG_MACH_DEGAS) += board-degas-display.o lcd_s6d7aa0x_mipi.o
obj-$(CONFIG_MACH_CS05) += board-cs05-display.o Lcd_mipi2rgb_vx6b3e.o
obj-$(CONFIG_MACH_CS02) += lcd_hx8369_mipi.o
obj-$(CONFIG_MACH_BAFFIN) += lcd_hx8369_mipi.o
obj-$(CONFIG_MACH_BAFFINQ) += lcd_mipi_generic.o board-baffinq-display.o
obj-$(CONFIG_MACH_GOLDEN) += board-golden-display.o lcd_s6e63m0.o lcd_s6e63m0_smart.o
obj-$(CONFIG_MACH_GOYA) += board-goya-display.o Lcd_mipi2lvds_vx5b3d.o
obj-$(CONFIG_LCD_ESD_RECOVERY) +=  esd_detect.o
