# Path of Qcom Device tree
QCOM_DTB := ../../qcom

dtbo-$(CONFIG_SEC_WINNERLTE_PROJECT) = sm8150-sec-winnerlte-overlay-r04.dtbo	\
					sm8150-sec-winnerlte-overlay-r06.dtbo	\
					sm8150-sec-winnerlte-overlay-r08.dtbo	\
					sm8150-sec-winnerlte-overlay-r09.dtbo   \
					sm8150-sec-winnerlte-overlay-r11.dtbo   \
					sm8150-sec-winnerlte-overlay-r12.dtbo	\
					sm8150-sec-winnerlte-overlay-r15.dtbo
dtbo-$(CONFIG_SEC_WINNERX_PROJECT) = sm8150-sec-winnerx-overlay-r00.dtbo	\
					sm8150-sec-winnerx-overlay-r01.dtbo	\
					sm8150-sec-winnerx-overlay-r02.dtbo	\
					sm8150-sec-winnerx-overlay-r03.dtbo	\
					sm8150-sec-winnerx-overlay-r04.dtbo	\
					sm8150-sec-winnerx-overlay-r05.dtbo	\
					sm8150-sec-winnerx-overlay-r06.dtbo	\
					sm8150-sec-winnerx-overlay-r07.dtbo

dtbo-$(CONFIG_MACH_WINNERX_KOR_SINGLE) = sm8150-sec-winnerx-kor-overlay-r00.dtbo \
	sm8150-sec-winnerx-kor-overlay-r01.dtbo \
	sm8150-sec-winnerx-kor-overlay-r02.dtbo \
	sm8150-sec-winnerx-kor-overlay-r03.dtbo \
	sm8150-sec-winnerx-kor-overlay-r04.dtbo \
	sm8150-sec-winnerx-kor-overlay-r05.dtbo

sm8150-sec-winnerlte-overlay-r04.dtbo-base := $(QCOM_DTB)/sm8150.dtb $(QCOM_DTB)/sm8150-v2.dtb
sm8150-sec-winnerlte-overlay-r06.dtbo-base := $(QCOM_DTB)/sm8150.dtb $(QCOM_DTB)/sm8150-v2.dtb
sm8150-sec-winnerlte-overlay-r08.dtbo-base := $(QCOM_DTB)/sm8150.dtb $(QCOM_DTB)/sm8150-v2.dtb
sm8150-sec-winnerlte-overlay-r09.dtbo-base := $(QCOM_DTB)/sm8150.dtb $(QCOM_DTB)/sm8150-v2.dtb
sm8150-sec-winnerlte-overlay-r11.dtbo-base := $(QCOM_DTB)/sm8150.dtb $(QCOM_DTB)/sm8150-v2.dtb
sm8150-sec-winnerlte-overlay-r12.dtbo-base := $(QCOM_DTB)/sm8150.dtb $(QCOM_DTB)/sm8150-v2.dtb
sm8150-sec-winnerlte-overlay-r15.dtbo-base := $(QCOM_DTB)/sm8150.dtb $(QCOM_DTB)/sm8150-v2.dtb
sm8150-sec-winnerx-overlay-r00.dtbo-base := $(QCOM_DTB)/sm8150.dtb $(QCOM_DTB)/sm8150-v2.dtb
sm8150-sec-winnerx-overlay-r01.dtbo-base := $(QCOM_DTB)/sm8150.dtb $(QCOM_DTB)/sm8150-v2.dtb
sm8150-sec-winnerx-overlay-r02.dtbo-base := $(QCOM_DTB)/sm8150.dtb $(QCOM_DTB)/sm8150-v2.dtb
sm8150-sec-winnerx-overlay-r03.dtbo-base := $(QCOM_DTB)/sm8150.dtb $(QCOM_DTB)/sm8150-v2.dtb
sm8150-sec-winnerx-overlay-r04.dtbo-base := $(QCOM_DTB)/sm8150.dtb $(QCOM_DTB)/sm8150-v2.dtb
sm8150-sec-winnerx-overlay-r05.dtbo-base := $(QCOM_DTB)/sm8150.dtb $(QCOM_DTB)/sm8150-v2.dtb
sm8150-sec-winnerx-overlay-r06.dtbo-base := $(QCOM_DTB)/sm8150.dtb $(QCOM_DTB)/sm8150-v2.dtb
sm8150-sec-winnerx-overlay-r07.dtbo-base := $(QCOM_DTB)/sm8150.dtb $(QCOM_DTB)/sm8150-v2.dtb
sm8150-sec-winnerx-kor-overlay-r00.dtbo-base := $(QCOM_DTB)/sm8150.dtb $(QCOM_DTB)/sm8150-v2.dtb
sm8150-sec-winnerx-kor-overlay-r01.dtbo-base := $(QCOM_DTB)/sm8150.dtb $(QCOM_DTB)/sm8150-v2.dtb
sm8150-sec-winnerx-kor-overlay-r02.dtbo-base := $(QCOM_DTB)/sm8150.dtb $(QCOM_DTB)/sm8150-v2.dtb
sm8150-sec-winnerx-kor-overlay-r03.dtbo-base := $(QCOM_DTB)/sm8150.dtb $(QCOM_DTB)/sm8150-v2.dtb
sm8150-sec-winnerx-kor-overlay-r04.dtbo-base := $(QCOM_DTB)/sm8150.dtb $(QCOM_DTB)/sm8150-v2.dtb
sm8150-sec-winnerx-kor-overlay-r05.dtbo-base := $(QCOM_DTB)/sm8150.dtb $(QCOM_DTB)/sm8150-v2.dtb

always      := $(dtbo-y)       
subdir-y    := $(dts-dirs)    
clean-files := *.dtbo 
