# When adding new entries keep the list in alphabetical order

obj-$(CONFIG_SEC_BSP) += sec_bsp.o sec_smem.o sec_hw_param.o
obj-$(CONFIG_SEC_DEBUG) += sec_debug.o sec_gaf.o sec_getlog.o
obj-$(CONFIG_SEC_DEBUG_DOUBLE_FREE) += sec_debug-dfd.o
obj-$(CONFIG_SEC_DEBUG_SUMMARY) += sec_debug_summary.o

