
ifeq ($(CONFIG_MACH_VIVALTO),y)
obj-y += flash_vivalto.o
else ifeq ($(CONFIG_MACH_KANAS_W),y)
obj-y += flash_kanas_w.o
else ifeq ($(CONFIG_MACH_SP8730SEA),y)
obj-y += flash_sgm3140.o
else ifeq ($(CONFIG_MACH_SP9836AEA_4MOD),y)
obj-y += flash_parallel_connect_bg.o
else ifeq ($(CONFIG_MACH_SP9838AEA_5MOD),y)
obj-y += flash_gpio.o
else ifeq ($(CONFIG_MACH_SP9838AEA_POWER_DEBUG),y)
obj-y += flash_gpio.o
else ifeq ($(CONFIG_MACH_SP9838AEA_8CORE_LIGHT_SLEEP),y)
obj-y += flash_gpio.o
else ifeq ($(CONFIG_MACH_SP9838AEA_FHD),y)
obj-y += flash_gpio.o
else ifeq ($(CONFIG_MACH_SP9630EA4MN),y)
obj-y += flash_parallel_connect_bg.o
else ifeq ($(CONFIG_MACH_SP9836AEA_3MOD), y)
obj-y += flash_parallel_connect_bg.o
else ifeq ($(CONFIG_MACH_SP9830AEA_5M_H100), y)
obj-y += flash_parallel_connect_bg.o
else ifeq ($(CONFIG_MACH_SP9830IEB_5M_H100), y)
obj-y += flash_parallel_connect_bg.o
else ifeq ($(CONFIG_MACH_SP7720EA), y)
obj-y += flash_parallel_connect_bg.o
else ifeq ($(CONFIG_MACH_COREPRIMELITE),y)
obj-y += flash_sm5701.o
else ifeq ($(CONFIG_MACH_SP8730SEEA_QHD),y)
obj-y += flash_sgm3140.o
else ifeq ($(CONFIG_MACH_SP9830IEA_5M_H100),y)
obj-y += flash_sprd_sm5701.o
else ifeq ($(CONFIG_MACH_GRANDPRIMEVE3G),y)
obj-y += flash_sm5701.o
else ifeq ($(CONFIG_MACH_COREPRIMEVE3G),y)
obj-y += flash_sm5701.o
else ifeq ($(CONFIG_MACH_J23G),y)
obj-y += flash_sm5701.o
else
obj-y += flash_common.o
endif
