ifeq ($(CONFIG_MACH_VIVALTO),y)
obj-y += flash_vivalto.o
else
ifeq ($(CONFIG_MACH_KANAS_W),y)
obj-y += flash_kanas_w.o
else
ifeq ($(CONFIG_MACH_SP8730SEA),y)
obj-y += flash_sgm3140.o
else
ifeq ($(CONFIG_MACH_SP9836AEA_4MOD),y)
obj-y += flash_parallel_connect_bg.o
else
ifeq ($(CONFIG_MACH_SP9838AEA_5MOD),y)
obj-y += flash_gpio.o
else
ifeq ($(CONFIG_MACH_SP9838AEA_POWER_DEBUG),y)
obj-y += flash_gpio.o
else
ifeq ($(CONFIG_MACH_SP9838AEA_8CORE_LIGHT_SLEEP),y)
obj-y += flash_gpio.o
else
ifeq ($(CONFIG_MACH_SP9838AEA_FHD),y)
obj-y += flash_gpio.o
else
ifeq ($(CONFIG_MACH_SP9838AEA_AUTO_SLT),y)
obj-y += flash_gpio.o
else
ifeq ($(CONFIG_MACH_SP9838AEA_2342A),y)
obj-y += flash_gpio.o
else
ifeq ($(CONFIG_MACH_SP9630EA4MN),y)
obj-y += flash_parallel_connect_bg.o
else
ifeq ($(CONFIG_MACH_SP9836AEA_3MOD), y)
obj-y += flash_parallel_connect_bg.o
else
ifeq ($(CONFIG_MACH_SP9830AEA_5M_H100), y)
obj-y += flash_parallel_connect_bg.o
else
ifeq ($(CONFIG_MACH_SP9830AEA_5M_VOLTE), y)
obj-y += flash_parallel_connect_bg.o
else
ifeq ($(CONFIG_MACH_SP9830AEA_PAD_H100), y)
obj-y += flash_sgm3140.o
else
ifeq ($(CONFIG_MACH_SP9830AED_5M_H100), y)
obj-y += flash_parallel_connect_bg.o
else
ifeq ($(CONFIG_MACH_SP9830AEF_5M_VOLTE), y)
obj-y += flash_parallel_connect_bg.o
else
ifeq ($(CONFIG_MACH_SP9830IEB_5M_H100), y)
obj-y += flash_parallel_connect_bg.o
else
ifeq ($(CONFIG_MACH_SP7720EA), y)
obj-y += flash_parallel_connect_bg.o
else
ifeq ($(CONFIG_MACH_SP7720EB), y)
obj-y += flash_parallel_connect_bg.o
else
ifeq ($(CONFIG_MACH_COREPRIMELITE),y)
obj-y += flash_sm5701.o
else
ifeq ($(CONFIG_MACH_SP8730SEEA_QHD),y)
obj-y += flash_sgm3140.o
else
ifeq ($(CONFIG_MACH_SP9830IEA_5M_H100),y)
obj-y += flash_sprd_sm5701.o
else
ifeq ($(CONFIG_MACH_GRANDPRIME3G_VE),y)
obj-y += flash_sm5701.o
else
ifeq ($(CONFIG_MACH_GRANDPRIME_DTV),y)
obj-y += flash_sm5701.o
else
ifeq ($(CONFIG_MACH_COREPRIME3G_VE),y)
obj-y += flash_sm5701.o
else
ifeq ($(CONFIG_MACH_SP9830IEC_4M_H100),y)
obj-y += flash_sgm3140.o
else
ifeq ($(CONFIG_MACH_SP9830IEE_4M_H100),y)
obj-y += flash_sgm3140.o
else
ifeq ($(CONFIG_MACH_SP9830AEC_4M_H100),y)
obj-y += flash_sgm3140.o
else
ifeq ($(CONFIG_MACH_SHARKL_J1POPLTE),y)
obj-y += flash_sm5701.o
else
ifeq ($(CONFIG_MACH_SHARKLS_J1MINI),y)
obj-y += flash_sm5701.o
else
ifeq ($(CONFIG_MACH_J1MINI3G),y)
obj-y += flash_no.o
else
ifeq ($(CONFIG_MACH_SHARKLS_J3LTE),y)
obj-y += flash_sm5701.o
else
ifeq ($(CONFIG_MACH_SHARKLS_J3VLT),y)
obj-y += flash_sm5701.o
else
ifeq ($(CONFIG_MACH_SS_SHARKLT8),y)
obj-y += flash_sm5701.o
else
ifeq ($(CONFIG_MACH_J1X3G),y)
obj-y += flash_sm5701.o
else
ifeq ($(CONFIG_MACH_J3X3G),y)
obj-y += flash_sm5701.o
else
ifeq ($(CONFIG_MACH_GTEXSWIFI),y)
obj-y += flash_no.o
else
obj-y += flash_common.o
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
endif
