ifeq ($(CONFIG_MACH_VIVALTO),y)
obj-y += flash_vivalto.o
else
ifeq ($(CONFIG_MACH_KANAS_W),y)
obj-y += flash_kanas_w.o
else
ifeq ($(CONFIG_MACH_SP8730SEA),y)
obj-y += flash_sgm3140.o
else
ifeq ($(CONFIG_MACH_CORE3_W),y)
obj-y += flash_core3.o
else
ifeq ($(CONFIG_MACH_VIVALTO3MVE3G_LTN),y)
obj-y += flash_core3.o
else
ifeq ($(CONFIG_MACH_VIVALTO5MVE3G),y)
obj-y += flash_core3.o
else
ifeq ($(CONFIG_MACH_GRANDNEOVE3G),y)
obj-y += flash_core3.o
else
ifeq ($(CONFIG_MACH_J13G),y)
obj-y += flash_sm5701.o
else
obj-y += flash_common.o
endif
endif
endif
endif
endif
endif
endif
endif