ccflags-y += -I$(srctree)/drivers/watchdog/mediatek/include	\
			 -I$(srctree)/drivers/misc/mediatek/multibridge/mt6735/mt8193/inc
ccflags-y += -I$(srctree)/drivers/watchdog/mediatek/wdt/$(MTK_PLATFORM)/
#obj-$(CONFIG_LOCAL_WDT) += mpcore_wdt.o
obj-y += mtk_wdt.o
