obj-$(CONFIG_SENSORS_SSC)	+= sensors_ssc.o
obj-$(CONFIG_SENSORS)           += sensors_core.o
#HS60 code for HS60-32/HS60-93 by zhuqiang at 2019/7/15 start
obj-$(CONFIG_SENSORS_SX9311)	+= sx9311/
obj-$(CONFIG_SENSORS_A96T346)	+= abov/
#HS60 code for HS60-32/HS60-93 by zhuqiang at 2019/7/15 end
#HS60 code for HS60-97 by zhuqiang at 2019/7/25 start
obj-$(CONFIG_SENSORS_SX9325)	+= sx9325/
#HS60 code for HS60-97 by zhuqiang at 2019/7/25 end
# HS50 code for HS50-41/SR-QL3095-01-127 by zhuqiang at 2020/08/19 start
obj-$(CONFIG_SENSORS_A96T349)   += a96t349/
# HS50 code for HS50-41/SR-QL3095-01-127 by zhuqiang at 2020/08/19 end

# HS50 code for QN3979-4292 by wurui at 2021/10/20  start
obj-$(CONFIG_SENSORS_SX932X)    += sx932x/
# HS50 code for QN3979-4292 by wurui at 2021/10/20  end
