# SPDX-License-Identifier: GPL-2.0-only
#obj-$(CONFIG_SENSORS_SSC)	+= sensors_ssc.o
obj-$(CONFIG_SENSORS)		+= sensors_core.o

# grip sensor
obj-$(CONFIG_SENSORS_SX9364)		+= sx9360.o
obj-$(CONFIG_SENSORS_SX9364_SUB)	+= sx9360_sub.o
obj-$(CONFIG_SENSORS_SX9360)		+= sx9360.o
obj-$(CONFIG_SENSORS_A96T3X6)		+= a96t3x6.o
obj-$(CONFIG_SENSORS_A96T3X6_SUB)	+= a96t3x6_sub.o
obj-$(CONFIG_SENSORS_A96T3X6_WIFI)	+= a96t3x6_wifi.o
obj-$(CONFIG_SENSORS_A96T396)		+= a96t396.o
obj-$(CONFIG_SENSORS_SX9380)  		+= sx938x.o