obj-$(CONFIG_SENSORS_SSC)	+= sensors_ssc.o
obj-$(CONFIG_SENSORS)		+= sensors_core.o

# grip sensor
obj-$(CONFIG_SENSORS_SX9360)		+= sx9360.o
obj-$(CONFIG_SENSORS_SX9364)		+= sx9360.o
obj-$(CONFIG_SENSORS_TC3XXK)		+= tc3xxk.o
obj-$(CONFIG_SENSORS_TC3XXK_DUMMY)	+= tc3xxk_dummy.o
obj-$(CONFIG_SENSORS_A96T3X6)		+= a96t3x6.o
obj-$(CONFIG_SENSORS_A96T3X6_SUB)	+= a96t3x6_sub.o
obj-$(CONFIG_SENSORS_ISG5320A)		+= isg5320a.o
obj-$(CONFIG_SENSORS_ISG5320A_SUB)	+= isg5320a_sub.o
obj-$(CONFIG_SENSORS_ISG6320)		+= isg6320.o