obj-$(CONFIG_SEC_DEBUG)			+= common/
obj-$(CONFIG_SEC_BOOT_STAT)		+= boot_stat/
obj-$(CONFIG_SEC_LOG_BUF)		+= log_buf/
obj-$(CONFIG_SEC_PMSG)			+= pmsg/
obj-$(CONFIG_SEC_REBOOT_CMD)		+= reboot_cmd/
obj-$(CONFIG_SEC_UPLOAD_CAUSE)		+= upload_cause/
obj-$(CONFIG_SEC_CRASHKEY)		+= crashkey/
obj-$(CONFIG_SEC_CRASHKEY_LONG)		+= crashkey_long/
obj-$(CONFIG_SEC_DEBUG_REGION)		+= debug_region/

obj-$(CONFIG_ARM64)			+= arm64/

obj-y					+= qcom/
