# SPDX-License-Identifier: GPL-2.0-only
# F52  code for SR-QN3979-01-25/SR-QN3979-01-89 by xiongxiaoliang at 20210202 start
obj-$(CONFIG_SENSORS_SX932X) += sx932x.o
# F52  code for SR-QN3979-01-25/SR-QN3979-01-89 by xiongxiaoliang at 20210202 end
