# Makefile for the Himax touchscreen drivers.
obj-$(CONFIG_TOUCHSCREEN_HIMAX_CHIPSET) += himax_mmi.o

himax_mmi-y += himax_debug.o
himax_mmi-y += himax_inspection.o
himax_mmi-y += himax_ic_HX83102j.o
himax_mmi-y += himax_ic_core.o
himax_mmi-y += himax_common.o
himax_mmi-y += himax_platform.o
himax_mmi-y += himax_firmware.o


