# SPDX-License-Identifier: GPL-2.0
dtb-y += mt6739.dtb
dtb-y += mt6739_a01core_swa_open_00.dtb
dtb-y += mt6739_a01core_swa_open_01.dtb
dtb-y += mt6739_a01core_swa_open_02.dtb
dtb-y += mt6739_a01core_swa_open_03.dtb
dtb-y += mt6739_a01core_swa_open_04.dtb

always            := $(dtb-y)
clean-files       := *.dtb*
