obj-$(CONFIG_SPRD_SIPA_V3) += sipa_phy_r3p0/

obj-$(CONFIG_SPRD_SIPA_V3) += sipa_core.o sipa_hal.o sipa_nic.o sipa_skb_recv.o \
			   sipa_skb_send.o sipa_rm_res.o sipa_rm_dep_graph.o \
			   sipa_rm.o sipa_rm_peers_list.o sipa_usb_cons.o \
			   sipa_eth.o sipa_dummy.o sipa_usb.o

obj-$(CONFIG_DEBUG_FS) += sipa_debugfs.o
