obj-$(CONFIG_DRM_PANEL_SAMSUNG_COMMON) += panel-samsung-drv.o
obj-$(CONFIG_DRM_PANEL_SAMSUNG_S6E3FAB) += panel-samsung-s6e3fab.o
obj-$(CONFIG_DRM_PANEL_SAMSUNG_S6E3FAC) += panel-samsung-s6e3fac.o
obj-$(CONFIG_DRM_PANEL_SAMSUNG_S6E3HAB) += panel-samsung-s6e3hab.o
obj-$(CONFIG_DRM_PANEL_SAMSUNG_S6E3FC3) += panel-samsung-s6e3fc3.o
obj-$(CONFIG_DRM_PANEL_SAMSUNG_S6E8FC1) += panel-samsung-s6e8fc1.o
obj-$(CONFIG_DRM_PANEL_SAMSUNG_EMUL) += panel-samsung-emul.o

obj-$(CONFIG_DRM_PANEL_MCD_COMMON) += mcd-panel-samsung-drv.o mcd-panel-samsung-helper.o
