obj-$(CONFIG_DRM_PANEL_SAMSUNG_COMMON) += panel-samsung-drv.o
obj-$(CONFIG_DRM_PANEL_SAMSUNG_COMMON) += panel-samsung-command-ctrl.o

obj-$(CONFIG_DRM_PANEL_MCD_COMMON) += mcd-panel-samsung-drv.o mcd-panel-samsung-helper.o
