# SPDX-License-Identifier: GPL-2.0

dts-dirs += galaxytab/gts8p
dts-dirs += galaxytab/gts8u
dts-dirs += galaxytab/gts8
dts-dirs += galaxytab/gts8uwifi
dts-dirs += galaxytab/gts8pwifi
dts-dirs += galaxytab/gts8wifi

always          := $(dtb-y)
subdir-y        := $(dts-dirs)

clean-files := *.dtb *.reverse.dts *.dtbo
