ifdef CONFIG_ARM64
KBUILD_CFLAGS += -mstrict-align
endif

obj-y += dpu_dvfs_sharkl5.o
obj-y += dpu_dvfs_sharkl5pro.o
obj-y += dpu_dvfs_qogirl6.o
obj-y += dpu_dvfs_roc1.o
obj-y += dpu_dvfs_qogirn6pro.o
