obj-$(CONFIG_TOUCHSCREEN_MTK_FOCALTECH_TS_N6_Q) += focaltech_test.o
obj-$(CONFIG_TOUCHSCREEN_MTK_FOCALTECH_TS_N6_Q) += focaltech_test_ini.o
obj-$(CONFIG_TOUCHSCREEN_MTK_FOCALTECH_TS_N6_Q) += supported_ic/
