obj-$(CONFIG_SEC_QC_MOCK)		+= sec_qc_mock.o

sec_qc_mock-objs			:= sec_qc_mock_main.o \
					   sec_qc_mock_qcom-cpufreq-hw.o \
					   sec_qc_mock_kryo_arm64_edac.o \
					   sec_qc_mock_qcom-dload-mode.o \
					   sec_qc_mock_memory_dump_v2.o \
					   sec_qc_mock_walt.o \
					   sec_qc_mock_msm_rtb.o \
					   sec_qc_mock_smem.o \
					   sec_qc_mock_qcom_wdt_core.o \
					   sec_qc_mock_epss-l3.o \
					   sec_qc_mock_qcom_lpm.o
