obj-$(CONFIG_USE_DIRECT_IS_CONTROL) += fimc-is-device-module-base.o

obj-$(CONFIG_CAMERA_CIS_6B2_OBJ) += fimc-is-device-module-6b2.o
obj-$(CONFIG_CAMERA_CIS_5E2_OBJ) += fimc-is-device-module-5e2.o
obj-$(CONFIG_CAMERA_CIS_5E3_OBJ) += fimc-is-device-module-5e3.o
obj-$(CONFIG_CAMERA_CIS_SR846_OBJ) += fimc-is-device-module-sr846.o
obj-$(CONFIG_CAMERA_CIS_4H5YC_OBJ) += fimc-is-device-module-4h5yc.o
obj-$(CONFIG_CAMERA_CIS_4H5_OBJ) += fimc-is-device-module-4h5.o
obj-$(CONFIG_CAMERA_CIS_2P2_OBJ) += fimc-is-device-module-2p2.o
obj-$(CONFIG_CAMERA_CIS_2P8_OBJ) += fimc-is-device-module-2p8.o
obj-$(CONFIG_CAMERA_CIS_3P3_OBJ) += fimc-is-device-module-3p3.o
obj-$(CONFIG_CAMERA_CIS_3L2_OBJ) += fimc-is-device-module-3l2.o
obj-$(CONFIG_CAMERA_CIS_4E6_OBJ) += fimc-is-device-module-4e6.o
obj-$(CONFIG_CAMERA_CIS_3M2_OBJ) += fimc-is-device-module-3m2.o
obj-$(CONFIG_CAMERA_CIS_IMX258_OBJ) += fimc-is-device-module-imx258.o
obj-$(CONFIG_CAMERA_CIS_SR259_OBJ) += fimc-is-device-module-sr259.o
obj-$(CONFIG_CAMERA_CIS_IMX241_OBJ) += fimc-is-device-module-imx241.o
obj-$(CONFIG_CAMERA_CIS_SR556_OBJ) += fimc-is-device-module-sr556.o
obj-$(CONFIG_CAMERA_CIS_SR556B_OBJ) += fimc-is-device-module-sr556b.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/include
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/vendor
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/sensor/module_framework
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/sensor
