#
# Makefile for the Zinitix Touchscreen driver
#

obj-$(CONFIG_TOUCHSCREEN_ZINITIX_BT432)	+= zxt_bt432_ts.o
obj-$(CONFIG_TOUCHSCREEN_ZINITIX_BT532)	+= zinitix_bt532_ts.o
obj-$(CONFIG_TOUCHSCREEN_ZINITIX_ZT75XX_OLD)	+= zinitix_bt532_ts_old.o
obj-$(CONFIG_TOUCHSCREEN_ZINITIX_ZT75XX)	+= zinitix_bt532_ts.o
