# SPDX-License-Identifier: GPL-2.0
# CPUfreq core

##################################################################################
# ARM SoC drivers
obj-$(CONFIG_DEVICE_MODULES_ARM_MEDIATEK_CPUFREQ_HW) += mediatek-cpufreq-hw.o
mediatek-cpufreq-hw-y := mediatek-cpufreq-hw_main.o mediatek-cpufreq-hw_fdvfs.o

# CPUfreq limit API
obj-$(CONFIG_CPU_FREQ_LIMIT)		+= cpufreq_limit.o