dtb-y += e3q_eur_openx_w00_r09.dtbo
dtb-y += e3q_eur_openx_w00_r08.dtbo
dtb-y += e3q_eur_openx_w00_r07.dtbo
dtb-y += e3q_eur_openx_w00_r05.dtbo
dtb-y += e3q_eur_openx_w00_r04.dtbo
dtb-y += e3q_eur_openx_w00_r03.dtbo
dtb-y += e3q_eur_openx_w00_r02.dtbo
dtb-y += e3q_eur_openx_w00_r01.dtbo
dtb-y += e3q_eur_openx_w00_r00.dtbo
# SPDX-License-Identifier: GPL-2.0
# COPYRIGHT(C) 2023 Samsung Electronics Co., Ltd. All Right Reserved.

# TODO: if lego is not avaiable then uncomment the following sub-makefile
# e3q_dir		:= $(srctree)/$(src)
# include $(e3q_dir)/without_lego.mk
