ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
# hs14 code for SR-AL6528A-01-406 by tangzhen at 20220907 start
obj-y += lcd_hx83112f_txd_boe_mipi_fhd_video.o
# hs14 code for SR-AL6528A-01-406 by tangzhen at 20220907 end
# hs14 code for SR-AL6528A-01-413 by duanyaoming at 20220910 start
obj-y += lcd_td4375_cw_inx_mipi_fhd_video.o
# hs14 code for SR-AL6528A-01-413 by duanyaoming at 20220910 end
# hs14 code for SR-AL6528A-01-420 by duanyaoming at 20220907 start
obj-y += lcd_jd9522t_xx_boe_mipi_fhd_video.o
# hs14 code for SR-AL6528A-01-420 by duanyaoming at 20220907 end
# hs14 code for SR-AL6528A-01-427 by tangzhen at 20220913 start
obj-y += lcd_nl9922c_jz_tm_mipi_fhd_video.o
# hs14 code for SR-AL6528A-01-427 by tangzhen at 20220913 end
obj-y += lcd_td4375_txd_jdi_mipi_fhd_video.o
# hs14 code for AL6528A-20 by duanyaoming at 20220906 start
obj-y += lcd_default_mipi_fhd_video.o
# hs14 code for AL6528A-20 by duanyaoming at 20220906 end