obj-$(CONFIG_CHARGER_SM5714)	+= sm5714_charger.o sm5714_charger_oper.o
obj-$(CONFIG_CHARGER_SM5440)   += sm_direct_charger.o sm5440_charger.o
obj-$(CONFIG_CHARGER_PCA9468)	+= pca9468_charger.o

ccflags-y := -Wformat
