#
# panel object
# namd : ss_dsi_panel_"DDI NAME"_"PANEL NAME".o
#
ccflags-y := -Iinclude/drm -Idrivers/gpu/drm/msm -Idrivers/gpu/drm/msm/dsi-staging
ccflags-y += -Idrivers/gpu/drm/msm/sde
ccflags-y += -Idrivers/gpu/drm/msm/samsung
ccflags-y += -Idrivers/gpu/drm/msm/samsung/BLIC_ISL98611

obj-y  += ss_dsi_panel_NT36672A_BS063YPM.o
