#obj-$(CONFIG_EXYNOS_COMMON_PANEL) += exynos_panel_drv.o panel-samsung-s6e3ha9.o panel-samsung-s6e3ha8.o panel-samsung-s6e3fa0.o panel-samsung-ea8076.o panel-samsung-td4150.o panel_i2c.o
obj-$(CONFIG_EXYNOS_COMMON_PANEL) += common_panel_drv.o common_mipi_lcd.o
