#obj-$(CONFIG_EXYNOS_COMMON_PANEL) += exynos_panel_drv.o panel-samsung-s6e3ha9.o panel-samsung-s6e3ha8.o panel-samsung-s6e3fa0.o panel-anapass-ana6705.o panel-samsung-s6e3fa9-octa.o panel-samsung-s6e3fa9-ub.o panel-samsung-s6e3ha8-fhdp.o
obj-$(CONFIG_EXYNOS_COMMON_PANEL) += common_panel_drv.o common_mipi_lcd.o
