#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHSCREEN_IST30XXB) += ist30xxb.o ist30xxb_update.o ist30xxb_tracking.o ist30xxb_misc.o ist30xxb_sys.o ist30xxb_sec.o ist30xxb_cmcs.o