obj-$(CONFIG_VIDEO_EXYNOS_CAMERA_POSTPROCESS_GDC)	+= gdc/
obj-$(CONFIG_VIDEO_EXYNOS_CAMERA_POSTPROCESS_STR)	+= str/
obj-$(CONFIG_VIDEO_EXYNOS_CAMERA_POSTPROCESS_VRA)	+= vra/

subdir-ccflags-y += -I$(srctree)/drivers/media/platform/exynos/camera/lib