obj-$(CONFIG_OLED_COMMON_TEST)		+= oled_common_test.o
obj-$(CONFIG_OLED_COMMON_AOD_TEST)		+= oled_common_aod_test.o
obj-$(CONFIG_OLED_COMMON_AOD_TEST)		+= oled_common_cond_test.o
obj-$(CONFIG_OLED_COMMON_DUMP_TEST)		+= oled_common_dump_test.o
obj-$(CONFIG_OLED_COMMON_MDNIE_TEST)		+= oled_common_mdnie_test.o
obj-$(CONFIG_OLED_FUNCTION_TEST)		+= oled_function_test.o
