# drivers/staging/samsung/sec_notifier/Makefile
#
# Copyright (c) 2010-2011 Samsung Electronics Co., Ltd.
#		http://www.samsung.com/
#
# Licensed under GPLv2

obj-y				:=
obj-m				:=
obj-n				:=
obj-				:=

ccflags-y := -Wformat

obj-$(CONFIG_VBUS_NOTIFIER)	+= vbus_notifier.o
# Samsung sec NAD Feature
obj-$(CONFIG_SEC_NAD)		+= sec_nad.o
