# drivers/staging/samsung/Makefile
#
# Copyright (c) 2010-2016 Samsung Electronics Co., Ltd.
#		http://www.samsung.com/
#
# Licensed under GPLv2

# Samsung Logging Feature
obj-$(CONFIG_SEC_EXT)			+= sec_log.o
# Samsung Bootstat Feature
obj-$(CONFIG_SEC_BOOTSTAT)		+= sec_bootstat.o
# Samsung NAD Feature
obj-$(CONFIG_SEC_NAD)			+= sec_nad.o
# Samsung USB Feature
obj-$(CONFIG_VBUS_NOTIFIER)		+= vbus_notifier.o
obj-$(CONFIG_CABLE_TYPE_NOTIFIER)	+= cable_type_notifier.o

obj-$(CONFIG_SEC_MISC)			+= sec_chipid.o