obj-$(CONFIG_EXYNOS_DECON_LCD) += dsim_panel.o
obj-$(CONFIG_EXYNOS_DECON_MDNIE_LITE) += mdnie_lite.o

obj-$(CONFIG_PANEL_EA8064G_DYNAMIC) += ea8064g_lcd_ctrl.o dimming_core.o
obj-$(CONFIG_PANEL_S6E3FA3_J7XE) += s6e3fa3_a7xe_lcd_ctrl.o dynamic_aid.o
obj-$(CONFIG_PANEL_S6E3FA3_A7MAX) += s6e3fa3_a7max_lcd_ctrl.o dynamic_aid.o
obj-$(CONFIG_PANEL_EA8061S_J7XE) += ea8061_lcd_ctrl.o ea8061s_lcd_ctrl.o dimming_core.o
obj-$(CONFIG_PANEL_S6E3AA2_AMS484KF09) += s6e3aa2_ams474kf09_lcd_ctrl.o dynamic_aid.o
obj-$(CONFIG_PANEL_LTL101AL06) += ltl101al06_lcd_ctrl.o
obj-$(CONFIG_PANEL_S6D7AA0) += s6d7aa0_degas2_lcd_ctrl.o
obj-$(CONFIG_PANEL_HX8279D) += hx8279d_lcd_ctrl.o
obj-$(CONFIG_PANEL_S6D7AA0_BV055HDM) += s6d7aa0_bv055hdm_lcd_ctrl.o
obj-$(CONFIG_PANEL_TD4300) += td4300_lcd_ctrl.o