obj-$(CONFIG_EXYNOS_DECON_LCD) += dsim_panel.o
obj-$(CONFIG_EXYNOS_DECON_MDNIE_LITE) += mdnie_lite.o

obj-$(CONFIG_PANEL_S6E8AA5X01)	+= s6e8aa5x01_lcd_ctrl.o dimming_core.o
obj-$(CONFIG_PANEL_TD4100)	+= td4100_lcd_ctrl.o
obj-$(CONFIG_PANEL_TD4100_J3POP)	+= td4100_j3pop_lcd_ctrl.o
obj-$(CONFIG_PANEL_S6D7AA0_XCOVER4)	+= s6d7aa0_xcover4_lcd_ctrl.o
obj-$(CONFIG_PANEL_TD4100_J3Y17)	+= td4100_j3y17_lcd_ctrl.o