#
# Makefile for the sensor drivers.
#

# Each configuration option enables a list of files.

obj-y 	+= accelometer_sensor.o
obj-$(CONFIG_SENSORS_SSP_ACCELOMETER_ICM42605M)		+= accel_icm42605m.o
obj-$(CONFIG_SENSORS_SSP_ACCELOMETER_ICM42632M)		+= accel_icm42632m.o
obj-$(CONFIG_SENSORS_SSP_ACCELOMETER_LSM6DSL)		+= accel_lsm6dsl.o
obj-$(CONFIG_SENSORS_SSP_ACCELOMETER_K6DS3TR)		+= accel_k6ds3tr.o
obj-$(CONFIG_SENSORS_SSP_ACCELOMETER_LIS2DLC12)		+= accel_lis2dlc12.o
