#
# Copyright (c) 2013 Samsung Electronics Co., Ltd.
#		http://www.samsung.com
#
# Licensed under GPLv2
#

obj-$(CONFIG_EXYNOS_MIPI_DSIM) += timenval.o panel.o panel_bl.o dimming.o panel_drv.o panel_irc.o decon_board.o
obj-$(CONFIG_EXYNOS_DECON_MDNIE) += mdnie.o
obj-$(CONFIG_EXYNOS_DECON_LCD_SYSFS) += sysfs.o
obj-$(CONFIG_EXYNOS_DECON_LCD_SPI) += spi.o
obj-$(CONFIG_EXYNOS_DECON_LCD_COPR) += copr.o
obj-$(CONFIG_DISPLAY_USE_INFO) += dpui.o
obj-$(CONFIG_PANEL_NOTIFY) += panel_notify.o
obj-$(CONFIG_SUPPORT_DDI_FLASH) += panel_poc.o
obj-$(CONFIG_EXTEND_LIVE_CLOCK) += aod/aod_drv.o
obj-$(CONFIG_SUPPORT_POC_SPI) += panel_spi.o
obj-$(CONFIG_SUPPORT_I2C) += panel_i2c.o
obj-$(CONFIG_DYNAMIC_FREQ) += df/dynamic_freq.o

obj-$(CONFIG_EXYNOS_DECON_LCD_EA8076_A21S) += ea8076/ea8076.o ea8076/ea8076_aod.o
obj-$(CONFIG_EXYNOS_DECON_LCD_ILI9882N_M12S) += ili9882n/ili9882n.o
obj-$(CONFIG_EXYNOS_DECON_LCD_NT36525_XCOVER5) += nt36525/nt36525.o
obj-$(CONFIG_EXYNOS_DECON_LCD_NT36675_M12) += nt36675/nt36675.o
obj-$(CONFIG_EXYNOS_DECON_LCD_ILI7806S_M12) += ili7806s/ili7806s.o
obj-$(CONFIG_EXYNOS_DECON_LCD_NT36525B_CTC_A12S) += nt36525b_ctc/nt36525b_ctc.o
obj-$(CONFIG_EXYNOS_DECON_LCD_ILI9882Q_BOE_A12S) += ili9882q_boe/ili9882q_boe.o
obj-$(CONFIG_EXYNOS_DECON_LCD_NT36525B_SHARP_A12S) += nt36525b_sharp/nt36525b_sharp.o
obj-$(CONFIG_EXYNOS_DECON_LCD_NT36525B_DTC_A12S) += nt36525b_dtc/nt36525b_dtc.o
obj-$(CONFIG_EXYNOS_DECON_LCD_TD4150_BOE_A12S) += td4150_boe/td4150_boe.o
obj-$(CONFIG_EXYNOS_DECON_LCD_TD4375_BOE_A12S) += td4375_boe/td4375_boe.o
obj-$(CONFIG_EXYNOS_DECON_LCD_ILI7807S_A12S) += ili7807s/ili7807s.o
obj-$(CONFIG_EXYNOS_DECON_LCD_TD4160_BOE_A12S) += td4160_boe/td4160_boe.o
obj-$(CONFIG_EXYNOS_DECON_LCD_A12S_BLIC_DUAL) += decon_void_regulator.o