dtbo-y += r0q_gbl_openx_w00_r12.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
r0q_gbl_openx_w00_r12.dtbo-base := ../../../vendor/qcom/waipio.dtb ../../../vendor/qcom/waipio-v2.dtb ../../../vendor/qcom/waipiop.dtb ../../../vendor/qcom/waipiop-v2.dtb # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
dtbo-y += r0q_gbl_openx_w00_r11.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
r0q_gbl_openx_w00_r11.dtbo-base := ../../../vendor/qcom/waipio.dtb ../../../vendor/qcom/waipio-v2.dtb ../../../vendor/qcom/waipiop.dtb ../../../vendor/qcom/waipiop-v2.dtb # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
dtbo-y += r0q_gbl_openx_w00_r10.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
r0q_gbl_openx_w00_r10.dtbo-base := ../../../vendor/qcom/waipio.dtb ../../../vendor/qcom/waipio-v2.dtb ../../../vendor/qcom/waipiop.dtb ../../../vendor/qcom/waipiop-v2.dtb # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
dtbo-y += r0q_gbl_openx_w00_r09.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
r0q_gbl_openx_w00_r09.dtbo-base := ../../../vendor/qcom/waipio.dtb ../../../vendor/qcom/waipio-v2.dtb ../../../vendor/qcom/waipiop.dtb ../../../vendor/qcom/waipiop-v2.dtb # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
dtbo-y += r0q_gbl_openx_w00_r08.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
r0q_gbl_openx_w00_r08.dtbo-base := ../../../vendor/qcom/waipio.dtb ../../../vendor/qcom/waipio-v2.dtb ../../../vendor/qcom/waipiop.dtb ../../../vendor/qcom/waipiop-v2.dtb # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
# SPDX-License-Identifier: GPL-2.0

#define __sec_dtbo_build
#dtbo-$(2) += $(1)
#$(1)-base := $(3)
#endef
#
#define sec_dtbo_build
#$(foreach dtbo, $(1), $(eval $(call __sec_dtbo_build, $(dtbo),$(2),$(3))))
#endef
#
# WAIPIO BASE DTB
#QCOM_DTB := ../../../vendor/qcom
#SEC_WAIPIO_BASE_DTB := $(QCOM_DTB)/waipio.dtb $(QCOM_DTB)/waipiop.dtb
#
#ifeq ($(CONFIG_BUILD_ARM64_DT_OVERLAY),y)
#
# R0Q
#SEC_R0Q_DTBO := \
#    waipio-sec.r0q.overlay.00.dtbo
#
#$(eval $(call sec_dtbo_build, \
#    $(SEC_R0Q_DTBO),$(CONFIG_ARCH_WAIPIO),$(SEC_WAIPIO_BASE_DTB)))
#endif

clean-files := *.dtb *.reverse.dts *.dtbo

