obj-$(CONFIG_EXYNOS_DECON7880_LCD) += dsim_panel.o
obj-$(CONFIG_EXYNOS_DECON_MDNIE_LITE) += mdnie_lite.o
obj-$(CONFIG_DISPLAY_USE_INFO) += dpui.o

obj-$(CONFIG_PANEL_S6E3FA3_A7Y17) += s6e3fa3_a7y17_lcd_ctrl.o dynamic_aid.o
obj-$(CONFIG_PANEL_S6E3FA3_A5Y17) += s6e3fa3_a7y17_lcd_ctrl.o dynamic_aid.o

