#
# Makefile for the GalaxyCore touchscreen driver.
#

obj-$(CONFIG_TOUCHSCREEN_GALAXYCORE)	+=  gcore_drv_main.o
obj-$(CONFIG_TOUCHSCREEN_GALAXYCORE)	+=  gcore_drv_sprd.o
obj-$(CONFIG_TOUCHSCREEN_GALAXYCORE)	+=  gcore_drv_fw_update.o
obj-$(CONFIG_TOUCHSCREEN_GALAXYCORE)	+=  gcore_drv_interface.o
obj-$(CONFIG_TOUCHSCREEN_GALAXYCORE)	+=  gcore_drv_mp_test.o
