# Android Switch Class Driver
subdir-ccflags-y := -Wformat
obj-$(CONFIG_ANDROID_SWITCH)		+= sec_switch_class.o
sec_switch_class-y		:= switch_class.o
sec_switch_class-$(CONFIG_ANDROID_SWITCH_GPIO)	+= switch_gpio.o
