subdir-ccflags-y += -I$(src)

obj-y += dp_api.o
obj-y += dp_audio.o
obj-y += dp_aux.o
obj-y += dp_core.o
obj-y += dp_link.o
obj-y += dp_test.o
obj-y += dp_video.o
obj-y += dw_dptx.o
obj-y += dp_hdcp.o
