# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2022 Samsung Electronics Co., Ltd

SENSOR_NAME  := sr846d
PROJECT_NAME := $(subst ",,$(CONFIG_CAMERA_SAMSUNG_MODEL_NAME))

obj-y += $(SENSOR_NAME)mipiraw_Sensor.o
$(info used project[$(PROJECT_NAME)]driver: $(SENSOR_NAME))
