# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_QCOM_PMIC_VOTER)	+= qcom-pmic-voter.o
obj-$(CONFIG_AFC_GPIO_HVDCP)	+= afc_gpio.o
obj-$(CONFIG_UPM6918_CHARGER)	+= upm6918_charger.o
obj-$(CONFIG_FG_SM5602)		+= sm5602_fg.o
obj-$(CONFIG_UPM6720_CHARGER)	+= upm6720_charger.o
obj-$(CONFIG_CHARGER_SC89890)	+= sc89890h.o
obj-$(CONFIG_CHARGER_SD76030)		+= sd76030.o
obj-$(CONFIG_FG_OZ8806)			+= sd77428.o
obj-$(CONFIG_SC8541_CHARGER)  	+= sc8541.o
sd77428-objs:= oz8806_battery.o parameter.o table.o bmulib.o calculate.o
obj-$(CONFIG_FG_CW221X)			+= cw221X_fuel_gauge.o
