# Makefile for the Himax touchscreen drivers.
obj-$(CONFIG_TOUCHSCREEN_HX83102_INCELL)   		+=	himax_ic_incell_core.o
obj-$(CONFIG_TOUCHSCREEN_HIMAX_HX83102)		+=	himax_ic_HX83102.o
obj-$(CONFIG_TOUCHSCREEN_HX83102_COMMON)   		+=	himax_common.o himax_platform.o
obj-$(CONFIG_TOUCHSCREEN_HX83102_DEBUG)   		+=	himax_debug.o
obj-$(CONFIG_TOUCHSCREEN_HX83102_INSPECT)   		+=	himax_inspection.o