#
#  Makefile for the kernel Sensor device drivers.
#

#  Object files in subdirectories
obj-$(CONFIG_SENSORS_CORE)		+= sensors_core.o
obj-$(CONFIG_SENSORS_K3DH)		+= k3dh.o
obj-$(CONFIG_SENSORS_K2HH)		+= k2hh.o
