/*
 * leds-et6034a.h - platform data structure for et6034a led controller
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 */
#ifndef __LINUX_LEDS_ET6034A_H
#define __LINUX_LEDS_ET6034A_H
#define SW_RSTCTR_ON	0X00
#define SW_RSTCTR_OFF	0x01
#define RGB_OE_MASK     0x3f
#define WHITE_MAX_BRIGHTNESS     0x7F7F7F7F7F7F7F7F
#define MAX_BRIGHTNESS  0x7f
#define BRIGHTNESS_OFF  0x00

#define LED_OFF		0
#define LED_ON		1
#define RGB_LOOP	-1

#define LED_STEP 20

enum et6034a_led_type {
	WHITE_LED,
	RGB_LED,
};

enum led_color {
	LED_RED,
	LED_GREEN,
	LED_BLUE,
	LED_WHITE,
};

enum led_color_set {
	RED_SET = 0xFF0000,
	GREEN_SET = 0x00FF00,
	BLUE_SET = 0x0000FF,
	WHITE_SET = 0xFFFFFF,
	AMBER_SET = 0xFFBF00,
};

enum et6034a_reg {
	ET6034A_RSTCTR = 0,
	ET6034A_RGB_OE,
	ET6034A_FIXBRIT_LED0,
	ET6034A_FIXBRIT_LED1,
	ET6034A_FIXBRIT_LED2,
	ET6034A_FIXBRIT_LED3,
	ET6034A_FIXBRIT_LED4,
	ET6034A_FIXBRIT_LED5,
	ET6034A_FIXBRIT_LED6,
	ET6034A_FIXBRIT_LED7,
	ET6034A_FIXBRIT_LED8 = 0x0C,
	ET6034A_FIXBRIT_LED9,
	ET6034A_FIXBRIT_LED10,
	ET6034A_FIXBRIT_LED11,
	ET6034A_FIXBRIT_LED12,
	ET6034A_FIXBRIT_LED13,
	ET6034A_FIXBRIT_LED14,
	ET6034A_FIXBRIT_LED15,
};

enum led_patterns {
	IDLED_READY = 0,
	WAIT_SETUP,
	PROCESSING_ANIMATION,
	FADE_IN_OUT1,
	FADE_IN_OUT2,
	NOTIFICATION,
	TIMER_ALRAM,
	MIC_OFF,
	BIXBY_PROCESSING,
	BIXBY_WAKEUP,
	VOLUME_LEVEL,
	BIXBY_TIMEOUT,
	MAX_BRIGHTNESS_PREVIEW,
	MAX_BRIGHTNESS_PATTERN,
	PATTERNS_MAX,
};

enum rgb_patterns {
	RGB_BLINK_OFF = 0,
	RGB_BLINK_COLOR,
	RGB_BLINK_BOOT,
	RGB_BLINK_BT_CONNECTED,
	RGB_BLINK_NETWORK_ERR,
	RGB_BLINK_ERR,
	RGB_BLINK_POWER_OFF,
	RGB_BLINK_DEBUG_LEVEL,
	RGB_MIC_OFF,
	RGB_BLINK_LOW_POWER_TA,
	RGB_BLINK_MAX,
};
#endif /* __LINUX_LEDS_ET6034A_H */
