#
# Makefile for the fingerprint device.
#

# Each configuration option enables a list of files.

#obj-$(CONFIG_GOODIX_FINGERPRINT)	+= gf_tee.o
#gf_tee-y := gf_spi_tee.o

obj-$(CONFIG_MTK_FINGERPRINT_GOODIX) := gf_spi_tee.o