obj-$(CONFIG_SEC_QC_HW_PARAM)		+= sec_qc_hw_param.o
sec_qc_hw_param-objs			:= sec_qc_hw_param_main.o \
					   sec_qc_ap_info.o \
					   sec_qc_ap_health.o \
					   sec_qc_last_dcvs.o \
					   sec_qc_extra_info.o \
					   sec_qc_extrb_info.o \
					   sec_qc_extrc_info.o \
					   sec_qc_extrt_info.o \
					   sec_qc_extrm_info.o \
					   sec_qc_errp_extra.o \
					   sec_qc_ddr_info.o
