/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2020 MediaTek Inc.
 */


#ifndef __APUSYS_APUMMU_MSG_H__
#define __APUSYS_APUMMU_MSG_H__

enum APUMMU_MSG_OPTION_TYPE {
	APUMMU_OPTION_GET,
	APUMMU_OPTION_SET,
	APUMMU_OPTION_MAX,
};

enum APUMMU_MSG_CMD_TYPE {
	APUMMU_CMD_HANDSHAKE = 0x0,
	APUMMU_CMD_SYSTEM_RAM,
	APUMMU_CMD_HW_DEFAULT_IOVA,
	APUMMU_CMD_HW_DEFAULT_IOVA_ONE_SHOT,
	APUMMU_CMD_MEM_OP,
	APUMMU_CMD_DBG_OP = 0x80,
	APUMMU_CMD_MAX,
};

enum APUMMU_MSG_MEM_TYPE {
	APUMMU_MEM_NONE,
	APUMMU_MEM_ALLOC,
	APUMMU_MEM_FREE,
	APUMMU_MEM_IMPORT,
	APUMMU_MEM_UNIMPORT,
	APUMMU_MEM_MAP,
	APUMMU_MEM_UNMAP,
	APUMMU_MEM_INFO,
	APUMMU_MEM_ADD_POOL,
	APUMMU_MEM_FREE_POOL,
	APUMMU_MEM_MAX,
};

struct apummu_msg {
	uint32_t cmd;
	uint32_t option;
	uint32_t ack;
	uint32_t sn;
	uint32_t data[12];
} __packed;


#endif
