sprd_debugstat_common := sprd_debugstat_core.o

obj-$(CONFIG_SPRD_POWER_STAT_SHARKL5PRO) += sprd_debugstat.o
sprd_debugstat-objs := $(sprd_debugstat_common) sprd_debugstat_sharkl5pro.o

obj-$(CONFIG_SPRD_POWER_STAT_SHARKL6) += sprd_debugstat.o
sprd_debugstat-objs := $(sprd_debugstat_common) sprd_debugstat_sharkl6.o
