# Makefile of gnssif

obj-$(CONFIG_EXYNOS_GNSS_IF) += gnss_mbox.o

obj-$(CONFIG_EXYNOS_GNSS_IF) += gnss_main.o \
				gnss_io_device.o \
				gnss_keplerctl_device.o \
				gnss_link_device_shmem.o \
				gnss_link_device_memory.o \
				pmu-gnss.o \
				gnss_utils.o
