#include "imgsensor_vendor_rom_config.h"

const struct imgsensor_vendor_rom_addr *vendor_rom_addr[SENSOR_POSITION_MAX] = {
	NULL, //[0] SENSOR_POSITION_REAR
	NULL, //[1] SENSOR_POSITION_FRONT
	NULL, //[2] SENSOR_POSITION_REAR2
	NULL, //[3] SENSOR_POSITION_FRONT2
	NULL, //[4] SENSOR_POSITION_REAR3
	NULL, //[5] SENSOR_POSITION_FRONT3
	NULL, //[6] SENSOR_POSITION_REAR4
	NULL, //[7] SENSOR_POSITION_FRONT4
	NULL, //[8] SENSOR_POSITION_REAR_TOF
	NULL, //[9] SENSOR_POSITION_FRONT_TOF
};
