#
# Makefile for the vibrator driver ICs with vibrator driver
#

obj-$(CONFIG_VIBETONZ) += vibrator.o
vibrator-objs +=tspdrv.o

# Makefile for Vibrator controlled by PMIC Regulator.
obj-$(CONFIG_MSM_VIBRATOR) += msm_vibrator.o

# Makefile for Vibrator controlled by SUB PMIC Regulator.
obj-$(CONFIG_SM5703_VIBRATOR) += sm5703_vibrator.o
