#
# Makefile for the vibrator driver ICs with vibrator driver
#

obj-$(CONFIG_DRV2603)	+= drv2603.o
obj-$(CONFIG_SEC_VIB)	+= sec_vib.o
obj-$(CONFIG_IMM_VIB)	+= imm_vib.o
obj-$(CONFIG_BD6478)		+= bd6478.o
obj-$(CONFIG_ISA1000)		+= isa1000.o
obj-$(CONFIG_MOTOR_DRV_DRV2603V)		+= drv2603v_vibrator.o
obj-$(CONFIG_VIBETONZ)			+= vibrator.o
vibrator-objs				+= tspdrv.o
