#
# Samsung SoC MIPI LCD CONTROL functions
#
# Copyright (c) 2017 Samsung Electronics
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#

#
# Makefile for misc devices that really don't fit anywhere else.

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc

obj-$(CONFIG_LCD_GENERIC) += gen_panel/
obj-$(CONFIG_LCD_GENERIC) += mtk_gen_panel.o mtk_gen_common.o