pablo-hws-objs := pablo-hw.o
obj-$(CONFIG_VIDEO_EXYNOS_PABLO_ISP) += pablo-hws.o

pablo-hws-$(CONFIG_COMMON_DMA_V1_0) += api/is-hw-common-dma.o
pablo-hws-$(CONFIG_COMMON_DMA_V2_0) += api/pablo-hw-common-dma-v2.o
pablo-hws-$(CONFIG_PABLO_HW_HELPER_V2) += pablo-hw-helper-v2.o

# v8.1
pablo-hws-$(CONFIG_PABLO_V8_1_0) += is-hw-mcscaler-v3.o \
				is-hw-djag-v2.o \
				is-hw-cac.o \
				api/is-hw-api-mcscaler-v8_1.o
# v8.10
pablo-hws-$(CONFIG_PABLO_V8_10_0) += is-hw-mcscaler-v3.o \
				is-hw-djag-v2.o \
				is-hw-cac.o \
				api/is-hw-api-mcscaler-v8_10.o
# v8.20
pablo-hws-$(CONFIG_PABLO_V8_20_0) += is-hw-mcscaler-v3.o \
				is-hw-djag-v2.o \
				is-hw-cac.o \
				api/is-hw-api-mcscaler-v8_20-v8_21.o

# v9.1
pablo-hws-$(CONFIG_PABLO_V9_1_0) += is-hw-mcscaler-v3.o \
				is-hw-djag-v2.o \
				is-hw-cac.o \
				api/is-hw-api-mcscaler-v9_1.o
# v9.10
pablo-hws-$(CONFIG_PABLO_V9_10_0) += is-hw-mcscaler-v3.o \
				is-hw-djag-v2.o \
				is-hw-cac.o \
				api/is-hw-api-mcscaler-v9_10.o

# v10.1
pablo-hws-$(CONFIG_PABLO_V10_1_0) += is-hw-mcscaler-v3.o \
				is-hw-djag-v2.o \
				is-hw-cac-dummy.o \
				api/is-hw-api-mcscaler-v10_0.o

# v10.20
pablo-hws-$(CONFIG_PABLO_V10_20_0) += is-hw-mcscaler-v3.o \
				is-hw-djag-v2.o \
				is-hw-cac.o \
				api/is-hw-api-mcscaler-v10_20.o

# v11.0
pablo-hws-$(CONFIG_PABLO_V11_0_0) += is-hw-lme-v3.o \
				is-hw-byrp-v2.o \
				is-hw-rgbp-v2.o \
				is-hw-mcfp-v2.o \
				is-hw-yuvp-v2.o \
				is-hw-mcscaler-v4.o \
				is-hw-djag-v3.o \
				is-hw-cac-dummy.o \
				api/is-hw-api-lme-v3_0.o \
				api/is-hw-api-byrp-v2_0.o \
				api/is-hw-api-rgbp-v2_0.o \
				api/is-hw-api-mcfp-v11_0.o \
				api/is-hw-api-yuvp-v2_0.o \
				api/is-hw-api-mcscaler-v11_0.o

# v11.20
pablo-hws-$(CONFIG_PABLO_V11_20_0) += is-hw-lme-v3.o \
				is-hw-byrp-v2.o \
				is-hw-rgbp-v2.o \
				is-hw-mcfp-v2.o \
				is-hw-yuvp-v2.o \
				is-hw-mcscaler-v4.o \
				is-hw-djag-v3.o \
				is-hw-cac-dummy.o \
				api/is-hw-api-lme-v2_20.o \
				api/is-hw-api-byrp-v1_20.o \
				api/is-hw-api-rgbp-v1_20.o \
				api/is-hw-api-mcfp-v11_20.o \
				api/is-hw-api-yuvp-v1_20.o \
				api/is-hw-api-mcscaler-v11_20.o
# v11.30
pablo-hws-$(CONFIG_PABLO_V11_30_0) += is-hw-lme-v3.o \
				is-hw-byrp-v2.o \
				is-hw-rgbp-v2.o \
				is-hw-mcfp-v2.o \
				is-hw-yuvp-v2.o \
				is-hw-mcscaler-v4.o \
				is-hw-djag-v3.o \
				is-hw-cac-dummy.o \
				api/is-hw-api-lme-v2_20.o \
				api/is-hw-api-byrp-v1_30.o \
				api/is-hw-api-rgbp-v1_40.o \
				api/is-hw-api-mcfp-v11_20.o \
				api/is-hw-api-yuvp-v1_40.o \
				api/is-hw-api-mcscaler-v11_30.o

# v12.0
pablo-hws-$(CONFIG_PABLO_V12_0_0) += is-hw-lme-v3.o \
				is-hw-byrp-v2.o \
				is-hw-rgbp-v2.o \
				is-hw-mcfp-v2.o \
				is-hw-yuvp-v2.o \
				is-hw-shrp-v1.o \
				is-hw-mcscaler-v4.o \
				is-hw-djag-v3.o \
				is-hw-cac-dummy.o \
				api/is-hw-api-lme-v4_0.o \
				api/is-hw-api-byrp-v3_0.o \
				api/is-hw-api-rgbp-v3_0.o \
				api/is-hw-api-mcfp-v12_0.o \
				api/is-hw-api-yuvp-v3_0.o \
				api/is-hw-api-shrp-v3_0.o \
				api/is-hw-api-mcscaler-v12_0.o

pablo-hws-$(CONFIG_PABLO_DLFE) += pablo-hw-dlfe.o
pablo-hws-$(CONFIG_DLFE_API_V1_0) += api/pablo-hw-api-dlfe-v1_0.o
