#include $(srctree)/drivers/misc/mediatek/Makefile.custom
subdir-ccflags-$(CONFIG_CAMERA_HW_BIG_DATA) += -I$(srctree)/drivers/misc/mediatek/include/hwparam
obj-y += s5k3m3mipiraw_Sensor.o
obj-y += s5k3m3mipiraw_pdaf.o

