obj-$(CONFIG_SEC_QC_LOGGER)		+= sec_qc_logger.o
sec_qc_logger-objs			:= sec_qc_logger_main.o \
					   sec_qc_sched_log.o \
					   sec_qc_irq_log.o \
					   sec_qc_irq_exit_log.o \
					   sec_qc_msg_log.o
