# SPDX-License-Identifier: GPL-2.0

# 
obj-$(CONFIG_SND_SOC_SAMSUNG_AUDIO) += sec_audio_sysfs.o
# obj-$(CONFIG_SND_SOC_SAMSUNG_AUDIO) += snd_debug_proc.o
# obj-$(CONFIG_SEC_KUNIT)			+= kunit_test/
# GCOV_PROFILE_snd_debug_proc.o		:= $(CONFIG_SEC_KUNIT)
