obj-$(CONFIG_SEC_DEBUG_REGION)		+= sec_debug_region.o

sec_debug_region-objs			:= sec_debug_region_main.o \
					   sec_debug_region_pool.o \
					   sec_debug_region_gen_pool.o \
					   sec_debug_region_cma_pool.o
