dtb-y += e2s_kor_singlex_w01_r17.dtbo
dtb-y += e2s_kor_singlex_w01_r13.dtbo
dtb-y += e2s_kor_singlex_w01_r11.dtbo
dtb-y += e2s_kor_singlex_w01_r10.dtbo
dtb-y += e2s_kor_singlex_w01_r08.dtbo
# SPDX-License-Identifier: GPL-2.0
always-y	:= $(dtb-y) $(dtbo-y)
clean-files	:= *.dtb *.dtbo
