
ifeq ($(CONFIG_MACH_GRANDPRIME3G_VE),y)
obj-y += sensor_otp_coreprime3g_ve.o
else ifeq ($(CONFIG_MACH_J3_3G),y)
obj-y += sensor_otp_coreprime3g_ve.o
else ifeq ($(CONFIG_MACH_J3X3G),y)
obj-y += sensor_otp_coreprime3g_ve.o
else ifeq ($(CONFIG_MACH_SHARKLS_J3LTE),y)
obj-y += sensor_otp_coreprime3g_ve.o
else ifeq ($(CONFIG_MACH_SHARKLS_J3VLT),y)
obj-y += sensor_otp_coreprime3g_ve.o
else ifeq ($(CONFIG_MACH_SHARKLS_J1MINI),y)
obj-y += sensor_hi544_otp.o
else ifeq ($(CONFIG_MACH_J3XLTE),y)
obj-y += sensor_otp_coreprime3g_ve.o
else ifeq ($(CONFIG_MACH_SHARKLS_J3VLT),y)
obj-y += sensor_otp_coreprime3g_ve.o
else ifeq ($(CONFIG_MACH_J1MINI3G),y)
obj-y += sensor_hi544_otp.o
else
obj-y += sensor_otp.o
endif

