obj-$(CONFIG_SND_SOC_DBMD2) := dbmd2.o
obj-$(CONFIG_SND_SOC_DBMD2) += dbmd2-i2c.o
obj-$(CONFIG_SND_SOC_DBMD2) += dbmd2-uart.o
obj-$(CONFIG_SND_SOC_DBMD2) += dbmd2-i2s.o
obj-$(CONFIG_SND_SOC_DBMD2) += dbmd2-spi.o
obj-$(CONFIG_SND_SOC_DBMD2) += dbmd2-customer.o
obj-$(CONFIG_SND_SOC_DBMD2) += dbmd2-cdev.o
obj-$(CONFIG_SND_SOC_DBMD2) += dbmd2-event.o
