#
#Exynos Smart Secure Platform configuration
#

# Exynos Strong driver
strong-objs				:= exynos-ssp.o strong_mailbox_common.o strong_mailbox_ree.o

obj-$(CONFIG_EXYNOS_SSP)		+= strong.o

obj-$(CONFIG_EXYNOS_CAMELLIA_TEST)	+= camellia_test.o
