obj-$(CONFIG_TOUCHSCREEN_ILI9882N) +=   ili9881x.o \
	                                ili9881x_spi.o \
	                                ili9881x_qcom.o \
	                                ili9881x_ic.o \
	                                ili9881x_touch.o \
	                                ili9881x_mp.o \
	                                ili9881x_hostdl.o \
	                                ili9881x_node.o

