#
# Makefile for the Novatek NT36xxx touchscreen driver.
#

# Each configuration option enables a list of files.
# Tab A8 code for SR-AX6300-01-405 by luxinjun at 2021/09/09 start
obj-$(CONFIG_TOUCHSCREEN_NT36XXX_HOSTDL_SPI_A8) += nt36xxx.o nt36xxx_fw_update.o nt36xxx_ext_proc.o nt36xxx_mp_ctrlram.o nt36xxx_sec_fn.o
# Tab A8 code for SR-AX6300-01-405 by luxinjun at 2021/09/09 end