ccflags-y += -Idrivers/marvell/marvell-telephony/errorhandler
ccflags-y += -Idrivers/marvell/marvell-telephony/m3_rm
msocketk-objs := portqueue.o shm.o shm_map.o msocket.o acipcd.o data_path.o direct_rb.o tel_trace.o amipcd.o debugfs.o skb_llist.o common_regs.o
obj-$(CONFIG_MRVL_MMP_MODEM)	+= msocketk.o
