# SPDX-License-Identifier: GPL-2.0

#ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/mtk-interconnect/
#ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/cmdq/mailbox/
#ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/dma-buf/heaps/
#ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/media/platform/mtk-videobuf/
#ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/media/platform/mtk-isp/imgsys/
#ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/iommu
#ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/iommu

#mtk_aie-objs := \
mem/aie_videobuf2-dma-contig.o\
mem/aie_videobuf2-memops.o\
mem/aie_videobuf2-vmalloc.o\
mtk_aie_53.o\
mtk_aie_drv_isp71.o \
mtk_aie_drv_isp7s.o \
mtk_aie_drv_isp7sp.o

#obj-$(CONFIG_MTK_CAMERA_FD_ISP7S_ISP7SP) += mtk_aie.o
