# SPDX-License-Identifier: GPL-2.0
#
# Makefile for multifunction miscellaneous devices for samsung pmic
#

obj-$(CONFIG_MFD_S2MPS25)		+= s2mps25_mfd.o
s2mps25_mfd-$(CONFIG_MFD_S2MPS25)	+= s2mps25_core.o s2mps25_irq.o
obj-$(CONFIG_MFD_S2MPS26)		+= s2mps26_mfd.o
s2mps26_mfd-$(CONFIG_MFD_S2MPS26)	+= s2mps26_core.o s2mps26_notifier.o
obj-$(CONFIG_MFD_S2MPM07)		+= s2mpm07_mfd.o
s2mpm07_mfd-$(CONFIG_MFD_S2MPM07)	+= s2mpm07_core.o
obj-$(CONFIG_MFD_S2MPB02)		+= s2mpb02_mfd.o
s2mpb02_mfd-$(CONFIG_MFD_S2MPB02)	+= s2mpb02-core.o s2mpb02-irq.o
obj-$(CONFIG_MFD_S2MPS25_9935)		+= s2mps25_mfd.o
s2mps25_mfd-$(CONFIG_MFD_S2MPS25_9935)	+= s2mps25_core_9935.o s2mps25_irq_9935.o
obj-$(CONFIG_MFD_S2MPS26_9935)		+= s2mps26_mfd.o
s2mps26_mfd-$(CONFIG_MFD_S2MPS26_9935)	+= s2mps26_core_9935.o s2mps26_notifier_9935.o
obj-$(CONFIG_MFD_S2MPM07_9935)		+= s2mpm07_mfd.o
s2mpm07_mfd-$(CONFIG_MFD_S2MPM07_9935)	+= s2mpm07_core_9935.o
obj-$(CONFIG_MFD_S2MPA05_9935)		+= s2mpa05_mfd.o
s2mpa05_mfd-$(CONFIG_MFD_S2MPA05_9935)	+= s2mpa05_core_9935.o s2mpa05_notifier_9935.o
obj-$(CONFIG_MFD_S2MPU15_8535)		+= s2mpu15_mfd.o
s2mpu15_mfd-$(CONFIG_MFD_S2MPU15_8535)	+= s2mpu15_core_8535.o s2mpu15_irq_8535.o
obj-$(CONFIG_MFD_S2MPA05_8535)		+= s2mpa05_mfd.o
s2mpa05_mfd-$(CONFIG_MFD_S2MPA05_8535)	+= s2mpa05_core_8535.o s2mpa05_notifier_8535.o
obj-$(CONFIG_MFD_S2MPB06)		+= s2mpb06_mfd.o
s2mpb06_mfd-$(CONFIG_MFD_S2MPB06)	+= s2mpb06-core.o s2mpb06-irq.o
obj-$(CONFIG_MFD_S2MPU15_8835)		+= s2mpu15_mfd.o
s2mpu15_mfd-$(CONFIG_MFD_S2MPU15_8835)	+= s2mpu15_core_8835.o s2mpu15_irq_8835.o
obj-$(CONFIG_MFD_S2MPU16_8835)		+= s2mpu16_mfd.o
s2mpu16_mfd-$(CONFIG_MFD_S2MPU16_8835)	+= s2mpu16_core_8835.o s2mpu16_notifier_8835.o
