obj-$(CONFIG_SEC_CLASS)			+= class/
obj-$(CONFIG_SEC_KEY_NOTIFIER)		+= key_notifier/
obj-$(CONFIG_SEC_PARAM)			+= param/
obj-$(CONFIG_SEC_RELOC_GPIO)		+= reloc_gpio/
obj-$(CONFIG_SEC_SYSUP)			+= sysup/
obj-$(CONFIG_ARGOS)			+= argos/

obj-y					+= qcom/
