obj-$(CONFIG_SEC_CLASS)			+= class/
obj-$(CONFIG_SEC_KEY_NOTIFIER)		+= key_notifier/
obj-$(CONFIG_SEC_PARAM)			+= param/
obj-$(CONFIG_SEC_RELOC_GPIO)		+= reloc_gpio/
obj-$(CONFIG_ARGOS)			+= argos/
obj-$(CONFIG_SEC_OF_KUNIT)		+= of_kunit/

obj-y					+= qcom/
