obj-$(CONFIG_SPRDWL_NG) += sprdwl_ng.o
sprdwl_ng-objs += main.o
sprdwl_ng-objs += cfg80211.o
sprdwl_ng-objs += txrx.o
sprdwl_ng-objs += cmdevt.o
sprdwl_ng-objs += npi.o
sprdwl_ng-objs += wapi.o
sprdwl_ng-objs += msg.o
sprdwl_ng-objs += work.o
sprdwl_ng-objs += vendor.o

sprdwl_ng-$(CONFIG_SPRDWL_NG_SDIO) += sdio.o
sprdwl_ng-$(CONFIG_SPRDWL_NG_SDIO_BA) += sdio_ba.o
