#
# Makefile for muic devices
#
obj-$(CONFIG_MUIC_NOTIFIER_MODULE)	+= common_muic.o
common_muic-y	:= muic-core.o muic_notifier.o
obj-$(CONFIG_MUIC_SM5714)		+= common/
obj-$(CONFIG_MUIC_SM5714)		+= sm/sm5714/
