# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the sec_input drivers.
#

obj-$(CONFIG_SEC_DEBUG_TSP_LOG_LEGO) += sec_tsp_log.o
obj-$(CONFIG_INPUT_TOUCHSCREEN_TCLMV2_LEGO)	+= sec_tclm_v2.o
obj-$(CONFIG_INPUT_SEC_SECURE_TOUCH_LEGO)	+= sec_secure_touch.o
obj-$(CONFIG_TOUCHSCREEN_DUMP_MODE_LEGO)	+= sec_tsp_dumpkey.o
obj-$(CONFIG_INPUT_SEC_NOTIFIER_LEGO) += sec_input_notifier.o
obj-$(CONFIG_TOUCHSCREEN_DUAL_FOLDABLE_LEGO)	+= sec_virtual_tsp.o
obj-$(CONFIG_INPUT_SEC_INPUT_LEGO) += sec_common_fn.o sec_cmd.o