cmd_drivers/video/msm/mdss/samsung/ss_dsi_smart_dimming_common.o := /home/longjian.cui/SM-E7000_CHN_CHC_Kernel/scripts/gcc-wrapper.py /opt/toolchains/arm-eabi-4.7/bin/arm-eabi-gcc -Wp,-MD,drivers/video/msm/mdss/samsung/.ss_dsi_smart_dimming_common.o.d  -nostdinc -isystem /opt/toolchains/arm-eabi-4.7/bin/../lib/gcc/arm-eabi/4.7/include -I/home/longjian.cui/SM-E7000_CHN_CHC_Kernel/arch/arm/include -Iarch/arm/include/generated  -Iinclude -I/home/longjian.cui/SM-E7000_CHN_CHC_Kernel/arch/arm/include/uapi -Iarch/arm/include/generated/uapi -I/home/longjian.cui/SM-E7000_CHN_CHC_Kernel/include/uapi -Iinclude/generated/uapi -include /home/longjian.cui/SM-E7000_CHN_CHC_Kernel/include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Iarch/arm/mach-msm/include -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -fno-delete-null-pointer-checks -Os -Wno-maybe-uninitialized -fno-dwarf2-cfi-asm -fstack-protector -mabi=aapcs-linux -mno-thumb-interwork -funwind-tables -marm -D__LINUX_ARM_ARCH__=7 -march=armv7-a -msoft-float -Uarm -Wframe-larger-than=1024 -Wno-unused-but-set-variable -fomit-frame-pointer -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fconserve-stack -DCC_HAVE_ASM_GOTO    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(ss_dsi_smart_dimming_common)"  -D"KBUILD_MODNAME=KBUILD_STR(ss_dsi_smart_dimming_common)" -c -o drivers/video/msm/mdss/samsung/.tmp_ss_dsi_smart_dimming_common.o drivers/video/msm/mdss/samsung/ss_dsi_smart_dimming_common.c

source_drivers/video/msm/mdss/samsung/ss_dsi_smart_dimming_common.o := drivers/video/msm/mdss/samsung/ss_dsi_smart_dimming_common.c

deps_drivers/video/msm/mdss/samsung/ss_dsi_smart_dimming_common.o := \
  drivers/video/msm/mdss/samsung/ss_dsi_smart_dimming_common.h \

drivers/video/msm/mdss/samsung/ss_dsi_smart_dimming_common.o: $(deps_drivers/video/msm/mdss/samsung/ss_dsi_smart_dimming_common.o)

$(deps_drivers/video/msm/mdss/samsung/ss_dsi_smart_dimming_common.o):
