#
# Samsung Common file.
#
obj-y += ss_dsi_panel_common.o
obj-y += ss_dsi_mdnie_lite_common.o
obj-y += ss_dsi_smart_dimming_common.o

#
# panel directory make file
#

# K panel/Kcat6 panel/
obj-$(CONFIG_PANEL_S6E3FA2_AMS510CV01_FHD) += S6E3FA2_AMS510CV01/

# LENITS panel
obj-$(CONFIG_PANEL_S6E3HA0_AMS510CW01_WQHD) += S6E3HA0_AMS510CW01/

# TB panel
obj-$(CONFIG_PANEL_S6E3HF2_AMS559DE01_WQXGA) += S6E3HF2_AMS559DE01/

# TR panel
obj-$(CONFIG_PANEL_S6E3HA2_AMS567DJ01_WQHD) += S6E3HA2_AMS567DJ01/
