#
# Makefile for the CMUCAL drivers.
#
#obj-$(CONFIG_CAL_IF)			+= cmupmucal.o
#cmupmucal-$(CONFIG_PMUCAL)		+= pmucal_system.o pmucal_local.o pmucal_cpu.o pmucal_rae.o pmucal_powermode.o
#cmupmucal-$(CONFIG_PMUCAL_DBG)		+= pmucal_dbg.o
#cmupmucal-$(CONFIG_CP_PMUCAL) += pmucal_cp.o
#cmupmucal-$(CONFIG_GNSS_PMUCAL) += pmucal_gnss.o
#cmupmucal-$(CONFIG_CHUB_PMUCAL) += pmucal_chub.o
