sprd_debuglog_common := sprd_debuglog_core.o sprd_debuglog_drv.o

obj-$(CONFIG_SPRD_POWER_LOG_SHARKL6PRO)	+= sprd_powerlog_sharkl6pro.o
sprd_powerlog_sharkl6pro-objs := $(sprd_debuglog_common) sprd_debuglog_sharkl6pro.o

obj-$(CONFIG_SPRD_POWER_LOG_SHARKL6)	+= sprd_powerlog_sharkl6.o
sprd_powerlog_sharkl6-objs := $(sprd_debuglog_common) sprd_debuglog_sharkl6.o

obj-$(CONFIG_SPRD_POWER_LOG_SHARKL5PRO)	+= sprd_powerlog_sharkl5pro.o
sprd_powerlog_sharkl5pro-objs := $(sprd_debuglog_common) sprd_debuglog_sharkl5pro.o

obj-$(CONFIG_SPRD_POWER_LOG_SHARKL5)	+= sprd_powerlog_sharkl5.o
sprd_powerlog_sharkl5-objs := $(sprd_debuglog_common) sprd_debuglog_sharkl5.o

obj-$(CONFIG_SPRD_POWER_LOG_SHARKL3)	+= sprd_powerlog_sharkl3.o
sprd_powerlog_sharkl3-objs := $(sprd_debuglog_common) sprd_debuglog_sharkl3.o

obj-$(CONFIG_SPRD_POWER_LOG_SHARKLE)	+= sprd_powerlog_sharkle.o
sprd_powerlog_sharkle-objs := $(sprd_debuglog_common) sprd_debuglog_sharkle.o
