# SPDX-License-Identifier: GPL-2.0
#
# Makefile for samsung regulator drivers.
#

obj-$(CONFIG_DRV_SAMSUNG_PMIC) += pmic_class.o
obj-$(CONFIG_REGULATOR_S2MPS25)		+= s2mps25-regulator.o
s2mps25-regulator-$(CONFIG_REGULATOR_S2MPS25)	+= s2mps25_regulator.o s2mps25_powermeter.o
obj-$(CONFIG_REGULATOR_S2MPS26)		+= s2mps26-regulator.o
s2mps26-regulator-$(CONFIG_REGULATOR_S2MPS26)	+= s2mps26_regulator.o s2mps26_powermeter.o
obj-$(CONFIG_REGULATOR_S2MPM07) += s2mpm07_regulator.o
obj-$(CONFIG_REGULATOR_S2MPB02) += s2mpb02-regulator.o
obj-$(CONFIG_REGULATOR_S2MPB03) += s2mpb03.o
obj-$(CONFIG_REGULATOR_S2DOS05)		+= s2dos05-regulator.o
s2dos05-regulator-$(CONFIG_REGULATOR_S2DOS05)	+= s2dos05.o s2dos05_powermeter.o
obj-$(CONFIG_REGULATOR_S2MPS25_9935)		+= s2mps25-regulator.o
s2mps25-regulator-$(CONFIG_REGULATOR_S2MPS25_9935)	+= s2mps25_regulator_9935.o s2mps25_powermeter_9935.o
obj-$(CONFIG_REGULATOR_S2MPS26_9935)		+= s2mps26-regulator.o
s2mps26-regulator-$(CONFIG_REGULATOR_S2MPS26_9935)	+= s2mps26_regulator_9935.o s2mps26_powermeter_9935.o
obj-$(CONFIG_REGULATOR_S2MPM07_9935) += s2mpm07_regulator_9935.o
obj-$(CONFIG_REGULATOR_S2MPA05_9935) += s2mpa05_regulator_9935.o
obj-$(CONFIG_REGULATOR_S2MPU15_8535) += s2mpu15_regulator_8535.o
obj-$(CONFIG_REGULATOR_S2MPA05_8535) += s2mpa05_regulator_8535.o
obj-$(CONFIG_REGULATOR_S2MPB06) += s2mpb06-regulator.o
obj-$(CONFIG_REGULATOR_S2MPU15_8835) += s2mpu15_regulator_8835.o
obj-$(CONFIG_REGULATOR_S2MPU16_8835) += s2mpu16_regulator_8835.o
obj-$(CONFIG_REGULATOR_S2DPS01) += s2dps01.o
