# Samsung Connector Check Feature
obj-$(CONFIG_SEC_ABC_DETECT_CONN)	+= sec_abc_detect_conn.o
sec_abc_detect_conn-objs := connector_setup.o connector_state.o connector_disconnected_count.o
ccflags-y := -Wformat
