/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (C) 2019 MediaTek Inc.
 */

#ifndef __ECCCI_INTERNAL_OPTION__
#define __ECCCI_INTERNAL_OPTION__

#define MD_GENERATION       (6293)
#define CCCI_EE_OFFSET_EPON_MD3 (0x464)

#define ENABLE_MD_SEC_SMEM
#define ENABLE_SECURITY_SHARE_MEMORY
#define CUST_FT_DUMP_BUF_FROM_DT
#define CUST_FT_CARKIT_ENABLE
#define CUST_FT_BIGDATA
#define CUST_FT_EE_TRIGGER_REBOOT
#define CUST_FT_BUS_TIMEOUT_DEBUG
#define CUST_FT_EMI_DUMP_EN
#define CUST_FT_DEVAPC_MD_DEBUG
#define CUST_FT_SEND_TX_POWER

#endif
