/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2023 MediaTek Inc.
 */

#ifndef __INTFHUB_REGS_MT6985_H__
#define __INTFHUB_REGS_MT6985_H__

#include "common_def_id.h"

#ifndef REG_BASE_C_MODULE
// ----------------- INTFHUB Bit Field Definitions -------------------

extern unsigned long INTFHUB_BASE_MT6985;

#define DEV0_STA_ADDR                                    (INTFHUB_BASE_MT6985 + 0x00)
#define DEV0_STA_SET_ADDR                                (INTFHUB_BASE_MT6985 + 0x04)
#define DEV0_STA_CLR_ADDR                                (INTFHUB_BASE_MT6985 + 0x08)
#define DEV0_RX_ERR_CRC_STA_ADDR                         (INTFHUB_BASE_MT6985 + 0x10)
#define DEV1_RX_ERR_CRC_STA_ADDR                         (INTFHUB_BASE_MT6985 + 0x14)
#define DEV2_RX_ERR_CRC_STA_ADDR                         (INTFHUB_BASE_MT6985 + 0x18)
#define DEV0_PKT_CNT_ADDR                                (INTFHUB_BASE_MT6985 + 0x1C)
#define DEV0_CRC_STA_ADDR                                (INTFHUB_BASE_MT6985 + 0x20)
#define DEV0_IRQ_STA_ADDR                                (INTFHUB_BASE_MT6985 + 0x30)
#define DEV0_IRQ_CLR_ADDR                                (INTFHUB_BASE_MT6985 + 0x34)
#define DEV0_IRQ_MASK_ADDR                               (INTFHUB_BASE_MT6985 + 0x38)
#define DEV1_STA_ADDR                                    (INTFHUB_BASE_MT6985 + 0x40)
#define DEV1_STA_SET_ADDR                                (INTFHUB_BASE_MT6985 + 0x44)
#define DEV1_STA_CLR_ADDR                                (INTFHUB_BASE_MT6985 + 0x48)
#define DEV1_PKT_CNT_ADDR                                (INTFHUB_BASE_MT6985 + 0x50)
#define DEV1_CRC_STA_ADDR                                (INTFHUB_BASE_MT6985 + 0x54)
#define DEV2_STA_ADDR                                    (INTFHUB_BASE_MT6985 + 0x80)
#define DEV2_STA_SET_ADDR                                (INTFHUB_BASE_MT6985 + 0x84)
#define DEV2_STA_CLR_ADDR                                (INTFHUB_BASE_MT6985 + 0x88)
#define DEV2_PKT_CNT_ADDR                                (INTFHUB_BASE_MT6985 + 0x90)
#define DEV2_CRC_STA_ADDR                                (INTFHUB_BASE_MT6985 + 0x94)
#define CON0_ADDR                                        (INTFHUB_BASE_MT6985 + 0xC0)
#define CON1_ADDR                                        (INTFHUB_BASE_MT6985 + 0xC4)
#define CON2_ADDR                                        (INTFHUB_BASE_MT6985 + 0xC8)
#define CON3_ADDR                                        (INTFHUB_BASE_MT6985 + 0xCC)
#define IRQ_STA_ADDR                                     (INTFHUB_BASE_MT6985 + 0xD0)
#define IRQ_CLR_ADDR                                     (INTFHUB_BASE_MT6985 + 0xD4)
#define IRQ_MASK_ADDR                                    (INTFHUB_BASE_MT6985 + 0xD8)
#define STA0_ADDR                                        (INTFHUB_BASE_MT6985 + 0xE0)
#define LOOPBACK_ADDR                                    (INTFHUB_BASE_MT6985 + 0xE4)
#define CON4_ADDR                                        (INTFHUB_BASE_MT6985 + 0xF0)
#define DBG_ADDR                                         (INTFHUB_BASE_MT6985 + 0xF4)

#endif


#define DEV0_STA_FLD_dev0_intfhub_ready                        REG_FLD(1, 9)
#define DEV0_STA_FLD_dev0_intfhub_busy                         REG_FLD(1, 8)
#define DEV0_STA_FLD_dev0_hw_tx_busy                           REG_FLD(1, 3)
#define DEV0_STA_FLD_dev0_hw_rx_busy                           REG_FLD(1, 2)
#define DEV0_STA_FLD_dev0_sw_tx_sta                            REG_FLD(1, 1)
#define DEV0_STA_FLD_dev0_sw_rx_sta                            REG_FLD(1, 0)

#define DEV0_STA_SET_FLD_dev0_sw_tx_set                        REG_FLD(1, 1)
#define DEV0_STA_SET_FLD_dev0_sw_rx_set                        REG_FLD(1, 0)

#define DEV0_STA_CLR_FLD_dev0_hw_rx_clr                        REG_FLD(1, 2)
#define DEV0_STA_CLR_FLD_dev0_sw_tx_clr                        REG_FLD(1, 1)
#define DEV0_STA_CLR_FLD_dev0_sw_rx_clr                        REG_FLD(1, 0)

#define DEV0_RX_ERR_CRC_STA_FLD_dev0_rx_err_crc_result         REG_FLD(16, 16)
#define DEV0_RX_ERR_CRC_STA_FLD_dev0_rx_err_crc_data           REG_FLD(16, 0)

#define DEV1_RX_ERR_CRC_STA_FLD_dev1_rx_err_crc_result         REG_FLD(16, 16)
#define DEV1_RX_ERR_CRC_STA_FLD_dev1_rx_err_crc_data           REG_FLD(16, 0)

#define DEV2_RX_ERR_CRC_STA_FLD_dev2_rx_err_crc_result         REG_FLD(16, 16)
#define DEV2_RX_ERR_CRC_STA_FLD_dev2_rx_err_crc_data           REG_FLD(16, 0)

#define DEV0_PKT_CNT_FLD_dev0_tx_pkt_cnt                       REG_FLD(8, 24)
#define DEV0_PKT_CNT_FLD_dev0_tx_timeout_cnt                   REG_FLD(8, 16)
#define DEV0_PKT_CNT_FLD_dev0_rx_pkt_cnt                       REG_FLD(8, 8)
#define DEV0_PKT_CNT_FLD_dev0_rx_timeout_cnt                   REG_FLD(8, 0)

#define DEV0_CRC_STA_FLD_dev0_rx_crc_data                      REG_FLD(16, 16)
#define DEV0_CRC_STA_FLD_dev0_tx_crc_result                    REG_FLD(16, 0)

#define DEV0_IRQ_STA_FLD_intfhub_dev2_tx_err                   REG_FLD(1, 17)
#define DEV0_IRQ_STA_FLD_intfhub_dev1_tx_err                   REG_FLD(1, 16)
#define DEV0_IRQ_STA_FLD_intfhub_dev0_tx_err                   REG_FLD(1, 15)
#define DEV0_IRQ_STA_FLD_intfhub_dev_rx_err                    REG_FLD(1, 14)
#define DEV0_IRQ_STA_FLD_intfhub_restore_err                   REG_FLD(1, 13)
#define DEV0_IRQ_STA_FLD_rx_pkt_type_err                       REG_FLD(1, 12)
#define DEV0_IRQ_STA_FLD_dev2_rx_timeout_err                   REG_FLD(1, 11)
#define DEV0_IRQ_STA_FLD_dev1_rx_timeout_err                   REG_FLD(1, 10)
#define DEV0_IRQ_STA_FLD_dev0_rx_timeout_err                   REG_FLD(1, 9)
#define DEV0_IRQ_STA_FLD_dev2_tx_pkt_type_err                  REG_FLD(1, 8)
#define DEV0_IRQ_STA_FLD_dev1_tx_pkt_type_err                  REG_FLD(1, 7)
#define DEV0_IRQ_STA_FLD_dev0_tx_pkt_type_err                  REG_FLD(1, 6)
#define DEV0_IRQ_STA_FLD_dev2_tx_timeout_err                   REG_FLD(1, 5)
#define DEV0_IRQ_STA_FLD_dev1_tx_timeout_err                   REG_FLD(1, 4)
#define DEV0_IRQ_STA_FLD_dev0_tx_timeout_err                   REG_FLD(1, 3)
#define DEV0_IRQ_STA_FLD_dev2_crc_err                          REG_FLD(1, 2)
#define DEV0_IRQ_STA_FLD_dev1_crc_err                          REG_FLD(1, 1)
#define DEV0_IRQ_STA_FLD_dev0_crc_err                          REG_FLD(1, 0)

#define DEV0_IRQ_CLR_FLD_intfhub_dev2_tx_err_clr               REG_FLD(1, 17)
#define DEV0_IRQ_CLR_FLD_intfhub_dev1_tx_err_clr               REG_FLD(1, 16)
#define DEV0_IRQ_CLR_FLD_intfhub_dev0_tx_err_clr               REG_FLD(1, 15)
#define DEV0_IRQ_CLR_FLD_intfhub_dev_rx_err_clr                REG_FLD(1, 14)
#define DEV0_IRQ_CLR_FLD_intfhub_restore_err_clr               REG_FLD(1, 13)
#define DEV0_IRQ_CLR_FLD_rx_pkt_type_err_clr                   REG_FLD(1, 12)
#define DEV0_IRQ_CLR_FLD_dev2_rx_timeout_err_clr               REG_FLD(1, 11)
#define DEV0_IRQ_CLR_FLD_dev1_rx_timeout_err_clr               REG_FLD(1, 10)
#define DEV0_IRQ_CLR_FLD_dev0_rx_timeout_err_clr               REG_FLD(1, 9)
#define DEV0_IRQ_CLR_FLD_dev2_tx_pkt_type_err_clr              REG_FLD(1, 8)
#define DEV0_IRQ_CLR_FLD_dev1_tx_pkt_type_err_clr              REG_FLD(1, 7)
#define DEV0_IRQ_CLR_FLD_dev0_tx_pkt_type_err_clr              REG_FLD(1, 6)
#define DEV0_IRQ_CLR_FLD_dev2_tx_timeout_err_clr               REG_FLD(1, 5)
#define DEV0_IRQ_CLR_FLD_dev1_tx_timeout_err_clr               REG_FLD(1, 4)
#define DEV0_IRQ_CLR_FLD_dev0_tx_timeout_err_clr               REG_FLD(1, 3)
#define DEV0_IRQ_CLR_FLD_dev2_crc_err_clr                      REG_FLD(1, 2)
#define DEV0_IRQ_CLR_FLD_dev1_crc_err_clr                      REG_FLD(1, 1)
#define DEV0_IRQ_CLR_FLD_dev0_crc_err_clr                      REG_FLD(1, 0)

#define DEV0_IRQ_MASK_FLD_intfhub_dev2_tx_err_mask             REG_FLD(1, 17)
#define DEV0_IRQ_MASK_FLD_intfhub_dev1_tx_err_mask             REG_FLD(1, 16)
#define DEV0_IRQ_MASK_FLD_intfhub_dev0_tx_err_mask             REG_FLD(1, 15)
#define DEV0_IRQ_MASK_FLD_intfhub_dev_rx_err_mask              REG_FLD(1, 14)
#define DEV0_IRQ_MASK_FLD_intfhub_restore_err_mask             REG_FLD(1, 13)
#define DEV0_IRQ_MASK_FLD_rx_pkt_type_err_mask                 REG_FLD(1, 12)
#define DEV0_IRQ_MASK_FLD_dev2_rx_timeout_err_mask             REG_FLD(1, 11)
#define DEV0_IRQ_MASK_FLD_dev1_rx_timeout_err_mask             REG_FLD(1, 10)
#define DEV0_IRQ_MASK_FLD_dev0_rx_timeout_err_mask             REG_FLD(1, 9)
#define DEV0_IRQ_MASK_FLD_dev2_tx_pkt_type_err_mask            REG_FLD(1, 8)
#define DEV0_IRQ_MASK_FLD_dev1_tx_pkt_type_err_mask            REG_FLD(1, 7)
#define DEV0_IRQ_MASK_FLD_dev0_tx_pkt_type_err_mask            REG_FLD(1, 6)
#define DEV0_IRQ_MASK_FLD_dev2_tx_timeout_err_mask             REG_FLD(1, 5)
#define DEV0_IRQ_MASK_FLD_dev1_tx_timeout_err_mask             REG_FLD(1, 4)
#define DEV0_IRQ_MASK_FLD_dev0_tx_timeout_err_mask             REG_FLD(1, 3)
#define DEV0_IRQ_MASK_FLD_dev2_crc_err_mask                    REG_FLD(1, 2)
#define DEV0_IRQ_MASK_FLD_dev1_crc_err_mask                    REG_FLD(1, 1)
#define DEV0_IRQ_MASK_FLD_dev0_crc_err_mask                    REG_FLD(1, 0)

#define DEV1_STA_FLD_dev1_intfhub_ready                        REG_FLD(1, 9)
#define DEV1_STA_FLD_dev1_intfhub_busy                         REG_FLD(1, 8)
#define DEV1_STA_FLD_dev1_hw_tx_busy                           REG_FLD(1, 3)
#define DEV1_STA_FLD_dev1_hw_rx_busy                           REG_FLD(1, 2)
#define DEV1_STA_FLD_dev1_sw_tx_sta                            REG_FLD(1, 1)
#define DEV1_STA_FLD_dev1_sw_rx_sta                            REG_FLD(1, 0)

#define DEV1_STA_SET_FLD_dev1_sw_tx_set                        REG_FLD(1, 1)
#define DEV1_STA_SET_FLD_dev1_sw_rx_set                        REG_FLD(1, 0)

#define DEV1_STA_CLR_FLD_dev1_hw_rx_clr                        REG_FLD(1, 2)
#define DEV1_STA_CLR_FLD_dev1_sw_tx_clr                        REG_FLD(1, 1)
#define DEV1_STA_CLR_FLD_dev1_sw_rx_clr                        REG_FLD(1, 0)

#define DEV1_PKT_CNT_FLD_dev1_tx_pkt_cnt                       REG_FLD(8, 24)
#define DEV1_PKT_CNT_FLD_dev1_tx_timeout_cnt                   REG_FLD(8, 16)
#define DEV1_PKT_CNT_FLD_dev1_rx_pkt_cnt                       REG_FLD(8, 8)
#define DEV1_PKT_CNT_FLD_dev1_rx_timeout_cnt                   REG_FLD(8, 0)

#define DEV1_CRC_STA_FLD_dev1_rx_crc_data                      REG_FLD(16, 16)
#define DEV1_CRC_STA_FLD_dev1_tx_crc_result                    REG_FLD(16, 0)

#define DEV2_STA_FLD_dev2_intfhub_ready                        REG_FLD(1, 9)
#define DEV2_STA_FLD_dev2_intfhub_busy                         REG_FLD(1, 8)
#define DEV2_STA_FLD_dev2_hw_tx_busy                           REG_FLD(1, 3)
#define DEV2_STA_FLD_dev2_hw_rx_busy                           REG_FLD(1, 2)
#define DEV2_STA_FLD_dev2_sw_tx_sta                            REG_FLD(1, 1)
#define DEV2_STA_FLD_dev2_sw_rx_sta                            REG_FLD(1, 0)

#define DEV2_STA_SET_FLD_dev2_sw_tx_set                        REG_FLD(1, 1)
#define DEV2_STA_SET_FLD_dev2_sw_rx_set                        REG_FLD(1, 0)

#define DEV2_STA_CLR_FLD_dev2_hw_rx_clr                        REG_FLD(1, 2)
#define DEV2_STA_CLR_FLD_dev2_sw_tx_clr                        REG_FLD(1, 1)
#define DEV2_STA_CLR_FLD_dev2_sw_rx_clr                        REG_FLD(1, 0)

#define DEV2_PKT_CNT_FLD_dev2_tx_pkt_cnt                       REG_FLD(8, 24)
#define DEV2_PKT_CNT_FLD_dev2_tx_timeout_cnt                   REG_FLD(8, 16)
#define DEV2_PKT_CNT_FLD_dev2_rx_pkt_cnt                       REG_FLD(8, 8)
#define DEV2_PKT_CNT_FLD_dev2_rx_timeout_cnt                   REG_FLD(8, 0)

#define DEV2_CRC_STA_FLD_dev2_rx_crc_data                      REG_FLD(16, 16)
#define DEV2_CRC_STA_FLD_dev2_tx_crc_result                    REG_FLD(16, 0)

#define CON0_FLD_dev1_pkt_type_end                             REG_FLD(8, 24)
#define CON0_FLD_dev1_pkt_type_start                           REG_FLD(8, 16)
#define CON0_FLD_dev0_pkt_type_end                             REG_FLD(8, 8)
#define CON0_FLD_dev0_pkt_type_start                           REG_FLD(8, 0)

#define CON1_FLD_dev2_pkt_type_end                             REG_FLD(8, 8)
#define CON1_FLD_dev2_pkt_type_start                           REG_FLD(8, 0)

#define CON2_FLD_intfhub_bypass                                REG_FLD(1, 2)
#define CON2_FLD_crc_en                                        REG_FLD(1, 1)

#define CON3_FLD_dev_timeout_time                              REG_FLD(4, 24)
#define CON3_FLD_dev2_header_mode                              REG_FLD(2, 20)
#define CON3_FLD_dev1_header_mode                              REG_FLD(2, 18)
#define CON3_FLD_dev0_header_mode                              REG_FLD(2, 16)
#define CON3_FLD_dev_wdata_addr                                REG_FLD(8, 8)
#define CON3_FLD_dev_rdata_addr                                REG_FLD(8, 0)

#define IRQ_STA_FLD_intfhub_ckon_req                           REG_FLD(1, 2)
#define IRQ_STA_FLD_intfhub_ckoff_req                          REG_FLD(1, 1)
#define IRQ_STA_FLD_intfhub_restore_req                        REG_FLD(1, 0)

#define IRQ_CLR_FLD_intfhub_ckon_req_clr                       REG_FLD(1, 2)
#define IRQ_CLR_FLD_intfhub_ckoff_req_clr                      REG_FLD(1, 1)
#define IRQ_CLR_FLD_intfhub_restore_req_clr                    REG_FLD(1, 0)

#define IRQ_MASK_FLD_intfhub_ckon_req_mask                     REG_FLD(1, 2)
#define IRQ_MASK_FLD_intfhub_ckoff_req_mask                    REG_FLD(1, 1)
#define IRQ_MASK_FLD_intfhub_restore_req_mask                  REG_FLD(1, 0)

#define STA0_FLD_intfhub_busy                                  REG_FLD(1, 1)
#define STA0_FLD_intfhub_active                                REG_FLD(1, 0)

#define LOOPBACK_FLD_dev2_rx2tx_loopback                       REG_FLD(1, 5)
#define LOOPBACK_FLD_dev2_tx2rx_loopback                       REG_FLD(1, 4)
#define LOOPBACK_FLD_dev1_rx2tx_loopback                       REG_FLD(1, 3)
#define LOOPBACK_FLD_dev1_tx2rx_loopback                       REG_FLD(1, 2)
#define LOOPBACK_FLD_dev0_rx2tx_loopback                       REG_FLD(1, 1)
#define LOOPBACK_FLD_dev0_tx2rx_loopback                       REG_FLD(1, 0)

#define CON4_FLD_sw3_rst                                       REG_FLD(1, 3)
#define CON4_FLD_sw2_rst                                       REG_FLD(1, 2)
#define CON4_FLD_sw_rst                                        REG_FLD(1, 1)
#define CON4_FLD_intfhub_sw_on_trg                             REG_FLD(1, 0)

#define DBG_FLD_intfhub_dbg_sel                                REG_FLD(4, 0)

#define DEV0_STA_GET_dev0_intfhub_ready(reg32)                 REG_FLD_GET(DEV0_STA_FLD_dev0_intfhub_ready, (reg32))
#define DEV0_STA_GET_dev0_intfhub_busy(reg32)                  REG_FLD_GET(DEV0_STA_FLD_dev0_intfhub_busy, (reg32))
#define DEV0_STA_GET_dev0_hw_tx_busy(reg32)                    REG_FLD_GET(DEV0_STA_FLD_dev0_hw_tx_busy, (reg32))
#define DEV0_STA_GET_dev0_hw_rx_busy(reg32)                    REG_FLD_GET(DEV0_STA_FLD_dev0_hw_rx_busy, (reg32))
#define DEV0_STA_GET_dev0_sw_tx_sta(reg32)                     REG_FLD_GET(DEV0_STA_FLD_dev0_sw_tx_sta, (reg32))
#define DEV0_STA_GET_dev0_sw_rx_sta(reg32)                     REG_FLD_GET(DEV0_STA_FLD_dev0_sw_rx_sta, (reg32))

#define DEV0_STA_SET_GET_dev0_sw_tx_set(reg32)                 REG_FLD_GET(DEV0_STA_SET_FLD_dev0_sw_tx_set, (reg32))
#define DEV0_STA_SET_GET_dev0_sw_rx_set(reg32)                 REG_FLD_GET(DEV0_STA_SET_FLD_dev0_sw_rx_set, (reg32))

#define DEV0_STA_CLR_GET_dev0_hw_rx_clr(reg32)                 REG_FLD_GET(DEV0_STA_CLR_FLD_dev0_hw_rx_clr, (reg32))
#define DEV0_STA_CLR_GET_dev0_sw_tx_clr(reg32)                 REG_FLD_GET(DEV0_STA_CLR_FLD_dev0_sw_tx_clr, (reg32))
#define DEV0_STA_CLR_GET_dev0_sw_rx_clr(reg32)                 REG_FLD_GET(DEV0_STA_CLR_FLD_dev0_sw_rx_clr, (reg32))

#define DEV0_RX_ERR_CRC_STA_GET_dev0_rx_err_crc_result(reg32)  REG_FLD_GET(DEV0_RX_ERR_CRC_STA_FLD_dev0_rx_err_crc_result, (reg32))
#define DEV0_RX_ERR_CRC_STA_GET_dev0_rx_err_crc_data(reg32)    REG_FLD_GET(DEV0_RX_ERR_CRC_STA_FLD_dev0_rx_err_crc_data, (reg32))

#define DEV1_RX_ERR_CRC_STA_GET_dev1_rx_err_crc_result(reg32)  REG_FLD_GET(DEV1_RX_ERR_CRC_STA_FLD_dev1_rx_err_crc_result, (reg32))
#define DEV1_RX_ERR_CRC_STA_GET_dev1_rx_err_crc_data(reg32)    REG_FLD_GET(DEV1_RX_ERR_CRC_STA_FLD_dev1_rx_err_crc_data, (reg32))

#define DEV2_RX_ERR_CRC_STA_GET_dev2_rx_err_crc_result(reg32)  REG_FLD_GET(DEV2_RX_ERR_CRC_STA_FLD_dev2_rx_err_crc_result, (reg32))
#define DEV2_RX_ERR_CRC_STA_GET_dev2_rx_err_crc_data(reg32)    REG_FLD_GET(DEV2_RX_ERR_CRC_STA_FLD_dev2_rx_err_crc_data, (reg32))

#define DEV0_PKT_CNT_GET_dev0_tx_pkt_cnt(reg32)                REG_FLD_GET(DEV0_PKT_CNT_FLD_dev0_tx_pkt_cnt, (reg32))
#define DEV0_PKT_CNT_GET_dev0_tx_timeout_cnt(reg32)            REG_FLD_GET(DEV0_PKT_CNT_FLD_dev0_tx_timeout_cnt, (reg32))
#define DEV0_PKT_CNT_GET_dev0_rx_pkt_cnt(reg32)                REG_FLD_GET(DEV0_PKT_CNT_FLD_dev0_rx_pkt_cnt, (reg32))
#define DEV0_PKT_CNT_GET_dev0_rx_timeout_cnt(reg32)            REG_FLD_GET(DEV0_PKT_CNT_FLD_dev0_rx_timeout_cnt, (reg32))

#define DEV0_CRC_STA_GET_dev0_rx_crc_data(reg32)               REG_FLD_GET(DEV0_CRC_STA_FLD_dev0_rx_crc_data, (reg32))
#define DEV0_CRC_STA_GET_dev0_tx_crc_result(reg32)             REG_FLD_GET(DEV0_CRC_STA_FLD_dev0_tx_crc_result, (reg32))

#define DEV0_IRQ_STA_GET_intfhub_dev2_tx_err(reg32)            REG_FLD_GET(DEV0_IRQ_STA_FLD_intfhub_dev2_tx_err, (reg32))
#define DEV0_IRQ_STA_GET_intfhub_dev1_tx_err(reg32)            REG_FLD_GET(DEV0_IRQ_STA_FLD_intfhub_dev1_tx_err, (reg32))
#define DEV0_IRQ_STA_GET_intfhub_dev0_tx_err(reg32)            REG_FLD_GET(DEV0_IRQ_STA_FLD_intfhub_dev0_tx_err, (reg32))
#define DEV0_IRQ_STA_GET_intfhub_dev_rx_err(reg32)             REG_FLD_GET(DEV0_IRQ_STA_FLD_intfhub_dev_rx_err, (reg32))
#define DEV0_IRQ_STA_GET_intfhub_restore_err(reg32)            REG_FLD_GET(DEV0_IRQ_STA_FLD_intfhub_restore_err, (reg32))
#define DEV0_IRQ_STA_GET_rx_pkt_type_err(reg32)                REG_FLD_GET(DEV0_IRQ_STA_FLD_rx_pkt_type_err, (reg32))
#define DEV0_IRQ_STA_GET_dev2_rx_timeout_err(reg32)            REG_FLD_GET(DEV0_IRQ_STA_FLD_dev2_rx_timeout_err, (reg32))
#define DEV0_IRQ_STA_GET_dev1_rx_timeout_err(reg32)            REG_FLD_GET(DEV0_IRQ_STA_FLD_dev1_rx_timeout_err, (reg32))
#define DEV0_IRQ_STA_GET_dev0_rx_timeout_err(reg32)            REG_FLD_GET(DEV0_IRQ_STA_FLD_dev0_rx_timeout_err, (reg32))
#define DEV0_IRQ_STA_GET_dev2_tx_pkt_type_err(reg32)           REG_FLD_GET(DEV0_IRQ_STA_FLD_dev2_tx_pkt_type_err, (reg32))
#define DEV0_IRQ_STA_GET_dev1_tx_pkt_type_err(reg32)           REG_FLD_GET(DEV0_IRQ_STA_FLD_dev1_tx_pkt_type_err, (reg32))
#define DEV0_IRQ_STA_GET_dev0_tx_pkt_type_err(reg32)           REG_FLD_GET(DEV0_IRQ_STA_FLD_dev0_tx_pkt_type_err, (reg32))
#define DEV0_IRQ_STA_GET_dev2_tx_timeout_err(reg32)            REG_FLD_GET(DEV0_IRQ_STA_FLD_dev2_tx_timeout_err, (reg32))
#define DEV0_IRQ_STA_GET_dev1_tx_timeout_err(reg32)            REG_FLD_GET(DEV0_IRQ_STA_FLD_dev1_tx_timeout_err, (reg32))
#define DEV0_IRQ_STA_GET_dev0_tx_timeout_err(reg32)            REG_FLD_GET(DEV0_IRQ_STA_FLD_dev0_tx_timeout_err, (reg32))
#define DEV0_IRQ_STA_GET_dev2_crc_err(reg32)                   REG_FLD_GET(DEV0_IRQ_STA_FLD_dev2_crc_err, (reg32))
#define DEV0_IRQ_STA_GET_dev1_crc_err(reg32)                   REG_FLD_GET(DEV0_IRQ_STA_FLD_dev1_crc_err, (reg32))
#define DEV0_IRQ_STA_GET_dev0_crc_err(reg32)                   REG_FLD_GET(DEV0_IRQ_STA_FLD_dev0_crc_err, (reg32))

#define DEV0_IRQ_CLR_GET_intfhub_dev2_tx_err_clr(reg32)        REG_FLD_GET(DEV0_IRQ_CLR_FLD_intfhub_dev2_tx_err_clr, (reg32))
#define DEV0_IRQ_CLR_GET_intfhub_dev1_tx_err_clr(reg32)        REG_FLD_GET(DEV0_IRQ_CLR_FLD_intfhub_dev1_tx_err_clr, (reg32))
#define DEV0_IRQ_CLR_GET_intfhub_dev0_tx_err_clr(reg32)        REG_FLD_GET(DEV0_IRQ_CLR_FLD_intfhub_dev0_tx_err_clr, (reg32))
#define DEV0_IRQ_CLR_GET_intfhub_dev_rx_err_clr(reg32)         REG_FLD_GET(DEV0_IRQ_CLR_FLD_intfhub_dev_rx_err_clr, (reg32))
#define DEV0_IRQ_CLR_GET_intfhub_restore_err_clr(reg32)        REG_FLD_GET(DEV0_IRQ_CLR_FLD_intfhub_restore_err_clr, (reg32))
#define DEV0_IRQ_CLR_GET_rx_pkt_type_err_clr(reg32)            REG_FLD_GET(DEV0_IRQ_CLR_FLD_rx_pkt_type_err_clr, (reg32))
#define DEV0_IRQ_CLR_GET_dev2_rx_timeout_err_clr(reg32)        REG_FLD_GET(DEV0_IRQ_CLR_FLD_dev2_rx_timeout_err_clr, (reg32))
#define DEV0_IRQ_CLR_GET_dev1_rx_timeout_err_clr(reg32)        REG_FLD_GET(DEV0_IRQ_CLR_FLD_dev1_rx_timeout_err_clr, (reg32))
#define DEV0_IRQ_CLR_GET_dev0_rx_timeout_err_clr(reg32)        REG_FLD_GET(DEV0_IRQ_CLR_FLD_dev0_rx_timeout_err_clr, (reg32))
#define DEV0_IRQ_CLR_GET_dev2_tx_pkt_type_err_clr(reg32)       REG_FLD_GET(DEV0_IRQ_CLR_FLD_dev2_tx_pkt_type_err_clr, (reg32))
#define DEV0_IRQ_CLR_GET_dev1_tx_pkt_type_err_clr(reg32)       REG_FLD_GET(DEV0_IRQ_CLR_FLD_dev1_tx_pkt_type_err_clr, (reg32))
#define DEV0_IRQ_CLR_GET_dev0_tx_pkt_type_err_clr(reg32)       REG_FLD_GET(DEV0_IRQ_CLR_FLD_dev0_tx_pkt_type_err_clr, (reg32))
#define DEV0_IRQ_CLR_GET_dev2_tx_timeout_err_clr(reg32)        REG_FLD_GET(DEV0_IRQ_CLR_FLD_dev2_tx_timeout_err_clr, (reg32))
#define DEV0_IRQ_CLR_GET_dev1_tx_timeout_err_clr(reg32)        REG_FLD_GET(DEV0_IRQ_CLR_FLD_dev1_tx_timeout_err_clr, (reg32))
#define DEV0_IRQ_CLR_GET_dev0_tx_timeout_err_clr(reg32)        REG_FLD_GET(DEV0_IRQ_CLR_FLD_dev0_tx_timeout_err_clr, (reg32))
#define DEV0_IRQ_CLR_GET_dev2_crc_err_clr(reg32)               REG_FLD_GET(DEV0_IRQ_CLR_FLD_dev2_crc_err_clr, (reg32))
#define DEV0_IRQ_CLR_GET_dev1_crc_err_clr(reg32)               REG_FLD_GET(DEV0_IRQ_CLR_FLD_dev1_crc_err_clr, (reg32))
#define DEV0_IRQ_CLR_GET_dev0_crc_err_clr(reg32)               REG_FLD_GET(DEV0_IRQ_CLR_FLD_dev0_crc_err_clr, (reg32))

#define DEV0_IRQ_MASK_GET_intfhub_dev2_tx_err_mask(reg32)      REG_FLD_GET(DEV0_IRQ_MASK_FLD_intfhub_dev2_tx_err_mask, (reg32))
#define DEV0_IRQ_MASK_GET_intfhub_dev1_tx_err_mask(reg32)      REG_FLD_GET(DEV0_IRQ_MASK_FLD_intfhub_dev1_tx_err_mask, (reg32))
#define DEV0_IRQ_MASK_GET_intfhub_dev0_tx_err_mask(reg32)      REG_FLD_GET(DEV0_IRQ_MASK_FLD_intfhub_dev0_tx_err_mask, (reg32))
#define DEV0_IRQ_MASK_GET_intfhub_dev_rx_err_mask(reg32)       REG_FLD_GET(DEV0_IRQ_MASK_FLD_intfhub_dev_rx_err_mask, (reg32))
#define DEV0_IRQ_MASK_GET_intfhub_restore_err_mask(reg32)      REG_FLD_GET(DEV0_IRQ_MASK_FLD_intfhub_restore_err_mask, (reg32))
#define DEV0_IRQ_MASK_GET_rx_pkt_type_err_mask(reg32)          REG_FLD_GET(DEV0_IRQ_MASK_FLD_rx_pkt_type_err_mask, (reg32))
#define DEV0_IRQ_MASK_GET_dev2_rx_timeout_err_mask(reg32)      REG_FLD_GET(DEV0_IRQ_MASK_FLD_dev2_rx_timeout_err_mask, (reg32))
#define DEV0_IRQ_MASK_GET_dev1_rx_timeout_err_mask(reg32)      REG_FLD_GET(DEV0_IRQ_MASK_FLD_dev1_rx_timeout_err_mask, (reg32))
#define DEV0_IRQ_MASK_GET_dev0_rx_timeout_err_mask(reg32)      REG_FLD_GET(DEV0_IRQ_MASK_FLD_dev0_rx_timeout_err_mask, (reg32))
#define DEV0_IRQ_MASK_GET_dev2_tx_pkt_type_err_mask(reg32)     REG_FLD_GET(DEV0_IRQ_MASK_FLD_dev2_tx_pkt_type_err_mask, (reg32))
#define DEV0_IRQ_MASK_GET_dev1_tx_pkt_type_err_mask(reg32)     REG_FLD_GET(DEV0_IRQ_MASK_FLD_dev1_tx_pkt_type_err_mask, (reg32))
#define DEV0_IRQ_MASK_GET_dev0_tx_pkt_type_err_mask(reg32)     REG_FLD_GET(DEV0_IRQ_MASK_FLD_dev0_tx_pkt_type_err_mask, (reg32))
#define DEV0_IRQ_MASK_GET_dev2_tx_timeout_err_mask(reg32)      REG_FLD_GET(DEV0_IRQ_MASK_FLD_dev2_tx_timeout_err_mask, (reg32))
#define DEV0_IRQ_MASK_GET_dev1_tx_timeout_err_mask(reg32)      REG_FLD_GET(DEV0_IRQ_MASK_FLD_dev1_tx_timeout_err_mask, (reg32))
#define DEV0_IRQ_MASK_GET_dev0_tx_timeout_err_mask(reg32)      REG_FLD_GET(DEV0_IRQ_MASK_FLD_dev0_tx_timeout_err_mask, (reg32))
#define DEV0_IRQ_MASK_GET_dev2_crc_err_mask(reg32)             REG_FLD_GET(DEV0_IRQ_MASK_FLD_dev2_crc_err_mask, (reg32))
#define DEV0_IRQ_MASK_GET_dev1_crc_err_mask(reg32)             REG_FLD_GET(DEV0_IRQ_MASK_FLD_dev1_crc_err_mask, (reg32))
#define DEV0_IRQ_MASK_GET_dev0_crc_err_mask(reg32)             REG_FLD_GET(DEV0_IRQ_MASK_FLD_dev0_crc_err_mask, (reg32))

#define DEV1_STA_GET_dev1_intfhub_ready(reg32)                 REG_FLD_GET(DEV1_STA_FLD_dev1_intfhub_ready, (reg32))
#define DEV1_STA_GET_dev1_intfhub_busy(reg32)                  REG_FLD_GET(DEV1_STA_FLD_dev1_intfhub_busy, (reg32))
#define DEV1_STA_GET_dev1_hw_tx_busy(reg32)                    REG_FLD_GET(DEV1_STA_FLD_dev1_hw_tx_busy, (reg32))
#define DEV1_STA_GET_dev1_hw_rx_busy(reg32)                    REG_FLD_GET(DEV1_STA_FLD_dev1_hw_rx_busy, (reg32))
#define DEV1_STA_GET_dev1_sw_tx_sta(reg32)                     REG_FLD_GET(DEV1_STA_FLD_dev1_sw_tx_sta, (reg32))
#define DEV1_STA_GET_dev1_sw_rx_sta(reg32)                     REG_FLD_GET(DEV1_STA_FLD_dev1_sw_rx_sta, (reg32))

#define DEV1_STA_SET_GET_dev1_sw_tx_set(reg32)                 REG_FLD_GET(DEV1_STA_SET_FLD_dev1_sw_tx_set, (reg32))
#define DEV1_STA_SET_GET_dev1_sw_rx_set(reg32)                 REG_FLD_GET(DEV1_STA_SET_FLD_dev1_sw_rx_set, (reg32))

#define DEV1_STA_CLR_GET_dev1_hw_rx_clr(reg32)                 REG_FLD_GET(DEV1_STA_CLR_FLD_dev1_hw_rx_clr, (reg32))
#define DEV1_STA_CLR_GET_dev1_sw_tx_clr(reg32)                 REG_FLD_GET(DEV1_STA_CLR_FLD_dev1_sw_tx_clr, (reg32))
#define DEV1_STA_CLR_GET_dev1_sw_rx_clr(reg32)                 REG_FLD_GET(DEV1_STA_CLR_FLD_dev1_sw_rx_clr, (reg32))

#define DEV1_PKT_CNT_GET_dev1_tx_pkt_cnt(reg32)                REG_FLD_GET(DEV1_PKT_CNT_FLD_dev1_tx_pkt_cnt, (reg32))
#define DEV1_PKT_CNT_GET_dev1_tx_timeout_cnt(reg32)            REG_FLD_GET(DEV1_PKT_CNT_FLD_dev1_tx_timeout_cnt, (reg32))
#define DEV1_PKT_CNT_GET_dev1_rx_pkt_cnt(reg32)                REG_FLD_GET(DEV1_PKT_CNT_FLD_dev1_rx_pkt_cnt, (reg32))
#define DEV1_PKT_CNT_GET_dev1_rx_timeout_cnt(reg32)            REG_FLD_GET(DEV1_PKT_CNT_FLD_dev1_rx_timeout_cnt, (reg32))

#define DEV1_CRC_STA_GET_dev1_rx_crc_data(reg32)               REG_FLD_GET(DEV1_CRC_STA_FLD_dev1_rx_crc_data, (reg32))
#define DEV1_CRC_STA_GET_dev1_tx_crc_result(reg32)             REG_FLD_GET(DEV1_CRC_STA_FLD_dev1_tx_crc_result, (reg32))

#define DEV2_STA_GET_dev2_intfhub_ready(reg32)                 REG_FLD_GET(DEV2_STA_FLD_dev2_intfhub_ready, (reg32))
#define DEV2_STA_GET_dev2_intfhub_busy(reg32)                  REG_FLD_GET(DEV2_STA_FLD_dev2_intfhub_busy, (reg32))
#define DEV2_STA_GET_dev2_hw_tx_busy(reg32)                    REG_FLD_GET(DEV2_STA_FLD_dev2_hw_tx_busy, (reg32))
#define DEV2_STA_GET_dev2_hw_rx_busy(reg32)                    REG_FLD_GET(DEV2_STA_FLD_dev2_hw_rx_busy, (reg32))
#define DEV2_STA_GET_dev2_sw_tx_sta(reg32)                     REG_FLD_GET(DEV2_STA_FLD_dev2_sw_tx_sta, (reg32))
#define DEV2_STA_GET_dev2_sw_rx_sta(reg32)                     REG_FLD_GET(DEV2_STA_FLD_dev2_sw_rx_sta, (reg32))

#define DEV2_STA_SET_GET_dev2_sw_tx_set(reg32)                 REG_FLD_GET(DEV2_STA_SET_FLD_dev2_sw_tx_set, (reg32))
#define DEV2_STA_SET_GET_dev2_sw_rx_set(reg32)                 REG_FLD_GET(DEV2_STA_SET_FLD_dev2_sw_rx_set, (reg32))

#define DEV2_STA_CLR_GET_dev2_hw_rx_clr(reg32)                 REG_FLD_GET(DEV2_STA_CLR_FLD_dev2_hw_rx_clr, (reg32))
#define DEV2_STA_CLR_GET_dev2_sw_tx_clr(reg32)                 REG_FLD_GET(DEV2_STA_CLR_FLD_dev2_sw_tx_clr, (reg32))
#define DEV2_STA_CLR_GET_dev2_sw_rx_clr(reg32)                 REG_FLD_GET(DEV2_STA_CLR_FLD_dev2_sw_rx_clr, (reg32))

#define DEV2_PKT_CNT_GET_dev2_tx_pkt_cnt(reg32)                REG_FLD_GET(DEV2_PKT_CNT_FLD_dev2_tx_pkt_cnt, (reg32))
#define DEV2_PKT_CNT_GET_dev2_tx_timeout_cnt(reg32)            REG_FLD_GET(DEV2_PKT_CNT_FLD_dev2_tx_timeout_cnt, (reg32))
#define DEV2_PKT_CNT_GET_dev2_rx_pkt_cnt(reg32)                REG_FLD_GET(DEV2_PKT_CNT_FLD_dev2_rx_pkt_cnt, (reg32))
#define DEV2_PKT_CNT_GET_dev2_rx_timeout_cnt(reg32)            REG_FLD_GET(DEV2_PKT_CNT_FLD_dev2_rx_timeout_cnt, (reg32))

#define DEV2_CRC_STA_GET_dev2_rx_crc_data(reg32)               REG_FLD_GET(DEV2_CRC_STA_FLD_dev2_rx_crc_data, (reg32))
#define DEV2_CRC_STA_GET_dev2_tx_crc_result(reg32)             REG_FLD_GET(DEV2_CRC_STA_FLD_dev2_tx_crc_result, (reg32))

#define CON0_GET_dev1_pkt_type_end(reg32)                      REG_FLD_GET(CON0_FLD_dev1_pkt_type_end, (reg32))
#define CON0_GET_dev1_pkt_type_start(reg32)                    REG_FLD_GET(CON0_FLD_dev1_pkt_type_start, (reg32))
#define CON0_GET_dev0_pkt_type_end(reg32)                      REG_FLD_GET(CON0_FLD_dev0_pkt_type_end, (reg32))
#define CON0_GET_dev0_pkt_type_start(reg32)                    REG_FLD_GET(CON0_FLD_dev0_pkt_type_start, (reg32))

#define CON1_GET_dev2_pkt_type_end(reg32)                      REG_FLD_GET(CON1_FLD_dev2_pkt_type_end, (reg32))
#define CON1_GET_dev2_pkt_type_start(reg32)                    REG_FLD_GET(CON1_FLD_dev2_pkt_type_start, (reg32))

#define CON2_GET_intfhub_bypass(reg32)                         REG_FLD_GET(CON2_FLD_intfhub_bypass, (reg32))
#define CON2_GET_crc_en(reg32)                                 REG_FLD_GET(CON2_FLD_crc_en, (reg32))

#define CON3_GET_dev_timeout_time(reg32)                       REG_FLD_GET(CON3_FLD_dev_timeout_time, (reg32))
#define CON3_GET_dev2_header_mode(reg32)                       REG_FLD_GET(CON3_FLD_dev2_header_mode, (reg32))
#define CON3_GET_dev1_header_mode(reg32)                       REG_FLD_GET(CON3_FLD_dev1_header_mode, (reg32))
#define CON3_GET_dev0_header_mode(reg32)                       REG_FLD_GET(CON3_FLD_dev0_header_mode, (reg32))
#define CON3_GET_dev_wdata_addr(reg32)                         REG_FLD_GET(CON3_FLD_dev_wdata_addr, (reg32))
#define CON3_GET_dev_rdata_addr(reg32)                         REG_FLD_GET(CON3_FLD_dev_rdata_addr, (reg32))

#define IRQ_STA_GET_intfhub_ckon_req(reg32)                    REG_FLD_GET(IRQ_STA_FLD_intfhub_ckon_req, (reg32))
#define IRQ_STA_GET_intfhub_ckoff_req(reg32)                   REG_FLD_GET(IRQ_STA_FLD_intfhub_ckoff_req, (reg32))
#define IRQ_STA_GET_intfhub_restore_req(reg32)                 REG_FLD_GET(IRQ_STA_FLD_intfhub_restore_req, (reg32))

#define IRQ_CLR_GET_intfhub_ckon_req_clr(reg32)                REG_FLD_GET(IRQ_CLR_FLD_intfhub_ckon_req_clr, (reg32))
#define IRQ_CLR_GET_intfhub_ckoff_req_clr(reg32)               REG_FLD_GET(IRQ_CLR_FLD_intfhub_ckoff_req_clr, (reg32))
#define IRQ_CLR_GET_intfhub_restore_req_clr(reg32)             REG_FLD_GET(IRQ_CLR_FLD_intfhub_restore_req_clr, (reg32))

#define IRQ_MASK_GET_intfhub_ckon_req_mask(reg32)              REG_FLD_GET(IRQ_MASK_FLD_intfhub_ckon_req_mask, (reg32))
#define IRQ_MASK_GET_intfhub_ckoff_req_mask(reg32)             REG_FLD_GET(IRQ_MASK_FLD_intfhub_ckoff_req_mask, (reg32))
#define IRQ_MASK_GET_intfhub_restore_req_mask(reg32)           REG_FLD_GET(IRQ_MASK_FLD_intfhub_restore_req_mask, (reg32))

#define STA0_GET_intfhub_busy(reg32)                           REG_FLD_GET(STA0_FLD_intfhub_busy, (reg32))
#define STA0_GET_intfhub_active(reg32)                         REG_FLD_GET(STA0_FLD_intfhub_active, (reg32))

#define LOOPBACK_GET_dev2_rx2tx_loopback(reg32)                REG_FLD_GET(LOOPBACK_FLD_dev2_rx2tx_loopback, (reg32))
#define LOOPBACK_GET_dev2_tx2rx_loopback(reg32)                REG_FLD_GET(LOOPBACK_FLD_dev2_tx2rx_loopback, (reg32))
#define LOOPBACK_GET_dev1_rx2tx_loopback(reg32)                REG_FLD_GET(LOOPBACK_FLD_dev1_rx2tx_loopback, (reg32))
#define LOOPBACK_GET_dev1_tx2rx_loopback(reg32)                REG_FLD_GET(LOOPBACK_FLD_dev1_tx2rx_loopback, (reg32))
#define LOOPBACK_GET_dev0_rx2tx_loopback(reg32)                REG_FLD_GET(LOOPBACK_FLD_dev0_rx2tx_loopback, (reg32))
#define LOOPBACK_GET_dev0_tx2rx_loopback(reg32)                REG_FLD_GET(LOOPBACK_FLD_dev0_tx2rx_loopback, (reg32))

#define CON4_GET_sw3_rst(reg32)                                REG_FLD_GET(CON4_FLD_sw3_rst, (reg32))
#define CON4_GET_sw2_rst(reg32)                                REG_FLD_GET(CON4_FLD_sw2_rst, (reg32))
#define CON4_GET_sw_rst(reg32)                                 REG_FLD_GET(CON4_FLD_sw_rst, (reg32))
#define CON4_GET_intfhub_sw_on_trg(reg32)                      REG_FLD_GET(CON4_FLD_intfhub_sw_on_trg, (reg32))

#define DBG_GET_intfhub_dbg_sel(reg32)                         REG_FLD_GET(DBG_FLD_intfhub_dbg_sel, (reg32))

#define DEV0_STA_SET_dev0_intfhub_ready(reg32, val)            REG_FLD_SET(DEV0_STA_FLD_dev0_intfhub_ready, (reg32), (val))
#define DEV0_STA_SET_dev0_intfhub_busy(reg32, val)             REG_FLD_SET(DEV0_STA_FLD_dev0_intfhub_busy, (reg32), (val))
#define DEV0_STA_SET_dev0_hw_tx_busy(reg32, val)               REG_FLD_SET(DEV0_STA_FLD_dev0_hw_tx_busy, (reg32), (val))
#define DEV0_STA_SET_dev0_hw_rx_busy(reg32, val)               REG_FLD_SET(DEV0_STA_FLD_dev0_hw_rx_busy, (reg32), (val))
#define DEV0_STA_SET_dev0_sw_tx_sta(reg32, val)                REG_FLD_SET(DEV0_STA_FLD_dev0_sw_tx_sta, (reg32), (val))
#define DEV0_STA_SET_dev0_sw_rx_sta(reg32, val)                REG_FLD_SET(DEV0_STA_FLD_dev0_sw_rx_sta, (reg32), (val))

#define DEV0_STA_SET_SET_dev0_sw_tx_set(reg32, val)            REG_FLD_SET(DEV0_STA_SET_FLD_dev0_sw_tx_set, (reg32), (val))
#define DEV0_STA_SET_SET_dev0_sw_rx_set(reg32, val)            REG_FLD_SET(DEV0_STA_SET_FLD_dev0_sw_rx_set, (reg32), (val))

#define DEV0_STA_CLR_SET_dev0_hw_rx_clr(reg32, val)            REG_FLD_SET(DEV0_STA_CLR_FLD_dev0_hw_rx_clr, (reg32), (val))
#define DEV0_STA_CLR_SET_dev0_sw_tx_clr(reg32, val)            REG_FLD_SET(DEV0_STA_CLR_FLD_dev0_sw_tx_clr, (reg32), (val))
#define DEV0_STA_CLR_SET_dev0_sw_rx_clr(reg32, val)            REG_FLD_SET(DEV0_STA_CLR_FLD_dev0_sw_rx_clr, (reg32), (val))

#define DEV0_RX_ERR_CRC_STA_SET_dev0_rx_err_crc_result(reg32, val) REG_FLD_SET(DEV0_RX_ERR_CRC_STA_FLD_dev0_rx_err_crc_result, (reg32), (val))
#define DEV0_RX_ERR_CRC_STA_SET_dev0_rx_err_crc_data(reg32, val) REG_FLD_SET(DEV0_RX_ERR_CRC_STA_FLD_dev0_rx_err_crc_data, (reg32), (val))

#define DEV1_RX_ERR_CRC_STA_SET_dev1_rx_err_crc_result(reg32, val) REG_FLD_SET(DEV1_RX_ERR_CRC_STA_FLD_dev1_rx_err_crc_result, (reg32), (val))
#define DEV1_RX_ERR_CRC_STA_SET_dev1_rx_err_crc_data(reg32, val) REG_FLD_SET(DEV1_RX_ERR_CRC_STA_FLD_dev1_rx_err_crc_data, (reg32), (val))

#define DEV2_RX_ERR_CRC_STA_SET_dev2_rx_err_crc_result(reg32, val) REG_FLD_SET(DEV2_RX_ERR_CRC_STA_FLD_dev2_rx_err_crc_result, (reg32), (val))
#define DEV2_RX_ERR_CRC_STA_SET_dev2_rx_err_crc_data(reg32, val) REG_FLD_SET(DEV2_RX_ERR_CRC_STA_FLD_dev2_rx_err_crc_data, (reg32), (val))

#define DEV0_PKT_CNT_SET_dev0_tx_pkt_cnt(reg32, val)           REG_FLD_SET(DEV0_PKT_CNT_FLD_dev0_tx_pkt_cnt, (reg32), (val))
#define DEV0_PKT_CNT_SET_dev0_tx_timeout_cnt(reg32, val)       REG_FLD_SET(DEV0_PKT_CNT_FLD_dev0_tx_timeout_cnt, (reg32), (val))
#define DEV0_PKT_CNT_SET_dev0_rx_pkt_cnt(reg32, val)           REG_FLD_SET(DEV0_PKT_CNT_FLD_dev0_rx_pkt_cnt, (reg32), (val))
#define DEV0_PKT_CNT_SET_dev0_rx_timeout_cnt(reg32, val)       REG_FLD_SET(DEV0_PKT_CNT_FLD_dev0_rx_timeout_cnt, (reg32), (val))

#define DEV0_CRC_STA_SET_dev0_rx_crc_data(reg32, val)          REG_FLD_SET(DEV0_CRC_STA_FLD_dev0_rx_crc_data, (reg32), (val))
#define DEV0_CRC_STA_SET_dev0_tx_crc_result(reg32, val)        REG_FLD_SET(DEV0_CRC_STA_FLD_dev0_tx_crc_result, (reg32), (val))

#define DEV0_IRQ_STA_SET_intfhub_dev2_tx_err(reg32, val)       REG_FLD_SET(DEV0_IRQ_STA_FLD_intfhub_dev2_tx_err, (reg32), (val))
#define DEV0_IRQ_STA_SET_intfhub_dev1_tx_err(reg32, val)       REG_FLD_SET(DEV0_IRQ_STA_FLD_intfhub_dev1_tx_err, (reg32), (val))
#define DEV0_IRQ_STA_SET_intfhub_dev0_tx_err(reg32, val)       REG_FLD_SET(DEV0_IRQ_STA_FLD_intfhub_dev0_tx_err, (reg32), (val))
#define DEV0_IRQ_STA_SET_intfhub_dev_rx_err(reg32, val)        REG_FLD_SET(DEV0_IRQ_STA_FLD_intfhub_dev_rx_err, (reg32), (val))
#define DEV0_IRQ_STA_SET_intfhub_restore_err(reg32, val)       REG_FLD_SET(DEV0_IRQ_STA_FLD_intfhub_restore_err, (reg32), (val))
#define DEV0_IRQ_STA_SET_rx_pkt_type_err(reg32, val)           REG_FLD_SET(DEV0_IRQ_STA_FLD_rx_pkt_type_err, (reg32), (val))
#define DEV0_IRQ_STA_SET_dev2_rx_timeout_err(reg32, val)       REG_FLD_SET(DEV0_IRQ_STA_FLD_dev2_rx_timeout_err, (reg32), (val))
#define DEV0_IRQ_STA_SET_dev1_rx_timeout_err(reg32, val)       REG_FLD_SET(DEV0_IRQ_STA_FLD_dev1_rx_timeout_err, (reg32), (val))
#define DEV0_IRQ_STA_SET_dev0_rx_timeout_err(reg32, val)       REG_FLD_SET(DEV0_IRQ_STA_FLD_dev0_rx_timeout_err, (reg32), (val))
#define DEV0_IRQ_STA_SET_dev2_tx_pkt_type_err(reg32, val)      REG_FLD_SET(DEV0_IRQ_STA_FLD_dev2_tx_pkt_type_err, (reg32), (val))
#define DEV0_IRQ_STA_SET_dev1_tx_pkt_type_err(reg32, val)      REG_FLD_SET(DEV0_IRQ_STA_FLD_dev1_tx_pkt_type_err, (reg32), (val))
#define DEV0_IRQ_STA_SET_dev0_tx_pkt_type_err(reg32, val)      REG_FLD_SET(DEV0_IRQ_STA_FLD_dev0_tx_pkt_type_err, (reg32), (val))
#define DEV0_IRQ_STA_SET_dev2_tx_timeout_err(reg32, val)       REG_FLD_SET(DEV0_IRQ_STA_FLD_dev2_tx_timeout_err, (reg32), (val))
#define DEV0_IRQ_STA_SET_dev1_tx_timeout_err(reg32, val)       REG_FLD_SET(DEV0_IRQ_STA_FLD_dev1_tx_timeout_err, (reg32), (val))
#define DEV0_IRQ_STA_SET_dev0_tx_timeout_err(reg32, val)       REG_FLD_SET(DEV0_IRQ_STA_FLD_dev0_tx_timeout_err, (reg32), (val))
#define DEV0_IRQ_STA_SET_dev2_crc_err(reg32, val)              REG_FLD_SET(DEV0_IRQ_STA_FLD_dev2_crc_err, (reg32), (val))
#define DEV0_IRQ_STA_SET_dev1_crc_err(reg32, val)              REG_FLD_SET(DEV0_IRQ_STA_FLD_dev1_crc_err, (reg32), (val))
#define DEV0_IRQ_STA_SET_dev0_crc_err(reg32, val)              REG_FLD_SET(DEV0_IRQ_STA_FLD_dev0_crc_err, (reg32), (val))

#define DEV0_IRQ_CLR_SET_intfhub_dev2_tx_err_clr(reg32, val)   REG_FLD_SET(DEV0_IRQ_CLR_FLD_intfhub_dev2_tx_err_clr, (reg32), (val))
#define DEV0_IRQ_CLR_SET_intfhub_dev1_tx_err_clr(reg32, val)   REG_FLD_SET(DEV0_IRQ_CLR_FLD_intfhub_dev1_tx_err_clr, (reg32), (val))
#define DEV0_IRQ_CLR_SET_intfhub_dev0_tx_err_clr(reg32, val)   REG_FLD_SET(DEV0_IRQ_CLR_FLD_intfhub_dev0_tx_err_clr, (reg32), (val))
#define DEV0_IRQ_CLR_SET_intfhub_dev_rx_err_clr(reg32, val)    REG_FLD_SET(DEV0_IRQ_CLR_FLD_intfhub_dev_rx_err_clr, (reg32), (val))
#define DEV0_IRQ_CLR_SET_intfhub_restore_err_clr(reg32, val)   REG_FLD_SET(DEV0_IRQ_CLR_FLD_intfhub_restore_err_clr, (reg32), (val))
#define DEV0_IRQ_CLR_SET_rx_pkt_type_err_clr(reg32, val)       REG_FLD_SET(DEV0_IRQ_CLR_FLD_rx_pkt_type_err_clr, (reg32), (val))
#define DEV0_IRQ_CLR_SET_dev2_rx_timeout_err_clr(reg32, val)   REG_FLD_SET(DEV0_IRQ_CLR_FLD_dev2_rx_timeout_err_clr, (reg32), (val))
#define DEV0_IRQ_CLR_SET_dev1_rx_timeout_err_clr(reg32, val)   REG_FLD_SET(DEV0_IRQ_CLR_FLD_dev1_rx_timeout_err_clr, (reg32), (val))
#define DEV0_IRQ_CLR_SET_dev0_rx_timeout_err_clr(reg32, val)   REG_FLD_SET(DEV0_IRQ_CLR_FLD_dev0_rx_timeout_err_clr, (reg32), (val))
#define DEV0_IRQ_CLR_SET_dev2_tx_pkt_type_err_clr(reg32, val)  REG_FLD_SET(DEV0_IRQ_CLR_FLD_dev2_tx_pkt_type_err_clr, (reg32), (val))
#define DEV0_IRQ_CLR_SET_dev1_tx_pkt_type_err_clr(reg32, val)  REG_FLD_SET(DEV0_IRQ_CLR_FLD_dev1_tx_pkt_type_err_clr, (reg32), (val))
#define DEV0_IRQ_CLR_SET_dev0_tx_pkt_type_err_clr(reg32, val)  REG_FLD_SET(DEV0_IRQ_CLR_FLD_dev0_tx_pkt_type_err_clr, (reg32), (val))
#define DEV0_IRQ_CLR_SET_dev2_tx_timeout_err_clr(reg32, val)   REG_FLD_SET(DEV0_IRQ_CLR_FLD_dev2_tx_timeout_err_clr, (reg32), (val))
#define DEV0_IRQ_CLR_SET_dev1_tx_timeout_err_clr(reg32, val)   REG_FLD_SET(DEV0_IRQ_CLR_FLD_dev1_tx_timeout_err_clr, (reg32), (val))
#define DEV0_IRQ_CLR_SET_dev0_tx_timeout_err_clr(reg32, val)   REG_FLD_SET(DEV0_IRQ_CLR_FLD_dev0_tx_timeout_err_clr, (reg32), (val))
#define DEV0_IRQ_CLR_SET_dev2_crc_err_clr(reg32, val)          REG_FLD_SET(DEV0_IRQ_CLR_FLD_dev2_crc_err_clr, (reg32), (val))
#define DEV0_IRQ_CLR_SET_dev1_crc_err_clr(reg32, val)          REG_FLD_SET(DEV0_IRQ_CLR_FLD_dev1_crc_err_clr, (reg32), (val))
#define DEV0_IRQ_CLR_SET_dev0_crc_err_clr(reg32, val)          REG_FLD_SET(DEV0_IRQ_CLR_FLD_dev0_crc_err_clr, (reg32), (val))

#define DEV0_IRQ_MASK_SET_intfhub_dev2_tx_err_mask(reg32, val) REG_FLD_SET(DEV0_IRQ_MASK_FLD_intfhub_dev2_tx_err_mask, (reg32), (val))
#define DEV0_IRQ_MASK_SET_intfhub_dev1_tx_err_mask(reg32, val) REG_FLD_SET(DEV0_IRQ_MASK_FLD_intfhub_dev1_tx_err_mask, (reg32), (val))
#define DEV0_IRQ_MASK_SET_intfhub_dev0_tx_err_mask(reg32, val) REG_FLD_SET(DEV0_IRQ_MASK_FLD_intfhub_dev0_tx_err_mask, (reg32), (val))
#define DEV0_IRQ_MASK_SET_intfhub_dev_rx_err_mask(reg32, val)  REG_FLD_SET(DEV0_IRQ_MASK_FLD_intfhub_dev_rx_err_mask, (reg32), (val))
#define DEV0_IRQ_MASK_SET_intfhub_restore_err_mask(reg32, val) REG_FLD_SET(DEV0_IRQ_MASK_FLD_intfhub_restore_err_mask, (reg32), (val))
#define DEV0_IRQ_MASK_SET_rx_pkt_type_err_mask(reg32, val)     REG_FLD_SET(DEV0_IRQ_MASK_FLD_rx_pkt_type_err_mask, (reg32), (val))
#define DEV0_IRQ_MASK_SET_dev2_rx_timeout_err_mask(reg32, val) REG_FLD_SET(DEV0_IRQ_MASK_FLD_dev2_rx_timeout_err_mask, (reg32), (val))
#define DEV0_IRQ_MASK_SET_dev1_rx_timeout_err_mask(reg32, val) REG_FLD_SET(DEV0_IRQ_MASK_FLD_dev1_rx_timeout_err_mask, (reg32), (val))
#define DEV0_IRQ_MASK_SET_dev0_rx_timeout_err_mask(reg32, val) REG_FLD_SET(DEV0_IRQ_MASK_FLD_dev0_rx_timeout_err_mask, (reg32), (val))
#define DEV0_IRQ_MASK_SET_dev2_tx_pkt_type_err_mask(reg32, val) REG_FLD_SET(DEV0_IRQ_MASK_FLD_dev2_tx_pkt_type_err_mask, (reg32), (val))
#define DEV0_IRQ_MASK_SET_dev1_tx_pkt_type_err_mask(reg32, val) REG_FLD_SET(DEV0_IRQ_MASK_FLD_dev1_tx_pkt_type_err_mask, (reg32), (val))
#define DEV0_IRQ_MASK_SET_dev0_tx_pkt_type_err_mask(reg32, val) REG_FLD_SET(DEV0_IRQ_MASK_FLD_dev0_tx_pkt_type_err_mask, (reg32), (val))
#define DEV0_IRQ_MASK_SET_dev2_tx_timeout_err_mask(reg32, val) REG_FLD_SET(DEV0_IRQ_MASK_FLD_dev2_tx_timeout_err_mask, (reg32), (val))
#define DEV0_IRQ_MASK_SET_dev1_tx_timeout_err_mask(reg32, val) REG_FLD_SET(DEV0_IRQ_MASK_FLD_dev1_tx_timeout_err_mask, (reg32), (val))
#define DEV0_IRQ_MASK_SET_dev0_tx_timeout_err_mask(reg32, val) REG_FLD_SET(DEV0_IRQ_MASK_FLD_dev0_tx_timeout_err_mask, (reg32), (val))
#define DEV0_IRQ_MASK_SET_dev2_crc_err_mask(reg32, val)        REG_FLD_SET(DEV0_IRQ_MASK_FLD_dev2_crc_err_mask, (reg32), (val))
#define DEV0_IRQ_MASK_SET_dev1_crc_err_mask(reg32, val)        REG_FLD_SET(DEV0_IRQ_MASK_FLD_dev1_crc_err_mask, (reg32), (val))
#define DEV0_IRQ_MASK_SET_dev0_crc_err_mask(reg32, val)        REG_FLD_SET(DEV0_IRQ_MASK_FLD_dev0_crc_err_mask, (reg32), (val))

#define DEV1_STA_SET_dev1_intfhub_ready(reg32, val)            REG_FLD_SET(DEV1_STA_FLD_dev1_intfhub_ready, (reg32), (val))
#define DEV1_STA_SET_dev1_intfhub_busy(reg32, val)             REG_FLD_SET(DEV1_STA_FLD_dev1_intfhub_busy, (reg32), (val))
#define DEV1_STA_SET_dev1_hw_tx_busy(reg32, val)               REG_FLD_SET(DEV1_STA_FLD_dev1_hw_tx_busy, (reg32), (val))
#define DEV1_STA_SET_dev1_hw_rx_busy(reg32, val)               REG_FLD_SET(DEV1_STA_FLD_dev1_hw_rx_busy, (reg32), (val))
#define DEV1_STA_SET_dev1_sw_tx_sta(reg32, val)                REG_FLD_SET(DEV1_STA_FLD_dev1_sw_tx_sta, (reg32), (val))
#define DEV1_STA_SET_dev1_sw_rx_sta(reg32, val)                REG_FLD_SET(DEV1_STA_FLD_dev1_sw_rx_sta, (reg32), (val))

#define DEV1_STA_SET_SET_dev1_sw_tx_set(reg32, val)            REG_FLD_SET(DEV1_STA_SET_FLD_dev1_sw_tx_set, (reg32), (val))
#define DEV1_STA_SET_SET_dev1_sw_rx_set(reg32, val)            REG_FLD_SET(DEV1_STA_SET_FLD_dev1_sw_rx_set, (reg32), (val))

#define DEV1_STA_CLR_SET_dev1_hw_rx_clr(reg32, val)            REG_FLD_SET(DEV1_STA_CLR_FLD_dev1_hw_rx_clr, (reg32), (val))
#define DEV1_STA_CLR_SET_dev1_sw_tx_clr(reg32, val)            REG_FLD_SET(DEV1_STA_CLR_FLD_dev1_sw_tx_clr, (reg32), (val))
#define DEV1_STA_CLR_SET_dev1_sw_rx_clr(reg32, val)            REG_FLD_SET(DEV1_STA_CLR_FLD_dev1_sw_rx_clr, (reg32), (val))

#define DEV1_PKT_CNT_SET_dev1_tx_pkt_cnt(reg32, val)           REG_FLD_SET(DEV1_PKT_CNT_FLD_dev1_tx_pkt_cnt, (reg32), (val))
#define DEV1_PKT_CNT_SET_dev1_tx_timeout_cnt(reg32, val)       REG_FLD_SET(DEV1_PKT_CNT_FLD_dev1_tx_timeout_cnt, (reg32), (val))
#define DEV1_PKT_CNT_SET_dev1_rx_pkt_cnt(reg32, val)           REG_FLD_SET(DEV1_PKT_CNT_FLD_dev1_rx_pkt_cnt, (reg32), (val))
#define DEV1_PKT_CNT_SET_dev1_rx_timeout_cnt(reg32, val)       REG_FLD_SET(DEV1_PKT_CNT_FLD_dev1_rx_timeout_cnt, (reg32), (val))

#define DEV1_CRC_STA_SET_dev1_rx_crc_data(reg32, val)          REG_FLD_SET(DEV1_CRC_STA_FLD_dev1_rx_crc_data, (reg32), (val))
#define DEV1_CRC_STA_SET_dev1_tx_crc_result(reg32, val)        REG_FLD_SET(DEV1_CRC_STA_FLD_dev1_tx_crc_result, (reg32), (val))

#define DEV2_STA_SET_dev2_intfhub_ready(reg32, val)            REG_FLD_SET(DEV2_STA_FLD_dev2_intfhub_ready, (reg32), (val))
#define DEV2_STA_SET_dev2_intfhub_busy(reg32, val)             REG_FLD_SET(DEV2_STA_FLD_dev2_intfhub_busy, (reg32), (val))
#define DEV2_STA_SET_dev2_hw_tx_busy(reg32, val)               REG_FLD_SET(DEV2_STA_FLD_dev2_hw_tx_busy, (reg32), (val))
#define DEV2_STA_SET_dev2_hw_rx_busy(reg32, val)               REG_FLD_SET(DEV2_STA_FLD_dev2_hw_rx_busy, (reg32), (val))
#define DEV2_STA_SET_dev2_sw_tx_sta(reg32, val)                REG_FLD_SET(DEV2_STA_FLD_dev2_sw_tx_sta, (reg32), (val))
#define DEV2_STA_SET_dev2_sw_rx_sta(reg32, val)                REG_FLD_SET(DEV2_STA_FLD_dev2_sw_rx_sta, (reg32), (val))

#define DEV2_STA_SET_SET_dev2_sw_tx_set(reg32, val)            REG_FLD_SET(DEV2_STA_SET_FLD_dev2_sw_tx_set, (reg32), (val))
#define DEV2_STA_SET_SET_dev2_sw_rx_set(reg32, val)            REG_FLD_SET(DEV2_STA_SET_FLD_dev2_sw_rx_set, (reg32), (val))

#define DEV2_STA_CLR_SET_dev2_hw_rx_clr(reg32, val)            REG_FLD_SET(DEV2_STA_CLR_FLD_dev2_hw_rx_clr, (reg32), (val))
#define DEV2_STA_CLR_SET_dev2_sw_tx_clr(reg32, val)            REG_FLD_SET(DEV2_STA_CLR_FLD_dev2_sw_tx_clr, (reg32), (val))
#define DEV2_STA_CLR_SET_dev2_sw_rx_clr(reg32, val)            REG_FLD_SET(DEV2_STA_CLR_FLD_dev2_sw_rx_clr, (reg32), (val))

#define DEV2_PKT_CNT_SET_dev2_tx_pkt_cnt(reg32, val)           REG_FLD_SET(DEV2_PKT_CNT_FLD_dev2_tx_pkt_cnt, (reg32), (val))
#define DEV2_PKT_CNT_SET_dev2_tx_timeout_cnt(reg32, val)       REG_FLD_SET(DEV2_PKT_CNT_FLD_dev2_tx_timeout_cnt, (reg32), (val))
#define DEV2_PKT_CNT_SET_dev2_rx_pkt_cnt(reg32, val)           REG_FLD_SET(DEV2_PKT_CNT_FLD_dev2_rx_pkt_cnt, (reg32), (val))
#define DEV2_PKT_CNT_SET_dev2_rx_timeout_cnt(reg32, val)       REG_FLD_SET(DEV2_PKT_CNT_FLD_dev2_rx_timeout_cnt, (reg32), (val))

#define DEV2_CRC_STA_SET_dev2_rx_crc_data(reg32, val)          REG_FLD_SET(DEV2_CRC_STA_FLD_dev2_rx_crc_data, (reg32), (val))
#define DEV2_CRC_STA_SET_dev2_tx_crc_result(reg32, val)        REG_FLD_SET(DEV2_CRC_STA_FLD_dev2_tx_crc_result, (reg32), (val))

#define CON0_SET_dev1_pkt_type_end(reg32, val)                 REG_FLD_SET(CON0_FLD_dev1_pkt_type_end, (reg32), (val))
#define CON0_SET_dev1_pkt_type_start(reg32, val)               REG_FLD_SET(CON0_FLD_dev1_pkt_type_start, (reg32), (val))
#define CON0_SET_dev0_pkt_type_end(reg32, val)                 REG_FLD_SET(CON0_FLD_dev0_pkt_type_end, (reg32), (val))
#define CON0_SET_dev0_pkt_type_start(reg32, val)               REG_FLD_SET(CON0_FLD_dev0_pkt_type_start, (reg32), (val))

#define CON1_SET_dev2_pkt_type_end(reg32, val)                 REG_FLD_SET(CON1_FLD_dev2_pkt_type_end, (reg32), (val))
#define CON1_SET_dev2_pkt_type_start(reg32, val)               REG_FLD_SET(CON1_FLD_dev2_pkt_type_start, (reg32), (val))

#define CON2_SET_intfhub_bypass(reg32, val)                    REG_FLD_SET(CON2_FLD_intfhub_bypass, (reg32), (val))
#define CON2_SET_crc_en(reg32, val)                            REG_FLD_SET(CON2_FLD_crc_en, (reg32), (val))

#define CON3_SET_dev_timeout_time(reg32, val)                  REG_FLD_SET(CON3_FLD_dev_timeout_time, (reg32), (val))
#define CON3_SET_dev2_header_mode(reg32, val)                  REG_FLD_SET(CON3_FLD_dev2_header_mode, (reg32), (val))
#define CON3_SET_dev1_header_mode(reg32, val)                  REG_FLD_SET(CON3_FLD_dev1_header_mode, (reg32), (val))
#define CON3_SET_dev0_header_mode(reg32, val)                  REG_FLD_SET(CON3_FLD_dev0_header_mode, (reg32), (val))
#define CON3_SET_dev_wdata_addr(reg32, val)                    REG_FLD_SET(CON3_FLD_dev_wdata_addr, (reg32), (val))
#define CON3_SET_dev_rdata_addr(reg32, val)                    REG_FLD_SET(CON3_FLD_dev_rdata_addr, (reg32), (val))

#define IRQ_STA_SET_intfhub_ckon_req(reg32, val)               REG_FLD_SET(IRQ_STA_FLD_intfhub_ckon_req, (reg32), (val))
#define IRQ_STA_SET_intfhub_ckoff_req(reg32, val)              REG_FLD_SET(IRQ_STA_FLD_intfhub_ckoff_req, (reg32), (val))
#define IRQ_STA_SET_intfhub_restore_req(reg32, val)            REG_FLD_SET(IRQ_STA_FLD_intfhub_restore_req, (reg32), (val))

#define IRQ_CLR_SET_intfhub_ckon_req_clr(reg32, val)           REG_FLD_SET(IRQ_CLR_FLD_intfhub_ckon_req_clr, (reg32), (val))
#define IRQ_CLR_SET_intfhub_ckoff_req_clr(reg32, val)          REG_FLD_SET(IRQ_CLR_FLD_intfhub_ckoff_req_clr, (reg32), (val))
#define IRQ_CLR_SET_intfhub_restore_req_clr(reg32, val)        REG_FLD_SET(IRQ_CLR_FLD_intfhub_restore_req_clr, (reg32), (val))

#define IRQ_MASK_SET_intfhub_ckon_req_mask(reg32, val)         REG_FLD_SET(IRQ_MASK_FLD_intfhub_ckon_req_mask, (reg32), (val))
#define IRQ_MASK_SET_intfhub_ckoff_req_mask(reg32, val)        REG_FLD_SET(IRQ_MASK_FLD_intfhub_ckoff_req_mask, (reg32), (val))
#define IRQ_MASK_SET_intfhub_restore_req_mask(reg32, val)      REG_FLD_SET(IRQ_MASK_FLD_intfhub_restore_req_mask, (reg32), (val))

#define STA0_SET_intfhub_busy(reg32, val)                      REG_FLD_SET(STA0_FLD_intfhub_busy, (reg32), (val))
#define STA0_SET_intfhub_active(reg32, val)                    REG_FLD_SET(STA0_FLD_intfhub_active, (reg32), (val))

#define LOOPBACK_SET_dev2_rx2tx_loopback(reg32, val)           REG_FLD_SET(LOOPBACK_FLD_dev2_rx2tx_loopback, (reg32), (val))
#define LOOPBACK_SET_dev2_tx2rx_loopback(reg32, val)           REG_FLD_SET(LOOPBACK_FLD_dev2_tx2rx_loopback, (reg32), (val))
#define LOOPBACK_SET_dev1_rx2tx_loopback(reg32, val)           REG_FLD_SET(LOOPBACK_FLD_dev1_rx2tx_loopback, (reg32), (val))
#define LOOPBACK_SET_dev1_tx2rx_loopback(reg32, val)           REG_FLD_SET(LOOPBACK_FLD_dev1_tx2rx_loopback, (reg32), (val))
#define LOOPBACK_SET_dev0_rx2tx_loopback(reg32, val)           REG_FLD_SET(LOOPBACK_FLD_dev0_rx2tx_loopback, (reg32), (val))
#define LOOPBACK_SET_dev0_tx2rx_loopback(reg32, val)           REG_FLD_SET(LOOPBACK_FLD_dev0_tx2rx_loopback, (reg32), (val))

#define CON4_SET_sw3_rst(reg32, val)                           REG_FLD_SET(CON4_FLD_sw3_rst, (reg32), (val))
#define CON4_SET_sw2_rst(reg32, val)                           REG_FLD_SET(CON4_FLD_sw2_rst, (reg32), (val))
#define CON4_SET_sw_rst(reg32, val)                            REG_FLD_SET(CON4_FLD_sw_rst, (reg32), (val))
#define CON4_SET_intfhub_sw_on_trg(reg32, val)                 REG_FLD_SET(CON4_FLD_intfhub_sw_on_trg, (reg32), (val))

#define DBG_SET_intfhub_dbg_sel(reg32, val)                    REG_FLD_SET(DBG_FLD_intfhub_dbg_sel, (reg32), (val))

#define DEV0_STA_VAL_dev0_intfhub_ready(val)                   REG_FLD_VAL(DEV0_STA_FLD_dev0_intfhub_ready, (val))
#define DEV0_STA_VAL_dev0_intfhub_busy(val)                    REG_FLD_VAL(DEV0_STA_FLD_dev0_intfhub_busy, (val))
#define DEV0_STA_VAL_dev0_hw_tx_busy(val)                      REG_FLD_VAL(DEV0_STA_FLD_dev0_hw_tx_busy, (val))
#define DEV0_STA_VAL_dev0_hw_rx_busy(val)                      REG_FLD_VAL(DEV0_STA_FLD_dev0_hw_rx_busy, (val))
#define DEV0_STA_VAL_dev0_sw_tx_sta(val)                       REG_FLD_VAL(DEV0_STA_FLD_dev0_sw_tx_sta, (val))
#define DEV0_STA_VAL_dev0_sw_rx_sta(val)                       REG_FLD_VAL(DEV0_STA_FLD_dev0_sw_rx_sta, (val))

#define DEV0_STA_SET_VAL_dev0_sw_tx_set(val)                   REG_FLD_VAL(DEV0_STA_SET_FLD_dev0_sw_tx_set, (val))
#define DEV0_STA_SET_VAL_dev0_sw_rx_set(val)                   REG_FLD_VAL(DEV0_STA_SET_FLD_dev0_sw_rx_set, (val))

#define DEV0_STA_CLR_VAL_dev0_hw_rx_clr(val)                   REG_FLD_VAL(DEV0_STA_CLR_FLD_dev0_hw_rx_clr, (val))
#define DEV0_STA_CLR_VAL_dev0_sw_tx_clr(val)                   REG_FLD_VAL(DEV0_STA_CLR_FLD_dev0_sw_tx_clr, (val))
#define DEV0_STA_CLR_VAL_dev0_sw_rx_clr(val)                   REG_FLD_VAL(DEV0_STA_CLR_FLD_dev0_sw_rx_clr, (val))

#define DEV0_RX_ERR_CRC_STA_VAL_dev0_rx_err_crc_result(val)    REG_FLD_VAL(DEV0_RX_ERR_CRC_STA_FLD_dev0_rx_err_crc_result, (val))
#define DEV0_RX_ERR_CRC_STA_VAL_dev0_rx_err_crc_data(val)      REG_FLD_VAL(DEV0_RX_ERR_CRC_STA_FLD_dev0_rx_err_crc_data, (val))

#define DEV1_RX_ERR_CRC_STA_VAL_dev1_rx_err_crc_result(val)    REG_FLD_VAL(DEV1_RX_ERR_CRC_STA_FLD_dev1_rx_err_crc_result, (val))
#define DEV1_RX_ERR_CRC_STA_VAL_dev1_rx_err_crc_data(val)      REG_FLD_VAL(DEV1_RX_ERR_CRC_STA_FLD_dev1_rx_err_crc_data, (val))

#define DEV2_RX_ERR_CRC_STA_VAL_dev2_rx_err_crc_result(val)    REG_FLD_VAL(DEV2_RX_ERR_CRC_STA_FLD_dev2_rx_err_crc_result, (val))
#define DEV2_RX_ERR_CRC_STA_VAL_dev2_rx_err_crc_data(val)      REG_FLD_VAL(DEV2_RX_ERR_CRC_STA_FLD_dev2_rx_err_crc_data, (val))

#define DEV0_PKT_CNT_VAL_dev0_tx_pkt_cnt(val)                  REG_FLD_VAL(DEV0_PKT_CNT_FLD_dev0_tx_pkt_cnt, (val))
#define DEV0_PKT_CNT_VAL_dev0_tx_timeout_cnt(val)              REG_FLD_VAL(DEV0_PKT_CNT_FLD_dev0_tx_timeout_cnt, (val))
#define DEV0_PKT_CNT_VAL_dev0_rx_pkt_cnt(val)                  REG_FLD_VAL(DEV0_PKT_CNT_FLD_dev0_rx_pkt_cnt, (val))
#define DEV0_PKT_CNT_VAL_dev0_rx_timeout_cnt(val)              REG_FLD_VAL(DEV0_PKT_CNT_FLD_dev0_rx_timeout_cnt, (val))

#define DEV0_CRC_STA_VAL_dev0_rx_crc_data(val)                 REG_FLD_VAL(DEV0_CRC_STA_FLD_dev0_rx_crc_data, (val))
#define DEV0_CRC_STA_VAL_dev0_tx_crc_result(val)               REG_FLD_VAL(DEV0_CRC_STA_FLD_dev0_tx_crc_result, (val))

#define DEV0_IRQ_STA_VAL_intfhub_dev2_tx_err(val)              REG_FLD_VAL(DEV0_IRQ_STA_FLD_intfhub_dev2_tx_err, (val))
#define DEV0_IRQ_STA_VAL_intfhub_dev1_tx_err(val)              REG_FLD_VAL(DEV0_IRQ_STA_FLD_intfhub_dev1_tx_err, (val))
#define DEV0_IRQ_STA_VAL_intfhub_dev0_tx_err(val)              REG_FLD_VAL(DEV0_IRQ_STA_FLD_intfhub_dev0_tx_err, (val))
#define DEV0_IRQ_STA_VAL_intfhub_dev_rx_err(val)               REG_FLD_VAL(DEV0_IRQ_STA_FLD_intfhub_dev_rx_err, (val))
#define DEV0_IRQ_STA_VAL_intfhub_restore_err(val)              REG_FLD_VAL(DEV0_IRQ_STA_FLD_intfhub_restore_err, (val))
#define DEV0_IRQ_STA_VAL_rx_pkt_type_err(val)                  REG_FLD_VAL(DEV0_IRQ_STA_FLD_rx_pkt_type_err, (val))
#define DEV0_IRQ_STA_VAL_dev2_rx_timeout_err(val)              REG_FLD_VAL(DEV0_IRQ_STA_FLD_dev2_rx_timeout_err, (val))
#define DEV0_IRQ_STA_VAL_dev1_rx_timeout_err(val)              REG_FLD_VAL(DEV0_IRQ_STA_FLD_dev1_rx_timeout_err, (val))
#define DEV0_IRQ_STA_VAL_dev0_rx_timeout_err(val)              REG_FLD_VAL(DEV0_IRQ_STA_FLD_dev0_rx_timeout_err, (val))
#define DEV0_IRQ_STA_VAL_dev2_tx_pkt_type_err(val)             REG_FLD_VAL(DEV0_IRQ_STA_FLD_dev2_tx_pkt_type_err, (val))
#define DEV0_IRQ_STA_VAL_dev1_tx_pkt_type_err(val)             REG_FLD_VAL(DEV0_IRQ_STA_FLD_dev1_tx_pkt_type_err, (val))
#define DEV0_IRQ_STA_VAL_dev0_tx_pkt_type_err(val)             REG_FLD_VAL(DEV0_IRQ_STA_FLD_dev0_tx_pkt_type_err, (val))
#define DEV0_IRQ_STA_VAL_dev2_tx_timeout_err(val)              REG_FLD_VAL(DEV0_IRQ_STA_FLD_dev2_tx_timeout_err, (val))
#define DEV0_IRQ_STA_VAL_dev1_tx_timeout_err(val)              REG_FLD_VAL(DEV0_IRQ_STA_FLD_dev1_tx_timeout_err, (val))
#define DEV0_IRQ_STA_VAL_dev0_tx_timeout_err(val)              REG_FLD_VAL(DEV0_IRQ_STA_FLD_dev0_tx_timeout_err, (val))
#define DEV0_IRQ_STA_VAL_dev2_crc_err(val)                     REG_FLD_VAL(DEV0_IRQ_STA_FLD_dev2_crc_err, (val))
#define DEV0_IRQ_STA_VAL_dev1_crc_err(val)                     REG_FLD_VAL(DEV0_IRQ_STA_FLD_dev1_crc_err, (val))
#define DEV0_IRQ_STA_VAL_dev0_crc_err(val)                     REG_FLD_VAL(DEV0_IRQ_STA_FLD_dev0_crc_err, (val))

#define DEV0_IRQ_CLR_VAL_intfhub_dev2_tx_err_clr(val)          REG_FLD_VAL(DEV0_IRQ_CLR_FLD_intfhub_dev2_tx_err_clr, (val))
#define DEV0_IRQ_CLR_VAL_intfhub_dev1_tx_err_clr(val)          REG_FLD_VAL(DEV0_IRQ_CLR_FLD_intfhub_dev1_tx_err_clr, (val))
#define DEV0_IRQ_CLR_VAL_intfhub_dev0_tx_err_clr(val)          REG_FLD_VAL(DEV0_IRQ_CLR_FLD_intfhub_dev0_tx_err_clr, (val))
#define DEV0_IRQ_CLR_VAL_intfhub_dev_rx_err_clr(val)           REG_FLD_VAL(DEV0_IRQ_CLR_FLD_intfhub_dev_rx_err_clr, (val))
#define DEV0_IRQ_CLR_VAL_intfhub_restore_err_clr(val)          REG_FLD_VAL(DEV0_IRQ_CLR_FLD_intfhub_restore_err_clr, (val))
#define DEV0_IRQ_CLR_VAL_rx_pkt_type_err_clr(val)              REG_FLD_VAL(DEV0_IRQ_CLR_FLD_rx_pkt_type_err_clr, (val))
#define DEV0_IRQ_CLR_VAL_dev2_rx_timeout_err_clr(val)          REG_FLD_VAL(DEV0_IRQ_CLR_FLD_dev2_rx_timeout_err_clr, (val))
#define DEV0_IRQ_CLR_VAL_dev1_rx_timeout_err_clr(val)          REG_FLD_VAL(DEV0_IRQ_CLR_FLD_dev1_rx_timeout_err_clr, (val))
#define DEV0_IRQ_CLR_VAL_dev0_rx_timeout_err_clr(val)          REG_FLD_VAL(DEV0_IRQ_CLR_FLD_dev0_rx_timeout_err_clr, (val))
#define DEV0_IRQ_CLR_VAL_dev2_tx_pkt_type_err_clr(val)         REG_FLD_VAL(DEV0_IRQ_CLR_FLD_dev2_tx_pkt_type_err_clr, (val))
#define DEV0_IRQ_CLR_VAL_dev1_tx_pkt_type_err_clr(val)         REG_FLD_VAL(DEV0_IRQ_CLR_FLD_dev1_tx_pkt_type_err_clr, (val))
#define DEV0_IRQ_CLR_VAL_dev0_tx_pkt_type_err_clr(val)         REG_FLD_VAL(DEV0_IRQ_CLR_FLD_dev0_tx_pkt_type_err_clr, (val))
#define DEV0_IRQ_CLR_VAL_dev2_tx_timeout_err_clr(val)          REG_FLD_VAL(DEV0_IRQ_CLR_FLD_dev2_tx_timeout_err_clr, (val))
#define DEV0_IRQ_CLR_VAL_dev1_tx_timeout_err_clr(val)          REG_FLD_VAL(DEV0_IRQ_CLR_FLD_dev1_tx_timeout_err_clr, (val))
#define DEV0_IRQ_CLR_VAL_dev0_tx_timeout_err_clr(val)          REG_FLD_VAL(DEV0_IRQ_CLR_FLD_dev0_tx_timeout_err_clr, (val))
#define DEV0_IRQ_CLR_VAL_dev2_crc_err_clr(val)                 REG_FLD_VAL(DEV0_IRQ_CLR_FLD_dev2_crc_err_clr, (val))
#define DEV0_IRQ_CLR_VAL_dev1_crc_err_clr(val)                 REG_FLD_VAL(DEV0_IRQ_CLR_FLD_dev1_crc_err_clr, (val))
#define DEV0_IRQ_CLR_VAL_dev0_crc_err_clr(val)                 REG_FLD_VAL(DEV0_IRQ_CLR_FLD_dev0_crc_err_clr, (val))

#define DEV0_IRQ_MASK_VAL_intfhub_dev2_tx_err_mask(val)        REG_FLD_VAL(DEV0_IRQ_MASK_FLD_intfhub_dev2_tx_err_mask, (val))
#define DEV0_IRQ_MASK_VAL_intfhub_dev1_tx_err_mask(val)        REG_FLD_VAL(DEV0_IRQ_MASK_FLD_intfhub_dev1_tx_err_mask, (val))
#define DEV0_IRQ_MASK_VAL_intfhub_dev0_tx_err_mask(val)        REG_FLD_VAL(DEV0_IRQ_MASK_FLD_intfhub_dev0_tx_err_mask, (val))
#define DEV0_IRQ_MASK_VAL_intfhub_dev_rx_err_mask(val)         REG_FLD_VAL(DEV0_IRQ_MASK_FLD_intfhub_dev_rx_err_mask, (val))
#define DEV0_IRQ_MASK_VAL_intfhub_restore_err_mask(val)        REG_FLD_VAL(DEV0_IRQ_MASK_FLD_intfhub_restore_err_mask, (val))
#define DEV0_IRQ_MASK_VAL_rx_pkt_type_err_mask(val)            REG_FLD_VAL(DEV0_IRQ_MASK_FLD_rx_pkt_type_err_mask, (val))
#define DEV0_IRQ_MASK_VAL_dev2_rx_timeout_err_mask(val)        REG_FLD_VAL(DEV0_IRQ_MASK_FLD_dev2_rx_timeout_err_mask, (val))
#define DEV0_IRQ_MASK_VAL_dev1_rx_timeout_err_mask(val)        REG_FLD_VAL(DEV0_IRQ_MASK_FLD_dev1_rx_timeout_err_mask, (val))
#define DEV0_IRQ_MASK_VAL_dev0_rx_timeout_err_mask(val)        REG_FLD_VAL(DEV0_IRQ_MASK_FLD_dev0_rx_timeout_err_mask, (val))
#define DEV0_IRQ_MASK_VAL_dev2_tx_pkt_type_err_mask(val)       REG_FLD_VAL(DEV0_IRQ_MASK_FLD_dev2_tx_pkt_type_err_mask, (val))
#define DEV0_IRQ_MASK_VAL_dev1_tx_pkt_type_err_mask(val)       REG_FLD_VAL(DEV0_IRQ_MASK_FLD_dev1_tx_pkt_type_err_mask, (val))
#define DEV0_IRQ_MASK_VAL_dev0_tx_pkt_type_err_mask(val)       REG_FLD_VAL(DEV0_IRQ_MASK_FLD_dev0_tx_pkt_type_err_mask, (val))
#define DEV0_IRQ_MASK_VAL_dev2_tx_timeout_err_mask(val)        REG_FLD_VAL(DEV0_IRQ_MASK_FLD_dev2_tx_timeout_err_mask, (val))
#define DEV0_IRQ_MASK_VAL_dev1_tx_timeout_err_mask(val)        REG_FLD_VAL(DEV0_IRQ_MASK_FLD_dev1_tx_timeout_err_mask, (val))
#define DEV0_IRQ_MASK_VAL_dev0_tx_timeout_err_mask(val)        REG_FLD_VAL(DEV0_IRQ_MASK_FLD_dev0_tx_timeout_err_mask, (val))
#define DEV0_IRQ_MASK_VAL_dev2_crc_err_mask(val)               REG_FLD_VAL(DEV0_IRQ_MASK_FLD_dev2_crc_err_mask, (val))
#define DEV0_IRQ_MASK_VAL_dev1_crc_err_mask(val)               REG_FLD_VAL(DEV0_IRQ_MASK_FLD_dev1_crc_err_mask, (val))
#define DEV0_IRQ_MASK_VAL_dev0_crc_err_mask(val)               REG_FLD_VAL(DEV0_IRQ_MASK_FLD_dev0_crc_err_mask, (val))

#define DEV1_STA_VAL_dev1_intfhub_ready(val)                   REG_FLD_VAL(DEV1_STA_FLD_dev1_intfhub_ready, (val))
#define DEV1_STA_VAL_dev1_intfhub_busy(val)                    REG_FLD_VAL(DEV1_STA_FLD_dev1_intfhub_busy, (val))
#define DEV1_STA_VAL_dev1_hw_tx_busy(val)                      REG_FLD_VAL(DEV1_STA_FLD_dev1_hw_tx_busy, (val))
#define DEV1_STA_VAL_dev1_hw_rx_busy(val)                      REG_FLD_VAL(DEV1_STA_FLD_dev1_hw_rx_busy, (val))
#define DEV1_STA_VAL_dev1_sw_tx_sta(val)                       REG_FLD_VAL(DEV1_STA_FLD_dev1_sw_tx_sta, (val))
#define DEV1_STA_VAL_dev1_sw_rx_sta(val)                       REG_FLD_VAL(DEV1_STA_FLD_dev1_sw_rx_sta, (val))

#define DEV1_STA_SET_VAL_dev1_sw_tx_set(val)                   REG_FLD_VAL(DEV1_STA_SET_FLD_dev1_sw_tx_set, (val))
#define DEV1_STA_SET_VAL_dev1_sw_rx_set(val)                   REG_FLD_VAL(DEV1_STA_SET_FLD_dev1_sw_rx_set, (val))

#define DEV1_STA_CLR_VAL_dev1_hw_rx_clr(val)                   REG_FLD_VAL(DEV1_STA_CLR_FLD_dev1_hw_rx_clr, (val))
#define DEV1_STA_CLR_VAL_dev1_sw_tx_clr(val)                   REG_FLD_VAL(DEV1_STA_CLR_FLD_dev1_sw_tx_clr, (val))
#define DEV1_STA_CLR_VAL_dev1_sw_rx_clr(val)                   REG_FLD_VAL(DEV1_STA_CLR_FLD_dev1_sw_rx_clr, (val))

#define DEV1_PKT_CNT_VAL_dev1_tx_pkt_cnt(val)                  REG_FLD_VAL(DEV1_PKT_CNT_FLD_dev1_tx_pkt_cnt, (val))
#define DEV1_PKT_CNT_VAL_dev1_tx_timeout_cnt(val)              REG_FLD_VAL(DEV1_PKT_CNT_FLD_dev1_tx_timeout_cnt, (val))
#define DEV1_PKT_CNT_VAL_dev1_rx_pkt_cnt(val)                  REG_FLD_VAL(DEV1_PKT_CNT_FLD_dev1_rx_pkt_cnt, (val))
#define DEV1_PKT_CNT_VAL_dev1_rx_timeout_cnt(val)              REG_FLD_VAL(DEV1_PKT_CNT_FLD_dev1_rx_timeout_cnt, (val))

#define DEV1_CRC_STA_VAL_dev1_rx_crc_data(val)                 REG_FLD_VAL(DEV1_CRC_STA_FLD_dev1_rx_crc_data, (val))
#define DEV1_CRC_STA_VAL_dev1_tx_crc_result(val)               REG_FLD_VAL(DEV1_CRC_STA_FLD_dev1_tx_crc_result, (val))

#define DEV2_STA_VAL_dev2_intfhub_ready(val)                   REG_FLD_VAL(DEV2_STA_FLD_dev2_intfhub_ready, (val))
#define DEV2_STA_VAL_dev2_intfhub_busy(val)                    REG_FLD_VAL(DEV2_STA_FLD_dev2_intfhub_busy, (val))
#define DEV2_STA_VAL_dev2_hw_tx_busy(val)                      REG_FLD_VAL(DEV2_STA_FLD_dev2_hw_tx_busy, (val))
#define DEV2_STA_VAL_dev2_hw_rx_busy(val)                      REG_FLD_VAL(DEV2_STA_FLD_dev2_hw_rx_busy, (val))
#define DEV2_STA_VAL_dev2_sw_tx_sta(val)                       REG_FLD_VAL(DEV2_STA_FLD_dev2_sw_tx_sta, (val))
#define DEV2_STA_VAL_dev2_sw_rx_sta(val)                       REG_FLD_VAL(DEV2_STA_FLD_dev2_sw_rx_sta, (val))

#define DEV2_STA_SET_VAL_dev2_sw_tx_set(val)                   REG_FLD_VAL(DEV2_STA_SET_FLD_dev2_sw_tx_set, (val))
#define DEV2_STA_SET_VAL_dev2_sw_rx_set(val)                   REG_FLD_VAL(DEV2_STA_SET_FLD_dev2_sw_rx_set, (val))

#define DEV2_STA_CLR_VAL_dev2_hw_rx_clr(val)                   REG_FLD_VAL(DEV2_STA_CLR_FLD_dev2_hw_rx_clr, (val))
#define DEV2_STA_CLR_VAL_dev2_sw_tx_clr(val)                   REG_FLD_VAL(DEV2_STA_CLR_FLD_dev2_sw_tx_clr, (val))
#define DEV2_STA_CLR_VAL_dev2_sw_rx_clr(val)                   REG_FLD_VAL(DEV2_STA_CLR_FLD_dev2_sw_rx_clr, (val))

#define DEV2_PKT_CNT_VAL_dev2_tx_pkt_cnt(val)                  REG_FLD_VAL(DEV2_PKT_CNT_FLD_dev2_tx_pkt_cnt, (val))
#define DEV2_PKT_CNT_VAL_dev2_tx_timeout_cnt(val)              REG_FLD_VAL(DEV2_PKT_CNT_FLD_dev2_tx_timeout_cnt, (val))
#define DEV2_PKT_CNT_VAL_dev2_rx_pkt_cnt(val)                  REG_FLD_VAL(DEV2_PKT_CNT_FLD_dev2_rx_pkt_cnt, (val))
#define DEV2_PKT_CNT_VAL_dev2_rx_timeout_cnt(val)              REG_FLD_VAL(DEV2_PKT_CNT_FLD_dev2_rx_timeout_cnt, (val))

#define DEV2_CRC_STA_VAL_dev2_rx_crc_data(val)                 REG_FLD_VAL(DEV2_CRC_STA_FLD_dev2_rx_crc_data, (val))
#define DEV2_CRC_STA_VAL_dev2_tx_crc_result(val)               REG_FLD_VAL(DEV2_CRC_STA_FLD_dev2_tx_crc_result, (val))

#define CON0_VAL_dev1_pkt_type_end(val)                        REG_FLD_VAL(CON0_FLD_dev1_pkt_type_end, (val))
#define CON0_VAL_dev1_pkt_type_start(val)                      REG_FLD_VAL(CON0_FLD_dev1_pkt_type_start, (val))
#define CON0_VAL_dev0_pkt_type_end(val)                        REG_FLD_VAL(CON0_FLD_dev0_pkt_type_end, (val))
#define CON0_VAL_dev0_pkt_type_start(val)                      REG_FLD_VAL(CON0_FLD_dev0_pkt_type_start, (val))

#define CON1_VAL_dev2_pkt_type_end(val)                        REG_FLD_VAL(CON1_FLD_dev2_pkt_type_end, (val))
#define CON1_VAL_dev2_pkt_type_start(val)                      REG_FLD_VAL(CON1_FLD_dev2_pkt_type_start, (val))

#define CON2_VAL_intfhub_bypass(val)                           REG_FLD_VAL(CON2_FLD_intfhub_bypass, (val))
#define CON2_VAL_crc_en(val)                                   REG_FLD_VAL(CON2_FLD_crc_en, (val))

#define CON3_VAL_dev_timeout_time(val)                         REG_FLD_VAL(CON3_FLD_dev_timeout_time, (val))
#define CON3_VAL_dev2_header_mode(val)                         REG_FLD_VAL(CON3_FLD_dev2_header_mode, (val))
#define CON3_VAL_dev1_header_mode(val)                         REG_FLD_VAL(CON3_FLD_dev1_header_mode, (val))
#define CON3_VAL_dev0_header_mode(val)                         REG_FLD_VAL(CON3_FLD_dev0_header_mode, (val))
#define CON3_VAL_dev_wdata_addr(val)                           REG_FLD_VAL(CON3_FLD_dev_wdata_addr, (val))
#define CON3_VAL_dev_rdata_addr(val)                           REG_FLD_VAL(CON3_FLD_dev_rdata_addr, (val))

#define IRQ_STA_VAL_intfhub_ckon_req(val)                      REG_FLD_VAL(IRQ_STA_FLD_intfhub_ckon_req, (val))
#define IRQ_STA_VAL_intfhub_ckoff_req(val)                     REG_FLD_VAL(IRQ_STA_FLD_intfhub_ckoff_req, (val))
#define IRQ_STA_VAL_intfhub_restore_req(val)                   REG_FLD_VAL(IRQ_STA_FLD_intfhub_restore_req, (val))

#define IRQ_CLR_VAL_intfhub_ckon_req_clr(val)                  REG_FLD_VAL(IRQ_CLR_FLD_intfhub_ckon_req_clr, (val))
#define IRQ_CLR_VAL_intfhub_ckoff_req_clr(val)                 REG_FLD_VAL(IRQ_CLR_FLD_intfhub_ckoff_req_clr, (val))
#define IRQ_CLR_VAL_intfhub_restore_req_clr(val)               REG_FLD_VAL(IRQ_CLR_FLD_intfhub_restore_req_clr, (val))

#define IRQ_MASK_VAL_intfhub_ckon_req_mask(val)                REG_FLD_VAL(IRQ_MASK_FLD_intfhub_ckon_req_mask, (val))
#define IRQ_MASK_VAL_intfhub_ckoff_req_mask(val)               REG_FLD_VAL(IRQ_MASK_FLD_intfhub_ckoff_req_mask, (val))
#define IRQ_MASK_VAL_intfhub_restore_req_mask(val)             REG_FLD_VAL(IRQ_MASK_FLD_intfhub_restore_req_mask, (val))

#define STA0_VAL_intfhub_busy(val)                             REG_FLD_VAL(STA0_FLD_intfhub_busy, (val))
#define STA0_VAL_intfhub_active(val)                           REG_FLD_VAL(STA0_FLD_intfhub_active, (val))

#define LOOPBACK_VAL_dev2_rx2tx_loopback(val)                  REG_FLD_VAL(LOOPBACK_FLD_dev2_rx2tx_loopback, (val))
#define LOOPBACK_VAL_dev2_tx2rx_loopback(val)                  REG_FLD_VAL(LOOPBACK_FLD_dev2_tx2rx_loopback, (val))
#define LOOPBACK_VAL_dev1_rx2tx_loopback(val)                  REG_FLD_VAL(LOOPBACK_FLD_dev1_rx2tx_loopback, (val))
#define LOOPBACK_VAL_dev1_tx2rx_loopback(val)                  REG_FLD_VAL(LOOPBACK_FLD_dev1_tx2rx_loopback, (val))
#define LOOPBACK_VAL_dev0_rx2tx_loopback(val)                  REG_FLD_VAL(LOOPBACK_FLD_dev0_rx2tx_loopback, (val))
#define LOOPBACK_VAL_dev0_tx2rx_loopback(val)                  REG_FLD_VAL(LOOPBACK_FLD_dev0_tx2rx_loopback, (val))

#define CON4_VAL_sw3_rst(val)                                  REG_FLD_VAL(CON4_FLD_sw3_rst, (val))
#define CON4_VAL_sw2_rst(val)                                  REG_FLD_VAL(CON4_FLD_sw2_rst, (val))
#define CON4_VAL_sw_rst(val)                                   REG_FLD_VAL(CON4_FLD_sw_rst, (val))
#define CON4_VAL_intfhub_sw_on_trg(val)                        REG_FLD_VAL(CON4_FLD_intfhub_sw_on_trg, (val))

#define DBG_VAL_intfhub_dbg_sel(val)                           REG_FLD_VAL(DBG_FLD_intfhub_dbg_sel, (val))

#endif // __INTFHUB_REGS_MT6985_H__
