# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_MTK_DEVINFO)	+= nvmem_mtk-devinfo.o
nvmem_mtk-devinfo-y		:= mtk-devinfo.o
obj-$(CONFIG_MT635X_EFUSE)	+= nvmem-mt635x-efuse.o
nvmem-mt635x-efuse-y		:= mt635x-efuse.o
obj-$(CONFIG_MT6338_EFUSE)	+= nvmem-mt6338-efuse.o
nvmem-mt6338-efuse-y		:= mt6338-efuse.o
obj-$(CONFIG_MT6681_EFUSE)	+= nvmem-mt6681-efuse.o
nvmem-mt6681-efuse-y		:= mt6681-efuse.o
