dtb-y += e1q_chn_hkx_w00_r09.dtbo
dtb-y += e1q_chn_hkx_w00_r04.dtbo
dtb-y += e1q_chn_hkx_w00_r03.dtbo
dtb-y += e1q_chn_hkx_w00_r02.dtbo
# SPDX-License-Identifier: GPL-2.0
# COPYRIGHT(C) 2023 Samsung Electronics Co., Ltd. All Right Reserved.

# TODO: if lego is not avaiable then uncomment the following sub-makefile
# e1q_dir		:= $(srctree)/$(src)
# include $(e1q_dir)/without_lego.mk