obj-$(CONFIG_WT_SECUREBOOT_FUSE)	+= wt_secboot_fuse.o
$(warning CONFIG_WT_SECUREBOOT_FUSE=$(CONFIG_WT_SECUREBOOT_FUSE) !!!!)

obj-$(CONFIG_WT_SERIAL_NUM)	+= wt_serial_num.o
$(warning CONFIG_WT_SERIAL_NUM=$(CONFIG_WT_SERIAL_NUM) !!!!)

obj-$(CONFIG_WT_EM)	+= wt_em_status.o
$(warning CONFIG_WT_EM=$(CONFIG_WT_EM) !!!!)

obj-$(CONFIG_WT_RP_VALUE)     += wt_rp_value.o
$(warning CONFIG_WT_RP_VALUE=$(CONFIG_WT_RP_VALUE) !!!!)
