/*
 * Copyright (c) 2015 Samsung Electronics Co., Ltd. All rights reserved.
 *		http://www.samsung.com
 *
 * Chip Abstraction Layer for System power down support
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#include "../pwrcal-env.h"
#include "../pwrcal.h"
#include "../pwrcal-pmu.h"
#include "../pwrcal-rae.h"
#include "S5E7880-cmusfr.h"
#include "S5E7880-pmusfr.h"
#include "S5E7880-cmu.h"

enum sys_powerdown {
	SYS_SICD,
	SYS_STOP,
	SYS_LPD,
	SYS_DSTOP,
	NUM_SYS_POWERDOWN,
};

struct exynos_pmu_conf {
	unsigned int *reg;
	unsigned int val[NUM_SYS_POWERDOWN];
};


/* init_pmu_l2_option */
#define MANUAL_ACINACTM_VALUE		(0x1 << 3)
#define MANUAL_ACINACTM_CONTROL		(0x1 << 2)
#define MANUAL_AINACTS_VALUE		(0x1 << 1)
#define MANUAL_AINACTS_CONTROL		(0x1 << 0)
#define USE_AUTOMATIC_L2FLUSHREQ	(0x1 << 17)
#define USE_STANDBYWFIL2		(0x1 << 16)
#define USE_RETENTION			(0x1 << 4)

/* CPU option */
#define USE_SMPEN			(0x1 << 28)
#define USE_STANDBYWFE			(0x1 << 24)
#define USE_STANDBYWFI			(0x1 << 16)
#define USE_IRQCPU_FOR_PWR		(0x3 << 4)
#define USE_MEMPWRDOWN_FEEDBACK		(0x1 << 3)
#define USE_MEMPWRDOWN_COUNTER		(0x1 << 2)
#define USE_SC_FEEDBACK			(0x1 << 1)
#define USE_SC_COUNTER			(0x1 << 0)
#define DUR_WAIT_RESET			(0xF << 20)
#define DUR_SCALL			(0xF << 4)

/* init_pmu_up_scheduler */
#define ENABLE_CPUCL0_CPU		(0x1 << 0)
#define ENABLE_CPUCL1_CPU		(0x1 << 1)

/* init_set_duration */
#define DUR_STABLE_MASK			0xFFFFF
#define DUR_DVS_MASK			0x1FFF
#define TCXO_DUR_STABLE			0x657		// Setting Value -> 1ms (Need -> 355us)
#define EXTREG_DUR_STABLE		0x657		// Setting Value -> 1ms (Need -> 427us)
#define CP_DVS_COUNTER			0x0

/* init_pshold_setting_value*/
#define ENABLE_HW_TRIP			(0x1 << 31)
#define PS_HOLD_OUTPUT_HIGH		(0x3 << 8)

/* init_ect_setting_value*/
#define TIMEOUT_ENABLE			(0x1 << 0)
#define PAD_INITIATE_WAKEUP		(0x1 << 28)
#define EMULATION_ENABLE	(0x1 << 31)
#define	PWRCAL_CENTRALSEQ_PWR_CFG	0x10000


struct system_power_backup_reg {
	void *reg;
	unsigned int backup;
	void *reg_stat;
	unsigned int backup_stat;
	void *pwr_stat_reg;	/* if pwr_check true, this reg should be set */
	unsigned int valid;
};

struct cmu_backup {
	void *sfr;
	unsigned int mask;
	void *power;
	unsigned int backup;
	int backup_valid;
};


#define SYS_PWR_BACK_REG(_reg, _reg_stat, _pwr_stat_reg)	\
{						\
	.reg		= _reg,			\
	.backup		= 0,			\
	.reg_stat	= _reg_stat,		\
	.backup_stat	= 0,			\
	.pwr_stat_reg	= _pwr_stat_reg,	\
	.valid		= 0,			\
}

static unsigned int *pmu_cpuoption_sfrlist[] = {
	PMU_CPUCL0_CPU0_OPTION,
	PMU_CPUCL0_CPU1_OPTION,
	PMU_CPUCL0_CPU2_OPTION,
	PMU_CPUCL0_CPU3_OPTION,
	PMU_CPUCL1_CPU0_OPTION,
	PMU_CPUCL1_CPU1_OPTION,
	PMU_CPUCL1_CPU2_OPTION,
	PMU_CPUCL1_CPU3_OPTION,
};

static unsigned int *pmu_cpuduration_sfrlist[] = {
	PMU_CPUCL0_CPU0_DURATION0,
	PMU_CPUCL0_CPU1_DURATION0,
	PMU_CPUCL0_CPU2_DURATION0,
	PMU_CPUCL0_CPU3_DURATION0,
	PMU_CPUCL1_CPU0_DURATION0,
	PMU_CPUCL1_CPU1_DURATION0,
	PMU_CPUCL1_CPU2_DURATION0,
	PMU_CPUCL1_CPU3_DURATION0,
};

static unsigned int *pmu_noncpuoption_sfrlist[] = {
	PMU_CPUCL0_NONCPU_OPTION,
	PMU_CPUCL1_NONCPU_OPTION,
};

static unsigned int *pmu_noncpuduration_sfrlist[] = {
	PMU_CPUCL0_NONCPU_DURATION0,
	PMU_CPUCL1_NONCPU_DURATION0,
};



static void init_pmu_cpu_option(void)
{
	unsigned long long cpu;
	unsigned int tmp;

	/* Joon use sc_counter */
	/* enable to wait for low SMP-bit at sys power down */
	for (cpu = 0; cpu < sizeof(pmu_cpuoption_sfrlist) / sizeof(pmu_cpuoption_sfrlist[0]); cpu++) {
		tmp = pwrcal_readl(pmu_cpuoption_sfrlist[cpu]);
		tmp |= USE_SC_COUNTER;
		tmp |= USE_SMPEN;
		tmp |= USE_STANDBYWFI;
		tmp |= USE_MEMPWRDOWN_FEEDBACK;
		tmp &= ~USE_SC_FEEDBACK;
		tmp &= ~USE_STANDBYWFE;
		pwrcal_writel(pmu_cpuoption_sfrlist[cpu], tmp);

		pwrcal_setf(pmu_cpuduration_sfrlist[cpu], 0x8, 0xf, 0x3);
		pwrcal_setf(pmu_cpuduration_sfrlist[cpu], 0x4, 0xf, 0x3);
	}
}

static void init_pmu_noncpu_option(void)
{

	unsigned long long i;
	unsigned int tmp;

	/* Joon use sc_counter */
	for (i = 0; i < sizeof(pmu_noncpuoption_sfrlist) / sizeof(pmu_noncpuoption_sfrlist[0]); i++) {
		tmp = pwrcal_readl(pmu_noncpuoption_sfrlist[i]);
		tmp |= USE_SC_COUNTER;
		tmp &= ~USE_SC_FEEDBACK;
		pwrcal_writel(pmu_noncpuoption_sfrlist[i], tmp);

		pwrcal_setf(pmu_noncpuduration_sfrlist[i], 0x8, 0xf, 0x3);
		pwrcal_setf(pmu_noncpuduration_sfrlist[i], 0x4, 0xf, 0x3);
	}
}


static void init_pmu_l2_option(void)
{
	unsigned int tmp;

	/* disable automatic L2 flush */
	/* disable L2 retention */

	tmp = pwrcal_readl(PMU_CPUCL0_L2_OPTION);
	tmp &= ~(USE_AUTOMATIC_L2FLUSHREQ | USE_RETENTION);
	tmp |= USE_STANDBYWFIL2;
	pwrcal_writel(PMU_CPUCL0_L2_OPTION, tmp);


	tmp = pwrcal_readl(PMU_CPUCL1_L2_OPTION);
	tmp &= ~(USE_AUTOMATIC_L2FLUSHREQ | USE_RETENTION);
	tmp |= USE_STANDBYWFIL2;
	pwrcal_writel(PMU_CPUCL1_L2_OPTION, tmp);
}

static void init_pmu_up_scheduler(void)
{
	unsigned int tmp;

	/* limit in-rush current for CPUCL0/1 local power up */
	tmp = pwrcal_readl(PMU_UP_SCHEDULER);
	tmp |= ENABLE_CPUCL0_CPU | ENABLE_CPUCL1_CPU;
	pwrcal_writel(PMU_UP_SCHEDULER, tmp);
}

/* init_pmu_feedback */
static unsigned int *pmu_feedback_sfrlist[] = {
	PMU_TOP_PWR_OPTION,
	PMU_TOP_PWR_MIF_OPTION,
	PMU_TOP_PWR_CPUCL_OPTION,
	PMU_DISPAUD_OPTION,
	PMU_MFCMSCL_OPTION,
	PMU_ISP_OPTION,
	PMU_MEMORY_CPUCL_OPTION,
};

static void init_set_duration(void)
{
	unsigned int tmp;

	tmp = pwrcal_readl(PMU_TCXO_DURATION3);
	tmp &= ~DUR_STABLE_MASK;
	tmp |= TCXO_DUR_STABLE;
	pwrcal_writel(PMU_TCXO_DURATION3, tmp);

	tmp = pwrcal_readl(PMU_EXT_REGULATOR_SUB_DURATION3);
	tmp &= ~DUR_STABLE_MASK;
	tmp |= EXTREG_DUR_STABLE;
	pwrcal_writel(PMU_EXT_REGULATOR_SUB_DURATION3, tmp);

	tmp = pwrcal_readl(PMU_CP_DVS_COUNTER);
	tmp &= ~DUR_DVS_MASK;
	tmp |= CP_DVS_COUNTER;
	pwrcal_writel(PMU_CP_DVS_COUNTER, tmp);

}

static void init_pmu_feedback(void)
{
	unsigned long long i;
	unsigned int tmp;

	for (i = 0; i < sizeof(pmu_feedback_sfrlist) / sizeof(pmu_feedback_sfrlist[0]); i++) {
		tmp = pwrcal_readl(pmu_feedback_sfrlist[i]);
		tmp &= ~USE_SC_COUNTER;
		tmp |= USE_SC_FEEDBACK;

		if (pmu_feedback_sfrlist[i] == PMU_DISPAUD_OPTION)
			tmp |= EMULATION_ENABLE;

		pwrcal_writel(pmu_feedback_sfrlist[i], tmp);
	}
}

static void init_ps_hold_setting(void)
{
	unsigned int tmp;

	tmp = pwrcal_readl(PMU_PS_HOLD_CONTROL);
	tmp |= (ENABLE_HW_TRIP | PS_HOLD_OUTPUT_HIGH);
	pwrcal_writel(PMU_PS_HOLD_CONTROL, tmp);
}

static void set_pmu_lpi_timeout(void)
{
	unsigned int tmp;

	tmp = pwrcal_readl(PMU_RESET_LPI_TIMEOUT_QCH);
	tmp |= TIMEOUT_ENABLE;
	pwrcal_writel(PMU_RESET_LPI_TIMEOUT_QCH, tmp);
}

static void enable_armidleclockdown(void)
{
	pwrcal_setbit(CPUCL0_PWR_CTRL3, 0, 1);
	pwrcal_setbit(CPUCL0_PWR_CTRL3, 1, 1);

	pwrcal_setbit(CPUCL1_PWR_CTRL3, 0, 1);
	pwrcal_setbit(CPUCL1_PWR_CTRL3, 1, 1);
}

inline void disable_armidleclockdown(void)
{
	pwrcal_setbit(CPUCL0_PWR_CTRL3, 0, 0);
	pwrcal_setbit(CPUCL1_PWR_CTRL3, 0, 0);
}

static void syspwr_init(void)
{
	init_pmu_feedback();
	init_pmu_l2_option();
	init_pmu_cpu_option();
	init_pmu_noncpu_option();
	init_pmu_up_scheduler();
	init_ps_hold_setting();
	init_set_duration();
	enable_armidleclockdown();
	set_pmu_lpi_timeout();
}

static struct exynos_pmu_conf exynos_syspwr_pmu_config[] = {
	/* { .addr = address, .val = { SICD, STOP, LPD, DSTOP } } */
	{ PMU_CPUCL0_CPU0_SYS_PWR_REG,					{0x0, 0x8, 0x0, 0x0} },
	{ PMU_DIS_IRQ_CPUCL0_CPU0_LOCAL_SYS_PWR_REG,			{0x0, 0x0, 0x0, 0x0} },
	{ PMU_DIS_IRQ_CPUCL0_CPU0_CENTRAL_SYS_PWR_REG,			{0x0, 0x0, 0x0, 0x0} },
	{ PMU_DIS_IRQ_CPUCL0_CPU0_CPUSEQUENCER_SYS_PWR_REG,		{0x0, 0x0, 0x0, 0x0} },
	{ PMU_CPUCL0_CPU1_SYS_PWR_REG,					{0x0, 0x8, 0x0, 0x0} },
	{ PMU_DIS_IRQ_CPUCL0_CPU1_LOCAL_SYS_PWR_REG,			{0x0, 0x0, 0x0, 0x0} },
	{ PMU_DIS_IRQ_CPUCL0_CPU1_CENTRAL_SYS_PWR_REG,			{0x0, 0x0, 0x0, 0x0} },
	{ PMU_DIS_IRQ_CPUCL0_CPU1_CPUSEQUENCER_SYS_PWR_REG,		{0x0, 0x0, 0x0, 0x0} },
	{ PMU_CPUCL0_CPU2_SYS_PWR_REG,					{0x0, 0x8, 0x0, 0x0} },
	{ PMU_DIS_IRQ_CPUCL0_CPU2_LOCAL_SYS_PWR_REG,			{0x0, 0x0, 0x0, 0x0} },
	{ PMU_DIS_IRQ_CPUCL0_CPU2_CENTRAL_SYS_PWR_REG,			{0x0, 0x0, 0x0, 0x0} },
	{ PMU_DIS_IRQ_CPUCL0_CPU2_CPUSEQUENCER_SYS_PWR_REG,		{0x0, 0x0, 0x0, 0x0} },
	{ PMU_CPUCL0_CPU3_SYS_PWR_REG,					{0x0, 0x8, 0x0, 0x0} },
	{ PMU_DIS_IRQ_CPUCL0_CPU3_LOCAL_SYS_PWR_REG,			{0x0, 0x0, 0x0, 0x0} },
	{ PMU_DIS_IRQ_CPUCL0_CPU3_CENTRAL_SYS_PWR_REG,			{0x0, 0x0, 0x0, 0x0} },
	{ PMU_DIS_IRQ_CPUCL0_CPU3_CPUSEQUENCER_SYS_PWR_REG,		{0x0, 0x0, 0x0, 0x0} },
	{ PMU_CPUCL1_CPU0_SYS_PWR_REG,					{0x0, 0x8, 0x0, 0x0} },
	{ PMU_DIS_IRQ_CPUCL1_CPU0_LOCAL_SYS_PWR_REG,			{0x0, 0x0, 0x0, 0x0} },
	{ PMU_DIS_IRQ_CPUCL1_CPU0_CENTRAL_SYS_PWR_REG,			{0x0, 0x0, 0x0, 0x0} },
	{ PMU_DIS_IRQ_CPUCL1_CPU0_CPUSEQUENCER_SYS_PWR_REG,		{0x0, 0x0, 0x0, 0x0} },
	{ PMU_CPUCL1_CPU1_SYS_PWR_REG,					{0x0, 0x8, 0x0, 0x0} },
	{ PMU_DIS_IRQ_CPUCL1_CPU1_LOCAL_SYS_PWR_REG,			{0x0, 0x0, 0x0, 0x0} },
	{ PMU_DIS_IRQ_CPUCL1_CPU1_CENTRAL_SYS_PWR_REG,			{0x0, 0x0, 0x0, 0x0} },
	{ PMU_DIS_IRQ_CPUCL1_CPU1_CPUSEQUENCER_SYS_PWR_REG,		{0x0, 0x0, 0x0, 0x0} },
	{ PMU_CPUCL1_CPU2_SYS_PWR_REG,					{0x0, 0x8, 0x0, 0x0} },
	{ PMU_DIS_IRQ_CPUCL1_CPU2_LOCAL_SYS_PWR_REG,			{0x0, 0x0, 0x0, 0x0} },
	{ PMU_DIS_IRQ_CPUCL1_CPU2_CENTRAL_SYS_PWR_REG,			{0x0, 0x0, 0x0, 0x0} },
	{ PMU_DIS_IRQ_CPUCL1_CPU2_CPUSEQUENCER_SYS_PWR_REG,		{0x0, 0x0, 0x0, 0x0} },
	{ PMU_CPUCL1_CPU3_SYS_PWR_REG,					{0x0, 0x8, 0x0, 0x0} },
	{ PMU_DIS_IRQ_CPUCL1_CPU3_LOCAL_SYS_PWR_REG,			{0x0, 0x0, 0x0, 0x0} },
	{ PMU_DIS_IRQ_CPUCL1_CPU3_CENTRAL_SYS_PWR_REG,			{0x0, 0x0, 0x0, 0x0} },
	{ PMU_DIS_IRQ_CPUCL1_CPU3_CPUSEQUENCER_SYS_PWR_REG,		{0x0, 0x0, 0x0, 0x0} },
	{ PMU_CPUCL0_NONCPU_SYS_PWR_REG,				{0xF, 0xF, 0x0, 0x0} },
	{ PMU_CPUCL1_NONCPU_SYS_PWR_REG,				{0xF, 0xF, 0x0, 0x0} },
	{ PMU_CPUCL0_L2_SYS_PWR_REG,					{0x7, 0x7, 0x0, 0x0} },
	{ PMU_CPUCL1_L2_SYS_PWR_REG,					{0x7, 0x7, 0x0, 0x0} },
	{ PMU_CLKSTOP_CMU_TOP_SYS_PWR_REG,				{0x1, 0x0, 0x0, 0x0} },
	{ PMU_CLKRUN_CMU_TOP_SYS_PWR_REG,				{0x1, 0x0, 0x0, 0x0} },
	{ PMU_RETENTION_CMU_TOP_SYS_PWR_REG,				{0x3, 0x3, 0x0, 0x0} },
	{ PMU_RESET_CMU_TOP_SYS_PWR_REG,				{0x3, 0x3, 0x3, 0x3} },
	{ PMU_RESET_CPUCLKSTOP_SYS_PWR_REG,				{0x3, 0x3, 0x3, 0x0} },
	{ PMU_CLKSTOP_CMU_MIF_SYS_PWR_REG,				{0x1, 0x0, 0x1, 0x0} },
	{ PMU_CLKRUN_CMU_MIF_SYS_PWR_REG,				{0x1, 0x0, 0x1, 0x0} },
	{ PMU_RETENTION_CMU_MIF_SYS_PWR_REG,				{0x3, 0x3, 0x3, 0x0} },
	{ PMU_RESET_CMU_MIF_SYS_PWR_REG,				{0x3, 0x3, 0x3, 0x3} },
	{ PMU_DDRPHY_CLKSTOP_SYS_PWR_REG,				{0x1, 0x0, 0x1, 0x0} },
	{ PMU_DDRPHY_ISO_SYS_PWR_REG,					{0x1, 0x1, 0x1, 0x0} },
	{ PMU_DDRPHY_SOC2_ISO_SYS_PWR_REG,				{0x1, 0x1, 0x1, 0x1} },
	{ PMU_DDRPHY_DLL_CLK_SYS_PWR_REG,				{0x0, 0x0, 0x1, 0x0} },
	{ PMU_DISABLE_PLL_CMU_TOP_SYS_PWR_REG,				{0x0, 0x0, 0x0, 0x0} },
	{ PMU_RESET_CMU_CPUCL_SYS_PWR_REG,				{0x3, 0x3, 0x3, 0x0} },
	{ PMU_RETENTION_CMU_CPUCL_SYS_PWR_REG,				{0x3, 0x3, 0x0, 0x3} },
	{ PMU_DISABLE_PLL_CMU_MIF_SYS_PWR_REG,				{0x0, 0x0, 0x1, 0x0} },
	{ PMU_RESET_AHEAD_CP_SYS_PWR_REG,				{0x3, 0x3, 0x3, 0x3} },
	{ PMU_RESET_AHEAD_GNSS_SYS_PWR_REG,				{0x3, 0x3, 0x3, 0x3} },
	{ PMU_SLEEP_RESET_CPUCL_SYS_PWR_REG,				{0x3, 0x3, 0x3, 0x0} },
	{ PMU_TOP_BUS_SYS_PWR_REG,					{0x7, 0x0, 0x0, 0x0} },
	{ PMU_TOP_RETENTION_SYS_PWR_REG,				{0x3, 0x3, 0x0, 0x0} },
	{ PMU_TOP_PWR_SYS_PWR_REG,					{0x3, 0x3, 0x0, 0x0} },
	{ PMU_TOP_RETENTION_CPUCL_SYS_PWR_REG,				{0x3, 0x3, 0x0, 0x3} },
	{ PMU_TOP_BUS_MIF_SYS_PWR_REG,					{0x0, 0x0, 0x7, 0x0} },
	{ PMU_TOP_RETENTION_MIF_SYS_PWR_REG,				{0x3, 0x3, 0x3, 0x0} },
	{ PMU_TOP_PWR_MIF_SYS_PWR_REG,					{0x3, 0x3, 0x3, 0x0} },
	{ PMU_TOP_PWR_CPUCL_SYS_PWR_REG,				{0x3, 0x3, 0x0, 0x3} },
	{ PMU_LOGIC_RESET_SYS_PWR_REG,					{0x3, 0x3, 0x0, 0x0} },
	{ PMU_OSCCLK_GATE_SYS_PWR_REG,					{0x1, 0x0, 0x0, 0x0} },
	{ PMU_SLEEP_RESET_SYS_PWR_REG,					{0x3, 0x3, 0x3, 0x3} },
	{ PMU_OSCCLK_GATE_CPUCL_SYS_PWR_REG,				{0x1, 0x0, 0x0, 0x1} },
	{ PMU_LOGIC_RESET_MIF_SYS_PWR_REG,				{0x3, 0x3, 0x3, 0x0} },
	{ PMU_OSCCLK_GATE_MIF_SYS_PWR_REG,				{0x1, 0x0, 0x1, 0x0} },
	{ PMU_SLEEP_RESET_MIF_SYS_PWR_REG,				{0x3, 0x3, 0x3, 0x3} },
	{ PMU_RESET_ASB_MIF_GNSS_SYS_PWR_REG,				{0x3, 0x3, 0x3, 0x3} },
	{ PMU_MEMORY_TOP_SYS_PWR_REG,					{0x3, 0x3, 0x0, 0x0} },
	{ PMU_TCXO_GATE_GNSS_SYS_PWR_REG,				{0x1, 0x1, 0x1, 0x1} },
	{ PMU_RESET_ASB_GNSS_SYS_PWR_REG,				{0x3, 0x3, 0x3, 0x3} },
	{ PMU_CLEANY_BUS_CP_SYS_PWR_REG,				{0x1, 0x1, 0x1, 0x1} },
	{ PMU_LOGIC_RESET_CP_SYS_PWR_REG,				{0x3, 0x3, 0x3, 0x3} },
	{ PMU_TCXO_GATE_CP_SYS_PWR_REG,					{0x1, 0x1, 0x1, 0x1} },
	{ PMU_RESET_ASB_CP_SYS_PWR_REG,					{0x3, 0x3, 0x3, 0x3} },
	{ PMU_RESET_ASB_MIF_CP_SYS_PWR_REG,				{0x3, 0x3, 0x3, 0x3} },
	{ PMU_MEMORY_MIF_TOP_SYS_PWR_REG,				{0x3, 0x3, 0x3, 0x0} },
	{ PMU_CLEANY_BUS_GNSS_SYS_PWR_REG,				{0x1, 0x1, 0x1, 0x1} },
	{ PMU_LOGIC_RESET_GNSS_SYS_PWR_REG,				{0x3, 0x3, 0x3, 0x3} },
	{ PMU_LOGIC_RESET_DDRPHY_SYS_PWR_REG,				{0x3, 0x3, 0x3, 0x3} },
	{ PMU_RETENTION_DDRPHY_SYS_PWR_REG,				{0x3, 0x3, 0x3, 0x3} },
	{ PMU_MEMORY_CPUCL_SYS_PWR_REG,					{0x3, 0x3, 0x3, 0x3} },
	{ PMU_PWR_DDRPHY_SYS_PWR_REG,					{0x3, 0x3, 0x3, 0x0} },
	{ PMU_PAD_RETENTION_LPDDR4_SYS_PWR_REG,				{0x1, 0x1, 0x1, 0x0} },
	{ PMU_PAD_RETENTION_AUD_SYS_PWR_REG,				{0x1, 0x1, 0x1, 0x0} },
	{ PMU_PAD_RETENTION_MMC2_SYS_PWR_REG,				{0x1, 0x1, 0x0, 0x0} },
	{ PMU_PAD_RETENTION_TOP_SYS_PWR_REG,				{0x1, 0x1, 0x0, 0x0} },
	{ PMU_PAD_RETENTION_UART_SYS_PWR_REG,				{0x1, 0x1, 0x0, 0x0} },
	{ PMU_PAD_RETENTION_MMC0_SYS_PWR_REG,				{0x1, 0x1, 0x0, 0x0} },
	{ PMU_PAD_RETENTION_MMC1_SYS_PWR_REG,				{0x1, 0x1, 0x0, 0x0} },
	{ PMU_PAD_RETENTION_SPI_SYS_PWR_REG,				{0x1, 0x1, 0x0, 0x0} },
	{ PMU_PAD_RETENTION_MIF_SYS_PWR_REG,				{0x1, 0x1, 0x1, 0x0} },
	{ PMU_PAD_ISOLATION_SYS_PWR_REG,				{0x1, 0x1, 0x0, 0x0} },
	{ PMU_PAD_RETENTION_BOOTLDO_SYS_PWR_REG,			{0x1, 0x1, 0x0, 0x0} },
	{ PMU_PAD_RETENTION_UFS_SYS_PWR_REG,				{0x1, 0x1, 0x1, 0x1} },
	{ PMU_PAD_ISOLATION_MIF_SYS_PWR_REG,				{0x1, 0x1, 0x1, 0x0} },
	{ PMU_PAD_ALV_SEL_SYS_PWR_REG,					{0x1, 0x1, 0x1, 0x1} },
	{ PMU_TCXO_SYS_PWR_REG,						{0x1, 0x0, 0x1, 0x0} },
	{ PMU_EXT_REGULATOR_SUB_SYS_PWR_REG,				{0x1, 0x1, 0x1, 0x0} },
	{ PMU_EXT_REGULATOR_MAIN_SYS_PWR_REG,				{0x1, 0x1, 0x1, 0x1} },
	{ PMU_GPIO_MODE_SYS_PWR_REG,					{0x1, 0x1, 0x0, 0x0} },
	{ PMU_GPIO_MODE_MIF_SYS_PWR_REG,				{0x1, 0x1, 0x1, 0x0} },
	{ PMU_GPIO_MODE_DISPAUD_SYS_PWR_REG,				{0x1, 0x1, 0x1, 0x0} },
	{ PMU_CLKSTOP_OPEN_CMU_TOP_SYS_PWR_REG,				{0x0, 0x0, 0x0, 0x0} },
	{ PMU_CLKSTOP_OPEN_CMU_MIF_SYS_PWR_REG,				{0x0, 0x0, 0x0, 0x0} },
	{ PMU_CLKSTOP_OPEN_CMU_G3D_SYS_PWR_REG,				{0x0, 0x0, 0x0, 0x0} },
	{ PMU_CLKSTOP_OPEN_CMU_DISPAUD_SYS_PWR_REG,			{0x0, 0x0, 0x0, 0x0} },
	{ PMU_CLKSTOP_OPEN_CMU_ISP_SYS_PWR_REG,				{0x0, 0x0, 0x0, 0x0} },
	{ PMU_CLKSTOP_OPEN_CMU_MFCMSCL_SYS_PWR_REG,			{0x0, 0x0, 0x0, 0x0} },
	{ PMU_G3D_SYS_PWR_REG,						{0xF, 0x0, 0x0, 0x0} },
	{ PMU_DISPAUD_SYS_PWR_REG,					{0xF, 0x0, 0xF, 0x0} },
	{ PMU_ISP_SYS_PWR_REG,						{0xF, 0x0, 0x0, 0x0} },
	{ PMU_MFCMSCL_SYS_PWR_REG,					{0xF, 0x0, 0x0, 0x0} },
	{ PMU_CLKRUN_CMU_G3D_SYS_PWR_REG,				{0x0, 0x0, 0x0, 0x0} },
	{ PMU_CLKRUN_CMU_DISPAUD_SYS_PWR_REG,				{0x1, 0x0, 0x0, 0x0} },
	{ PMU_CLKRUN_CMU_ISP_SYS_PWR_REG,				{0x0, 0x0, 0x0, 0x0} },
	{ PMU_CLKRUN_CMU_MFCMSCL_SYS_PWR_REG,				{0x0, 0x0, 0x0, 0x0} },
	{ PMU_CLKSTOP_CMU_G3D_SYS_PWR_REG,				{0x0, 0x0, 0x0, 0x0} },
	{ PMU_CLKSTOP_CMU_DISPAUD_SYS_PWR_REG,				{0x1, 0x0, 0x0, 0x0} },
	{ PMU_CLKSTOP_CMU_ISP_SYS_PWR_REG,				{0x0, 0x0, 0x0, 0x0} },
	{ PMU_CLKSTOP_CMU_MFCMSCL_SYS_PWR_REG,				{0x0, 0x0, 0x0, 0x0} },
	{ PMU_DISABLE_PLL_CMU_G3D_SYS_PWR_REG,				{0x0, 0x0, 0x0, 0x0} },
	{ PMU_DISABLE_PLL_CMU_DISPAUD_SYS_PWR_REG,			{0x0, 0x0, 0x0, 0x0} },
	{ PMU_DISABLE_PLL_CMU_ISP_SYS_PWR_REG,				{0x0, 0x0, 0x0, 0x0} },
	{ PMU_DISABLE_PLL_CMU_MFCMSCL_SYS_PWR_REG,			{0x0, 0x0, 0x0, 0x0} },
	{ PMU_RESET_LOGIC_G3D_SYS_PWR_REG,				{0x0, 0x0, 0x0, 0x0} },
	{ PMU_RESET_LOGIC_DISPAUD_SYS_PWR_REG,				{0x3, 0x0, 0x0, 0x0} },
	{ PMU_RESET_LOGIC_ISP_SYS_PWR_REG,				{0x0, 0x0, 0x0, 0x0} },
	{ PMU_RESET_LOGIC_MFCMSCL_SYS_PWR_REG,				{0x0, 0x0, 0x0, 0x0} },
	{ PMU_MEMORY_G3D_SYS_PWR_REG,					{0x0, 0x0, 0x0, 0x0} },
	{ PMU_MEMORY_DISPAUD_SYS_PWR_REG,				{0x3, 0x0, 0x0, 0x0} },
	{ PMU_MEMORY_ISP_SYS_PWR_REG,					{0x0, 0x0, 0x0, 0x0} },
	{ PMU_MEMORY_MFCMSCL_SYS_PWR_REG,				{0x0, 0x0, 0x0, 0x0} },
	{ PMU_RESET_CMU_G3D_SYS_PWR_REG,				{0x0, 0x0, 0x0, 0x0} },
	{ PMU_RESET_CMU_DISPAUD_SYS_PWR_REG,				{0x3, 0x0, 0x0, 0x0} },
	{ PMU_RESET_CMU_ISP_SYS_PWR_REG,				{0x0, 0x0, 0x0, 0x0} },
	{ PMU_RESET_CMU_MFCMSCL_SYS_PWR_REG,				{0x0, 0x0, 0x0, 0x0} },
	{ 0, },
};

static struct exynos_pmu_conf exynos_syspwr_pmu_option[] = {
	/* { .addr = address, .val =					{ SICD, STOP, LPD, DSTOP } } */
	{PMU_PMU_SYNC_CTRL,					{0x1, 0x1, 0x1, 0x1} },
	{PMU_CENTRAL_SEQ_OPTION,				{0xFF0000, 0xFF0000, 0xFF0000, 0xFF0000} },
	{PMU_CENTRAL_SEQ_OPTION1,				{0x10000000, 0x10000000, 0x10000000, 0x10000000} },
	{PMU_CENTRAL_SEQ_MIF_OPTION,				{0x10, 0x10, 0x10, 0x10} },
	{0, },
};


static struct cmu_backup cmu_backup_list[] = {
	{MEDIA_PLL_LOCK,	0xFFFFFFFF,	NULL,	0,	0},
	{BUS_PLL_LOCK,	0xFFFFFFFF,	NULL,	0,	0},
	{MEDIA_PLL_CON0,	0xFFFFFFFF,	NULL,	0,	0},
	{MEDIA_PLL_CON1,	0xFFFFFFFF,	NULL,	0,	0},
	{BUS_PLL_CON0,	0xFFFFFFFF,	NULL,	0,	0},
	{BUS_PLL_CON1,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_MEDIA_PLL,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_BUS_PLL,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_MIF_SWITCH,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLK_CCORE_BUSD,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLK_CCORE_CCI,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_ISP_VRA,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_ISP_CAM,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_ISP_ISP,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_DISPAUD_BUS,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_DISPAUD_DECON_INT_VCLK,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_DISPAUD_DECON_INT_ECLK,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_MFCMSCL_MSCL,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_MFCMSCL_MFC,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_FSYS_BUS,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_FSYS_MMC0,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_FSYS_MMC1,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_FSYS_MMC2,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_FSYS_UFSUNIPRO,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_FSYS_UFSUNIPRO_CFG,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_FSYS_USB20DRD_REFCLK,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_PERI_BUS,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_PERI_UART_BTWIFIFM,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_PERI_UART_DEBUG,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_PERI_UART_SENSOR,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_PERI_SPI_FRONTFROM,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_PERI_SPI_REARFROM,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_PERI_SPI_ESE,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_PERI_SPI_VOICEPROCESSOR,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_PERI_SPI_SENSORHUB,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_ISP_SENSOR0,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_ISP_SENSOR1,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_ISP_SENSOR2,	0xFFDFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_MIF_SWITCH,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLK_CCORE_BUSD,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLK_CCORE_APB,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLK_CCORE_CCI,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLK_CCORE_BUSP,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLK_CCORE_HSI2C,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_CP_MEDIA_PLL,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_CPUCL0_SWITCH,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_CPUCL1_SWITCH,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_G3D_SWITCH,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_ISP_VRA,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_ISP_CAM,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_ISP_ISP,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_DISPAUD_BUS,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_DISPAUD_DECON_INT_VCLK,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_DISPAUD_DECON_INT_ECLK,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_MFCMSCL_MSCL,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_MFCMSCL_MFC,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_FSYS_BUS,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_FSYS_MMC0,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_FSYS_MMC1,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_FSYS_MMC2,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_FSYS_UFSUNIPRO,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_FSYS_UFSUNIPRO_CFG,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_FSYS_USB20DRD_REFCLK,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_PERI_BUS,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_PERI_UART_BTWIFIFM,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_PERI_UART_DEBUG,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_PERI_UART_SENSOR,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_PERI_SPI_FRONTFROM,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_PERI_SPI_REARFROM,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_PERI_SPI_ESE,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_PERI_SPI_VOICEPROCESSOR,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_PERI_SPI_SENSORHUB,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_ISP_SENSOR0,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_ISP_SENSOR1,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_CLKCMU_ISP_SENSOR2,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_CCORE_OSCCLK,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_VAL_CLK_CCORE_BUSD,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_VAL_CLK_CCORE_CCI,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_CCORE_BUSD,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_CCORE_APB_0,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_CCORE_APB_1,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_CCORE_APB_SECURE_MODAPIF,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_CCORE_CCI,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_CCORE_BUSP,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_CCORE_HSI2C,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_CP_MEDIA_PLL,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_MIF_SWITCH,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_CPUCL0_SWITCH,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_CPUCL1_SWITCH,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_G3D_SWITCH,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_ISP_VRA,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_ISP_CAM,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_ISP_ISP,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_DISPAUD_BUS,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_DISPAUD_DECON_INT_VCLK,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_DISPAUD_DECON_INT_ECLK,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_MFCMSCL_MSCL,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_MFCMSCL_MFC,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_FSYS_BUS,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_FSYS_MMC0,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_FSYS_MMC1,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_FSYS_MMC2,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_FSYS_UFSUNIPRO,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_FSYS_UFSUNIPRO_CFG,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_FSYS_USB20DRD_REFCLK,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_PERI_BUS,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_PERI_UART_BTWIFIFM,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_PERI_UART_DEBUG,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_PERI_UART_SENSOR,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_PERI_SPI_FRONTFROM,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_PERI_SPI_REARFROM,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_PERI_SPI_ESE,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_PERI_SPI_VOICEPROCESSOR,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_PERI_SPI_SENSORHUB,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_ISP_SENSOR0,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_ISP_SENSOR1,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKCMU_ISP_SENSOR2,	0xFFFFFFFF,	NULL,	0,	0},
	{CLKOUT_CMU_CCORE,	0xFFFFFFFF,	NULL,	0,	0},
	{CCORE_ROOTCLKEN,	0xFFFFFFFF,	NULL,	0,	0},
	{CCORE_ROOTCLKEN_ON_GATE,	0xFFFFFFFF,	NULL,	0,	0},
	{DREX_FREQ_CTRL1,	0xFFFFFFFF,	NULL,	0,	0},
	{ACG_ENABLE,	0xFFFFFFFF,	NULL,	0,	0},
	{CP_CTRL_HSI2C_ENABLE,	0xFFFFFFFF,	NULL,	0,	0},
	{CP_CTRL_ADCIF_ENABLE,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_MAN_CLK_CCORE_BUSD,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_MAN_CLK_CCORE_CCI,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_STAT_CLK_CCORE_BUSD_0,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_STAT_CLK_CCORE_BUSD_1,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_STAT_CLK_CCORE_CCI,	0xFFFFFFFF,	NULL,	0,	0},
	{QCH_CTRL_UID_CCORE_D_CCI,	0xFFFFFFFF,	NULL,	0,	0},
	{QCH_CTRL_UID_CCORE_D_NRT,	0xFFFFFFFF,	NULL,	0,	0},
	{QCH_CTRL_UID_CCORE_D_RT,	0xFFFFFFFF,	NULL,	0,	0},
	{QCH_CTRL_UID_ASYNCM_LH_G3D0_CCORE_D_NRT,	0xFFFFFFFF,	NULL,	0,	0},
	{QCH_CTRL_UID_ASYNCM_LH_G3D1_CCORE_D_NRT,	0xFFFFFFFF,	NULL,	0,	0},
	{QCH_CTRL_UID_ASYNCM_LH_MFCMSCL_CCORE_D_NRT,	0xFFFFFFFF,	NULL,	0,	0},
	{QCH_CTRL_UID_ASYNCM_LH_FSYS_CCORE_D_NRT,	0xFFFFFFFF,	NULL,	0,	0},
	{QCH_CTRL_UID_ASYNCM_LH_ISP_CCORE_D_NRT,	0xFFFFFFFF,	NULL,	0,	0},
	{QCH_CTRL_UID_ASYNCM_LH_ISP_CCORE_D_RT,	0xFFFFFFFF,	NULL,	0,	0},
	{QCH_CTRL_UID_ASYNCM_LH_DISPAUD_CCORE_D_RT,	0xFFFFFFFF,	NULL,	0,	0},
	{QCH_CTRL_UID_ASYNCM_LH_CP_CCORE_D_CP,	0xFFFFFFFF,	NULL,	0,	0},
	{QCH_CTRL_UID_ASYNCM_LH_GNSS_CCORE_D_CP,	0xFFFFFFFF,	NULL,	0,	0},
	{QCH_CTRL_UID_CCORE_D_CP,	0xFFFFFFFF,	NULL,	0,	0},
	{QCH_CTRL_UID_CCORE_D_CP_PCLK,	0xFFFFFFFF,	NULL,	0,	0},
	{MIF_CLK_CTRL0,	0xFFFFFFFF,	NULL,	0,	0},
	{MIF_CLK_CTRL1,	0xFFFFFFFF,	NULL,	0,	0},
	{MIF_CLK_CTRL2,	0xFFFFFFFF,	NULL,	0,	0},
	{MIF_CLK_CTRL3,	0xFFFFFFFF,	NULL,	0,	0},
	{MIF_CLK_CTRL4,	0xFFFFFFFF,	NULL,	0,	0},

	{G3D_PLL_LOCK,	0xFFFFFFFF,	PMU_G3D_STATUS,	0,	0},
	{G3D_PLL_CON0,	0xFFFFFFFF,	PMU_G3D_STATUS,	0,	0},
	{G3D_PLL_CON1,	0xFFFFFFFF,	PMU_G3D_STATUS,	0,	0},
	{CLK_CON_MUX_G3D_PLL,	0xFFFFFFFF,	PMU_G3D_STATUS,	0,	0},
	{CLK_CON_MUX_CLKCMU_G3D_SWITCH_USER,	0xFFFFFFFF,	PMU_G3D_STATUS,	0,	0},
	{CLK_CON_MUX_CLK_G3D,	0xFFFFFFFF,	PMU_G3D_STATUS,	0,	0},
	{CLK_CON_DIV_CLK_G3D_BUS,	0xFFFFFFFF,	PMU_G3D_STATUS,	0,	0},
	{CLK_CON_DIV_CLK_G3D_APB,	0xFFFFFFFF,	PMU_G3D_STATUS,	0,	0},
	{CLK_ENABLE_CLK_G3D_OSCCLK,	0xFFFFFFFF,	PMU_G3D_STATUS,	0,	0},
	{CLK_ENABLE_CLK_G3D_BUS,	0xFFFFFFFF,	PMU_G3D_STATUS,	0,	0},
	{CLK_ENABLE_CLK_G3D_APB,	0xFFFFFFFF,	PMU_G3D_STATUS,	0,	0},
	{CLK_ENABLE_CLK_G3D_BUS_SECURE_CFW_G3D,	0xFFFFFFFF,	PMU_G3D_STATUS,	0,	0},
	{CLK_ENABLE_CLK_G3D_APB_SECURE_CFW_G3D,	0xFFFFFFFF,	PMU_G3D_STATUS,	0,	0},
	{CLKOUT_CMU_G3D,	0xFFFFFFFF,	PMU_G3D_STATUS,	0,	0},

	{USB_PLL_LOCK,	0xFFFFFFFF,	NULL,	0,	0},
	{USB_PLL_CON0,	0xFFFFFFFF,	NULL,	0,	0},
	{USB_PLL_CON1,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_USB_PLL,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKPHY_FSYS_USB20DRD_PHYCLOCK_USER,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKPHY_FSYS_UFS_TX0_SYMBOL_USER,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_CLKPHY_FSYS_UFS_RX0_SYMBOL_USER,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_FSYS_OSCCLK,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_FSYS_BUS,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_FSYS_SECURE_RTIC,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_FSYS_SECURE_SSS,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_FSYS_SECURE_PDMA1,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_FSYS_MMC0,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_FSYS_MMC1,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_FSYS_MMC2,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_FSYS_UFSUNIPRO,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_FSYS_UFSUNIPRO_CFG,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_FSYS_USB20DRD_REFCLK,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKPHY_FSYS_USB20DRD_PHYCLOCK,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKPHY_FSYS_UFS_TX0_SYMBOL,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLKPHY_FSYS_UFS_RX0_SYMBOL,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_FSYS_BUS_SECURE_INTMEM,	0xFFFFFFFF,	NULL,	0,	0},
	{SECURE_ENABLE_BUSD0_FSYS,	0xFFFFFFFF,	NULL,	0,	0},
	{CLKOUT_CMU_FSYS,	0xFFFFFFFF,	NULL,	0,	0},

	{CLK_ENABLE_CLK_PERI_OSCCLK,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_PERI_OSCCLK_SECURE_CHIPID,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_PERI_BUS0,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_PERI_BUS1,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_PERI_BUS_SECURE_TZPC,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_PERI_BUS_SECURE_CHIPID,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_PERI_BUS_SECURE_OTP_CON_TOP,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_PERI_BUS_SECURE_RTC_ALIVE,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_PERI_BUS_SECURE_RTC_TOP,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_PERI_UART_BTWIFIFM,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_PERI_UART_DEBUG,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_PERI_UART_SENSOR,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_PERI_SPI_FRONTFROM,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_PERI_SPI_REARFROM,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_PERI_SPI_ESE,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_PERI_SPI_VOICEPROCESSOR,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_ENABLE_CLK_PERI_SPI_SENSORHUB,	0xFFFFFFFF,	NULL,	0,	0},
	{CLKOUT_CMU_PERI,	0xFFFFFFFF,	NULL,	0,	0},

	{MIF1_PLL_LOCK,	0xFFFFFFFF,	NULL,	0,	0},
	{MIF1_PLL_CON0,	0xFFFFFFFF,	NULL,	0,	0},
	{MIF1_PLL_CON1,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_MIF1_PLL,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_BUS_PLL_USER_MIF1,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_ACLK_MIF1_PLL,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_PCLK_MIF1,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_PCLK_MIF1,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_VAL_ACLK_MIF1,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_VAL_ACLK_MIF1_SECURE_DREX_TZ,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_VAL_PCLK_MIF1_SECURE_DREX_TZ,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_VAL_PCLK_MIF1,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_VAL_SCLK_RCLK_DREX_MIF1,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_VAL_DDRPHY_MIF1,	0xFFFFFFFF,	NULL,	0,	0},
	{CLKOUT_CMU_MIF1,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_MAN_ACLK_MIF1,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_MAN_ACLK_MIF1_SECURE_DREX_TZ,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_MAN_PCLK_MIF1_SECURE_DREX_TZ,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_MAN_PCLK_MIF1,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_MAN_SCLK_RCLK_DREX_MIF1,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_MAN_DDRPHY_MIF1,	0xFFFFFFFF,	NULL,	0,	0},
	{QCH_CTRL_LH_P_MIF1,	0xFFFFFFFF,	NULL,	0,	0},
	{QCH_CTRL_PMU_MIF1,	0xFFFFFFFF,	NULL,	0,	0},
	{QCH_CTRL_SYSREG_MIF1,	0xFFFFFFFF,	NULL,	0,	0},
	{QCH_CTRL_PPMU_DMC_CPU_MIF1,	0xFFFFFFFF,	NULL,	0,	0},
	{QCH_CTRL_LH_DMC_CPU_MIF1,	0xFFFFFFFF,	NULL,	0,	0},
	{QCH_CTRL_LH_DMC_BUSD_MIF1,	0xFFFFFFFF,	NULL,	0,	0},
	{QCH_CTRL_CMU_MIF1,	0xFFFFFFFF,	NULL,	0,	0},
	{PCH_CTRL_DREX_PCH_0_MIF1,	0xFFFFFFFF,	NULL,	0,	0},
	{PCH_CTRL_DREX_PCH_1_MIF1,	0xFFFFFFFF,	NULL,	0,	0},
	{QSTATE_CTRL_DREX_RCLK_MIF1,	0xFFFFFFFF,	NULL,	0,	0},

	{MIF0_PLL_LOCK,	0xFFFFFFFF,	NULL,	0,	0},
	{MIF0_PLL_CON0,	0xFFFFFFFF,	NULL,	0,	0},
	{MIF0_PLL_CON1,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_MIF0_PLL,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_BUS_PLL_USER_MIF0,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_ACLK_MIF0_PLL,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_MUX_PCLK_MIF0,	0xFFFFFFFF,	NULL,	0,	0},
	{CLK_CON_DIV_PCLK_MIF0,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_VAL_ACLK_MIF0,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_VAL_ACLK_MIF0_SECURE_DREX_TZ,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_VAL_PCLK_MIF0_SECURE_DREX_TZ,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_VAL_PCLK_MIF0,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_VAL_SCLK_RCLK_DREX_MIF0,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_VAL_DDRPHY_MIF0,	0xFFFFFFFF,	NULL,	0,	0},
	{CLKOUT_CMU_MIF0,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_MAN_ACLK_MIF0,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_MAN_ACLK_MIF0_SECURE_DREX_TZ,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_MAN_PCLK_MIF0_SECURE_DREX_TZ,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_MAN_PCLK_MIF0,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_MAN_SCLK_RCLK_DREX_MIF0,	0xFFFFFFFF,	NULL,	0,	0},
	{CG_CTRL_MAN_DDRPHY_MIF0,	0xFFFFFFFF,	NULL,	0,	0},
	{QCH_CTRL_LH_P_MIF0,	0xFFFFFFFF,	NULL,	0,	0},
	{QCH_CTRL_PMU_MIF0,	0xFFFFFFFF,	NULL,	0,	0},
	{QCH_CTRL_SYSREG_MIF0,	0xFFFFFFFF,	NULL,	0,	0},
	{QCH_CTRL_PPMU_DMC_CPU_MIF0,	0xFFFFFFFF,	NULL,	0,	0},
	{QCH_CTRL_LH_DMC_CPU_MIF0,	0xFFFFFFFF,	NULL,	0,	0},
	{QCH_CTRL_LH_DMC_BUSD_MIF0,	0xFFFFFFFF,	NULL,	0,	0},
	{QCH_CTRL_CMU_MIF0,	0xFFFFFFFF,	NULL,	0,	0},
	{PCH_CTRL_DREX_PCH_0_MIF0,	0xFFFFFFFF,	NULL,	0,	0},
	{PCH_CTRL_DREX_PCH_1_MIF0,	0xFFFFFFFF,	NULL,	0,	0},
	{QSTATE_CTRL_DREX_RCLK_MIF0,	0xFFFFFFFF,	NULL,	0,	0},

	{CLK_CON_MUX_CLKCMU_MFCMSCL_MSCL_USER,	0xFFFFFFFF,	PMU_MFCMSCL_STATUS,	0,	0},
	{CLK_CON_MUX_CLKCMU_MFCMSCL_MFC_USER,	0xFFFFFFFF,	PMU_MFCMSCL_STATUS,	0,	0},
	{CLK_CON_DIV_CLK_MFCMSCL_APB,	0xFFFFFFFF,	PMU_MFCMSCL_STATUS,	0,	0},
	{CLK_ENABLE_CLK_MFCMSCL_OSCCLK,	0xFFFFFFFF,	PMU_MFCMSCL_STATUS,	0,	0},
	{CLK_ENABLE_CLK_MFCMSCL_MSCL,	0xFFFFFFFF,	PMU_MFCMSCL_STATUS,	0,	0},
	{CLK_ENABLE_CLK_MFCMSCL_MFC,	0xFFFFFFFF,	PMU_MFCMSCL_STATUS,	0,	0},
	{CLK_ENABLE_CLK_MFCMSCL_APB,	0xFFFFFFFF,	PMU_MFCMSCL_STATUS,	0,	0},
	{CLK_ENABLE_CLK_MFCMSCL_SECURE_CFW,	0xFFFFFFFF,	PMU_MFCMSCL_STATUS,	0,	0},
	{CLKOUT_CMU_MFCMSCL,	0xFFFFFFFF,	PMU_MFCMSCL_STATUS,	0,	0},

	{DISP_PLL_LOCK,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{AUD_PLL_LOCK,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{DISP_PLL_CON0,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{DISP_PLL_CON1,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{AUD_PLL_CON0,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{AUD_PLL_CON1,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{AUD_PLL_CON2,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_CON_MUX_DISP_PLL,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_CON_MUX_AUD_PLL,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_CON_MUX_CLKCMU_DISPAUD_BUS_USER,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_CON_MUX_CLKCMU_DISPAUD_DECON_INT_VCLK_USER,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_CON_MUX_CLKCMU_DISPAUD_DECON_INT_ECLK_USER,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_CON_MUX_CLK_DISPAUD_DECON_INT_VCLK,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_CON_MUX_CLK_DISPAUD_DECON_INT_ECLK,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_CON_MUX_CLKPHY_DISPAUD_MIPIPHY_TXBYTECLKHS_0_USER,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_CON_MUX_CLKPHY_DISPAUD_MIPIPHY_RXCLKESC0_0_USER,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_CON_MUX_CLKPHY_DISPAUD_MIPIPHY_TXBYTECLKHS_1_USER,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_CON_MUX_CLKPHY_DISPAUD_MIPIPHY_RXCLKESC0_1_USER,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_CON_MUX_CLK_DISPAUD_MI2S,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_CON_DIV_CLK_DISPAUD_APB,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_CON_DIV_CLK_DISPAUD_DECON_INT_VCLK,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_CON_DIV_CLK_DISPAUD_DECON_INT_ECLK,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_CON_DIV_CLK_DISPAUD_MI2S,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_CON_DIV_CLK_DISPAUD_MIXER,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_ENABLE_CLK_DISPAUD_OSCCLK,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_ENABLE_CLK_DISPAUD_BUS,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_ENABLE_CLK_DISPAUD_APB,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_ENABLE_CLK_DISPAUD_SECURE_CFW_DISP,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_ENABLE_CLK_DISPAUD_DECON_INT_VCLK,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_ENABLE_CLK_DISPAUD_DECON_INT_ECLK,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_ENABLE_CLKPHY_DISPAUD_MIPIPHY_TXBYTECLKHS,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_ENABLE_CLKPHY_DISPAUD_MIPIPHY_RXCLKESC0,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_ENABLE_CLK_DISPAUD_MI2S,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_ENABLE_CLK_DISPAUD_MIXER,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_ENABLE_CLKIO_DISPAUD_MIXER_SCLK_AP,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_ENABLE_CLKIO_DISPAUD_MIXER_BCLK_BT,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_ENABLE_CLKIO_DISPAUD_MIXER_BCLK_CP,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLK_ENABLE_CLKIO_DISPAUD_MIXER_BCLK_FM,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},
	{CLKOUT_CMU_DISPAUD,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0},

	{ISP_PLL_LOCK,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{ISP_PLL_CON0,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{ISP_PLL_CON1,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_CON_MUX_ISP_PLL,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_CON_MUX_CLKCMU_ISP_VRA_USER,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_CON_MUX_CLKCMU_ISP_CAM_USER,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_CON_MUX_CLKCMU_ISP_ISP_USER,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_CON_MUX_CLK_ISP_VRA,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_CON_MUX_CLK_ISP_CAM,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_CON_MUX_CLK_ISP_ISP,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_CON_MUX_CLK_ISP_ISPD,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_CON_MUX_CLKPHY_ISP_S_RXBYTECLKHS0_S4_USER,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_CON_MUX_CLKPHY_ISP_S_RXBYTECLKHS1_S4_USER,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_CON_MUX_CLKPHY_ISP_S_RXBYTECLKHS2_S4_USER,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_CON_MUX_CLKPHY_ISP_S_RXBYTECLKHS3_S4_USER,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_CON_MUX_CLKPHY_ISP_S_RXBYTECLKHS0_S4S_USER,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_CON_MUX_CLKPHY_ISP_S_RXBYTECLKHS1_S4S_USER,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_CON_MUX_CLKPHY_ISP_S_RXBYTECLKHS2_S4S_USER,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_CON_MUX_CLKPHY_ISP_S_RXBYTECLKHS3_S4S_USER,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_CON_DIV_CLK_ISP_APB,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_CON_DIV_CLK_ISP_CAM_HALF,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_ENABLE_CLK_ISP_OSCCLK,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_ENABLE_CLK_ISP_VRA,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_ENABLE_CLK_ISP_APB,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_ENABLE_CLK_ISP_ISPD,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_ENABLE_CLK_ISP_CAM,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_ENABLE_CLK_ISP_CAM_HALF,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_ENABLE_CLK_ISP_ISP,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_ENABLE_CLKPHY_ISP_S_RXBYTECLKHS0_S4,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_ENABLE_CLKPHY_ISP_S_RXBYTECLKHS1_S4,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_ENABLE_CLKPHY_ISP_S_RXBYTECLKHS2_S4,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_ENABLE_CLKPHY_ISP_S_RXBYTECLKHS3_S4,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_ENABLE_CLKPHY_ISP_S_RXBYTECLKHS0_S4S,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_ENABLE_CLKPHY_ISP_S_RXBYTECLKHS1_S4S,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_ENABLE_CLKPHY_ISP_S_RXBYTECLKHS2_S4S,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLK_ENABLE_CLKPHY_ISP_S_RXBYTECLKHS3_S4S,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
	{CLKOUT_CMU_ISP,	0xFFFFFFFF,	PMU_ISP_STATUS,	0,	0},
};

static struct cmu_backup cmu_backup_topmux_list[] = {
	{CLK_CON_MUX_CLKCMU_ISP_VRA,	0x00200000,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_ISP_CAM,	0x00200000,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_ISP_ISP,	0x00200000,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_DISPAUD_BUS,	0x00200000,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_DISPAUD_DECON_INT_VCLK,	0x00200000,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_DISPAUD_DECON_INT_ECLK,	0x00200000,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_MFCMSCL_MSCL,	0x00200000,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_MFCMSCL_MFC,	0x00200000,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_FSYS_BUS,	0x00200000,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_FSYS_MMC0,	0x00200000,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_FSYS_MMC1,	0x00200000,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_FSYS_MMC2,	0x00200000,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_FSYS_UFSUNIPRO,	0x00200000,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_FSYS_UFSUNIPRO_CFG,	0x00200000,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_FSYS_USB20DRD_REFCLK,	0x00200000,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_PERI_BUS,	0x00200000,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_PERI_UART_BTWIFIFM,	0x00200000,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_PERI_UART_DEBUG,	0x00200000,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_PERI_UART_SENSOR,	0x00200000,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_PERI_SPI_FRONTFROM,	0x00200000,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_PERI_SPI_REARFROM,	0x00200000,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_PERI_SPI_ESE,	0x00200000,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_PERI_SPI_VOICEPROCESSOR,	0x00200000,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_PERI_SPI_SENSORHUB,	0x00200000,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_ISP_SENSOR0,	0x00200000,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_ISP_SENSOR1,	0x00200000,	NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_ISP_SENSOR2,	0x00200000,	NULL,	0,	0},
};

static struct cmu_backup cmu_backup_sicd_list[] = {
	{CLK_CON_DIV_CLK_DISPAUD_APB,	0xFFFFFFFF, PMU_DISPAUD_STATUS, 0,	0},
	{CLK_CON_MUX_CLKCMU_DISPAUD_BUS_USER,	0xFFFFFFFF,	PMU_DISPAUD_STATUS,	0,	0}, /* ADMA as OSC at SICD */

	{QCH_CTRL_LH_P_MIF0,	0x00000001,	NULL,	0,	0},
	{QCH_CTRL_PMU_MIF0,	0x00000001, NULL,	0,	0},
	{QCH_CTRL_SYSREG_MIF0,	0x00000001, NULL,	0,	0},
	{QCH_CTRL_PPMU_DMC_CPU_MIF0,	0x00000001, NULL,	0,	0},
	{QCH_CTRL_LH_DMC_CPU_MIF0,	0x00000001, NULL,	0,	0},
	{QCH_CTRL_LH_DMC_BUSD_MIF0,	0x00000001, NULL,	0,	0},
	{QCH_CTRL_CMU_MIF0,	0x00000001, NULL,	0,	0},
	{PCH_CTRL_DREX_PCH_0_MIF0,	0x00000001, NULL,	0,	0},
	{QSTATE_CTRL_DREX_RCLK_MIF0,	0x00000001, NULL,	0,	0},

	{QCH_CTRL_LH_P_MIF1,	0x00000001, NULL,	0,	0},
	{QCH_CTRL_PMU_MIF1,	0x00000001, NULL,	0,	0},
	{QCH_CTRL_SYSREG_MIF1,	0x00000001, NULL,	0,	0},
	{QCH_CTRL_PPMU_DMC_CPU_MIF1,	0x00000001, NULL,	0,	0},
	{QCH_CTRL_LH_DMC_CPU_MIF1,	0x00000001, NULL,	0,	0},
	{QCH_CTRL_LH_DMC_BUSD_MIF1,	0x00000001, NULL,	0,	0},
	{QCH_CTRL_CMU_MIF1,	0x00000001, NULL,	0,	0},
	{PCH_CTRL_DREX_PCH_0_MIF1,	0x00000001, NULL,	0,	0},
	{QSTATE_CTRL_DREX_RCLK_MIF1,	0x00000001, NULL,	0,	0},
};

static struct cmu_backup cmu_backup_dstop0_list[] = {
	{CPUCL0_PLL_LOCK,	0xFFFFFFFF, NULL,	0,	0},
	{CPUCL0_PLL_CON0,	0xFFFFFFFF, NULL,	0,	0},
	{CPUCL0_PLL_CON1,	0xFFFFFFFF, NULL,	0,	0},
	{CLK_CON_MUX_CPUCL0_PLL,	0xFFFFFFFF, NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_CPUCL0_SWITCH_USER, 0xFFFFFFFF, NULL,	0,	0},
	{CLK_CON_MUX_CLK_CPUCL0,	0xFFFFFFFF, NULL,	0,	0},
	{CLK_CON_DIV_CLK_CPUCL0_1,	0xFFFFFFFF, NULL,	0,	0},
	{CLK_CON_DIV_CLK_CPUCL0_2,	0xFFFFFFFF, NULL,	0,	0},
	{CLK_CON_DIV_CLK_CPUCL0_ACLK,	0xFFFFFFFF, NULL,	0,	0},
	{CLK_CON_DIV_CLK_CPUCL0_PCLK,	0xFFFFFFFF, NULL,	0,	0},
	{CLK_CON_DIV_CLK_CPUCL0_ATCLK,	0xFFFFFFFF, NULL,	0,	0},
	{CLK_CON_DIV_CLK_CPUCL0_PCLKDBG,	0xFFFFFFFF, NULL,	0,	0},
	{CLK_CON_DIV_CLK_CPUCL0_CNTCLK, 0xFFFFFFFF, NULL,	0,	0},
	{CLK_CON_DIV_CLK_CPUCL0_RUN_MONITOR,	0xFFFFFFFF, NULL,	0,	0},
	{CLK_CON_DIV_CLK_CPUCL0_HPM,	0xFFFFFFFF, NULL,	0,	0},
	{CLK_CON_DIV_CLK_CPUCL0_PLL,	0xFFFFFFFF, NULL,	0,	0},
};

static struct cmu_backup cmu_backup_dstop1_list[] = {
	{CPUCL1_PLL_LOCK,	0xFFFFFFFF, NULL,	0,	0},
	{CPUCL1_PLL_CON0,	0xFFFFFFFF, NULL,	0,	0},
	{CPUCL1_PLL_CON1,	0xFFFFFFFF, NULL,	0,	0},
	{CLK_CON_MUX_CPUCL1_PLL,	0xFFFFFFFF, NULL,	0,	0},
	{CLK_CON_MUX_CLKCMU_CPUCL1_SWITCH_USER, 0xFFFFFFFF, NULL,	0,	0},
	{CLK_CON_MUX_CLK_CPUCL1,	0xFFFFFFFF, NULL,	0,	0},
	{CLK_CON_DIV_CLK_CPUCL1_1,	0xFFFFFFFF, NULL,	0,	0},
	{CLK_CON_DIV_CLK_CPUCL1_2,	0xFFFFFFFF, NULL,	0,	0},
	{CLK_CON_DIV_CLK_CPUCL1_ACLK,	0xFFFFFFFF, NULL,	0,	0},
	{CLK_CON_DIV_CLK_CPUCL1_PCLK,	0xFFFFFFFF, NULL,	0,	0},
	{CLK_CON_DIV_CLK_CPUCL1_ATCLK,	0xFFFFFFFF, NULL,	0,	0},
	{CLK_CON_DIV_CLK_CPUCL1_PCLKDBG,	0xFFFFFFFF, NULL,	0,	0},
	{CLK_CON_DIV_CLK_CPUCL1_CNTCLK, 0xFFFFFFFF, NULL,	0,	0},
	{CLK_CON_DIV_CLK_CPUCL1_RUN_MONITOR,	0xFFFFFFFF, NULL,	0,	0},
	{CLK_CON_DIV_CLK_CPUCL1_HPM,	0xFFFFFFFF, NULL,	0,	0},
	{CLK_CON_DIV_CLK_CPUCL1_PLL,	0xFFFFFFFF, NULL,	0,	0},
};


static int syspwr_hwacg_control(int mode)
{
	if (mode == SYS_LPD) {
		return 0;
	} else {
	/* QCH_CTRL in MIF0 / 1 */
	pwrcal_setbit(QCH_CTRL_LH_P_MIF0, 0, 1);
	pwrcal_setbit(QCH_CTRL_PMU_MIF0, 0, 1);
	pwrcal_setbit(QCH_CTRL_SYSREG_MIF0, 0, 1);
	pwrcal_setbit(QCH_CTRL_PPMU_DMC_CPU_MIF0, 0, 1);
	pwrcal_setbit(QCH_CTRL_LH_DMC_CPU_MIF0, 0, 1);
	pwrcal_setbit(QCH_CTRL_LH_DMC_BUSD_MIF0, 0, 1);
	pwrcal_setbit(QCH_CTRL_CMU_MIF0, 0, 1);
	pwrcal_setbit(QSTATE_CTRL_DREX_RCLK_MIF0, 0, 1);
	pwrcal_setbit(PCH_CTRL_DREX_PCH_0_MIF0, 0, 1);

	pwrcal_setbit(QCH_CTRL_LH_P_MIF1, 0, 1);
	pwrcal_setbit(QCH_CTRL_PMU_MIF1, 0, 1);
	pwrcal_setbit(QCH_CTRL_SYSREG_MIF1, 0, 1);
	pwrcal_setbit(QCH_CTRL_PPMU_DMC_CPU_MIF1, 0, 1);
	pwrcal_setbit(QCH_CTRL_LH_DMC_CPU_MIF1, 0, 1);
	pwrcal_setbit(QCH_CTRL_LH_DMC_BUSD_MIF1, 0, 1);
	pwrcal_setbit(QCH_CTRL_CMU_MIF1, 0, 1);
	pwrcal_setbit(QSTATE_CTRL_DREX_RCLK_MIF1, 0, 1);
	pwrcal_setbit(PCH_CTRL_DREX_PCH_0_MIF1, 0, 1);
	}

	if (mode == SYS_SICD) {
		return 0;
	} else {
	/* QCH_CTRL in CCORE */
	pwrcal_setbit(QCH_CTRL_UID_CCORE_D_CCI, 0, 1);
	pwrcal_setbit(QCH_CTRL_UID_CCORE_D_NRT, 0, 1);
	pwrcal_setbit(QCH_CTRL_UID_CCORE_D_RT, 0, 1);
	pwrcal_setbit(QCH_CTRL_UID_ASYNCM_LH_G3D0_CCORE_D_NRT, 0, 1);
	pwrcal_setbit(QCH_CTRL_UID_ASYNCM_LH_G3D1_CCORE_D_NRT, 0, 1);
	pwrcal_setbit(QCH_CTRL_UID_ASYNCM_LH_MFCMSCL_CCORE_D_NRT, 0, 1);
	pwrcal_setbit(QCH_CTRL_UID_ASYNCM_LH_FSYS_CCORE_D_NRT, 0, 1);
	pwrcal_setbit(QCH_CTRL_UID_ASYNCM_LH_ISP_CCORE_D_NRT, 0, 1);
	pwrcal_setbit(QCH_CTRL_UID_ASYNCM_LH_ISP_CCORE_D_RT, 0, 1);
	pwrcal_setbit(QCH_CTRL_UID_ASYNCM_LH_DISPAUD_CCORE_D_RT, 0, 1);

	/* W/A for DSTOP, when CP, GNSS are in reset */
	/* only for W/A, remove when CP, GNSS are up */
	if (mode == SYS_DSTOP) {
		pwrcal_setbit(QCH_CTRL_UID_ASYNCM_LH_CP_CCORE_D_CP, 0, 0);
		pwrcal_setbit(QCH_CTRL_UID_ASYNCM_LH_GNSS_CCORE_D_CP, 0, 0);
	}

	pwrcal_setbit(QCH_CTRL_UID_CCORE_D_CP, 0, 1);
	pwrcal_setbit(QCH_CTRL_UID_CCORE_D_CP_PCLK, 0, 1);

	}

	return 0;
}
static int syspwr_hwacg_control_post(int mode)
{
	return 0;
}


static void set_pmu_sys_pwr_reg(enum sys_powerdown mode)
{
	int i;

	for (i = 0; exynos_syspwr_pmu_config[i].reg != 0; i++)
		pwrcal_writel(exynos_syspwr_pmu_config[i].reg, exynos_syspwr_pmu_config[i].val[mode]);

	for (i = 0; exynos_syspwr_pmu_option[i].reg != 0; i++)
		pwrcal_writel(exynos_syspwr_pmu_option[i].reg, exynos_syspwr_pmu_option[i].val[mode]);
}
static void set_pmu_central_seq(int mode, bool enable)
{
	unsigned int tmp;

	/* central sequencer */
	tmp = pwrcal_readl(PMU_CENTRAL_SEQ_CONFIGURATION);
	if (enable)
		tmp &= ~PWRCAL_CENTRALSEQ_PWR_CFG;
	else
		tmp |= PWRCAL_CENTRALSEQ_PWR_CFG;
	pwrcal_writel(PMU_CENTRAL_SEQ_CONFIGURATION, tmp);

	/* central sequencer MIF */
	if (mode == SYS_LPD)
		enable = false;
	tmp = pwrcal_readl(PMU_CENTRAL_SEQ_MIF_CONFIGURATION);
	if (enable)
		tmp &= ~PWRCAL_CENTRALSEQ_PWR_CFG;
	else
		tmp |= PWRCAL_CENTRALSEQ_PWR_CFG;
	pwrcal_writel(PMU_CENTRAL_SEQ_MIF_CONFIGURATION, tmp);
}

static void syspwr_clock_config(int mode)
{
	pwrcal_setbit(CLK_CON_MUX_CLKPHY_FSYS_USB20DRD_PHYCLOCK_USER,	12,	0);
	pwrcal_setbit(CLK_CON_MUX_CLKPHY_FSYS_USB20DRD_PHYCLOCK_USER,	27,	1);
	if ((pwrcal_getf(PMU_DISPAUD_STATUS, 0, 0xf) == 0xf)) {
		if (mode != SYS_LPD) {
			pwrcal_setbit(CLK_CON_MUX_CLKPHY_DISPAUD_MIPIPHY_TXBYTECLKHS_0_USER,	12,	0x0);
			pwrcal_setbit(CLK_CON_MUX_CLKPHY_DISPAUD_MIPIPHY_RXCLKESC0_0_USER,	12,	0x0);
			pwrcal_setbit(CLK_CON_MUX_CLKPHY_DISPAUD_MIPIPHY_TXBYTECLKHS_1_USER,	12,	0x0);
			pwrcal_setbit(CLK_CON_MUX_CLKPHY_DISPAUD_MIPIPHY_RXCLKESC0_1_USER,	12,	0x0);
			pwrcal_setbit(CLK_CON_MUX_CLKPHY_DISPAUD_MIPIPHY_TXBYTECLKHS_0_USER,	27,	0x1);
			pwrcal_setbit(CLK_CON_MUX_CLKPHY_DISPAUD_MIPIPHY_RXCLKESC0_0_USER,	27,	0x1);
			pwrcal_setbit(CLK_CON_MUX_CLKPHY_DISPAUD_MIPIPHY_TXBYTECLKHS_1_USER,	27,	0x1);
			pwrcal_setbit(CLK_CON_MUX_CLKPHY_DISPAUD_MIPIPHY_RXCLKESC0_1_USER,	27,	0x1);
		}
		if (mode == SYS_SICD) {
			pwrcal_setbit(CLK_CON_MUX_CLKCMU_DISPAUD_BUS_USER, 12, 0x0);
			pwrcal_setf(CLK_CON_DIV_CLK_DISPAUD_APB, 0, 0x3, 0x0);
		}
	}
	if (pwrcal_getf(PMU_ISP_STATUS, 0, 0xf) == 0xf) {
		pwrcal_setbit(CLK_CON_MUX_CLKPHY_ISP_S_RXBYTECLKHS0_S4_USER,	12,	0x0);
		pwrcal_setbit(CLK_CON_MUX_CLKPHY_ISP_S_RXBYTECLKHS1_S4_USER,	12,	0x0);
		pwrcal_setbit(CLK_CON_MUX_CLKPHY_ISP_S_RXBYTECLKHS2_S4_USER,	12,	0x0);
		pwrcal_setbit(CLK_CON_MUX_CLKPHY_ISP_S_RXBYTECLKHS3_S4_USER,	12,	0x0);
		pwrcal_setbit(CLK_CON_MUX_CLKPHY_ISP_S_RXBYTECLKHS0_S4S_USER,	12,	0x0);
		pwrcal_setbit(CLK_CON_MUX_CLKPHY_ISP_S_RXBYTECLKHS1_S4S_USER,	12,	0x0);
		pwrcal_setbit(CLK_CON_MUX_CLKPHY_ISP_S_RXBYTECLKHS2_S4S_USER,	12,	0x0);
		pwrcal_setbit(CLK_CON_MUX_CLKPHY_ISP_S_RXBYTECLKHS3_S4S_USER,	12,	0x0);
		pwrcal_setbit(CLK_CON_MUX_CLKPHY_ISP_S_RXBYTECLKHS0_S4_USER,	27,	0x1);
		pwrcal_setbit(CLK_CON_MUX_CLKPHY_ISP_S_RXBYTECLKHS1_S4_USER,	27,	0x1);
		pwrcal_setbit(CLK_CON_MUX_CLKPHY_ISP_S_RXBYTECLKHS2_S4_USER,	27,	0x1);
		pwrcal_setbit(CLK_CON_MUX_CLKPHY_ISP_S_RXBYTECLKHS3_S4_USER,	27,	0x1);
		pwrcal_setbit(CLK_CON_MUX_CLKPHY_ISP_S_RXBYTECLKHS0_S4S_USER,	27,	0x1);
		pwrcal_setbit(CLK_CON_MUX_CLKPHY_ISP_S_RXBYTECLKHS1_S4S_USER,	27,	0x1);
		pwrcal_setbit(CLK_CON_MUX_CLKPHY_ISP_S_RXBYTECLKHS2_S4S_USER,	27,	0x1);
		pwrcal_setbit(CLK_CON_MUX_CLKPHY_ISP_S_RXBYTECLKHS3_S4S_USER,	27,	0x1);
	}
	if (mode == SYS_LPD) {
		/* in LPD mode, do not use PLL sharing, has no advantage on power reduction. */
		pwrcal_setbit(CCORE_ROOTCLKEN,	0,	1);
		pwrcal_setbit(CLK_ENABLE_CLKCMU_PERI_SPI_FRONTFROM,	0,	0);
		pwrcal_setbit(CLK_ENABLE_CLKCMU_PERI_SPI_REARFROM,	0,	0);
		pwrcal_setbit(CLK_ENABLE_CLKCMU_PERI_SPI_ESE,	0,	0);
		pwrcal_setbit(CLK_ENABLE_CLKCMU_PERI_SPI_VOICEPROCESSOR,	0,	0);
		pwrcal_setbit(CLK_ENABLE_CLKCMU_PERI_SPI_SENSORHUB,	0,	0);
	}
}

static int syspwr_clkpwr_optimize(unsigned int power_mode)
{
	disable_armidleclockdown();
	// MUXGATE of FSYS and ISP should be enabled clock.
	pwrcal_setbit(CLK_ENABLE_CLKCMU_FSYS_BUS, 0, 1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_FSYS_MMC0, 0, 1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_FSYS_MMC1, 0, 1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_FSYS_MMC2, 0, 1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_FSYS_UFSUNIPRO, 0, 1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_FSYS_UFSUNIPRO_CFG, 0, 1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_FSYS_USB20DRD_REFCLK, 0, 1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_ISP_SENSOR0, 0, 1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_ISP_SENSOR1, 0, 1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_ISP_SENSOR2, 0, 1);

	/* when MIF power gated  */
	if (power_mode == SYS_SICD || power_mode == SYS_DSTOP || power_mode == SYS_STOP) {
		pwrcal_setbit(PCH_CTRL_DREX_PCH_0_MIF0, 3, 1);
		pwrcal_setbit(PCH_CTRL_DREX_PCH_0_MIF1, 3, 1);
	}
	return 0;
}

static void save_sicd(void)
{
	unsigned long long i;

	for (i = 0; i < ARRAY_SIZE(cmu_backup_sicd_list); i++) {
		if (cmu_backup_sicd_list[i].power) {
					if (pwrcal_getf(cmu_backup_sicd_list[i].power, 0, 0xF) != 0xF)
						continue;
		}

		cmu_backup_sicd_list[i].backup = pwrcal_readl(cmu_backup_sicd_list[i].sfr);
		cmu_backup_sicd_list[i].backup_valid = 1;
	}
}

static void restore_sicd(void)
{
	unsigned long long i;

	for (i = 0; i < ARRAY_SIZE(cmu_backup_sicd_list); i++) {
		if (cmu_backup_sicd_list[i].backup_valid == 0)
			continue;

		if (cmu_backup_sicd_list[i].power)
			if (pwrcal_getf(cmu_backup_sicd_list[i].power, 0, 0xF) != 0xF)
				continue;

		pwrcal_setf(cmu_backup_sicd_list[i].sfr, 0, cmu_backup_sicd_list[i].mask, cmu_backup_sicd_list[i].backup);
	}
}

static void save_dstop(void)
{
	unsigned long long i;

	for (i = 0; i < ARRAY_SIZE(cmu_backup_dstop0_list); i++) {
		cmu_backup_dstop0_list[i].backup = pwrcal_readl(cmu_backup_dstop0_list[i].sfr);
		cmu_backup_dstop0_list[i].backup_valid = 1;
	}

	for (i = 0; i < ARRAY_SIZE(cmu_backup_dstop1_list); i++) {
		cmu_backup_dstop1_list[i].backup = pwrcal_readl(cmu_backup_dstop1_list[i].sfr);
		cmu_backup_dstop1_list[i].backup_valid = 1;
	}
}

static void restore_dstop(void)
{
	unsigned long long i;

	for (i = 0; i < ARRAY_SIZE(cmu_backup_dstop0_list); i++) {
		if (i == 3 || i == 5)
			continue;
		if (cmu_backup_dstop0_list[i].backup_valid == 0)
			continue;

		pwrcal_setf(cmu_backup_dstop0_list[i].sfr, 0, cmu_backup_dstop0_list[i].mask, cmu_backup_dstop0_list[i].backup);
	}

	for (i = 0; i < ARRAY_SIZE(cmu_backup_dstop1_list); i++) {
		if (i == 3 || i == 5)
			continue;
		if (cmu_backup_dstop1_list[i].backup_valid == 0)
			continue;

		pwrcal_setf(cmu_backup_dstop1_list[i].sfr, 0, cmu_backup_dstop1_list[i].mask, cmu_backup_dstop1_list[i].backup);
	}

	while (!(pwrcal_readl(cmu_backup_dstop0_list[1].sfr) & (1 << 29)));
	while (!(pwrcal_readl(cmu_backup_dstop1_list[1].sfr) & (1 << 29)));
	pwrcal_setf(cmu_backup_dstop0_list[3].sfr, 0, cmu_backup_dstop0_list[3].mask, cmu_backup_dstop0_list[3].backup);
	pwrcal_setf(cmu_backup_dstop0_list[5].sfr, 0, cmu_backup_dstop0_list[5].mask, cmu_backup_dstop0_list[5].backup);
	pwrcal_setf(cmu_backup_dstop1_list[3].sfr, 0, cmu_backup_dstop1_list[3].mask, cmu_backup_dstop1_list[3].backup);
	pwrcal_setf(cmu_backup_dstop1_list[5].sfr, 0, cmu_backup_dstop1_list[5].mask, cmu_backup_dstop1_list[5].backup);
}

static void save_cmusfr(int mode)
{
	unsigned long long i;

	if (mode == SYS_SICD) {
		save_sicd();
		return;
	}

	for (i = 0; i < ARRAY_SIZE(cmu_backup_list); i++) {
		cmu_backup_list[i].backup_valid = 0;
		if (cmu_backup_list[i].power) {
			if (pwrcal_getf(cmu_backup_list[i].power, 0, 0xF) != 0xF)
				continue;
		} else {
			continue; // != sleep, other mode do retention
		}

		cmu_backup_list[i].backup = pwrcal_readl(cmu_backup_list[i].sfr);
		cmu_backup_list[i].backup_valid = 1;
	}

	if (mode == SYS_DSTOP)
		save_dstop();
}

static void restore_cmusfr(int mode)
{
	unsigned long long i;

	if (mode == SYS_SICD) {
		restore_sicd();
		return;
	}

	for (i = 0; i < ARRAY_SIZE(cmu_backup_list); i++) {
		if (cmu_backup_list[i].backup_valid == 0)
			continue;

		if (cmu_backup_list[i].power)
			if (pwrcal_getf(cmu_backup_list[i].power, 0, 0xF) != 0xF)
				continue;

		pwrcal_setf(cmu_backup_list[i].sfr, 0, cmu_backup_list[i].mask, cmu_backup_list[i].backup);
	}

	if (mode == SYS_DSTOP)
		restore_dstop();
}

static void save_topmuxgate(void)
{
	unsigned long long i;

	for (i = 0; i < ARRAY_SIZE(cmu_backup_topmux_list); i++) {
		cmu_backup_topmux_list[i].backup_valid = 0;
		if (cmu_backup_topmux_list[i].power)
			if (pwrcal_getf(cmu_backup_topmux_list[i].power, 0, 0xF) != 0xF)
				continue;

		cmu_backup_topmux_list[i].backup = pwrcal_readl(cmu_backup_topmux_list[i].sfr);
		cmu_backup_topmux_list[i].backup_valid = 1;
	}
}

static void restore_topmuxgate(void)
{
	unsigned long long i;

	for (i = 0; i < ARRAY_SIZE(cmu_backup_topmux_list); i++) {
		if (cmu_backup_topmux_list[i].backup_valid == 0)
			continue;

		if (cmu_backup_topmux_list[i].power)
			if (pwrcal_getf(cmu_backup_topmux_list[i].power, 0, 0xF) != 0xF)
				continue;

		pwrcal_setf(cmu_backup_topmux_list[i].sfr, 0, cmu_backup_topmux_list[i].mask, cmu_backup_topmux_list[i].backup);
	}
}

static void topmux_enable(void)
{
	pwrcal_setbit(CLK_CON_MUX_CLKCMU_ISP_VRA,	21,	1);
	pwrcal_setbit(CLK_CON_MUX_CLKCMU_ISP_CAM,	21,	1);
	pwrcal_setbit(CLK_CON_MUX_CLKCMU_ISP_ISP,	21,	1);
	pwrcal_setbit(CLK_CON_MUX_CLKCMU_DISPAUD_BUS,	21,	1);
	pwrcal_setbit(CLK_CON_MUX_CLKCMU_DISPAUD_DECON_INT_VCLK,	21,	1);
	pwrcal_setbit(CLK_CON_MUX_CLKCMU_DISPAUD_DECON_INT_ECLK,	21,	1);
	pwrcal_setbit(CLK_CON_MUX_CLKCMU_MFCMSCL_MSCL,	21,	1);
	pwrcal_setbit(CLK_CON_MUX_CLKCMU_MFCMSCL_MFC,	21,	1);
	pwrcal_setbit(CLK_CON_MUX_CLKCMU_FSYS_BUS,	21,	1);
	pwrcal_setbit(CLK_CON_MUX_CLKCMU_FSYS_MMC0,	21,	1);
	pwrcal_setbit(CLK_CON_MUX_CLKCMU_FSYS_MMC1,	21,	1);
	pwrcal_setbit(CLK_CON_MUX_CLKCMU_FSYS_MMC2,	21,	1);
	pwrcal_setbit(CLK_CON_MUX_CLKCMU_FSYS_UFSUNIPRO,	21,	1);
	pwrcal_setbit(CLK_CON_MUX_CLKCMU_FSYS_UFSUNIPRO_CFG,	21,	1);
	pwrcal_setbit(CLK_CON_MUX_CLKCMU_FSYS_USB20DRD_REFCLK,	21,	1);
	pwrcal_setbit(CLK_CON_MUX_CLKCMU_PERI_BUS,	21,	1);
	pwrcal_setbit(CLK_CON_MUX_CLKCMU_PERI_UART_BTWIFIFM,	21,	1);
	pwrcal_setbit(CLK_CON_MUX_CLKCMU_PERI_UART_DEBUG,	21,	1);
	pwrcal_setbit(CLK_CON_MUX_CLKCMU_PERI_UART_SENSOR,	21,	1);
	pwrcal_setbit(CLK_CON_MUX_CLKCMU_PERI_SPI_FRONTFROM,	21,	1);
	pwrcal_setbit(CLK_CON_MUX_CLKCMU_PERI_SPI_REARFROM,	21,	1);
	pwrcal_setbit(CLK_CON_MUX_CLKCMU_PERI_SPI_ESE,	21,	1);
	pwrcal_setbit(CLK_CON_MUX_CLKCMU_PERI_SPI_VOICEPROCESSOR,	21,	1);
	pwrcal_setbit(CLK_CON_MUX_CLKCMU_PERI_SPI_SENSORHUB,	21,	1);
	pwrcal_setbit(CLK_CON_MUX_CLKCMU_ISP_SENSOR0,	21,	1);
	pwrcal_setbit(CLK_CON_MUX_CLKCMU_ISP_SENSOR1,	21,	1);
	pwrcal_setbit(CLK_CON_MUX_CLKCMU_ISP_SENSOR2,	21,	1);

	pwrcal_setbit(CLK_ENABLE_CLKCMU_ISP_VRA,	0,	1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_ISP_CAM,	0,	1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_ISP_ISP,	0,	1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_DISPAUD_BUS,	0,	1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_DISPAUD_DECON_INT_VCLK,	0,	1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_DISPAUD_DECON_INT_ECLK,	0,	1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_MFCMSCL_MSCL,	0,	1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_MFCMSCL_MFC,	0,	1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_FSYS_BUS,	0,	1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_FSYS_MMC0,	0,	1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_FSYS_MMC1,	0,	1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_FSYS_MMC2,	0,	1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_FSYS_UFSUNIPRO,	0,	1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_FSYS_UFSUNIPRO_CFG,	0,	1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_FSYS_USB20DRD_REFCLK,	0,	1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_PERI_BUS,	0,	1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_PERI_UART_BTWIFIFM,	0,	1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_PERI_UART_DEBUG,	0,	1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_PERI_UART_SENSOR,	0,	1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_PERI_SPI_FRONTFROM,	0,	1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_PERI_SPI_REARFROM,	0,	1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_PERI_SPI_ESE,	0,	1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_PERI_SPI_VOICEPROCESSOR,	0,	1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_PERI_SPI_SENSORHUB,	0,	1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_ISP_SENSOR0,	0,	1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_ISP_SENSOR1,	0,	1);
	pwrcal_setbit(CLK_ENABLE_CLKCMU_ISP_SENSOR2,	0,	1);
}

static void syspwr_set_additional_config(const enum sys_powerdown eMode)
{
	if (eMode == SYS_STOP) {

		pwrcal_setf(PMU_TOP_BUS_MIF_OPTION, 2, 0x1, 0x0);
		pwrcal_setf(PMU_TOP_BUS_MIF_OPTION, 1, 0x1, 0x0);
		pwrcal_setf(PMU_TOP_BUS_MIF_OPTION, 0, 0x1, 0x0);
		pwrcal_setf(PMU_WAKEUP_MASK, 30, 0x1, 0x1);
		pwrcal_setf(PMU_WAKEUP_MASK_MIF, 30, 0x1, 0x1);
		pwrcal_setf(PMU_G3D_OPTION, 31, 0x1, 0x1);
		pwrcal_setf(PMU_G3D_OPTION, 30, 0x1, 0x1);
		pwrcal_setf(PMU_DISPAUD_OPTION, 31, 0x1, 0x1);
		pwrcal_setf(PMU_DISPAUD_OPTION, 30, 0x1, 0x1);
		pwrcal_setf(PMU_DISPAUD_OPTION, 22, 0x1, 0x0);
		pwrcal_setf(PMU_DISPAUD_OPTION, 21, 0x1, 0x0);
		pwrcal_setf(PMU_ISP_OPTION, 31, 0x1, 0x1);
		pwrcal_setf(PMU_ISP_OPTION, 30, 0x1, 0x1);
		pwrcal_setf(PMU_MFCMSCL_OPTION, 31, 0x1, 0x1);
		pwrcal_setf(PMU_MFCMSCL_OPTION, 30, 0x1, 0x1);

	} else if (eMode == SYS_SICD) {

		pwrcal_setf(PMU_TOP_BUS_MIF_OPTION, 2, 0x1, 0x0);
		pwrcal_setf(PMU_TOP_BUS_MIF_OPTION, 1, 0x1, 0x1);
		pwrcal_setf(PMU_TOP_BUS_MIF_OPTION, 0, 0x1, 0x1);
		pwrcal_setf(PMU_WAKEUP_MASK, 30, 0x1, 0x1);
		pwrcal_setf(PMU_WAKEUP_MASK_MIF, 30, 0x1, 0x1);
		pwrcal_setf(PMU_G3D_OPTION, 31, 0x1, 0x0);
		pwrcal_setf(PMU_G3D_OPTION, 30, 0x1, 0x0);
		pwrcal_setf(PMU_DISPAUD_OPTION, 31, 0x1, 0x1);
		pwrcal_setf(PMU_DISPAUD_OPTION, 30, 0x1, 0x1);
		pwrcal_setf(PMU_DISPAUD_OPTION, 22, 0x1, 0x1);
		pwrcal_setf(PMU_DISPAUD_OPTION, 21, 0x1, 0x1);
		pwrcal_setf(PMU_ISP_OPTION, 31, 0x1, 0x0);
		pwrcal_setf(PMU_ISP_OPTION, 30, 0x1, 0x0);
		pwrcal_setf(PMU_MFCMSCL_OPTION, 31, 0x1, 0x0);
		pwrcal_setf(PMU_MFCMSCL_OPTION, 30, 0x1, 0x0);

	} else {

		pwrcal_setf(PMU_TOP_BUS_MIF_OPTION, 2, 0x1, 0x0);
		pwrcal_setf(PMU_TOP_BUS_MIF_OPTION, 1, 0x1, 0x0);
		pwrcal_setf(PMU_TOP_BUS_MIF_OPTION, 0, 0x1, 0x0);
		pwrcal_setf(PMU_WAKEUP_MASK, 30, 0x1, 0x1);
		pwrcal_setf(PMU_WAKEUP_MASK_MIF, 30, 0x1, 0x1);
		pwrcal_setf(PMU_G3D_OPTION, 31, 0x1, 0x0);
		pwrcal_setf(PMU_G3D_OPTION, 30, 0x1, 0x0);
		pwrcal_setf(PMU_DISPAUD_OPTION, 30, 0x1, 0x0);
		pwrcal_setf(PMU_DISPAUD_OPTION, 22, 0x1, 0x0);
		pwrcal_setf(PMU_DISPAUD_OPTION, 21, 0x1, 0x0);
		pwrcal_setf(PMU_ISP_OPTION, 31, 0x1, 0x0);
		pwrcal_setf(PMU_ISP_OPTION, 30, 0x1, 0x0);
		pwrcal_setf(PMU_MFCMSCL_OPTION, 31, 0x1, 0x0);
		pwrcal_setf(PMU_MFCMSCL_OPTION, 30, 0x1, 0x0);
	}
}

static void syspwr_set_additional_post_config(const enum sys_powerdown eMode)
{
		pwrcal_setf(PMU_TOP_BUS_MIF_OPTION, 2, 0x1, 0x0);
		pwrcal_setf(PMU_TOP_BUS_MIF_OPTION, 1, 0x1, 0x0);
		pwrcal_setf(PMU_TOP_BUS_MIF_OPTION, 0, 0x1, 0x0);
		pwrcal_setf(PMU_WAKEUP_MASK, 30, 0x1, 0x0);
		pwrcal_setf(PMU_WAKEUP_MASK_MIF, 30, 0x1, 0x0);
		pwrcal_setf(PMU_G3D_OPTION, 31, 0x1, 0x0);
		pwrcal_setf(PMU_G3D_OPTION, 30, 0x1, 0x0);
		pwrcal_setf(PMU_DISPAUD_OPTION, 30, 0x1, 0x0);
		pwrcal_setf(PMU_DISPAUD_OPTION, 22, 0x1, 0x0);
		pwrcal_setf(PMU_DISPAUD_OPTION, 21, 0x1, 0x0);
		pwrcal_setf(PMU_ISP_OPTION, 31, 0x1, 0x0);
		pwrcal_setf(PMU_ISP_OPTION, 30, 0x1, 0x0);
		pwrcal_setf(PMU_MFCMSCL_OPTION, 31, 0x1, 0x0);
		pwrcal_setf(PMU_MFCMSCL_OPTION, 30, 0x1, 0x0);

		if (eMode == SYS_SICD) {

			pwrcal_setf(PMU_CLKRUN_CMU_DISPAUD_SYS_PWR_REG, 0, 0x1, 0x0);
			pwrcal_setf(PMU_CLKSTOP_CMU_DISPAUD_SYS_PWR_REG, 0, 0x1, 0x0);
			pwrcal_setf(PMU_RESET_LOGIC_DISPAUD_SYS_PWR_REG, 0, 0x3, 0x0);
			pwrcal_setf(PMU_MEMORY_DISPAUD_SYS_PWR_REG, 0, 0x3, 0x0);
			pwrcal_setf(PMU_RESET_CMU_DISPAUD_SYS_PWR_REG, 0, 0x3, 0x0);
		}
}


extern unsigned int pwrcal_dmc_get_ptraing_state(void);
static int syspwr_prepare(int mode)
{
	if (mode == SYS_SICD){
		if (pwrcal_dmc_get_ptraing_state())
			return -1;
	}
	
	save_cmusfr(mode);

	save_topmuxgate();
	topmux_enable();
	syspwr_hwacg_control(mode);
	syspwr_clock_config(mode);
	syspwr_clkpwr_optimize(mode);

	set_pmu_sys_pwr_reg(mode);
	syspwr_set_additional_config(mode);
	set_pmu_central_seq(mode, true);

	return 0;
}

static void set_pmu_pad_retention_release(void)
{
	pwrcal_writel(PMU_PAD_RETENTION_AUD_OPTION, PAD_INITIATE_WAKEUP);
	pwrcal_writel(PMU_PAD_RETENTION_MMC2_OPTION, PAD_INITIATE_WAKEUP);
	pwrcal_writel(PMU_PAD_RETENTION_TOP_OPTION, PAD_INITIATE_WAKEUP);
	pwrcal_writel(PMU_PAD_RETENTION_UART_OPTION, PAD_INITIATE_WAKEUP);
	pwrcal_writel(PMU_PAD_RETENTION_MMC0_OPTION, PAD_INITIATE_WAKEUP);
	pwrcal_writel(PMU_PAD_RETENTION_MMC1_OPTION, PAD_INITIATE_WAKEUP);
	pwrcal_writel(PMU_PAD_RETENTION_SPI_OPTION, PAD_INITIATE_WAKEUP);
	pwrcal_writel(PMU_PAD_RETENTION_BOOTLDO_OPTION, PAD_INITIATE_WAKEUP);
}

static void syspwr_post(int mode)
{
	syspwr_hwacg_control_post(mode);
	enable_armidleclockdown();

	if (mode != SYS_SICD)
		set_pmu_pad_retention_release();

	set_pmu_central_seq(mode, false);

	switch (mode) {
	case SYS_SICD:
	case SYS_DSTOP:
	case SYS_STOP:
	case SYS_LPD:
		syspwr_set_additional_post_config(mode);
		pwrcal_setbit(CLK_CON_MUX_CLKPHY_FSYS_USB20DRD_PHYCLOCK_USER, 27, 0); //MUX_IGNORE
		break;
	default:
		return;
		break;
	}

	restore_cmusfr(mode);

	restore_topmuxgate();

	pwrcal_setbit(PCH_CTRL_DREX_PCH_0_MIF0, 3, 0); //Disable IGNORE_CLKGATE
	pwrcal_setbit(PCH_CTRL_DREX_PCH_0_MIF1, 3, 0);
}

static void syspwr_earlywakeup(int mode)
{
	set_pmu_central_seq(mode, false);
	syspwr_hwacg_control_post(mode);
	enable_armidleclockdown();

	switch (mode) {
	case SYS_SICD:
	case SYS_DSTOP:
	case SYS_STOP:
	case SYS_LPD:
		syspwr_set_additional_post_config(mode);
		pwrcal_setbit(CLK_CON_MUX_CLKPHY_FSYS_USB20DRD_PHYCLOCK_USER, 27, 0); //MUX_IGNORE
		break;
	default:
		return;
		break;
	}

	restore_cmusfr(mode);

	restore_topmuxgate();

	pwrcal_setbit(PCH_CTRL_DREX_PCH_0_MIF0, 3, 0); //Disable IGNORE_CLKGATE
	pwrcal_setbit(PCH_CTRL_DREX_PCH_0_MIF1, 3, 0);
}

struct cal_pm_ops cal_pm_ops = {
	.pm_enter = syspwr_prepare,
	.pm_exit = syspwr_post,
	.pm_earlywakeup = syspwr_earlywakeup,
	.pm_init = syspwr_init,
};
