# Generic Panel drivers

obj-$(CONFIG_GEN_PANEL_DYNAMIC_AID)	+= dimming_core.o
#obj-$(CONFIG_GEN_PANEL_DYNAMIC_AID)	+= dynamic_aid_gamma.o
obj-$(CONFIG_GEN_PANEL_MDNIE)		+= gen-panel-mdnie.o
obj-$(CONFIG_GEN_PANEL_TUNING)		+= gen-panel-tuning.o
obj-$(CONFIG_GEN_PANEL_BACKLIGHT)	+= gen-panel-bl.o
obj-$(CONFIG_GEN_PANEL_TFT)		+= gen-panel.o
obj-$(CONFIG_GEN_PANEL_OCTA)		+= gen-panel-octa.o
obj-$(CONFIG_DIMMING_DEBUG)		+= dimming_debug.o
