ccflags-y += -I$(srctree)/include/drm
ccflags-y += -I$(srctree)/drivers/gpu/drm/msm
ccflags-y += -I$(srctree)/drivers/gpu/drm/msm/dsi-staging
ccflags-y += -I$(srctree)/drivers/gpu/drm/msm/sde
ccflags-y += -I$(srctree)/drivers/clk/qcom/
ccflags-y += -I$(srctree)/drivers/gpu/drm/msm/samsung_lego

obj-y += self_display_HAB.o
