#
# for huaqin misc info
#

# huaqin added by tangqingyong for HS60-53 at 20190718 start
obj-$(CONFIG_HQ_SIM_TRAY_CHECK)   += sim_tray/
# huaqin added by tangqingyong for HS60-53 at 20190718 end
# hs70 add for HS70-1475 by liufurong at 20191123 start
obj-$(CONFIG_HW_INFO)   += hw_info/
# hs70 add for HS70-1475 by liufurong at 20191123 end
