#
# for huaqin misc info
#

# HS03 code for SR-SL6215-01-233 by sunxunou at 2021/08/02 start
obj-$(CONFIG_HQ_SIM_TRAY_CHECK)   += sim_tray/
# HS03 code for SR-SL6215-01-233 by sunxunou at 2021/08/02 end
