#
# Exynos HDCP drivers
#

# HDCP
hdcp2-objs := exynos-hdcp2.o exynos-hdcp2-teeif.o exynos-hdcp2-crypto.o exynos-hdcp2-session.o exynos-hdcp2-protocol-msg.o exynos-hdcp2-dplink-inter.o exynos-hdcp2-dplink.o exynos-hdcp2-dplink-if.o exynos-hdcp2-dplink-auth.o exynos-hdcp2-dplink-protocol-msg.o
obj-$(CONFIG_EXYNOS_HDCP2)     += hdcp2.o
