#SPRD CODEC

SPRD_SOUND_TREE := sound/soc/sprd/
ccflags-y += -I$(SPRD_SOUND_TREE)/codec/sprd

snd-soc-sprd-pdm-r2p0-objs   := sprd-pdm.o
# obj-$(CONFIG_SND_SOC_SPRD_PDM_R2P0)        += snd-soc-sprd-pdm-r2p0.o
obj-y        += snd-soc-sprd-pdm-r2p0.o
