obj-$(CONFIG_SEC_LOG)           += sec-log.o
obj-$(CONFIG_SEC_DEBUG)         += sec-debug.o sec-getlog.o sec-gaf.o sec-ftrace.o
obj-$(CONFIG_MACH_PXA_SAMSUNG)  += sec-common.o
#obj-$(CONFIG_SEC_FACTORY)	+= sec-factoryled.o
obj-$(CONFIG_SEC_BSP)		+= sec-bsp.o
obj-$(CONFIG_SEC_SLOW_MODE)	+= sec-slow.o
