
obj-$(CONFIG_ADSP_FACTORY) += adsp_factory.o ssc_core.o
obj-$(CONFIG_LSM6DSO_FACTORY) += lsm6dso_accel.o lsm6dso_gyro.o
obj-$(CONFIG_LSM6DSL_FACTORY) += lsm6dsl_accel.o lsm6dsl_gyro.o
obj-$(CONFIG_ICM4X6XX_FACTORY) += icm4x6xx_accel.o icm4x6xx_gyro.o
obj-$(CONFIG_STK31610_FACTORY) += stk31610_light.o
obj-$(CONFIG_AK09918_FACTORY) += ak09918_mag.o
obj-$(CONFIG_MMC5603X_FACTORY) += mmc5603x_mag.o
obj-$(CONFIG_VEML3235_FACTORY) += veml3xxx_light.o
obj-$(CONFIG_VEML3235_SUB_FACTORY) += veml3xxx_sub_light.o
obj-$(CONFIG_LPS22HH_FACTORY) += lps22hh_pressure.o
obj-$(CONFIG_STK3A9X_FACTORY) += stk3a9x_prox.o stk3a9x_light.o
obj-$(CONFIG_TMD3725_FACTORY) += tmd3725_prox.o tmd3725_light.o
obj-$(CONFIG_SPL07_FACTORY) += spl07_pressure.o
obj-$(CONFIG_FLIP_COVER_DETECTOR_FACTORY) += flip_cover_detector.o
