
obj-$(CONFIG_ADSP_FACTORY) += adsp_factory.o ssc_core.o
obj-$(CONFIG_ICM42605_FACTORY) += icm42605_accel.o icm42605_gyro.o
obj-$(CONFIG_STK33617_FACTORY) += stk33617_prox.o stk33617_light.o
obj-$(CONFIG_AK09918_FACTORY) += ak09918_mag.o
obj-$(CONFIG_MMC5603X_FACTORY) += mmc5603x_mag.o
obj-$(CONFIG_LPS22HH_FACTORY) += lps22hh_pressure.o
