
obj-$(CONFIG_ADSP_FACTORY) += adsp_factory.o ssc_core.o
obj-$(CONFIG_BMI168_FACTORY) += bmi168_accel.o bmi168_gyro.o
obj-$(CONFIG_K6DS3_FACTORY) += k6ds3_accel.o k6ds3_gyro.o
obj-$(CONFIG_AK09911C_FACTORY) += ak09911c_mag.o
obj-$(CONFIG_AK09916C_FACTORY) += ak09916c_mag.o
obj-$(CONFIG_BMP280_FACTORY) += bmp280_pressure.o
obj-$(CONFIG_CS5032_FACTORY) += cs5032_light.o
obj-$(CONFIG_CM3323_FACTORY) += cm3323_light.o
obj-$(CONFIG_TMD490X_FACTORY) += tmd490x_light.o tmd490x_prox.o barcode_emul_tmd4903.o
obj-$(CONFIG_SUPPORT_HIDDEN_HOLE) += hidden_hole.o