#! /usr/bin/env bash
# edit here
# def/undef for local target

# *** WARNING: Add enable/disable configs as newline ***

a04_00="
CONFIG_ZRAM_LRU_WRITEBACK_LIMIT=1024
CONFIG_KSWAPD_CPU=0xF0
"

a03su_00="
CONFIG_PAGE_BOOST=y
"

a21_00="
CONFIG_ZRAM_LRU_WRITEBACK_LIMIT=1024
"

