#! /usr/bin/env bash
# edit here
# def/undef for local target

# *** WARNING: Add enable/disable configs as newline ***

gta7lite_00="
###Project feature setting
CONFIG_RTC_AUTO_PWRON=y
CONFIG_PAGE_BOOST=y
"

gta7litewifi_00="
###Project feature setting
CONFIG_RTC_AUTO_PWRON=y
CONFIG_PAGE_BOOST=y
"