obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
#bug541231,zhaobeilong@wt,20200323,add booster chip tps61280 driver
obj-$(CONFIG_TPS61280A_POWER)  += tps61280a-power/
