#
#  Makefile for the kernel Sensor device drivers.
#

#  Object files in subdirectories
obj-$(CONFIG_SEC_SENSORS_CORE)		+= sensors_core.o
obj-$(CONFIG_SEC_SENSORS_CM36686)	+= cm36686.o
obj-$(CONFIG_SEC_SENSORS_K2HH)		+= k2hh.o
