obj-$(CONFIG_BATTERY_SAMSUNG)	+= sec_battery_qc.o
obj-$(CONFIG_BATTERY_SAMSUNG)	+= sec_battery_sysfs_qc.o
obj-$(CONFIG_BATTERY_SAMSUNG)	+= sec_battery_dt_qc.o
obj-$(CONFIG_BATTERY_SAMSUNG)	+= sec_battery_ttf.o
obj-$(CONFIG_BATTERY_CISD)	+= sec_cisd_qc.o