
SPRD_SOUND_TREE := sound/soc/sprd/
KBUILD_CFLAGS	+= -I$(SPRD_SOUND_TREE) -I$(SPRD_SOUND_TREE)/codec

snd-soc-sprd-null-codec-objs   := null-codec.o
obj-$(CONFIG_SND_SOC_NULL_CODEC)        += snd-soc-sprd-null-codec.o
