# Tab A9 code for AX6739A-761 by xiongxiaoliang at 20230607 start
obj-$(CONFIG_INPUT_SAR) += sensor_fac_node.o
obj-$(CONFIG_INPUT_SAR) += sensor_user_node.o
obj-$(CONFIG_INPUT_SAR) += sensors_core.o
obj-$(CONFIG_SAR_SX933X)+= sx933x.o
# Tab A9 code for AX6739A-761 by xiongxiaoliang at 20230607 end
