#
# Makefile for the GalaxyCore touchscreen driver.
#
#hs03s_NM code for SR-AL5625-01-624 by zhawei at 20220407 start
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
#hs03s_NM code for SR-AL5625-01-624 by zhawei at 20220407 end
obj-y	+=  gcore_drv_main.o
obj-y	+=  gcore_drv_mtk.o
obj-y	+=  gcore_drv_fw_update.o
obj-y	+=  gcore_drv_interface.o
obj-y	+=  gcore_drv_mp_test.o
#hs03s_NM code for SR-AL5625-01-640 by yuli at 20220420 start
obj-y	+=  gcore_sec.o
#hs03s_NM code for SR-AL5625-01-640 by yuli at 20220420 end