obj-y	+= sec_dt_init.o	\
			sec_battery.o

obj-$(CONFIG_FUELGAUGE_MAX17042)	+= max17042_fuelgauge.o
obj-$(CONFIG_FUELGAUGE_MAX17048)	+= max17048_fuelgauge.o
obj-$(CONFIG_FUELGAUGE_MAX17050)	+= max17050_fuelgauge.o
obj-$(CONFIG_FUELGAUGE_STC3115)		+= stc3115_fuelgauge.o
obj-$(CONFIG_FUELGAUGE_D2199)		+= d2199_fuelgauge.o
obj-$(CONFIG_FUELGAUGE_88PM822)		+= 88pm80x_fuelgauge.o
obj-$(CONFIG_FUELGAUGE_88PM800)     += 88pm80x_fuelgauge.o
obj-$(CONFIG_FUELGAUGE_88PM88X)     += 88pm88x_fuelgauge.o

obj-$(CONFIG_CHARGER_SM5701)   += sm5701_charger.o
obj-$(CONFIG_CHARGER_88PM88X)   += 88pm88x_charger.o
