ccflags-y += -I$(srctree)/include/drm
ccflags-y += -I$(srctree)/drivers/gpu/drm/msm
ccflags-y += -I$(srctree)/drivers/gpu/drm/msm/dsi-staging
ccflags-y += -I$(srctree)/drivers/gpu/drm/msm/samsung_lego
ccflags-y += -I$(srctree)/drivers/gpu/drm/msm/sde

obj-y += ss_dsi_mafpc_HAB.o
