msm_drm-$(CONFIG_DISPLAY_SAMSUNG) += samsung/MAFPC/ss_dsi_mafpc_FAB.o \
	samsung/MAFPC/ss_dsi_mafpc_HAB.o \
	samsung/MAFPC/ss_dsi_mafpc_HAC.o \
	samsung/MAFPC/ss_dsi_mafpc_HAD.o \
	samsung/MAFPC/ss_dsi_mafpc_XA1.o