# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_TYPEC)		+= typec.o
typec-y				:= class.o mux.o bus.o
obj-$(CONFIG_TYPEC)		+= altmodes/
obj-$(CONFIG_TYPEC_TCPM)	+= tcpm/
obj-$(CONFIG_TYPEC_UCSI)	+= ucsi/
obj-$(CONFIG_TYPEC_TPS6598X)	+= tps6598x.o
obj-$(CONFIG_TYPEC)		+= mux/
obj-$(CONFIG_TCPC_CLASS)	+= P86801_tcpc/
obj-$(CONFIG_AW35615_PD)	+= P86801_tcpc/aw35615/
