# arch/arm/mach-sc/board-teddy3g/Makefile
#
# Copyright (C) 2013 Samsung Electronics Co, Ltd.
#
# This software is licensed under the terms of the GNU General Public
# License version 2, as published by the Free Software Foundation, and
# may be copied, distributed, and modified under those terms.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

obj-y 	+=  board-teddy3g.o	\
			board-teddy3g-audio.o \
			board-teddy3g-serial.o \
			board-teddy3g-input.o \
			board-teddy3g-camera.o \
			board-teddy3g-display.o \
			board-teddy3g-connector.o \
			board-teddy3g-mmc.o \
			board-teddy3g-battery.o\
			board-teddy3g-pmic.o \

ccflags-y += -Iarch/arm/mach-sc/
