# SPRD Platform Support
snd-soc-i2s-objs         		:= i2s-r0p0-null-codec.o
obj-$(CONFIG_SND_SOC_SPRD_I2S_V0_NULL_CODEC)    	+= snd-soc-i2s.o
obj-$(CONFIG_SND_SOC_SPRD) += sprd-asoc-common.o sprd-asoc-card.o

obj-$(CONFIG_SND_SOC_SPRD_AUDIO_DMA)	+= dai/
obj-$(CONFIG_SND_SOC_SPRD_VBC_R1P0)	+= dai/vbc/r1p0/
obj-$(CONFIG_SND_SOC_SPRD_VBC_R2P0)	+= dai/vbc/r2p0/
obj-$(CONFIG_SND_SOC_SPRD_VAUDIO)     	+= dai/vaudio/
obj-$(CONFIG_SND_SOC_SPRD_I2S)		+= dai/i2s/
obj-$(CONFIG_SND_SOC_SPRD_CODEC_V1)	+= codec/sprd/v1/
obj-$(CONFIG_SND_SOC_SPRD_CODEC_V3)	+= codec/sprd/v3/
obj-$(CONFIG_SND_SOC_SPRD_CODEC_V4)	+= codec/sprd/v4/
obj-$(CONFIG_SND_SOC_NULL_CODEC)	+= codec/null-codec/
