#ifndef __CMUCAL_VCLKLUT_H__
#define __CMUCAL_VCLKLUT_H__

#include "../../cmucal.h"

/* DVFS VCLK */
extern unsigned int cmucal_VDDI_NM_lut_params[];
extern unsigned int cmucal_VDDI_UD_lut_params[];
extern unsigned int cmucal_VDDI_SUD_lut_params[];
extern unsigned int cmucal_VDDI_UUD_lut_params[];
extern unsigned int cmucal_VDD_ALIVE_SOD_lut_params[];
extern unsigned int cmucal_VDD_ALIVE_OD_lut_params[];
extern unsigned int cmucal_VDD_ALIVE_NM_lut_params[];
extern unsigned int cmucal_VDD_ALIVE_UD_lut_params[];
extern unsigned int cmucal_VDD_ALIVE_SUD_lut_params[];
extern unsigned int cmucal_VDD_ALIVE_UUD_lut_params[];
extern unsigned int cmucal_VDD_MIF_SOD_lut_params[];
extern unsigned int cmucal_VDD_MIF_OD_lut_params[];
extern unsigned int cmucal_VDD_MIF_NM_lut_params[];
extern unsigned int cmucal_VDD_MIF_UD_lut_params[];
extern unsigned int cmucal_VDD_MIF_SUD_lut_params[];
extern unsigned int cmucal_VDD_MIF_UUD_lut_params[];
extern unsigned int cmucal_VDD_CAM_SOD_lut_params[];
extern unsigned int cmucal_VDD_CAM_OD_lut_params[];
extern unsigned int cmucal_VDD_CAM_NM_lut_params[];
extern unsigned int cmucal_VDD_CAM_UD_lut_params[];
extern unsigned int cmucal_VDD_CAM_SUD_lut_params[];
extern unsigned int cmucal_VDD_CAM_UUD_lut_params[];
extern unsigned int cmucal_VDD_CHUBVTS_SOD_lut_params[];
extern unsigned int cmucal_VDD_CHUBVTS_OD_lut_params[];
extern unsigned int cmucal_VDD_CHUBVTS_NM_lut_params[];
extern unsigned int cmucal_VDD_CHUBVTS_UD_lut_params[];
extern unsigned int cmucal_VDD_CHUBVTS_SUD_lut_params[];
extern unsigned int cmucal_VDD_CHUBVTS_UUD_lut_params[];
extern unsigned int cmucal_VDD_NPU_SOD_lut_params[];
extern unsigned int cmucal_VDD_NPU_OD_lut_params[];
extern unsigned int cmucal_VDD_NPU_NM_lut_params[];
extern unsigned int cmucal_VDD_NPU_UD_lut_params[];
extern unsigned int cmucal_VDD_NPU_SUD_lut_params[];
extern unsigned int cmucal_VDD_NPU_UUD_lut_params[];
extern unsigned int cmucal_VDD_G3D_SOD_lut_params[];
extern unsigned int cmucal_VDD_G3D_OD_lut_params[];
extern unsigned int cmucal_VDD_G3D_NM_lut_params[];
extern unsigned int cmucal_VDD_G3D_UD_lut_params[];
extern unsigned int cmucal_VDD_G3D_SUD_lut_params[];
extern unsigned int cmucal_VDD_G3D_UUD_lut_params[];
extern unsigned int cmucal_VDD_CPUCL0_LIT_SOD_lut_params[];
extern unsigned int cmucal_VDD_CPUCL0_LIT_OD_lut_params[];
extern unsigned int cmucal_VDD_CPUCL0_LIT_NM_lut_params[];
extern unsigned int cmucal_VDD_CPUCL0_LIT_UD_lut_params[];
extern unsigned int cmucal_VDD_CPUCL0_LIT_SUD_lut_params[];
extern unsigned int cmucal_VDD_CPUCL0_LIT_UUD_lut_params[];
extern unsigned int cmucal_VDD_CPUCL1_BIG_SOD_lut_params[];
extern unsigned int cmucal_VDD_CPUCL1_BIG_OD_lut_params[];
extern unsigned int cmucal_VDD_CPUCL1_BIG_NM_lut_params[];
extern unsigned int cmucal_VDD_CPUCL1_BIG_UD_lut_params[];
extern unsigned int cmucal_VDD_CPUCL1_BIG_SUD_lut_params[];
extern unsigned int cmucal_VDD_CPUCL1_BIG_UUD_lut_params[];
/* SPECIAL VCLK */
extern unsigned int div_clk_hsi_ufs_embd_1776_params[];
/*PERIC/USI/CMGP*/
extern unsigned int div_clk_peri_400_lut_params[];
extern unsigned int div_clk_peri_200_lut_params[];
extern unsigned int div_clk_peri_133_lut_params[];
extern unsigned int div_clk_peri_100_lut_params[];
extern unsigned int div_clk_peri_80_lut_params[];
extern unsigned int div_clk_peri_66_lut_params[];
extern unsigned int div_clk_peri_57_lut_params[];
extern unsigned int div_clk_peri_50_lut_params[];
extern unsigned int div_clk_peri_44_lut_params[];
extern unsigned int div_clk_peri_40_lut_params[];
extern unsigned int div_clk_peri_36_lut_params[];
extern unsigned int div_clk_peri_33_lut_params[];
extern unsigned int div_clk_peri_30_lut_params[];
extern unsigned int div_clk_peri_28_lut_params[];
extern unsigned int div_clk_peri_26_lut_params[];
extern unsigned int div_clk_peri_25_lut_params[];
extern unsigned int div_clk_peri_19_lut_params[];
extern unsigned int div_clk_peri_15_lut_params[];
extern unsigned int div_clk_peri_12_lut_params[];
extern unsigned int div_clk_peri_10_lut_params[];
extern unsigned int div_clk_peri_9_lut_params[];
extern unsigned int div_clk_peri_8_lut_params[];
extern unsigned int div_clk_peri_7_lut_params[];
extern unsigned int div_clk_peri_6_lut_params[];
extern unsigned int div_clk_peri_6_4_lut_params[];
extern unsigned int div_clk_peri_5_9_lut_params[];
extern unsigned int div_clk_peri_5_4_lut_params[];
extern unsigned int div_clk_peri_5_1_lut_params[];
extern unsigned int div_clk_peri_4_8_lut_params[];
#endif
