#
# Self Display Object
# namd : ss_dsi_panel_"DDI NAME"_"PANEL NAME".c
#

ccflags-y := -Iinclude/drm -Idrivers/gpu/drm/msm -Idrivers/gpu/drm/msm/dsi-staging
ccflags-y += -Idrivers/gpu/drm/msm/sde
ccflags-y += -Idrivers/gpu/drm/msm/samsung

obj-y += self_display_FA7.o
obj-y += self_display_FA9.o
obj-y += self_display_HA8.o
obj-y += self_display_HA9.o
obj-y += self_display_XA0.o
