#
# Makefile for all kinds of Fingerprint
#


obj-$(CONFIG_CHIPONE_FINGERPRINT_N23) += chipone_n23/
obj-$(CONFIG_CHIPONE_FINGERPRINT) += chipone/
obj-$(CONFIG_CHIPONE_FINGERPRINT_W2) += chipone_w2/
obj-$(CONFIG_FPC1020_SUPPORT) += fpc/
obj-$(CONFIG_SILEAD_FINGERPRINT) += silead_fp/
obj-$(CONFIG_EGIS_FINGERPRINT) += egis/
obj-$(CONFIG_FOCALTECH_FINGERPRINT) += focaltech/
