#CONFIG_INPUT_FINGERPRINT
#CONFIG_FINGERPRINT_FPC1020
# Makefile for the fingerprint drivers.
#
# Each configuration option enables a list of files.

obj-$(CONFIG_FINGERPRINT_FPC1020) += fpc1020/
obj-$(CONFIG_FINGERPRINT_ET300)   += et300/