#
# Makefile for all kinds of Fingerprint
#


obj-$(CONFIG_EGIS_FINGERPRINT) += egis/
obj-$(CONFIG_CHIPONE_FINGERPRINT) += chipone/
obj-$(CONFIG_SILEAD_FINGERPRINT) += silead_fp/
obj-$(CONFIG_FOCALTECH_FINGERPRINT) += focaltech/

