obj-$(CONFIG_VIDEO_EXYNOS_PABLO_ISP) += is-interface-ischain.o \
		is-interface-library.o \
		is-interface-ddk.o

obj-$(CONFIG_PABLO_V7_0_0) += is-interface-vra.o

obj-$(CONFIG_PABLO_V8_0_0) += is-interface-vra.o

obj-$(CONFIG_PABLO_V8_1_0) += is-interface-vra.o

obj-$(CONFIG_PABLO_V8_10_0) += is-interface-vra.o

obj-$(CONFIG_PABLO_V8_20_0) += is-interface-vra-v2.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/include
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/hardware
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/hardware/api
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/camera/vendor
