# SPDX-License-Identifier: GPL-2.0
snd-soc-dp_dma-objs := dp_dma.o

obj-$(CONFIG_SND_SOC_SAMSUNG_DISPLAYPORT) += snd-soc-dp_dma.o
obj-$(CONFIG_SND_SOC_SAMSUNG_ABOX) += abox/
obj-$(CONFIG_SND_SOC_SAMSUNG_MAILBOX) += vts/
obj-$(CONFIG_SND_SOC_SAMSUNG_SLIF) += slif/

obj-$(CONFIG_SND_SOC_SAMSUNG_EXYNOS9925_SOUND) += exynos9925_sound.o
obj-$(CONFIG_SND_SOC_SAMSUNG_EXYNOS8825_SOUND) += exynos8825_sound.o
obj-$(CONFIG_SND_SOC_SAMSUNG_EXYNOS9935_SOUND) += exynos9935_sound.o
obj-$(CONFIG_SND_SOC_SAMSUNG_EXYNOS8535_SOUND) += exynos8535_sound.o
obj-$(CONFIG_SND_SOC_SAMSUNG_EXYNOS8835_SOUND) += exynos8835_sound.o
obj-$(CONFIG_SND_SOC_SAMSUNG_EXYNOS8835_AUDIO) += exynos8835_audio.o
obj-$(CONFIG_SND_SOC_SAMSUNG_EXYNOS8835_RT5665) += exynos8835_rt5665.o

obj-$(CONFIG_SND_SOC_SAMSUNG_AUDIO) += sec_audio_sysfs.o sec_audio_debug.o
