#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHSCREEN_IST30XX) += ist30xx.o ist30xx_update.o ist30xx_factory.o ist30xx_tracking.o ist30xx_misc.o ist30xx_sys.o
