#
# Makefile for the goodix touchscreen drivers.
#
obj-$(CONFIG_TOUCHSCREEN_GX)	+=  gt1x_extents.o
obj-$(CONFIG_TOUCHSCREEN_GX)	+=  gt1x_generic.o
obj-$(CONFIG_TOUCHSCREEN_GX)	+=  gt1x_tools.o
obj-$(CONFIG_TOUCHSCREEN_GX)	+=  gt1x.o
obj-$(CONFIG_TOUCHSCREEN_GX)	+=  gt1x_update.o
obj-$(CONFIG_TOUCHSCREEN_GX)    +=  gt1x_test.o
obj-$(CONFIG_TOUCHSCREEN_GX)    +=  test_function.o
# HS60 add for SR-ZQL1695-01000000583 by liufurong at 20190724 start
obj-$(CONFIG_TOUCHSCREEN_GX)    +=  gt1x_sec.o
# HS60 add for SR-ZQL1695-01000000583 by liufurong at 20190724 end
