
# In case the platform does NOT support this type of sensors

obj-$(CONFIG_LEDS_RT4832) += rt4832/

obj-$(CONFIG_LEDS_RT4832WSC) += rt4832wsc/

obj-$(CONFIG_LEDS_RT4832TDWSC) += rt4832tdwsc/

obj-$(CONFIG_LEDS_RT8542) += rt8542/

obj-$(CONFIG_DSV_SM5107) += sm5107/
obj-$(CONFIG_LEDS_SM5306) += sm5306/
