obj-$(CONFIG_WT_BOOTLOADER_LOG)	+= wt_bootloader_log_save.o
# CHK, douyingnan.wt, ADD, 20211222, dump display
obj-$(CONFIG_WT_BOOT_REASON)+=wt_boot_reason.o
obj-$(CONFIG_WT_SYSTEM_MONITOR)+=wt_system_monitor.o
