obj-$(CONFIG_USE_DIRECT_IS_CONTROL) += fimc-is-interface-ischain.o

EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/include
EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/vendor
