obj-$(CONFIG_EXYNOS3475_DECON_DISP_LCD) += dsim_panel.o dsim_backlight.o
obj-$(CONFIG_EXYNOS_DECON_MDNIE_LITE)		+= mdnie_lite.o mdnie_tuning.o
obj-$(CONFIG_PANEL_AID_DIMMING) += dimming_core.o
obj-$(CONFIG_EXYNOS_DECON_LCD_SYSFS)	+= lcd_sysfs.o
obj-$(CONFIG_EXYNOS3475_DECON_LCD_S6D78A)	+= s6d78a_lcd_ctrl.o
obj-$(CONFIG_EXYNOS3475_DECON_LCD_SC7798D)	+= sc7798d_lcd_ctrl.o
obj-$(CONFIG_EXYNOS3475_DECON_LCD_SC7798D_J2)	+= sc7798d_lcd_ctrl_j2.o  s6e8aa0_lcd_ctrl_j2.o
obj-$(CONFIG_PANEL_S6D7AA0_DYNAMIC) += s6d7aa0_lcd_ctrl.o