obj-$(CONFIG_EXYNOS3475_DECON_DISP_LCD) += dsim_panel.o
obj-$(CONFIG_EXYNOS_DECON_MDNIE_LITE)		+= mdnie_lite.o
obj-$(CONFIG_PANEL_AID_DIMMING) += dimming_core.o
obj-$(CONFIG_EXYNOS3475_DECON_LCD_S6D78A)	+= s6d78a_lcd_ctrl.o
obj-$(CONFIG_EXYNOS3475_DECON_LCD_SC7798D)	+= sc7798d_lcd_ctrl.o
obj-$(CONFIG_EXYNOS3475_DECON_LCD_S6E88A0)	+= s6e88a0_lcd_ctrl.o ea8061s_lcd_ctrl.o
obj-$(CONFIG_PANEL_S6D7AA0_DYNAMIC) += s6d7aa0_lcd_ctrl.o
obj-$(CONFIG_EXYNOS3475_DECON_LCD_ILI9881C)	+= ili9881c_lcd_ctrl.o
