dtb-y += b6q_kor_singlex_w00_r12.dtbo
dtb-y += b6q_kor_singlex_w00_r06.dtbo
dtb-y += b6q_kor_singlex_w00_r05.dtbo
dtb-y += b6q_kor_singlex_w00_r03.dtbo
# SPDX-License-Identifier: GPL-2.0
# COPYRIGHT(C) 2023 Samsung Electronics Co., Ltd. All Right Reserved.

# TODO: if lego is not avaiable then uncomment the following sub-makefile
# b6q_dir		:= $(srctree)/$(src)
# include $(b6q_dir)/without_lego.mk
