obj-$(CONFIG_SPRD_IOMMU) += sprd_iommu_vsp.o
obj-$(CONFIG_SPRD_IOMMU) += sprd_iommu_dcam.o
obj-$(CONFIG_SPRD_IOMMU) += sprd_iommu_dispc.o
obj-$(CONFIG_SPRD_IOMMU) += sprd_iommu_gsp0.o
obj-$(CONFIG_SPRD_IOMMU) += sprd_iommu_gsp1.o
obj-$(CONFIG_SPRD_IOMMU) += sprd_iommu_vpp.o
