obj-$(CONFIG_SCHED_EMS) += ems.o

ems-y += main.o
ems-y += core.o
ems-y += energy_table.o
ems-y += multi_load.o
ems-y += ontime.o
ems-y += sparing.o
ems-y += freqboost.o
ems-y += hook.o
ems-y += sysbusy.o
ems-y += frt.o
ems-y += profile.o
ems-y += state.o
ems-$(CONFIG_CPU_FREQ_GOV_ENERGYSTEP) += energy_step.o
ems-y += ego.o
ems-y += cpufreq.o
ems-$ += frt.o
ems-$(CONFIG_SCHED_EMS_TUNE) += tune.o
ems-y += gsc.o
ems-y += balance.o

obj-y += idle.o
