#ifndef _DT_BINDINGS_EXYNOS_H
#define _DT_BINDINGS_EXYNOS_H

/* EXYNOS_PM_QOS CLASSES IDS */
#define	PM_QOS_RESERVED			0
#define	PM_QOS_NETWORK_LATENCY		1
#define	PM_QOS_CLUSTER0_FREQ_MIN	2
#define	PM_QOS_CLUSTER0_FREQ_MAX	3
#define	PM_QOS_CLUSTER1_FREQ_MIN	4
#define	PM_QOS_CLUSTER1_FREQ_MAX	5
#define	PM_QOS_CPU_ONLINE_MIN		6
#define	PM_QOS_CPU_ONLINE_MAX		7
#define	PM_QOS_DEVICE_THROUGHPUT	8
#define	PM_QOS_INTCAM_THROUGHPUT	9
#define	PM_QOS_DEVICE_THROUGHPUT_MAX	10
#define	PM_QOS_INTCAM_THROUGHPUT_MAX	11
#define	PM_QOS_BUS_THROUGHPUT		12
#define	PM_QOS_BUS_THROUGHPUT_MAX	13
#define	PM_QOS_DISPLAY_THROUGHPUT	14
#define	PM_QOS_DISPLAY_THROUGHPUT_MAX	15
#define	PM_QOS_CAM_THROUGHPUT		16
#define	PM_QOS_AUD_THROUGHPUT		17
#define	PM_QOS_CAM_THROUGHPUT_MAX	18
#define	PM_QOS_AUD_THROUGHPUT_MAX	19
#define	PM_QOS_MFC_THROUGHPUT		20
#define	PM_QOS_MFC_THROUGHPUT_MAX	21
#define	PM_QOS_NPU_THROUGHPUT		22
#define	PM_QOS_NPU_THROUGHPUT_MAX	23
#define	PM_QOS_DSP_THROUGHPUT		24
#define	PM_QOS_DSP_THROUGHPUT_MAX	25
#define	PM_QOS_TNR_THROUGHPUT		26
#define	PM_QOS_TNR_THROUGHPUT_MAX	27
#define	PM_QOS_DNC_THROUGHPUT		28
#define	PM_QOS_DNC_THROUGHPUT_MAX	29
#define	PM_QOS_GPU_THROUGHPUT		30
#define	PM_QOS_GPU_THROUGHPUT_MAX	31
#endif
