# SPDX-License-Identifier: GPL-2.0
# SAMSUNG pmic pinmux support

obj-$(CONFIG_PINCTRL_SAMSUNG_S2MPS26) += pinctrl-samsung-s2mps26.o
obj-$(CONFIG_PINCTRL_SAMSUNG_S2MPM07) += pinctrl-samsung-s2mpm07.o
obj-$(CONFIG_PINCTRL_SAMSUNG_S2MPS26_9935) += s2mps26_pinctrl_9935.o
obj-$(CONFIG_PINCTRL_SAMSUNG_S2MPM07_9935) += s2mpm07_pinctrl_9935.o
obj-$(CONFIG_PINCTRL_SAMSUNG_S2MPA05_8535) += s2mpa05_pinctrl_8535.o
obj-$(CONFIG_PINCTRL_SAMSUNG_S2MPU15_8535) += s2mpu15_pinctrl_8535.o
obj-$(CONFIG_PINCTRL_SAMSUNG_S2MPU15_8835) += s2mpu15_pinctrl_8835.o
obj-$(CONFIG_PINCTRL_SAMSUNG_S2MPU16_8835) += s2mpu16_pinctrl_8835.o
