dtb-y += r12s_eur_openx_w01_r09.dtbo
dtb-y += r12s_eur_openx_w01_r08.dtbo
dtb-y += r12s_eur_openx_w01_r04.dtbo
dtb-y += r12s_eur_openx_w01_r02.dtbo
dtb-y += r12s_eur_openx_w01_r01.dtbo
dtb-y += r12s_eur_openx_w01_r00.dtbo
# SPDX-License-Identifier: GPL-2.0
always-y	:= $(dtb-y) $(dtbo-y)
clean-files	:= *.dtb *.dtbo
