# A06 code for SR-AL7160A-01-54 by hehaoran at 20240407 start
ifeq ($(CONFIG_MTK_FINGERPRINT_SUPPORT), y)
obj-$(CONFIG_SILEAD_FP)                += silead/
obj-$(CONFIG_JIIOV_FP)                += jiiov/
obj-$(CONFIG_FINGERPRINT_FOCALTECH)    += focaltech/
obj-$(CONFIG_FINGER_O8)               += fingerprint_sysfs.o
endif
# A06 code for SR-AL7160A-01-54 by hehaoran at 20240407 end
