ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc
# a06 code for AL7160A-5 by wenghailong at 20240313 start
obj-y += lcd_hx83108b_xx_hkc_mipi_hd_video.o
obj-y += lcd_default_mipi_fhd_video.o
# a06 code for AL7160A-5 by wenghailong at 20240313 end
