obj-$(CONFIG_SENSORS) += sensors_core.o
obj-$(CONFIG_CUSTOM_KERNEL_SAR_SENSOR)  +=  sensor_fac_node.o sx9338/
#HS14_U code for SR-AL6528E-01-37 by xiayujie at 2023/07/28 start
obj-$(CONFIG_CUSTOM_KERNEL_SAR_SENSOR) += sensor_user_node.o
#HS14_U code for SR-AL6528E-01-37 by xiayujie at 2023/07/28 end
