# Makefile for the focaltech touchscreen drivers.


obj-$(CONFIG_TOUCHSCREEN_FTS)	+=  focaltech_core.o
obj-$(CONFIG_TOUCHSCREEN_FTS)	+=  focaltech_ex_fun.o
obj-$(CONFIG_TOUCHSCREEN_FTS)	+=  focaltech_ex_mode.o
obj-$(CONFIG_TOUCHSCREEN_FTS)	+=  focaltech_gesture.o
obj-$(CONFIG_TOUCHSCREEN_FTS)	+=  focaltech_esdcheck.o
obj-$(CONFIG_TOUCHSCREEN_FTS)   +=  focaltech_point_report_check.o
obj-$(CONFIG_TOUCHSCREEN_FTS)   +=  focaltech_test/
obj-$(CONFIG_TOUCHSCREEN_FTS)	+=  focaltech_flash.o
obj-$(CONFIG_TOUCHSCREEN_FTS)   +=  focaltech_spi.o
# Tab A8 code for SR-AX6300-01-451 by gaozhengwei at 2021/11/22 start
obj-$(CONFIG_TOUCHSCREEN_FTS)   +=  focaltech_sec.o
# Tab A8 code for SR-AX6300-01-451 by gaozhengwei at 2021/11/22 end