#
# panel object
# namd : ss_dsi_panel_"DDI NAME"_"PANEL NAME".c
#

ccflags-y := -Iinclude/drm -Idrivers/gpu/drm/msm -Idrivers/gpu/drm/msm/dsi-staging
ccflags-y += -Idrivers/gpu/drm/msm/sde
ccflags-y += -Idrivers/gpu/drm/msm/samsung

obj-y  += ss_dsi_panel_ANA38401_AMSA05RB06.o
obj-y  += ss_dsi_smart_dimming_ANA38401_AMSA05RB06.o
obj-y  += ss_dsi_interpolation_ANA38401_AMSA05RB06.o
