KBUILD_CFLAGS += -Wno-unused-variable -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-frame-larger-than= -Wno-vla -Wno-uninitialized

obj-$(CONFIG_SENSORS_FLICKER_SELF_TEST) += flicker_test.o

KBUILD_CFLAGS += -Wno-unused-variable -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-frame-larger-than= -Wno-vla -Wno-uninitialized

flicker_sensor-y := tsl2585.o
flicker_sensor-$(CONFIG_FLICKER_PWM_CALIBRATION) += tsl2585_cal.o

obj-$(CONFIG_SENSORS_TSL2585) += flicker_sensor.o
