# Makefile for the focaltech touchscreen drivers.


obj-$(CONFIG_TOUCHSCREEN_FTS_N9)	+=  focaltech_core.o
obj-$(CONFIG_TOUCHSCREEN_FTS_N9)	+=  focaltech_ex_fun.o
obj-$(CONFIG_TOUCHSCREEN_FTS_N9)	+=  focaltech_ex_mode.o
obj-$(CONFIG_TOUCHSCREEN_FTS_N9)	+=  focaltech_gesture.o
obj-$(CONFIG_TOUCHSCREEN_FTS_N9)	+=  focaltech_esdcheck.o
obj-$(CONFIG_TOUCHSCREEN_FTS_N9)   +=  focaltech_point_report_check.o
obj-$(CONFIG_TOUCHSCREEN_FTS_N9)   +=  focaltech_test_n9/



obj-$(CONFIG_TOUCHSCREEN_FTS_N9)   +=  focaltech_spi.o
obj-$(CONFIG_TOUCHSCREEN_FTS_N9)	+=  focaltech_flash.o
