subdir-ccflags-y := -Wformat
obj-$(CONFIG_MUIC_S2MF301)	+= muic_s2mf301.o
muic_s2mf301-y			:= s2mf301-muic.o s2mf301-muic-afc.o

obj-$(CONFIG_MUIC_S2MF301)	+= top_s2mf301.o
top_s2mf301-y			:= s2mf301_top.o
