obj-$(CONFIG_SENSORS) += sensors_core.o
obj-$(CONFIG_CUSTOM_KERNEL_SAR_SENSOR) += a96t349/
obj-y    +=  sx932x/
#Tab A7 lite_T code for AX3565TDEV-837 by duxinqi at 2022/03/02 start
obj-$(CONFIG_CUSTOM_KERNEL_SAR_SENSOR) += sensor_user_node.o
#Tab A7 lite_T code for AX3565TDEV-837 by duxinqi at 2022/03/02 end
