obj-$(CONFIG_TOUCHSCREEN_CHIPONE_TDDI_O22) += chipone-tddi.o
# obj-m += chipone-tddi.o

chipone-tddi-objs := cts_i2c_driver.o
chipone-tddi-objs += cts_core.o
chipone-tddi-objs += cts_sfctrlv2.o
chipone-tddi-objs += cts_spi_flash.o
chipone-tddi-objs += cts_firmware.o
chipone-tddi-objs += cts_test.o
chipone-tddi-objs += cts_charger_detect.o
chipone-tddi-objs += cts_earjack_detect.o
chipone-tddi-objs += cts_hostcomm.o
chipone-tddi-objs += cts_tcs.o
chipone-tddi-objs += cts_platform.o
chipone-tddi-objs += cts_tool.o
chipone-tddi-objs += cts_sysfs.o
chipone-tddi-objs += cts_strerror.o
chipone-tddi-objs += cts_oem.o
# hs14 code for  SR-AL6528A-01-494 by hehaoran5 at 20220919 start
chipone-tddi-objs += cts_sec.o
# hs14 code for  SR-AL6528A-01-494 by hehaoran5 at 20220919 end