obj-$(CONFIG_SD87XX)				+= sd8787/
obj-$(CONFIG_SD8887)				+= sd8887/
obj-y  				+= kmalloc/
obj-y				+= graphics/galcore_src/
obj-y				+= marvell-telephony/drivers/
obj-y				+= security/wtpsp/drv/src/
obj-y				+= physrw/
