# SPRD audio assistant modules

obj-$(CONFIG_SPRD_AUDIO_AGDSP_ACCESS)		+= agdsp_access/
obj-$(CONFIG_SPRD_AUDIO_DSP_DUMP)		+= audiodspdump/
obj-$(CONFIG_SPRD_AUDIO_MEMORY_MANAGER)		+= audiomem/
obj-$(CONFIG_SPRD_AUDIO_MEMORY_MANAGER)		+= audio_pipe/
obj-$(CONFIG_SPRD_AUDIO_SIPC)			+= audiosipc/
obj-$(CONFIG_SPRD_AUDIO_MCDT)			        += mcdt/mcdt_r1p0/
obj-$(CONFIG_SPRD_AUDIO_MCDT_R2P0)			        += mcdt/mcdt_r2p0/
obj-$(CONFIG_SPRD_AUDIO_SAUDIO)			+= saudio/
obj-$(CONFIG_SPRD_HW_DEVICE_DVFS_AGCP) 		+= audiodvfs/
obj-$(CONFIG_SPRD_AUDIO_CPBOOT)				+= audiocpboot/
obj-$(CONFIG_SPRD_AUDIO_VOICE_TRIGGER)		+= voice_trigger/
