dtbo-y += gts8wifi_eur_open_w00_r08.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
gts8wifi_eur_open_w00_r08.dtbo-base := ../../../vendor/qcom/waipio.dtb ../../../vendor/qcom/waipio-v2.dtb ../../../vendor/qcom/waipiop.dtb ../../../vendor/qcom/waipiop-v2.dtb # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
dtbo-y += gts8wifi_eur_open_w00_r07.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
gts8wifi_eur_open_w00_r07.dtbo-base := ../../../vendor/qcom/waipio.dtb ../../../vendor/qcom/waipio-v2.dtb ../../../vendor/qcom/waipiop.dtb ../../../vendor/qcom/waipiop-v2.dtb # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
dtbo-y += gts8wifi_eur_open_w00_r06.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
gts8wifi_eur_open_w00_r06.dtbo-base := ../../../vendor/qcom/waipio.dtb ../../../vendor/qcom/waipio-v2.dtb ../../../vendor/qcom/waipiop.dtb ../../../vendor/qcom/waipiop-v2.dtb # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
dtbo-y += gts8wifi_eur_open_w00_r05.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
gts8wifi_eur_open_w00_r05.dtbo-base := ../../../vendor/qcom/waipio.dtb ../../../vendor/qcom/waipio-v2.dtb ../../../vendor/qcom/waipiop.dtb ../../../vendor/qcom/waipiop-v2.dtb # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
dtbo-y += gts8wifi_eur_open_w00_r04.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
gts8wifi_eur_open_w00_r04.dtbo-base := ../../../vendor/qcom/waipio.dtb ../../../vendor/qcom/waipio-v2.dtb ../../../vendor/qcom/waipiop.dtb ../../../vendor/qcom/waipiop-v2.dtb # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
# SPDX-License-Identifier: GPL-2.0

#define __sec_dtbo_build
#dtbo-$(2) += $(1)
#$(1)-base := $(3)
#endef
#
#define sec_dtbo_build
#$(foreach dtbo, $(1), $(eval $(call __sec_dtbo_build, $(dtbo),$(2),$(3))))
#endef
#
# WAIPIO BASE DTB
#QCOM_DTB := ../../../vendor/qcom
#SEC_WAIPIO_BASE_DTB := $(QCOM_DTB)/waipio.dtb $(QCOM_DTB)/waipiop.dtb
#
#ifeq ($(CONFIG_BUILD_ARM64_DT_OVERLAY),y)
#
# TABS8
#SEC_GTS8P_DTBO := \
#    waipio-sec.gts8p.overlay.00.dtbo
#
#$(eval $(call sec_dtbo_build, \
#    $(SEC_GTS8P_DTBO),$(CONFIG_ARCH_WAIPIO),$(SEC_WAIPIO_BASE_DTB)))
#endif

clean-files := *.dtb *.reverse.dts *.dtbo

