obj-$(CONFIG_VIDEO_EXYNOS_MFC) := exynos_mfc.o
exynos_mfc-y += mfc_perf_measure.o
exynos_mfc-y += mfc_ctx_ctrl.o
exynos_mfc-y += mfc_debugfs.o mfc_core_otf.o
exynos_mfc-y += mfc_llc.o
#Dev interface layer
exynos_mfc-y += mfc.o mfc_dec_v4l2.o mfc_dec_vb2.o mfc_enc_v4l2.o mfc_enc_vb2.o
#Dev control layer
exynos_mfc-y += mfc_rm.o mfc_meerkat.o mfc_sync.o
#Core interface layer
exynos_mfc-y += mfc_core.o mfc_core_ops.o mfc_core_nal_q.o mfc_core_isr.o
#Core control layer
exynos_mfc-y += mfc_core_hwlock.o mfc_core_intlock.o mfc_core_pm.o mfc_core_qos.o
exynos_mfc-y += mfc_core_buf_ctrl.o mfc_core_run.o mfc_core_meerkat.o
#Core HW access layer
exynos_mfc-y += mfc_core_enc_param.o mfc_core_cmd.o
exynos_mfc-y += mfc_core_hw_reg_api.o mfc_core_reg_api.o
#Common base layer
exynos_mfc-y += base/mfc_qos.o base/mfc_queue.o base/mfc_buf.o base/mfc_utils.o base/mfc_mem.o
exynos_mfc-y += base/mfc_memlog.o base/mfc_sysevent.o base/mfc_meminfo.o
