# Makefile for the Jadard touchscreen drivers.
obj-$(CONFIG_TOUCHSCREEN_JADARD_MODULE)         += jadard_module.o
obj-$(CONFIG_TOUCHSCREEN_JADARD_IC_JD9365T)     += jadard_ic_JD9365T.o
obj-$(CONFIG_TOUCHSCREEN_JADARD_COMMON)         += jadard_common.o jadard_platform.o
obj-$(CONFIG_TOUCHSCREEN_JADARD_DEBUG)          += jadard_debug.o
obj-$(CONFIG_TOUCHSCREEN_JADARD_SORTING)        += jadard_sorting.o
# HS03 code for SL6215DEV-521 by chenyihong at 20210826 start
obj-$(CONFIG_TOUCHSCREEN_JADARD_SEC)            += jadard_sec.o
# HS03 code for SL6215DEV-521 by chenyihong at 20210826 end