shub-y += comm/shub_comm.o
shub-y += comm/shub_iio.o
shub-y += comm/shub_kfifo_buf.o
shub-y += comm/misc/shub_misc.o
shub-y += comm/misc/shub_batch.o
shub-y += comm/misc/shub_injection.o
shub-y += comm/misc/shub_scontext.o
shub-y += debug/shub_debug.o
shub-y += debug/shub_debug_sysfs.o
shub-y += debug/shub_sensor_dump.o
shub-y += debug/shub_system_checker.o
shub-y += debug/shub_dump.o
shub-y += factory/shub_factory.o
shub-y += factory/accelerometer/accelerometer_factory.o
shub-y += factory/flip_cover_detector/flip_cover_detector_factory.o
shub-y	+= factory/gyroscope/gyroscope_factory.o
shub-y	+= factory/gyroscope/gyroscope_icm42605m_factory.o
shub-y	+= factory/gyroscope/gyroscope_lsm6dsl_factory.o
shub-y	+= factory/gyroscope/gyroscope_lsm6dsotr_factory.o
shub-y	+= factory/gyroscope/gyroscope_lsm6dsvtr_factory.o
shub-y	+= factory/gyroscope/gyroscope_icm42632m_factory.o
shub-y += factory/light/light_factory.o

shub-y += factory/magnetometer/magnetometer_factory.o
shub-y += factory/magnetometer/magnetometer_ak09918c_factory.o
shub-y += factory/magnetometer/magnetometer_mmc5633_factory.o
shub-y += factory/magnetometer/magnetometer_yas539_factory.o
shub-y += factory/magnetometer/magnetometer_mxg4300s_factory.o
shub-y += factory/pressure/pressure_factory.o
shub-y += factory/pressure/pressure_bmp580_factory.o
shub-y += factory/pressure/pressure_lps22hh_factory.o
shub-y += factory/pressure/pressure_lps22df_factory.o
shub-y += factory/pressure/pressure_lps25h_factory.o
shub-y += factory/proximity/proximity_factory.o
shub-y += factory/proximity/proximity_gp2ap110s_factory.o
shub-y += factory/proximity/proximity_stk3x6x_factory.o
shub-y += factory/proximity/proximity_stk3328_factory.o
shub-y += factory/proximity/proximity_tmd4912_factory.o
shub-y += factory/proximity/proximity_stk3391x_factory.o
shub-y += factory/proximity/proximity_stk33512_factory.o
shub-y += factory/proximity/proximity_stk3afx_factory.o

shub-y += others/shub_motor_callback.o
shub-y += others/shub_panel.o
shub-y += others/shub_pogo.o
shub-y += others/shub_aois.o

shub-y += sensor/accelerometer.o
shub-y += sensor/gyroscope.o
shub-y += sensor/gyroscope_uncal.o
shub-y += sensor/magnetometer.o
shub-y += sensor/magnetometer_uncal.o
shub-y += sensor/flip_cover_detector.o
shub-y += sensor/light.o
shub-y += sensor/light_cct.o
shub-y += sensor/light_autobrightness.o
shub-y += sensor/light_seamless.o
shub-y += sensor/led_cover_event.o
shub-y += sensor/pressure.o
shub-y += sensor/scontext.o
shub-y += sensor/step.o
shub-y += sensor/proximity.o
shub-y += sensor/proximity_raw.o
shub-y += sensor/proximity_calibration.o
shub-y += sensor/motion.o
shub-y += sensor/super.o
shub-y += sensor/hub_debugger.o
#shub-y += sensor/thermistor.o
shub-y += sensor/pocket_mode.o
shub-y += sensor/device_orientation.o
shub-y += sensor/sar_backoff_motion.o
shub-y += sensor/pogo_request_handler.o
shub-y += sensor/aois.o
shub-y += sensor/rotation_vector.o
shub-y += sensor/game_rotation_vector.o

shub-y += sensor/physical_sensor/accelerometer/accelerometer_icm42605m.o
shub-y += sensor/physical_sensor/accelerometer/accelerometer_lsm6dsl.o
shub-y += sensor/physical_sensor/accelerometer/accelerometer_lis2dlc12.o
shub-y += sensor/physical_sensor/accelerometer/accelerometer_lsm6dsotr.o
shub-y += sensor/physical_sensor/accelerometer/accelerometer_lsm6dsvtr.o
shub-y += sensor/physical_sensor/accelerometer/accelerometer_icm42632m.o
shub-y += sensor/physical_sensor/gyroscope/gyroscope_icm42605m.o
shub-y += sensor/physical_sensor/gyroscope/gyroscope_lsm6dsl.o
shub-y += sensor/physical_sensor/gyroscope/gyroscope_lsm6dsotr.o
shub-y += sensor/physical_sensor/gyroscope/gyroscope_lsm6dsvtr.o
shub-y += sensor/physical_sensor/gyroscope/gyroscope_icm42632m.o

shub-y += sensor/physical_sensor/magnetometer/magnetometer_ak09918c.o
shub-y += sensor/physical_sensor/magnetometer/magnetometer_mmc5633.o
shub-y += sensor/physical_sensor/magnetometer/magnetometer_yas539.o
shub-y += sensor/physical_sensor/magnetometer/magnetometer_mxg4300s.o
shub-y += sensor/physical_sensor/proximity/proximity_stk3x6x.o
shub-y += sensor/physical_sensor/proximity/proximity_gp2ap110s.o
shub-y += sensor/physical_sensor/proximity/proximity_stk3328.o
shub-y += sensor/physical_sensor/proximity/proximity_tmd4912.o
shub-y += sensor/physical_sensor/proximity/proximity_stk33512.o
shub-y += sensor/physical_sensor/proximity/proximity_stk3391x.o
shub-y += sensor/physical_sensor/proximity/proximity_stk3afx.o
shub-y += sensor/physical_sensor/light/light_stk33512.o

shub-y += sensor/physical_sensor/pressure/pressure_bmp580.o
shub-y += sensor/physical_sensor/pressure/pressure_lps22hh.o
shub-y += sensor/physical_sensor/pressure/pressure_lps22df.o

shub-y += sensorhub/shub_device.o
shub-y += sensorhub/shub_sysfs.o

shub-y += sensorhub/shub_device_wrapper.o
shub-y += sensorhub/shub_firmware.o

shub-y += sensormanager/shub_sensor_manager.o
shub-y += sensormanager/shub_sensor_sysfs.o
shub-y += sensormanager/shub_sensor.o

shub-y += utility/shub_utility.o
shub-y += utility/shub_wakelock.o
shub-y += utility/shub_dev_core.o
shub-y += utility/shub_wait_event.o
shub-y += utility/shub_file_manager.o

shub-$(CONFIG_SHUB_MTK) += vendor/shub_mtk.o
ccflags-$(CONFIG_MTK_TINYSYS_SCP_RV_SUPPORT) += -I$(srctree)/drivers/misc/mediatek/scp/include
ccflags-$(CONFIG_SHUB_MTK_SCP_INCLUDE) += -I$(srctree)/drivers/misc/mediatek/scp/include

shub-$(CONFIG_SHUB_LSI) += vendor/shub_lsi.o

obj-$(CONFIG_SHUB) += shub.o
obj-$(CONFIG_SHUB) += utility/sensor_core.o
