pablo-i2c-dummy-objs := is-i2c-dummy.o

obj-$(CONFIG_CAMERA_I2C_DUMMY) += pablo-i2c-dummy.o

EXTRA_CFLAGS += -I$(srctree)/drivers/media/platform/exynos/camera
EXTRA_CFLAGS += -I$(srctree)/drivers/media/platform/exynos/camera/include
EXTRA_CFLAGS += -I$(srctree)/drivers/media/platform/exynos/camera/vendor
EXTRA_CFLAGS += -I$(srctree)/drivers/media/platform/exynos/camera/sensor/module_framework
EXTRA_CFLAGS += -I$(srctree)/drivers/media/platform/exynos/camera/sensor
