obj-$(CONFIG_MACH_COREPRIMELITE) += board-coreprimelite.o
obj-$(CONFIG_MACH_COREPRIMEVE3G) += board_common_battery.o syssleep.o
obj-$(CONFIG_MACH_GRANDPRIMEVE3G) += board_common_battery.o syssleep.o
obj-$(CONFIG_MACH_J23G) += board_common_battery.o syssleep.o
obj-$(CONFIG_MACH_GTEL3G) += board_common_battery.o syssleep.o
obj-$(CONFIG_MACH_SCX35_DT) += mach-scx35-dt.o
obj-$(CONFIG_GPS_BCM47520) += sec_gps_bcm47520.o
obj-$(CONFIG_SEC_THERMISTOR) += sec_thermistor.o sc7723s_thermistor.o