#
# Makefile for mach
#

obj-y	+= mmpx-dt.o helanx-dt.o regs-addr.o pxa1908_lowpower.o pxa1928_lowpower.o pm.o pm-pxa1928.o pm-pxa1908.o  pxa1936_lowpower.o cpuidle_qos.o pm-pxa1936.o

obj-$(CONFIG_CORESIGHT_SUPPORT)	+= coresight-v8.o


obj-$(CONFIG_MACH_J1ACELTE)	+= soc_camera_j1ace.o

obj-$(CONFIG_MACH_COREPRIMEVELTE) += soc_camera_coreprimevelte.o
obj-$(CONFIG_MACH_J1ACELTE_LTN)	+= soc_camera_j1ace.o
obj-$(CONFIG_MACH_XCOVER3LTE)	+= soc_camera_xcover3lte.o
