snd-soc-smartpa-aw882xx-objs := aw882xx.o aw_monitor.o aw_init.o aw_dsp.o aw_device.o aw_calib.o aw_bin_parse.o bigdata_aw882xx_sysfs_cb.o
obj-$(CONFIG_SND_SMARTPA_AW882XX) += snd-soc-smartpa-aw882xx.o
