# SPDX-License-Identifier: GPL-2.0
#
# Makefile for PMIC RTC class/drivers.
#

obj-$(CONFIG_RTC_DRV_S2MPS25)   += rtc-s2mps25.o
obj-$(CONFIG_RTC_DRV_S2MPS25_9935)   += s2mps25_rtc_9935.o
obj-$(CONFIG_RTC_DRV_S2MPU15_8535)   += s2mpu15_rtc_8535.o
obj-$(CONFIG_RTC_DRV_S2MPU15_8835)   += s2mpu15_rtc_8835.o
