TARGET = fst1ba90a

$(TARGET)-objs	:= stm_ts.o stm_fw.o stm_sec.o stm_ts_tool_proc.o sec_input.o sec_cmd.o sec_tclm_v2.o sec_tsp_log.o sec_input_multi_dev.o

obj-m += $(TARGET).o

ccflags-y += -Wformat
