# SPDX-License-Identifier: GPL-2.0
#
# Makefile for multifunction miscellaneous devices for samsung pmic
#

#obj-$(CONFIG_IFCONN_NOTIFIER_MODULE)		+= ifconn_notifier_module.o
#ifconn_notifier_module-$(CONFIG_IFCONN_NOTIFIER) += ifconn_notifier.o
#ifconn_notifier_module-$(CONFIG_IFCONN_MANAGER) += ifconn_manager.o

obj-$(CONFIG_IFCONN_NOTIFIER_MODULE)	+= ifconn_notifier.o
obj-$(CONFIG_IFCONN_NOTIFIER_MODULE)	+= ifconn_manager.o

