/*
 * Copyright (c) 2018 Samsung Electronics Co., Ltd.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * Device Tree binding constants for Exynos9830 clock controller.
 */

#ifndef _DT_BINDINGS_CLOCK_EXYNOS_9925_H
#define _DT_BINDINGS_CLOCK_EXYNOS_9925_H

/* osc */
#define	NONE	(0 + 0)
#define	OSCCLK1	(0 + 1)
#define	OSCCLK2	(0 + 2)

/* alive */
#define	CLK_ALIVE_BASE	(10)
#define	GATE_MCT_ALIVE_QCH	(CLK_ALIVE_BASE + 0)
#define	GATE_USI_ALIVE0_QCH	(CLK_ALIVE_BASE + 1)
#define	DOUT_DIV_CLK_ALIVE_CHUB_NOC	(CLK_ALIVE_BASE + 2)
#define	DOUT_DIV_CLK_ALIVE_USI0	(CLK_ALIVE_BASE + 3)
#define	DOUT_CLK_ALIVE_OSCCLK_USB_LINK	(CLK_ALIVE_BASE + 4)

/* top */
#define	CLK_TOP_BASE	(100)
#define	DOUT_DIV_CLKCMU_AUD_NOC		(CLK_TOP_BASE + 0)
#define	DOUT_DIV_CLKCMU_AUD_CPU		(CLK_TOP_BASE + 1)
#define	DOUT_DIV_CLKCMU_CIS_CLK0	(CLK_TOP_BASE + 2)
#define	DOUT_DIV_CLKCMU_CIS_CLK1	(CLK_TOP_BASE + 3)
#define	DOUT_DIV_CLKCMU_CIS_CLK2	(CLK_TOP_BASE + 4)
#define	DOUT_DIV_CLKCMU_CIS_CLK3	(CLK_TOP_BASE + 5)
#define	DOUT_DIV_CLKCMU_CIS_CLK4	(CLK_TOP_BASE + 6)
#define	DOUT_DIV_CLKCMU_CIS_CLK5	(CLK_TOP_BASE + 7)
#define DOUT_DIV_CLKCMU_HSI_NOC		(CLK_TOP_BASE + 8)
#define	GATE_DFTMUX_CMU_QCH_CIS_CLK0	(CLK_TOP_BASE + 9)
#define	GATE_DFTMUX_CMU_QCH_CIS_CLK1	(CLK_TOP_BASE + 10)
#define	GATE_DFTMUX_CMU_QCH_CIS_CLK2	(CLK_TOP_BASE + 11)
#define	GATE_DFTMUX_CMU_QCH_CIS_CLK3	(CLK_TOP_BASE + 12)
#define	GATE_DFTMUX_CMU_QCH_CIS_CLK4	(CLK_TOP_BASE + 13)
#define	GATE_DFTMUX_CMU_QCH_CIS_CLK5	(CLK_TOP_BASE + 14)
#define DOUT_CLKCMU_HSI_UFS_EMBD	(CLK_TOP_BASE + 15)
#define DOUT_CLKCMU_USB_NOC		(CLK_TOP_BASE + 16)
#define DOUT_CLKCMU_USB_USB20DRD	(CLK_TOP_BASE + 17)
#define DOUT_CLKCMU_M2M_NOC		(CLK_TOP_BASE + 18)
#define DOUT_CLKCMU_M2M_JPEG		(CLK_TOP_BASE + 19)
#define DOUT_CLKCMU_M2M_GDC		(CLK_TOP_BASE + 20)
#define DOUT_CLKCMU_M2M_LME		(CLK_TOP_BASE + 21)
#define DOUT_CLKCMU_M2M_VRA		(CLK_TOP_BASE + 22)
#define DOUT_CLKCMU_PERI_MMC_CARD	(CLK_TOP_BASE + 23)

/* aud */
#define	CLK_AUD_BASE	(200)
#define	UMUX_CLKVTS_AUD_DMIC0	(CLK_AUD_BASE + 0)

#define	GATE_ABOX_QCH_BCLK_DSIF	(CLK_AUD_BASE + 2)
#define	GATE_ABOX_QCH_BCLK0	(CLK_AUD_BASE + 3)
#define	GATE_ABOX_QCH_BCLK1	(CLK_AUD_BASE + 4)
#define	GATE_ABOX_QCH_BCLK2	(CLK_AUD_BASE + 5)
#define	GATE_ABOX_QCH_BCLK3	(CLK_AUD_BASE + 6)
#define	GATE_ABOX_QCH_BCLK4	(CLK_AUD_BASE + 7)
#define	GATE_ABOX_QCH_BCLK5	(CLK_AUD_BASE + 8)
#define	GATE_ABOX_QCH_BCLK6	(CLK_AUD_BASE + 9)

#define	MOUT_CLK_AUD_UAIF6	(CLK_AUD_BASE + 12)
#define	MOUT_CLK_AUD_UAIF0	(CLK_AUD_BASE + 13)
#define	MOUT_CLK_AUD_UAIF1	(CLK_AUD_BASE + 14)
#define	MOUT_CLK_AUD_UAIF2	(CLK_AUD_BASE + 15)
#define	MOUT_CLK_AUD_UAIF3	(CLK_AUD_BASE + 16)
#define	MOUT_CLK_AUD_UAIF4	(CLK_AUD_BASE + 17)
#define	MOUT_CLK_AUD_UAIF5	(CLK_AUD_BASE + 18)
#define	UMUX_CP_PCMC_CLK	(CLK_AUD_BASE + 19)

#define	DOUT_DIV_CLK_AUD_DSIF	(CLK_AUD_BASE + 21)
#define	DOUT_DIV_CLK_AUD_UAIF0	(CLK_AUD_BASE + 22)
#define	DOUT_DIV_CLK_AUD_UAIF1	(CLK_AUD_BASE + 23)
#define	DOUT_DIV_CLK_AUD_UAIF2	(CLK_AUD_BASE + 24)
#define	DOUT_DIV_CLK_AUD_UAIF3	(CLK_AUD_BASE + 25)
#define	DOUT_DIV_CLK_AUD_USB_NOC	(CLK_AUD_BASE + 26)
#define	DOUT_DIV_CLK_AUD_UAIF4	(CLK_AUD_BASE + 28)
#define	DOUT_DIV_CLK_AUD_UAIF5	(CLK_AUD_BASE + 29)
#define	DOUT_DIV_CLK_AUD_UAIF6	(CLK_AUD_BASE + 30)

#define	MOUT_CLK_AUD_CPU_PLL	(CLK_AUD_BASE + 31)
#define	MOUT_CLK_AUD_PCMC	(CLK_AUD_BASE + 32)
#define	DOUT_DIV_CLK_AUD_NOCD	(CLK_AUD_BASE + 33)
#define	DOUT_DIV_CLK_AUD_CNT	(CLK_AUD_BASE + 34)
#define	DOUT_DIV_CLK_AUD_AUDIF	(CLK_AUD_BASE + 35)
#define	DOUT_DIV_CLK_AUD_FM	(CLK_AUD_BASE + 36)
#define	DOUT_CLK_AUD_PCMC	(CLK_AUD_BASE + 37)

/* hsi */
#define	CLK_UFS_BASE	(300)
#define	GATE_UFS_EMBD_QCH	(CLK_UFS_BASE + 0)
#define	GATE_UFS_EMBD_QCH_FMP	(CLK_UFS_BASE + 1)

/* peri */
#define CLK_PERI_BASE	(400)
#define GATE_USI00_I2C_QCH	(CLK_PERI_BASE + 0)
#define GATE_USI01_I2C_QCH	(CLK_PERI_BASE + 1)
#define GATE_USI02_I2C_QCH	(CLK_PERI_BASE + 2)
#define GATE_USI03_I2C_QCH	(CLK_PERI_BASE + 3)
#define GATE_USI04_I2C_QCH	(CLK_PERI_BASE + 4)
#define GATE_USI05_I2C_QCH	(CLK_PERI_BASE + 5)
#define GATE_USI07_I2C_QCH	(CLK_PERI_BASE + 6)
#define GATE_USI06_I2C_QCH	(CLK_PERI_BASE + 7)
#define GATE_USI01_USI_QCH	(CLK_PERI_BASE + 8)
#define GATE_USI02_USI_QCH	(CLK_PERI_BASE + 9)
#define GATE_USI03_USI_QCH	(CLK_PERI_BASE + 10)
#define GATE_USI04_USI_QCH	(CLK_PERI_BASE + 11)
#define GATE_USI05_USI_QCH	(CLK_PERI_BASE + 12)
#define GATE_USI06_USI_QCH	(CLK_PERI_BASE + 13)
#define UMUX_CLKCMU_PERI_MMC_CARD_USER	(CLK_PERI_BASE + 14)
#define UMUX_CLK_PERI_UART_DBG	(CLK_PERI_BASE + 15)
#define DOUT_DIV_CLK_PERI_UART_DBG	(CLK_PERI_BASE + 16)
#define DOUT_DIV_CLK_PERI_USI_I2C	(CLK_PERI_BASE + 17)
#define DOUT_DIV_CLK_PERI_USI06_USI	(CLK_PERI_BASE + 18)
#define DOUT_DIV_CLK_PERI_USI05_USI	(CLK_PERI_BASE + 19)
#define DOUT_DIV_CLK_PERI_USI04_USI	(CLK_PERI_BASE + 20)
#define DOUT_DIV_CLK_PERI_USI03_USI	(CLK_PERI_BASE + 21)
#define DOUT_DIV_CLK_PERI_USI02_USI	(CLK_PERI_BASE + 22)
#define DOUT_DIV_CLK_PERI_USI01_USI	(CLK_PERI_BASE + 23)
#define DOUT_DIV_CLK_PERI_USI00_USI	(CLK_PERI_BASE + 24)
#define GATE_WDT0_QCH	(CLK_PERI_BASE + 25)
#define GATE_WDT1_QCH	(CLK_PERI_BASE + 26)
#define GATE_PWM_QCH	(CLK_PERI_BASE + 27)
#define GATE_USI00_USI_QCH	(CLK_PERI_BASE + 28)
#define GATE_UART_DBG_QCH	(CLK_PERI_BASE + 29)
#define GATE_MMC_CARD_QCH	(CLK_PERI_BASE + 30)

/* rgbp */
#define	CLK_RGBP_BASE	(500)
#define GATE_MCFP_QCH	(CLK_RGBP_BASE + 0)

/* usb */
#define	CLK_USB_BASE	(600)

/* yuvp */
#define	CLK_YUVP_BASE	(700)
#define GATE_YUVP_QCH	(CLK_YUVP_BASE + 0)
#define GATE_MCSC_QCH	(CLK_YUVP_BASE + 1)

/* csis */
#define	CLK_CSIS_BASE	(800)
#define GATE_MIPI_DCPHY_LINK_WRAP_QCH_CSIS0	(CLK_CSIS_BASE + 0)
#define GATE_MIPI_DCPHY_LINK_WRAP_QCH_CSIS1	(CLK_CSIS_BASE + 1)
#define GATE_MIPI_DCPHY_LINK_WRAP_QCH_CSIS2	(CLK_CSIS_BASE + 2)
#define GATE_MIPI_DCPHY_LINK_WRAP_QCH_CSIS3	(CLK_CSIS_BASE + 3)
#define GATE_CSIS_PDP_QCH_DMA			(CLK_CSIS_BASE + 4)
#define GATE_CSIS_PDP_QCH_PDP_TOP		(CLK_CSIS_BASE + 5)
#define GATE_LH_AST_MI_OTF0_CSISCSTAT_QCH	(CLK_CSIS_BASE + 6)
#define GATE_LH_AST_MI_OTF1_CSISCSTAT_QCH	(CLK_CSIS_BASE + 7)

/* m2m */
#define	CLK_M2M_BASE	(900)
#define GATE_M2M_QCH	(CLK_M2M_BASE + 0)
#define GATE_LME_QCH	(CLK_M2M_BASE + 1)
#define GATE_GDC_QCH	(CLK_M2M_BASE + 2)
#define GATE_VRA_QCH	(CLK_M2M_BASE + 3)

/* cmgp */
#define	CLK_CMGP_BASE	(1000)
#define	GATE_I2C_CMGP0_QCH	(CLK_CMGP_BASE + 1)
#define	GATE_I2C_CMGP1_QCH	(CLK_CMGP_BASE + 2)
#define	GATE_I2C_CMGP2_QCH	(CLK_CMGP_BASE + 3)
#define	GATE_I2C_CMGP3_QCH	(CLK_CMGP_BASE + 4)
#define	GATE_I2C_CMGP4_QCH	(CLK_CMGP_BASE + 5)

#define	GATE_USI_CMGP0_QCH	(CLK_CMGP_BASE + 8)
#define	GATE_USI_CMGP1_QCH	(CLK_CMGP_BASE + 9)
#define	GATE_USI_CMGP2_QCH	(CLK_CMGP_BASE + 10)
#define	GATE_USI_CMGP3_QCH	(CLK_CMGP_BASE + 11)
#define	GATE_USI_CMGP4_QCH	(CLK_CMGP_BASE + 12)

#define	DOUT_DIV_CLK_CMGP_USI04_USI	(CLK_CMGP_BASE + 15)
#define	DOUT_DIV_CLK_CMGP_USI01_USI	(CLK_CMGP_BASE + 16)
#define	DOUT_DIV_CLK_CMGP_USI00_USI	(CLK_CMGP_BASE + 17)
#define	DOUT_DIV_CLK_CMGP_USI02_USI	(CLK_CMGP_BASE + 18)
#define	DOUT_DIV_CLK_CMGP_USI03_USI	(CLK_CMGP_BASE + 19)

#define	DOUT_DIV_CLK_CMGP_USI_I2C	(CLK_CMGP_BASE + 22)
#define	DOUT_DIV_CLK_CMGP_USI_I3C	(CLK_CMGP_BASE + 23)

/* cpucl0_glb */
#define	CLK_CPUCL0_GLB_BASE	(1100)
#define MOUT_CLKCMU_CPUCL0_DBG_NOC_USER (CLK_CPUCL0_GLB_BASE + 0)

/* mif */
#define	CLK_MIF_BASE	(1200)
#define MUX_MIF_DDRPHY2X_MIF0		(CLK_MIF_BASE + 0)
#define MUX_MIF_DDRPHY2X_MIF1		(CLK_MIF_BASE + 1)

/* nocl1a */
#define	CLK_NOCL1A_BASE	(1300)
#define GATE_PDMA_NOCL1A_QCH		(CLK_NOCL1A_BASE + 0)

/* mfc */
#define	CLK_MFC_BASE	(1400)
#define	UMUX_CLKCMU_MFC_NOC 		(CLK_MFC_BASE + 0)

/* clkout */
#define	CLK_CLKOUT_BASE	(2700)
#define	OSC_AUD	(CLK_CLKOUT_BASE + 0)

/* icpu */
#define CLK_ICPU_BASE    (2800)
#define GATE_ICPU_QCH_CPU0		(CLK_ICPU_BASE + 0)
#define GATE_ICPU_QCH_PERI		(CLK_ICPU_BASE + 1)
/* must be greater than maximal clock id */
#define	CLK_NR_CLKS	(2900 + 1)

#define ACPM_DVFS_MIF				(0x0B040000)
#define ACPM_DVFS_INT				(0x0B040001)
#define ACPM_DVFS_CPUCL0			(0x0B040002)
#define ACPM_DVFS_CPUCL1			(0x0B040003)
#define ACPM_DVFS_DSU				(0x0B040004)
#define ACPM_DVFS_M2M				(0x0B040005)
#define ACPM_DVFS_DISP				(0x0B040006)
#define ACPM_DVFS_AUD				(0x0B040007)
#define ACPM_DVFS_G3D				(0x0B040008)
#define ACPM_DVFS_CP_CPU			(0x0B040009)
#define ACPM_DVFS_CP				(0x0B04000A)
#define ACPM_DVFS_GNSS				(0x0B04000B)
#define ACPM_DVFS_CP_MCW			(0x0B04000C)
#define ACPM_DVFS_CAM				(0x0B04000D)
#define ACPM_DVFS_CSIS				(0x0B04000E)
#define ACPM_DVFS_ISP				(0x0B04000F)
#define ACPM_DVFS_MFC				(0x0B040010)
#define ACPM_DVFS_WLBT				(0x0B040011)

#define EWF_CMU_ALIVE		(0)
#define EWF_CMU_AUD		(1)
#define EWF_CMU_NOCL1A		(2)
#define EWF_CMU_NOCL1B		(3)
#define EWF_CMU_NOCL1C		(4)
#define EWF_CMU_BRP		(5)
#define EWF_CMU_CHUB		(6)
#define EWF_CMU_CMGP		(7)
#define EWF_CMU_NOCL0		(8)
#define EWF_CMU_CPUCL0_GLB		(9)
#define EWF_CMU_CPUCL0		(10)
#define EWF_CMU_CPUCL1		(11)
#define EWF_CMU_CPUCL2		(12)
#define EWF_CMU_CSIS		(13)
#define EWF_CMU_CSTAT		(14)
#define EWF_CMU_DPUB		(16)
#define EWF_CMU_DPUF		(17)
#define EWF_CMU_DSU		(19)
#define EWF_CMU_G3D		(20)
#define EWF_CMU_G3DCORE		(21)
#define EWF_CMU_GNPU0		(22)
#define EWF_CMU_GNPU1		(23)
#define EWF_CMU_HSI0		(24)
#define EWF_CMU_HSI1		(25)
#define EWF_CMU_LME		(26)
#define EWF_CMU_M2M		(27)
#define EWF_CMU_MCSC		(29)
#define EWF_CMU_MFC0		(30)
#define EWF_CMU_MFC1		(31)
#define EWF_CMU_MIF0		(31 + 0)
#define EWF_CMU_MIF1		(31 + 1)
#define EWF_CMU_MIF2		(31 + 2)
#define EWF_CMU_MIF3		(31 + 3)
#define EWF_CMU_PERIC0		(31 + 4)
#define EWF_CMU_PERIC1		(31 + 5)
#define EWF_CMU_PERIC2		(31 + 6)
#define EWF_CMU_PERIS		(31 + 7)
#define EWF_CMU_SDMA		(31 + 9)
#define EWF_CMU_SSP		(31 + 10)
#define EWF_CMU_STRONG		(31 + 11)
#define EWF_CMU_DNC		(31 + 12)
#define EWF_CMU_DSP0		(31 + 13)
#define EWF_CMU_VTS		(31 + 16)
#define EWF_CMU_YUVP		(31 + 17)
#define EWF_CMU_TOP		(31 + 18)
#define EWF_CMU_DBGCORE		(31 + 19)
#define EWF_CMU_UFD		(31 + 20)
#define EWF_CMU_UFS		(31 + 23)
#define EWF_CMU_CHUBVTS		(31 + 24)
#define EWF_CMU_ALLCSIS		(31 + 25)
#define EWF_GRP_CAM		(31 + 26)

#endif	/* _DT_BINDINGS_CLOCK_EXYNOS_9925_H */
