subdir-ccflags-y := -Wformat
obj-$(CONFIG_MFD_MAX77705)	+= mfd_max77705.o
mfd_max77705-y	:= max77705.o max77705-irq.o

subdir-ccflags-y := -Wformat
obj-$(CONFIG_MFD_MAX77775)	+= mfd_max77775.o
mfd_max77775-y	:= max77775.o max77775-irq.o
