# Copyright (C) 2021 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

VENDOR_EARLY_MODULE_LIST = [
    "drivers/soc/samsung/exynos/exynos-hyp/exynos-hypervisor.ko",
    "drivers/soc/samsung/exynos/exynos-chipid_v2.ko",
    "drivers/power/reset/exynos/exynos-reboot.ko",
    "drivers/clk/samsung/clk_exynos.ko",
    "drivers/watchdog/s3c2410_wdt.ko",
    "drivers/clocksource/exynos_mct_v3.ko",
    "drivers/samsung/debug/sec_debug_base_early.ko",
    "drivers/samsung/debug/sec_debug_mode.ko",
]

VENDOR_MODULE_LIST = [
    # No need to sort, but should not be duplicated
    "drivers/i2c/i2c-dev.ko",
    "drivers/soc/samsung/exynos/exynos-sdm.ko",
    "drivers/tty/serial/exynos_tty.ko",
    "drivers/mfd/samsung/pmic/s2mpa05_mfd.ko",
    "drivers/soc/samsung/exynos/sysevent.ko",
    "drivers/regulator/samsung/pmic/s2mps27_regulator.ko",
    "drivers/regulator/samsung/pmic/s2mpb02-regulator.ko",
    "drivers/soc/samsung/exynos-pd/exynos-pd_el3.ko",
    "drivers/soc/samsung/acpm/plugin_dbg.ko",
    "drivers/dma-buf/heaps/samsung/dma-buf-container.ko",
    "drivers/soc/samsung/exynos-pd/exynos-pd-dbg.ko",
    "drivers/gpu/drm/display/drm_display_helper.ko",
    "drivers/soc/samsung/exynos/debug/hardlockup-watchdog.ko",
    "drivers/soc/samsung/cal-if/cmupmucal.ko",
    "drivers/rtc/samsung/pmic/s2mps27_rtc.ko",
    "drivers/soc/samsung/exynos/sysevent_notif.ko",
    "drivers/soc/samsung/exynos/debug/dss.ko",
    "drivers/input/keyboard/samsung/pmic/s2mps27_key.ko",
    "drivers/i2c/busses/acpm-mfd-bus.ko",
    "drivers/soc/samsung/exynos/debug/exynos-itmon-v2.ko",
    "drivers/soc/samsung/exynos/debug/debug-snapshot-debug-kinfo.ko",
    "drivers/mfd/samsung/pmic/s2mpb02_mfd.ko",
    "drivers/iommu/samsung/samsung-secure-iova.ko",
    "drivers/gpu/drm/samsung/gpu/sgpu/sgpu.ko",
    "drivers/gpu/drm/samsung/dpu/exynos-drm.ko",
    "drivers/pinctrl/samsung/pmic/s2mpm07_pinctrl_9945.ko",
    "drivers/soc/samsung/exynos-cpupm.ko",
    "drivers/mfd/samsung/pmic/s2mps28_mfd.ko",
    "drivers/soc/samsung/exynos/debug/exynos-getcpustate.ko",
    "drivers/ufs/host/ufs-exynos-core.ko",
    "drivers/i2c/busses/i2c-exynos5.ko",
    "drivers/iommu/samsung/samsung_iommu_v9.ko",
    "drivers/phy/samsung/phy-exynos-mipi-dsim.ko",
    "drivers/iio/adc/samsung/pmic/s2mps27_adc.ko",
    "drivers/soc/samsung/exynos/debug/exynos-coresight.ko",
    "drivers/hwmon/hwmon.ko",
    "drivers/soc/samsung/exynos/memlogger.ko",
    "drivers/spi/spi-s3c64xx.ko",
    "drivers/dma-buf/heaps/samsung/samsung_dma_heap.ko",
    "drivers/regulator/samsung/pmic/s2mpb03.ko",
    "drivers/iommu/samsung/samsung-iommu-group-v9.ko",
    "drivers/soc/samsung/acpm/exynos_acpm.ko",
    "drivers/regulator/samsung/pmic/s2mps28_regulator.ko",
    "drivers/regulator/samsung/pmic/s2mpm07_regulator_9945.ko",
    "drivers/pinctrl/samsung/pmic/s2mps28_pinctrl.ko",
    "drivers/soc/samsung/exynos-pm/exynos-pm.ko",
    "drivers/soc/samsung/exynos/debug/exynos-ecc-handler.ko",
    "drivers/regulator/samsung/pmic/s2mpa05_regulator_9945.ko",
    "drivers/mfd/samsung/pmic/s2mpm07_mfd.ko",
    "drivers/gpu/drm/drm_ttm_helper.ko",
    "drivers/soc/samsung/exynos-pmu-if.ko",
    "drivers/mfd/samsung/pmic/s2mps27_mfd.ko",
    "drivers/pinctrl/samsung/pmic/s2mpa05_pinctrl_9945.ko",
    "drivers/soc/samsung/exynos-pd/exynos-pd.ko",
    "drivers/gpu/drm/scheduler/gpu-sched.ko",
    "drivers/pinctrl/samsung/pinctrl-samsung-core.ko",
    "drivers/soc/samsung/exynos/debug/exynos-ssld.ko",
    "drivers/dma/samsung/samsung-pdma.ko",
    "drivers/spi/spidev.ko",
    "drivers/phy/samsung/phy-exynos-usbdrd-super.ko",
    "drivers/usb/dwc3/dwc3-exynos-usb.ko",
    "drivers/i3c/master/exynos/i3c-hci-exynos.ko",
    "drivers/usb/gadget/function/usb_f_dm1.ko",
    "drivers/usb/host/xhci-exynos.ko",
    "drivers/usb/host/xhci-exynos-audio.ko",
    "drivers/usb/gadget/function/usb_f_dm.ko",
    "sound/usb/exynos-usb-audio-offloading.ko",
    "drivers/phy/samsung/exynos-phycal-if.ko",
    "drivers/pci/controller/dwc/pcie-exynos-rc-core.ko",
    "drivers/pci/controller/dwc/pcie-exynos-phycal.ko",
    "drivers/iommu/exynos-pcie-iommu.ko",
    "drivers/soc/samsung/pm_qos/exynos_pm_qos.ko",
    "drivers/soc/samsung/ect_parser/ect_parser.ko",
    "drivers/devfreq/exynos/exynos_devfreq.ko",
    "drivers/soc/samsung/dm/exynos-esca-dm.ko",
    "drivers/soc/samsung/exynos-wow.ko",
    "drivers/soc/samsung/exynos/exynos-seclog.ko",
    "sound/soc/samsung/exynos/sec_audio_sysfs.ko",
    "sound/soc/samsung/exynos/sec_audio_debug.ko",
    "sound/soc/samsung/snd-soc-s3c-dma.ko",
    "sound/soc/samsung/exynos/abox/snd-soc-samsung-abox-gic.ko",
    "sound/soc/samsung/exynos/abox/snd-soc-samsung-abox.ko",
    "sound/soc/samsung/exynos/snd-soc-dp_dma.ko",
    "drivers/soc/samsung/exynos/exynos-seh.ko",
    "drivers/pwm/pwm-samsung.ko",
    "drivers/bts/exynos-btsops9945.ko",
    "drivers/char/hw_random/exyswd-rng.ko",
    "drivers/bts/exynos-bts.ko",
    "drivers/media/platform/exynos/camera/fimc-is.ko",
    "sound/soc/samsung/exynos/slif/snd-soc-samsung-slif.ko",
    "drivers/soc/samsung/gnssif/gnss_mbox.ko",
    "drivers/cpufreq/exynos-cpufreq.ko",
    "drivers/cpufreq/freq-qos-tracer.ko",
    "drivers/soc/samsung/exynos_sci.ko",
    "drivers/soc/samsung/cpif/cpif_page.ko",
    "drivers/soc/samsung/exynos-icm.ko",
    "drivers/phy/samsung/phy-exynos-mipi.ko",
    "drivers/media/platform/exynos/smfc/smfc.ko",
    "drivers/iommu/exynos-cpif-iommu_v9.ko",
    "drivers/soc/samsung/cpif/cpif_memlogger.ko",
    "drivers/soc/samsung/exynos/exynos-tzasc.ko",
    "drivers/media/platform/exynos/camera/lib/votf/votf.ko",
    "drivers/soc/samsung/cpif/direct_dm.ko",
    "drivers/soc/samsung/cpif/mcu_ipc.ko",
    "drivers/media/platform/exynos/camera/testing/self/pablo-self-tests.ko",
    "sound/soc/samsung/exynos/vts/snd-soc-samsung-vts-mailbox.ko",
    "drivers/soc/samsung/exynos-sci_dbg.ko",
    "drivers/soc/samsung/cpif/shm_ipc.ko",
    "kernel/sched/ems/ems.ko",
    "kernel/sched/exynos_mpam_policy.ko",
    "drivers/soc/samsung/mpam/mpam_arch.ko",
    "drivers/media/platform/exynos/camera/lib/pablo-libs.ko",
    "drivers/soc/samsung/cpif/hook.ko",
    "drivers/soc/samsung/cpif/cpif.ko",
    "drivers/media/platform/exynos/camera/pablo-smc.ko",
    "drivers/vision/npu.ko",
    "drivers/media/platform/exynos/camera/hardware/pablo-hws.ko",
    "drivers/soc/samsung/gnssif/gnssif.ko",
    "drivers/media/platform/exynos/scaler/scaler.ko",
    "sound/soc/samsung/exynos/vts/snd-soc-samsung-vts.ko",
    "drivers/media/platform/exynos/camera/icpu/pablo-icpu.ko",
    "drivers/cpufreq/exynos-dsufreq.ko",
    "drivers/media/platform/exynos/mfc/exynos_mfc.ko",
    "drivers/media/platform/exynos/repeater/repeater.ko",
    "drivers/thermal/samsung/exynos_thermal_v2.ko",
    "drivers/media/platform/exynos/tsmux/tsmux.ko",
    "drivers/soc/samsung/exynos-cpuhp.ko",
    "drivers/soc/samsung/exynos-ssp.ko",
    "drivers/soc/samsung/exynos-bcm.ko",
    "drivers/soc/samsung/exynos/exynos-s2mpu.ko",
    "drivers/soc/samsung/exynos/exynos-el2.ko",
    "drivers/soc/samsung/xperf/xperf.ko",
    "drivers/staging/nanohub/nanohub.ko",
    "drivers/soc/samsung/exynos/imgloader.ko",
    "drivers/soc/samsung/exynos-afm.ko",
    "drivers/irqchip/exynos/irq-gic-v3-vh.ko",
    "drivers/soc/samsung/exynos-ufcc.ko",
    "drivers/soc/samsung/exynos-pm/exynos-s2i.ko",
    "drivers/soc/samsung/exynos/exynos-mcinfo.ko",
    "drivers/thermal/samsung/gpu_cooling.ko",
    "drivers/soc/samsung/acpm/flexpmu_dbg.ko",
    "drivers/thermal/samsung/exynos_amb_control.ko",
#   "drivers/misc/samsung/scsc/scsc_platform_mif.ko",
#    "drivers/misc/samsung/scsc/scsc_mx.ko",
#    "drivers/net/wireless/scsc/scsc_wifilogger.ko",
#    "drivers/misc/samsung/scsc/scsc_mmap.ko",
#    "drivers/misc/samsung/scsc/scsc_flash_service.ko",
    "drivers/soc/samsung/exynos/debug/exynos-adv-tracer.ko",
#    "drivers/misc/samsung/scsc/mx_client_test.ko",
    "drivers/soc/samsung/exynos/debug/exynos-adv-tracer-s2d.ko",
#    "drivers/misc/samsung/scsc/scsc_log_collection.ko",
#    "drivers/misc/samsung/scsc/scsc_logring.ko",
#    "drivers/misc/samsung/slsi_bt/scsc_bt.ko",
    "drivers/soc/samsung/profiler/include/exynos-profiler-fn.ko",
    "drivers/soc/samsung/profiler/v1/exynos-main-profiler.ko",
    "drivers/soc/samsung/profiler/v1/exynos-cpu-profiler.ko",
    "drivers/soc/samsung/profiler/v1/exynos-gpu-profiler.ko",
    "drivers/soc/samsung/profiler/v1/exynos-mif-profiler.ko",
#    "drivers/gud/gud-s5e9945/TlcTui/t-base-tui.ko",
    "drivers/media/platform/exynos/camera/post/gdc/gdc.ko",
    "drivers/soc/samsung/exynos/debug/ehld.ko",
    "drivers/scsi/scsi_srpmb.ko",
    "drivers/soc/samsung/exynos/secmem.ko",
    "drivers/soc/samsung/exynos/exynos-hdcp/hdcp2.ko",
    "drivers/soc/samsung/exynos/exynos-usi_v2.ko",
    "drivers/soc/samsung/hts/hts.ko",
    "drivers/soc/samsung/mhdvfs.ko",
    "drivers/samsung/pm/sec_pm_debug.ko",
    "drivers/samsung/pm/sec_thermistor.ko",
    "drivers/samsung/pm/sec_pm_smpl_warn.ko",
    "drivers/usb/gadget/function/usb_f_conn_gadget.ko",
    "drivers/usb/gadget/function/usb_f_ss_mon_gadget.ko",
    "drivers/bluetooth/btpower.ko",
    "net/qrtr/qrtr.ko",
    "net/qrtr/qrtr-mhi.ko",
    "drivers/bus/mhi/host/mhi.ko",
    "drivers/soc/qcom/qmi_helpers.ko",
    "drivers/net/wireless/cnss2/cnss2.ko",
    "drivers/net/wireless/cnss_utils/cnss_utils.ko",
    "drivers/net/wireless/cnss_prealloc/cnss_prealloc.ko",
    "drivers/net/wireless/cnss_utils/wlan_firmware_service.ko",
    "drivers/net/wireless/cnss_genl/cnss_nl.ko",
    "drivers/net/wireless/cnss_utils/cnss_plat_ipc_qmi_svc.ko",
    "kernel/trace/qcom_ipc_logging.ko",	
    "drivers/misc/tzdev/tzdev.ko",
    "drivers/misc/tui/tuihw.ko",
    "drivers/misc/tui/tuihw-inf.ko",
    "block/blk-sec-common.ko",
    "block/blk-sec-stats.ko",
    "block/blk-sec-wb.ko",
    "block/ssg.ko",
    "drivers/media/platform/exynos/jsqz/jsqz.ko",
    "drivers/media/platform/exynos/mcfrc/mcfrc.ko",
    "drivers/samsung/sec_class.ko",
    "drivers/samsung/sec_bootstat.ko",
    "drivers/samsung/sec_crash_key_user.ko",
    "drivers/samsung/sec_crash_key.ko",
    "drivers/samsung/sec_hard_reset_hook.ko",
    "drivers/samsung/sec_key_notifier.ko",
]

VENDOR_DEV_MODULE_LIST = [
    # modules only for debug/developments.
    "drivers/soc/samsung/exynos/debug/exynos-debug-test.ko",
    "drivers/pinctrl/samsung/secgpio_dvs.ko",
]


VENDOR_DLKM_MODULE_LIST = [
    # For vendor_dlkm in order
    #"drivers/net/wireless/scsc/scsc_wlan.ko",
    "net/wireless/cfg80211.ko",
    "drivers/net/wireless/qualcomm/kiwi_v2/qcacld-3.0/kiwi_v2.ko",
    "drivers/samsung/debug/sec_debug_ssld_info.ko"
]

FACTORY_BUILD_MODULE_LIST = [
    "drivers/samsung/sec_reloc_gpio.ko",
    "drivers/cpufreq/mesh_governor.ko",
]
