# SPDX-License-Identifier: GPL-2.0
#
# Makefile for multifunction miscellaneous devices for samsung pmic
#

obj-$(CONFIG_MFD_S2MU106)		+= s2mu106_mfd.o
s2mu106_mfd-$(CONFIG_MFD_S2MU106)	+= s2mu106_core.o s2mu106_irq.o

obj-$(CONFIG_MFD_S2MF301)		+= s2mf301_mfd.o
s2mf301_mfd-$(CONFIG_MFD_S2MF301)	+= s2mf301_core.o s2mf301_irq.o
