obj-$(CONFIG_SEC_QC_USER_RESET)		+= sec_qc_user_reset.o
sec_qc_user_reset-objs			:= sec_qc_user_reset_main.o \
					   sec_qc_ap_health.o \
					   sec_qc_reset_rwc.o \
					   sec_qc_reset_reason.o \
					   sec_qc_reset_summary.o \
					   sec_qc_reset_klog.o \
					   sec_qc_reset_tzlog.o \
					   sec_qc_auto_comment.o \
					   sec_qc_reset_history.o \
					   sec_qc_fmm_lock.o \
					   sec_qc_recovery_cause.o \
					   sec_qc_kryo_arm64_edac.o \
					   sec_qc_store_lastkmsg.o \
					   sec_qc_modem_reset_data.o
