# SPDX-License-Identifier: GPL-2.0
dtbo-$(CONFIG_ARCH_EXYNOS) += \
        s5e9925-erd9925.dtbo     \
        s5e9925_evt0-erd9925.dtbo \
        s5e9925-erd9925_r13.dtbo \
        s5e9925_evt0-erd9925_r11.dtbo \
        s5e9925_evt0_s5300-erd9925.dtbo \
        s5e9925_evt0_s5300-erd9925_r11.dtbo \
	s5e8825-erd8825.dtbo     \
	s5e8825-erd8825_r10.dtbo \
	s5e8825-erd8825_r11.dtbo

always-y	:= $(dtb-y) $(dtbo-y)
clean-files	:= *.dtb *.dtbo
