#
# Makefile for grip sensors
#

obj-$(CONFIG_SENSORS_SX9360)  		+= sx9360.o
obj-$(CONFIG_SENSORS_SX9360_SUB)	+= sx9360_sub.o
obj-$(CONFIG_SENSORS_SX9364)		+= sx9360.o
obj-$(CONFIG_SENSORS_SX9364_SUB)	+= sx9360_sub.o

