# SPDX-License-Identifier: GPL-2.0

ccflags-$(CONFIG_TCPC_CLASS) += -I$(srctree)/drivers/misc/mediatek/typec/tcpc/inc
ccflags-$(CONFIG_MTK_USB_TYPEC_U3_MUX) += -I$(srctree)/drivers/misc/mediatek/typec/switch

obj-$(CONFIG_EXTCON_MTK_USB) += extcon-mtk-usb.o
