#
# Makefile for the input core drivers.
#
# Each configuration option enables a list of files.
#obj-$(CONFIG_FINGERPRINT_FPC1020)  += fpc1020.o

obj-$(CONFIG_FINGERPRINT_FPC1020) := fpc1020_main.o fpc1020_common.o fpc1020_input.o fpc1020_capture.o fpc1020_regulator.o
#obj-y := fpc1020_main.o fpc1020_common.o fpc1020_input.o fpc1020_capture.o fpc1020_regulator.o
# called from kernel build system: just declare what our modules are



