
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-client_test.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-cpacket_buffer.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-fw_obj_index.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-fw_panic_record.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-gdb_transport.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-mifintrbit.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-mifmboxman.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-mifpmuman.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-mifproc.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-mifqos.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-miframman.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-mx_mmap.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-mifstream.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-mx140_file.o
obj-$(CONFIG_WLBT_KUNIT) 	+= kunit-test-mxfwconfig.o
obj-$(CONFIG_WLBT_KUNIT) 	+= kunit-test-mxlog.o
obj-$(CONFIG_WLBT_KUNIT) 	+= kunit-test-mxlogger_split.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-mxlog_transport.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-mxman_res.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-mxman_if.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-mxman_split.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-mxmgmt_transport.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-mxproc.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-mxsyserr.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-panicmon.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-platform_mif_module.o
ifeq ($(CONFIG_SOC_S5E8825),y)
#obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-platform_mif_s5e8825.o
endif
ifeq ($(CONFIG_SOC_S5E8535),y)
#obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-platform_mif_s5e8535.o
endif
ifeq ($(CONFIG_WLBT_REFACTORY),y)
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-platform_mif.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-s5e8845_legacy.o
endif
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-scsc_lerna.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-scsc_log_collector.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-scsc_log_collector_mmap.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-scsc_log_collector_proc.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-scsc_log_in_dram.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-scsc_logring_debugfs.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-scsc_logring_main.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-scsc_logring_ring.o
obj-$(CONFIG_WLBT_KUNIT) 	+= kunit-test-scsc_service.o
obj-$(CONFIG_WLBT_KUNIT) 	+= kunit-test-scsc_wlbtd.o
obj-$(CONFIG_WLBT_KUNIT) 	+= kunit-test-scsc_mx_impl.o
obj-$(CONFIG_WLBT_KUNIT) 	+= kunit-test-scsc_mx_module.o
obj-$(CONFIG_WLBT_KUNIT) 	+= kunit-test-whdr.o
obj-$(CONFIG_WLBT_KUNIT) 	+= kunit-test-suspendmon.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-bhdr.o
obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-pmu_cal.o
obj-$(CONFIG_WLBT_KUNIT)	+= common.o

#obj-$(CONFIG_WLBT_KUNIT)	+= kunit-test-sample_code.o
