dtbo-y += q4q_eur_openx_w00_r14.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
q4q_eur_openx_w00_r14.dtbo-base := ../../../vendor/qcom/cape.dtb # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
dtbo-y += q4q_eur_openx_w00_r13.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
q4q_eur_openx_w00_r13.dtbo-base := ../../../vendor/qcom/cape.dtb # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
dtbo-y += q4q_eur_openx_w00_r12.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
q4q_eur_openx_w00_r12.dtbo-base := ../../../vendor/qcom/cape.dtb # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
dtbo-y += q4q_eur_openx_w00_r11.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
q4q_eur_openx_w00_r11.dtbo-base := ../../../vendor/qcom/cape.dtb # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
dtbo-y += q4q_eur_openx_w00_r10.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
q4q_eur_openx_w00_r10.dtbo-base := ../../../vendor/qcom/cape.dtb # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
dtbo-y += q4q_eur_openx_w00_r09.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
q4q_eur_openx_w00_r09.dtbo-base := ../../../vendor/qcom/cape.dtb # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
dtbo-y += q4q_eur_openx_w00_r07.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
q4q_eur_openx_w00_r07.dtbo-base := ../../../vendor/qcom/cape.dtb # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
dtbo-y += q4q_eur_openx_w00_r04.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
q4q_eur_openx_w00_r04.dtbo-base := ../../../vendor/qcom/cape.dtb # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
dtbo-y += q4q_eur_openx_w00_r03.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
q4q_eur_openx_w00_r03.dtbo-base := ../../../vendor/qcom/cape.dtb # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
dtbo-y += q4q_eur_openx_w00_r02.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
q4q_eur_openx_w00_r02.dtbo-base := ../../../vendor/qcom/cape.dtb # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
dtbo-y += q4q_eur_openx_w00_r01.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
q4q_eur_openx_w00_r01.dtbo-base := ../../../vendor/qcom/waipio.dtb ../../../vendor/qcom/waipio-v2.dtb ../../../vendor/qcom/waipiop.dtb ../../../vendor/qcom/waipiop-v2.dtb # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
dtbo-y += q4q_eur_openx_w00_r00.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
q4q_eur_openx_w00_r00.dtbo-base := ../../../vendor/qcom/waipio.dtb ../../../vendor/qcom/waipio-v2.dtb ../../../vendor/qcom/waipiop.dtb ../../../vendor/qcom/waipiop-v2.dtb # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
# SPDX-License-Identifier: GPL-2.0

clean-files := *.dtb *.reverse.dts *.dtbo

