ccflags-y += -Idrivers/marvell/marvell-telephony/ppp/
ccflags-y += -Idrivers/marvell/marvell-telephony/cidatastub/

gs_modem-objs := \
	../ppp/chap.o \
	../ppp/ipcp.o \
	../ppp/lcp.o \
	../ppp/pap.o \
	../ppp/ppp.o \
	../ppp/ppp_log.o \
	../ppp/ppp_platform.o \
	modem_if.o
obj-m  += gs_modem.o
