#
# Makefile for nfc devices
#

obj-$(CONFIG_NFC_PN544)		+= pn544.o
obj-$(CONFIG_NFC_PN547)		+= pn547.o
obj-$(CONFIG_ST21NFCA)		+= st21nfca.o
obj-$(CONFIG_NFC_PN533)		+= pn533.o
obj-$(CONFIG_NFC_WILINK)	+= nfcwilink.o

ccflags-$(CONFIG_NFC_DEBUG) := -DDEBUG
