obj-$(CONFIG_SIPC)     += sipc.o smsg.o smem.o sbuf.o sblock.o sipc_debugfs.o

obj-$(CONFIG_SIPC_SPIPE)	+= spipe.o

obj-$(CONFIG_SIPC_SETH)	+= seth.o

obj-$(CONFIG_SIPC_SPOOL)	+= spool.o

obj-$(CONFIG_SIPC_STTY)	+= stty.o

obj-$(CONFIG_SIPC_SMSGC)   += smsgc.o

obj-$(CONFIG_SIPC_DUAL_SIM_PLUG) += dual_sim_plug.o

obj-$(CONFIG_ZERO_COPY_SIPX) += sipx.o
