# M55 code for SR-QN6887A-01-458|SR-QN6887A-01-460|SR-QN6887A-01-466 by lichang at 20230920 start
# M55 code for QN6887A-96 by zhangziyi at 20230925 start
ifeq ($(CONFIG_CUSTOM_FACTORY_BUILD),y)
obj-$(CONFIG_INPUT_SAR) += sensor_fac_node.o
endif
obj-$(CONFIG_INPUT_SAR) += sensor_user_node.o
obj-$(CONFIG_INPUT_SAR) += sensors_core.o
obj-$(CONFIG_SAR_SENSOR) += sx937x.o
# M55 code for QN6887A-96 by zhangziyi at 20230925 end
# M55 code for SR-QN6887A-01-458|SR-QN6887A-01-460|SR-QN6887A-01-466 by lichang at 20230920 end