# SPDX-License-Identifier: GPL-2.0
# Copyright (c) 2022 Samsung Electronics Inc.

ccflags-y += -I$(MTK_CUSTOM_PATH)/imgsensor/inc \

obj-y           += regulator/
obj-y           += gpio/
obj-y           += mclk/
obj-y           += imgsensor_cfg_table.o

