subdir-ccflags-y += -I$(srctree)/sound/soc/mediatek/common

snd-smartpa-aw883xx-objs += aw883xx.o \
							aw883xx_bin_parse.o \
							aw883xx_calib.o \
							aw883xx_device.o \
							aw883xx_init.o \
							aw883xx_monitor.o \
							aw883xx_spin.o \
							aw883xx_pid_2049_init.o \
							aw883xx_pid_2066_init.o \
							aw883xx_pid_2183_init.o


obj-$(CONFIG_SND_SMARTPA_AW883XX) += snd-smartpa-aw883xx.o
