obj-y += accelerometer_factory.o
obj-y += accelerometer_icm42605m_factory.o
obj-y += accelerometer_lis2dlc12_factory.o
obj-y += accelerometer_lsm6dsl_factory.o
obj-y += accelerometer_lsm6dsotr_factory.o
