# SPDX-License-Identifier: GPL-2.0-only

# DEBUG
obj-$(CONFIG_EXYNOS_DEBUG)		+= debug/

# Memlogger
obj-$(CONFIG_EXYNOS_MEMORY_LOGGER)	+= memlogger.o

# Subsystem
obj-$(CONFIG_EXYNOS_SYSTEM_EVENT)	+= sysevent.o sysevent_notif.o

# Image Loader
obj-$(CONFIG_EXYNOS_IMGLOADER)		+= imgloader.o

# Exynos EL2
obj-$(CONFIG_EXYNOS_EL2)		+= exynos-el2.o

# Exynos S2MPU
obj-$(CONFIG_EXYNOS_S2MPU)		+= exynos-s2mpu.o

# SDM
obj-$(CONFIG_EXYNOS_SDM)		+= exynos-sdm.o

# Exynos CryptoManager
obj-$(CONFIG_EXYNOS_CRYPTOMANAGER)	+= exynos-cm.o

# Exynos Chipid V2
obj-$(CONFIG_EXYNOS_CHIPID_V2)	+= exynos-chipid_v2.o

# Exynos TZASC
obj-$(CONFIG_EXYNOS_TZASC_FAIL_DETECTOR) += exynos-tzasc.o

# Exynos MCINFO
obj-$(CONFIG_EXYNOS_MCINFO)             += exynos-mcinfo.o

# secmem
obj-$(CONFIG_EXYNOS_CONTENT_PATH_PROTECTION) += secmem.o

# HDCP
obj-$(CONFIG_EXYNOS_HDCP2)		+= exynos-hdcp/

# Exynos USI V2
obj-$(CONFIG_EXYNOS_USI_V2)		+= exynos-usi_v2.o
