#
# Copyright (c) 2013 Samsung Electronics Co., Ltd.
#		http://www.samsung.com
#
# Licensed under GPLv2
#

obj-$(CONFIG_EXYNOS_MIPI_DSI) += dsim.o
dsim-y += dsim_drv.o dsim_reg_3475.o
obj-$(CONFIG_EXYNOS_DECON_EXYNOS3475) += decon.o
decon-y += decon_core.o decon-int_drv.o decon_helper.o decon_reg_3475.o decon_board.o
obj-y += panels/
