# SPDX-License-Identifier: GPL-2.0
#
# Makefile for IIO ADC drivers
#
# When adding new entries keep the list in alphabetical order

obj-$(CONFIG_S2MPS25_ADC) += s2mps25_adc.o
obj-$(CONFIG_S2MPS25_ADC_9935) += s2mps25_adc_9935.o
obj-$(CONFIG_S2MPU15_ADC_8535) += s2mpu15_adc_8535.o
obj-$(CONFIG_S2MPU15_ADC_8835) += s2mpu15_adc_8835.o
