# Makefile for the chipone touchscreen drivers.

obj-$(CONFIG_TOUCHSCREEN_CHIPONE_ICNL9958R) += icnl9951r.o

icnl9951r-y := cts_driver.o
icnl9951r-y += cts_core.o
icnl9951r-y += cts_sfctrlv2.o
icnl9951r-y += cts_spi_flash.o
icnl9951r-y += cts_firmware.o
icnl9951r-y += cts_test.o
icnl9951r-y += cts_charger_detect.o
icnl9951r-y += cts_earjack_detect.o
icnl9951r-y += cts_tcs.o
icnl9951r-y += cts_platform.o
icnl9951r-y += cts_tool.o
icnl9951r-y += cts_sysfs.o
icnl9951r-y += cts_strerror.o
icnl9951r-y += cts_oem.o