#
#  Makefile for the kernel Sensor device drivers.
#

#  Object files in subdirectories
obj-$(CONFIG_SENSORS)		+= sensors_core.o
obj-$(CONFIG_SENSORS_CM36686)		+= cm36686.o
obj-$(CONFIG_SENSORS_CM36672P)		+= cm36672p.o
obj-$(CONFIG_SENSORS_GP2A002)		+= gp2a002.o
obj-$(CONFIG_SENSORS_K2HH)		+= k2hh.o
obj-$(CONFIG_SENSORS_YAMAHA)		+= yas_mag_kernel.o
obj-$(CONFIG_SENSORS_YAS537)		+= yas_mag_drv-yas537.o
