#a06 code for SR-AL7160A-01-174  by suyurui at 2024/04/02 start
ifeq ($(HQ_FACTORY_BUILD),true)
#a06 code for SR-AL7160A-01-172  by suyurui at 2024/03/24 start
obj-$(CONFIG_CUSTOM_KERNEL_SAR_SENSOR) += sensor_fac_node.o
#a06 code for SR-AL7160A-01-172  by suyurui at 2024/03/24 end
endif
#a06 code for SR-AL7160A-01-175  by huofudong at 20240416 start
obj-$(CONFIG_CUSTOM_KERNEL_SAR_SENSOR) += sensor_user_node.o
obj-$(CONFIG_CUSTOM_KERNEL_SAR_SENSOR) += sensors_core.o
#a06 code for SR-AL7160A-01-175  by huofudong at 20240416 end
#a06 code for SR-AL7160A-01-174  by suyurui at 2024/04/02 end
obj-$(CONFIG_INPUT_SX933x)  += sx9338/
obj-$(CONFIG_INPUT_HX9031AS)  += hx9031as/
