# SPDX-License-Identifier: GPL-2.0

#zhangsen1

#obj-y += fsm_core.o fs1815.o fsm_i2c.o fsm_firmware.o fsm_i2c.o fsm_misc.o
ifeq ($(CONFIG_SND_SOC_FS1815N),y)

snd-soc-fs1815n-objs := \
				fs1815.o \
				fsm_core.o \
				fsm_firmware.o \
				fsm_i2c.o \
				fsm_misc.o


obj-y += snd-soc-fs1815n.o
endif
#zhangsen1
