# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_SKB_TRACER) += skb_tracer.o \
			    sock_queue_printer.o \
			    skb_queue_printer.o \
			    rb_queue_printer.o

skb_tracer-y := skb_tracer.o

obj-$(CONFIG_SKB_TRACER_TEST)	+= ./test/skb_tracer-test.o
