obj-$(CONFIG_SEC_QC_SMEM)		+= sec_qc_smem.o
sec_qc_smem-objs			:= sec_qc_smem_main.o \
					   sec_qc_smem_id_vendor1.o \
					   sec_qc_smem_id_vendor1_v5.o \
					   sec_qc_smem_id_vendor1_v6.o \
					   sec_qc_smem_id_vendor1_v7.o \
					   sec_qc_smem_lpddr.o \
					   sec_qc_smem_logger.o
