#SPRD CODEC

SPRD_SOUND_TREE := sound/soc/sprd/
KBUILD_CFLAGS	+= -I$(SPRD_SOUND_TREE) -I$(SPRD_SOUND_TREE)/codec

snd-soc-sprd-sprd-codec-v4-objs   := sprd-codec.o sprd-audio-power.o
obj-$(CONFIG_SND_SOC_SPRD_CODEC_V4)        += snd-soc-sprd-sprd-codec-v4.o
