obj-$(CONFIG_MTK_TINYSYS_MCUPM_SUPPORT) += mcupm.o
mcupm-objs += mcupm_driver.o
mcupm-objs += mcupm_plt.o
mcupm-objs += mcupm_logger.o
mcupm-objs += mcupm_timesync.o

ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/mcupm/include
