ccflags-y += -Idrivers/staging/android -Idrivers/clk/mmp
obj-$(CONFIG_MMP_DISP_CONTROLLER)	+= mmp_ctrl.o clk.o mmp_dsi.o vsync.o mmp_vdma.o shadow.o debug.o mmp_apical.o
obj-$(CONFIG_MMP_DISP_SPI)		+= mmp_spi.o
obj-$(CONFIG_MMP_DISP_DFC)		+= dfc.o
obj-$(CONFIG_MMP_ADAPTIVE_FPS)		+= adaptive_fps.o
