#ifndef __MELFAS_REG_H
#define __MELFAS_REG_H

/* Address */
#define MELFAS_TS_R0_INFO					0x01
#define MELFAS_TS_R1_INFO_PRODUCT_NAME				0x00
#define MELFAS_TS_R1_INFO_RESOLUTION_X				0x10
#define MELFAS_TS_R1_INFO_RESOLUTION_Y				0x12
#define MELFAS_TS_R1_INFO_NODE_NUM_X				0x14
#define MELFAS_TS_R1_INFO_NODE_NUM_Y				0x15
#define MELFAS_TS_R1_INFO_KEY_NUM				0x16
#define MELFAS_TS_R1_INFO_VERSION_BOOT				0x20
#define MELFAS_TS_R1_INFO_VERSION_CORE				0x22
#define MELFAS_TS_R1_INFO_VERSION_CUSTOM			0x24
#define MELFAS_TS_R1_INFO_VERSION_PARAM				0x26
#define MELFAS_TS_R1_INFO_SECT_BOOT_START			0x30
#define MELFAS_TS_R1_INFO_SECT_BOOT_END				0x31
#define MELFAS_TS_R1_INFO_SECT_CORE_START			0x32
#define MELFAS_TS_R1_INFO_SECT_CORE_END				0x33
#define MELFAS_TS_R1_INFO_SECT_CUSTOM_START			0x34
#define MELFAS_TS_R1_INFO_SECT_CUSTOM_END			0x35
#define MELFAS_TS_R1_INFO_SECT_PARAM_START			0x36
#define MELFAS_TS_R1_INFO_SECT_PARAM_END			0x37
#define MELFAS_TS_R1_INFO_BUILD_DATE				0x40
#define MELFAS_TS_R1_INFO_BUILD_TIME				0x44
#define MELFAS_TS_R1_INFO_CHECKSUM_PRECALC			0x48
#define MELFAS_TS_R1_INFO_CHECKSUM_REALTIME			0x4A
#define MELFAS_TS_R1_INFO_CHECKSUM_CALC				0x4C
#define MELFAS_TS_R1_INFO_PROTOCOL_NAME				0x50
#define MELFAS_TS_R1_INFO_PROTOCOL_VERSION			0x58
#define MELFAS_TS_R1_INFO_IC_ID					0x70
#define MELFAS_TS_R1_INFO_CONTACT_THD_SCR        		0x78
#define MELFAS_TS_R1_INFO_PROXIMITY_THD        			0x8E

#define MELFAS_TS_TS_CMD_SENSITIVITY_MODE			0x14
#define MELFAS_TS_TS_READ_SENSITIVITY_VALUE			0x26

#define MELFAS_TS_R0_EVENT					0x02
#define MELFAS_TS_R1_EVENT_SUPPORTED_FUNC			0x00
#define MELFAS_TS_R1_EVENT_FORMAT				0x04
#define MELFAS_TS_R1_EVENT_SIZE					0x06
#define MELFAS_TS_R1_EVENT_SIZE_TYPE				0x07
#define MELFAS_TS_R1_EVENT_PACKET_INFO				0x10
#define MELFAS_TS_R1_EVENT_PACKET_DATA				0x11

#define MELFAS_TS_R0_CTRL					0x06
#define MELFAS_TS_R1_CTRL_READY_STATUS				0x00
#define MELFAS_TS_R1_CTRL_EVENT_READY				0x01
#define MELFAS_TS_R1_CTRL_MODE					0x10
#define MELFAS_TS_R1_CTRL_EVENT_TRIGGER_TYPE			0x11
#define MELFAS_TS_R1_CTRL_RECALIBRATE				0x12
#define MELFAS_TS_R1_CTRL_POWER_STATE				0x13
#define MELFAS_TS_R1_CTRL_GESTURE_TYPE				0x14
#define MELFAS_TS_R1_CTRL_DISABLE_ESD_ALERT			0x18
#define MELFAS_TS_R1_CTRL_CHARGER_MODE				0x19
#define MELFAS_TS_R1_CTRL_GLOVE_MODE				0x1A
#define MELFAS_TS_R1_CTRL_COVER_MODE				0x1B
#define MELFAS_TS_R1_CTRL_PALM_REJECTION			0x1C
#define MELFAS_TS_R1_CTRL_DISABLE_EDGE_EXPAND			0x1D
#define MELFAS_TS_R1_CTRL_PROXIMITY				0x23
#define MELFAS_TS_R1_CTRL_TSP_CONNECTION_CHECK			0x25
#define MELFAS_TS_R1_CTRL_5POINT_TEST_MODE       		0x2B
#define MELFAS_TS_R1_CTRL_NP_ACTIVE_MODE			0x2C
#define MELFAS_TS_R1_CTRL_SYNC                   		0x31
#define MELFAS_TS_R1_CTRL_WET_MODE               		0x32
#define MELFAS_TS_R1_CTRL_PROX_OFF               		0x33
#define MELFAS_TS_R1_CTRL_ASYNC					0x34
#define MELFAS_TS_R1_CTRL_POCKET_MODE				0x36
#define MELFAS_TS_R1_CTRL_DELTA_TEST				0x38
#define MELFAS_TS_R1_CTRL_SNR_TEST_FRAME			0x39
#define MELFAS_TS_R1_CTRL_SNR_TEST_NONE_TOUCH_EN		0x3B
#define MELFAS_TS_R1_CTRL_SNR_TEST_TOUCH_EN			0x3C
#define MELFAS_TS_R1_CTRL_SNR_TEST_STATUS			0x3D


#define MELFAS_TS_R0_PARAM					0x08
#define MELFAS_TS_R1_PARAM_BUFFER_ADDR				0x00
#define MELFAS_TS_R1_PARAM_PROTOCOL				0x04
#define MELFAS_TS_R1_PARAM_MODE					0x10

#define MELFAS_TS_R0_TEST                         		0x0A
#define MELFAS_TS_R1_TEST_BUF_ADDR                		0x00
#define MELFAS_TS_R1_TEST_PROTOCOL                		0x02
#define MELFAS_TS_R1_TEST_VALIDITY                		0x08
#define MELFAS_TS_R1_TEST_TYPE                    		0x10
#define MELFAS_TS_R1_TEST_DATA_FORMAT             		0x20
#define MELFAS_TS_R1_TEST_ROW_NUM                 		0x20
#define MELFAS_TS_R1_TEST_COL_NUM                 		0x21
#define MELFAS_TS_R1_TEST_BUFFER_COL_NUM          		0x22
#define MELFAS_TS_R1_TEST_COL_AXIS                		0x23
#define MELFAS_TS_R1_TEST_KEY_NUM                 		0x24
#define MELFAS_TS_R1_TEST_DATA_TYPE               		0x25
#define MELFAS_TS_R1_TEST_VECTOR_NUM              		0x26
#define MELFAS_TS_R1_TEST_VECTOR_INFO             		0x28

#define MELFAS_TS_R0_IMAGE					0x0C
#define MELFAS_TS_R1_IMAGE_BUF_ADDR				0x00
#define MELFAS_TS_R1_IMAGE_PROTOCOL_ID				0x04
#define MELFAS_TS_R1_IMAGE_TYPE					0x10
#define MELFAS_TS_R1_IMAGE_DATA_FORMAT				0x20
#define MELFAS_TS_R1_IMAGE_ROW_NUM				0x20
#define MELFAS_TS_R1_IMAGE_COL_NUM				0x21
#define MELFAS_TS_R1_IMAGE_BUFFER_COL_NUM			0x22
#define MELFAS_TS_R1_IMAGE_COL_AXIS				0x23
#define MELFAS_TS_R1_IMAGE_KEY_NUM				0x24
#define MELFAS_TS_R1_IMAGE_DATA_TYPE				0x25
#define MELFAS_TS_R1_IMAGE_VECTOR_NUM            		0x26
#define MELFAS_TS_R1_IMAGE_VECTOR_INFO           		0x28
#define MELFAS_TS_R1_IMAGE_FINGER_NUM				0x30
#define MELFAS_TS_R1_IMAGE_FINGER_AREA				0x31

/*
 * Grip control register
 */
#define MELFAS_TS_R0_CUSTOM                      		0x0E
#define MELFAS_TS_R1_SEC_EDGE_HANDLER				0x4B
#define MELFAS_TS_R1_SEC_EDGE_AREA				0x38
#define MELFAS_TS_R1_SEC_DEAD_ZONE				0x32
#define MELFAS_TS_R1_SEC_DEAD_ZONE_ENABLE			0x3A
#define MELFAS_TS_R1_SEC_LANDSCAPE_MODE				0x3C
#define MELFAS_TS_R1_SEC_LANDSCAPE_MODE_CLR			0x40

#define MELFAS_TS_R0_LOG					0x10
#define MELFAS_TS_R1_LOG_TRIGGER				0x14

#define MELFAS_TS_R0_AOT					0x0E
#define MELFAS_TS_R0_AOT_CTRL					0x02
#define MELFAS_TS_R0_AOT_EVENT					0x03
#define MELFAS_TS_R0_AOT_BOX_W					0x04
#define MELFAS_TS_R0_AOT_POSITION_X				0x0C

/* Sponge */
#define MELFAS_TS_LIB_ADDR_START				0xA000
#define MELFAS_TS_LIB_ADDR_END					0xA3FF
#define MELFAS_TS_LIB_ADDR_SYNC					0x0631

/* Value */

#define MELFAS_TS_COORDINATE_EVENT				0
#define MELFAS_TS_ALERT_EVENT					1

#define MELFAS_TS_ALERT_ESD					1
#define MELFAS_TS_ALERT_WAKEUP					2
#define MELFAS_TS_ALERT_SRAM_FAILURE				6
#define MELFAS_TS_ALERT_MODE_STATE				9
#define MELFAS_TS_ALERT_POCKET_MODE_STATE			10
#define MELFAS_TS_ALERT_PROXIMITY_STATE				11
#define MELFAS_TS_ALERT_SPONGE_GESTURE				0xF1

#define MELFAS_TS_CTRL_STATUS_NONE				0x05
#define MELFAS_TS_CTRL_STATUS_READY				0xA0
#define MELFAS_TS_CTRL_STATUS_LOG				0x77

#define MELFAS_TS_CTRL_MODE_NORMAL				0
#define MELFAS_TS_CTRL_MODE_PARAM				1
#define MELFAS_TS_CTRL_MODE_TEST_CM				2

#define MELFAS_TS_CTRL_TRIGGER_NONE          			0
#define MELFAS_TS_CTRL_TRIGGER_INTR          			1
#define MELFAS_TS_CTRL_TRIGGER_REG           			2

#define MELFAS_TS_TEST_TYPE_NONE				0
#define MELFAS_TS_TEST_TYPE_CM					1
#define MELFAS_TS_TEST_TYPE_CM_ABS				2
#define MELFAS_TS_TEST_TYPE_CM_JITTER				3
#define MELFAS_TS_TEST_TYPE_SHORT				4
#define MELFAS_TS_TEST_TYPE_GPIO_LOW				5
#define MELFAS_TS_TEST_TYPE_GPIO_HIGH				6
#define MELFAS_TS_TEST_TYPE_CM_DIFF_HOR				17
#define MELFAS_TS_TEST_TYPE_CM_DIFF_VER				18
#define MELFAS_TS_TEST_TYPE_CP_LOW				19
#define MELFAS_TS_TEST_TYPE_CP					20
#define MELFAS_TS_TEST_TYPE_CP_DIFF_HOR				21
#define MELFAS_TS_TEST_TYPE_CP_DIFF_VER				22
#define MELFAS_TS_TEST_TYPE_CP_JITTER				23
#define MELFAS_TS_TEST_TYPE_CP_HIGH  				24
#define MELFAS_TS_TEST_TYPE_CP_SHORT				27
#define MELFAS_TS_TEST_TYPE_CP_LPM				28
#define MELFAS_TS_TEST_TYPE_PANEL_CONN				29
#define MELFAS_TS_TEST_TYPE_OPEN_SHORT				30
#define MELFAS_TS_TEST_TYPE_VSYNC				31

#define MELFAS_TS_IMG_TYPE_NONE					0
#define MELFAS_TS_IMG_TYPE_INTENSITY				1
#define MELFAS_TS_IMG_TYPE_RAWDATA				2
#define MELFAS_TS_IMG_TYPE_F_INTENSITY				3
#define MELFAS_TS_IMG_TYPE_GESTURE				5
#define MELFAS_TS_IMG_TYPE_HSELF_RAWDATA			6
#define MELFAS_TS_IMG_TYPE_HSELF_INTENSITY			7
#define MELFAS_TS_IMG_TYPE_HSELF_F_INTENSITY			8
#define MELFAS_TS_IMG_TYPE_BASELINE				9
#define MELFAS_TS_IMG_TYPE_5POINT_INTENSITY			30
#define MELFAS_TS_IMG_TYPE_PROX_INTENSITY			31
#define MELFAS_TS_IMG_TYPE_JITTER_DELTA				32
#define MELFAS_TS_IMG_TYPE_SNR_DATA				33

#define MELFAS_TS_IMG_TYPE_WAIT					255

#define MELFAS_TS_TRIGGER_TYPE_NONE				0
#define MELFAS_TS_TRIGGER_TYPE_INTR				1
#define MELFAS_TS_TRIGGER_TYPE_REG				2

#define MELFAS_TS_TOUCHTYPE_NORMAL				0
#define MELFAS_TS_TOUCHTYPE_HOVER				1
#define MELFAS_TS_TOUCHTYPE_FLIPCOVER				2
#define MELFAS_TS_TOUCHTYPE_GLOVE				3
#define MELFAS_TS_TOUCHTYPE_STYLUS				4
#define MELFAS_TS_TOUCHTYPE_PALM				5
#define MELFAS_TS_TOUCHTYPE_WET					6
#define MELFAS_TS_TOUCHTYPE_PROXIMITY				7
#define MELFAS_TS_TOUCHTYPE_JIG					8

#define MELFAS_TS_BIT_SETFUNC_TOUCH				(1 << 0)
#define MELFAS_TS_BIT_SETFUNC_MUTUAL				(1 << 0)
#define MELFAS_TS_BIT_SETFUNC_HOVER				(1 << 1)
#define MELFAS_TS_BIT_SETFUNC_COVER				(1 << 2)
#define MELFAS_TS_BIT_SETFUNC_GLOVE				(1 << 3)
#define MELFAS_TS_BIT_SETFUNC_STYLUS				(1 << 4)
#define MELFAS_TS_BIT_SETFUNC_PALM				(1 << 5)
#define MELFAS_TS_BIT_SETFUNC_WET				(1 << 6)
#define MELFAS_TS_BIT_SETFUNC_PROXIMITY				(1 << 7)

/**
 * LPM status bitmask
 */

#define MELFAS_TS_GESTURE_CODE_SWIPE				0x00
#define MELFAS_TS_GESTURE_CODE_DOUBLE_TAP			0x01
#define MELFAS_TS_GESTURE_CODE_PRESS				0x03
#define MELFAS_TS_GESTURE_CODE_SINGLE_TAP			0x04
#define MELFAS_TS_GESTURE_CODE_DUMPFLUSH			0x05

/* MELFAS_TS_GESTURE_ID */
#define MELFAS_TS_GESTURE_ID_AOD				0x00
#define MELFAS_TS_GESTURE_ID_DOUBLETAP_TO_WAKEUP		0x01

/* SEC_TS_DUMP_ID */
#define MELFAS_TS_SPONGE_DUMP_0			0x00
#define MELFAS_TS_SPONGE_DUMP_1			0x01

enum switch_system_mode {
	TO_TOUCH_MODE			= 0,
	TO_LOWPOWER_MODE		= 1,
	TO_SELFTEST_MODE		= 2,
	TO_FLASH_MODE			= 3,
};

#define ENTER_NOISE_MODE	0
#define EXIT_NOISE_MODE		1
#define ENTER_WET_MODE		2
#define EXIT_WET_MODE		3
#define MODE_STATE_VSYNC_ON	4
#define MODE_STATE_VSYNC_OFF	5

#endif 
