obj-y					+= pm_domain.o

obj-$(CONFIG_MMP_PM_DOMAIN_COMMON)	+= pd_common.o
obj-$(CONFIG_MMP_PM_DOMAIN_SC2_ISP) += pd_sc2_isp.o
obj-$(CONFIG_MMP_PM_DOMAIN_ISP_V3)	+= pd_isp_v3.o
obj-$(CONFIG_MMP_PM_DOMAIN_DISPLAY)	+= pd_display.o
obj-$(CONFIG_MMP_PM_DOMAIN_HANTRO)	+= pd_hantro.o
obj-$(CONFIG_MMP_PM_DOMAIN_GC2D)	+= pd_gc2d.o
obj-$(CONFIG_MMP_PM_DOMAIN_GC3D)	+= pd_gc3d.o
obj-$(CONFIG_MMP_PM_DOMAIN_SMMU)	+= pd_smmu.o
