#
# Makefile for MELFAS MIP4 Touchscreen driver (SEC)
#

obj-$(CONFIG_TOUCHSCREEN_MELFAS_MIP4) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_ts_sec.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS427) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mms400.o mip4_ts_sec.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS438) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mms400.o mip4_ts_sec.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS438S) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mms400.o mip4_ts_sec.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS449S) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mms449s.o mip4_ts_sec.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS449) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mms400.o mip4_ts_sec.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS458) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mms400.o mip4_ts_sec.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS500) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mms500.o mip4_ts_sec.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS600) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mms600.o mip4_ts_sec.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MCS8040L) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mcs8040l.o mip4_ts_sec.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MFS10) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mfs10.o mip4_ts_sec.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MOS50) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mos50.o mip4_ts_sec.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MAT100) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mat100.o mip4_ts_sec.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MSS100) += mip4_ts.o mip4_ts_mod.o mip4_ts_dev.o mip4_fw_mss100.o

