# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2022 Samsung Electronics Inc.

SENSOR_NAME  := s5kjn1

imgsensor_isp6s-objs += \
	$(subdrv-rpath)/$(SENSOR_NAME)mipiraw_Sensor.o
$(info used driver: $(SENSOR_NAME))
