#
# Makefile for spredtrum efuse drivers.
#

obj-$(CONFIG_OTP_SPRD) += core.o otp-helper.o
obj-$(CONFIG_OTP_SPRD_EFUSE) += efuse.o
obj-$(CONFIG_OTP_SPRD_ADIE_EFUSE) += ana_efuse.o otp-bitmap.o
obj-$(CONFIG_OTP_SPRD_LASER_FUSE) += laser_fuse.o
