package(default_visibility = ["//visibility:public"])

filegroup(
    name = "prebuilt_singlejar",
    srcs = ["java_tools/src/tools/singlejar/singlejar_local"],
)

filegroup(
    name = "ijar_prebuilt_binary",
    srcs = ["java_tools/ijar/ijar"],
)
