dtb-y += a55x_mea_open_w00_r06.dtbo
dtb-y += a55x_mea_open_w00_r04.dtbo
dtb-y += a55x_mea_open_w00_r03.dtbo
dtb-y += a55x_mea_open_w00_r00.dtbo
# SPDX-License-Identifier: GPL-2.0
always-y	:= $(dtb-y) $(dtbo-y)
clean-files	:= *.dtb *.dtbo
