ifdef CONFIG_ARM64
KBUILD_CFLAGS += -mstrict-align
endif

obj-y += vsp_dvfs_sharkl5.o
obj-y += vsp_dvfs_roc1.o
obj-y += vsp_dvfs_sharkl5pro.o
obj-y += vpudec_dvfs_qogirn6pro.o
obj-y += vpuenc_dvfs_qogirn6pro.o
