ifeq ($(CONFIG_MFD_S2MPB02),m)
mfd_s2mpb02-objs := s2mpb02-core.o s2mpb02-irq.o
obj-$(CONFIG_MFD_S2MPB02)       += mfd_s2mpb02.o
else
obj-$(CONFIG_MFD_S2MPB02)       += s2mpb02-core.o s2mpb02-irq.o
endif
