# SPDX-License-Identifier: GPL-2.0

ifneq ($(wildcard $(srctree)/$(src)/mtk-vmm-spm-mt6989.c),)
obj-$(CONFIG_MTK_VMM_SPM_MT6989) += mtk-vmm-spm-mt6989.o
endif
ifneq ($(wildcard $(srctree)/$(src)/mtk-vmm-spm.c),)
obj-$(CONFIG_MTK_VMM_SPM) += mtk-vmm-spm.o
endif

