# arch/arm/mach-sc/board-huskytd/Makefile
#
# Copyright (C) 2013 Samsung Electronics Co, Ltd.
#
# This software is licensed under the terms of the GNU General Public
# License version 2, as published by the Free Software Foundation, and
# may be copied, distributed, and modified under those terms.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

obj-y 	+=  board-huskytd.o	\
			board-huskytd-serial.o \
			board-huskytd-audio.o \
			board-huskytd-display.o \
			board-huskytd-camera.o \
			board-huskytd-input.o \
			board-huskytd-battery.o \
			board-huskytd-mmc.o \
			board-huskytd-sensors.o \
			board-huskytd-connector.o \
			board-huskytd-pmic.o \

ccflags-y += -Iarch/arm/mach-sc/