obj-$(CONFIG_FB_SC8825) := spi_simple_drv.o
obj-$(CONFIG_FB_SCX35) := spi_simple_drv.o
obj-$(CONFIG_FB_SCX30G) := spi_simple_drv.o
obj-$(CONFIG_FB_SCX15) := spi_simple_drv.o
ifeq ($(CONFIG_FB_SCX35L), y)
obj-$(CONFIG_SPI) := spi_simple_drv.o
endif
