#
# Makefile for the optics drivers.
#

# Each configuration option enables a list of files.

KBUILD_CFLAGS += -Wno-unused-variable -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-frame-larger-than=

obj-$(CONFIG_SENSORS_TCS3407)		+= tcs3407.o
