#
# Makefile for the optics drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SENSORS_HRM_MAX86902)	+= hrm_max86902.o
obj-$(CONFIG_SENSORS_HRM_ADPD143)	+= hrm_adpd143.o
obj-$(CONFIG_SENSORS_HRMSENSOR)		+= hrmsensor.o