#
# Self Display Object
# namd : ss_dsi_panel_"DDI NAME"_"PANEL NAME".c
#

ccflags-y := -I$(srctree)/include/drm
ccflags-y += -I$(srctree)/techpack/display/msm
ccflags-y += -I$(srctree)/techpack/display/msm/dsi
ccflags-y += -I$(srctree)/techpack/display/msm/sde
ccflags-y += -I$(srctree)/techpack/display/msm/samsung

obj-y += self_display_FA7.o
obj-y += self_display_FA9.o
obj-y += self_display_HA8.o
obj-y += self_display_HA9.o
obj-y += self_display_HAB.o
obj-y += self_display_XA0.o