# M55 code for SR-QN6887A-01-1023 by gaochao at 20231115 start
ifeq ($(CONFIG_CUSTOM_FACTORY_BUILD),y)
obj-$(CONFIG_KNOXVAULT_POWER) := KnoxVault2.o
endif
# M55 code for SR-QN6887A-01-1023 by gaochao at 20231115 end