#
# Makefile for the sensor drivers.
#

# Each configuration option enables a list of files.

obj-y	+= barometer_sensor.o
obj-$(CONFIG_SENSORS_SSP_BAROMETER_LPS22H)	+= barometer_lps22h.o
obj-$(CONFIG_SENSORS_SSP_BAROMETER_LPS25H)	+= barometer_lps25h.o
obj-$(CONFIG_SENSORS_SSP_BAROMETER_LPS22HH)	+= barometer_lps22hh.o