# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the input core pmic drivers.
#

obj-$(CONFIG_KEYBOARD_S2MPS25)          += s2mps25-key.o
obj-$(CONFIG_KEYBOARD_S2MPS25_9935)     += s2mps25_key_9935.o
obj-$(CONFIG_KEYBOARD_S2MPU15_8535)     += s2mpu15_key_8535.o
obj-$(CONFIG_KEYBOARD_S2MPU15_8835)     += s2mpu15_key_8835.o
