#
# Makefile for the GalaxyCore touchscreen driver.
#

obj-y	+=  gcore_drv_main.o
obj-y	+=  gcore_drv_sprd.o
obj-y	+=  gcore_drv_fw_update.o
obj-y	+=  gcore_drv_interface.o
obj-y	+=  gcore_drv_mp_test.o
obj-y	+=  gcore_sec.o