obj-$(CONFIG_UH) 		+= uh_debug_log.o
obj-$(CONFIG_UH_DEBUG) 	+= uh_debug.o
obj-$(CONFIG_RKP_TEST)	+= rkp_test.o
obj-$(CONFIG_KDP_TEST)	+= kdp_test.o
obj-$(CONFIG_RUSTUH_RKP)	+= rustrkp.o
obj-$(CONFIG_RUSTUH_KDP)	+= rustkdp.o
obj-$(CONFIG_RUSTUH_RKP_TEST)	+= rkp_test.o
obj-$(CONFIG_RUSTUH_KDP_TEST)	+= kdp_test.o
