obj-$(CONFIG_EXYNOS_DECON_LCD) += dsim_panel.o
obj-$(CONFIG_EXYNOS_DECON_MDNIE_LITE) += mdnie_lite.o
obj-$(CONFIG_PANEL_EA8064G_DYNAMIC) += ea8064g_lcd_ctrl.o dimming_core.o
obj-$(CONFIG_PANEL_LTM184HL01) += ltm184hl01_lcd_ctrl.o
obj-$(CONFIG_PANEL_S6E3AA2_A3XE) += s6e3aa2_a3xe_lcd_ctrl.o dynamic_aid.o
obj-$(CONFIG_PANEL_S6E3FA3_A5XE) += s6e3fa3_a5xe_lcd_ctrl.o dynamic_aid.o
obj-$(CONFIG_PANEL_S6E3FA3_A7XE) += s6e3fa3_a5xe_lcd_ctrl.o dynamic_aid.o
obj-$(CONFIG_PANEL_EA8061_DYNAMIC) += ea8061_lcd_ctrl.o dimming_core.o
obj-$(CONFIG_PANEL_S6E3FA3_J7XE) += s6e3fa3_j7xe_lcd_ctrl.o dynamic_aid.o

