obj-$(CONFIG_EXYNOS_DECON_LCD) += dsim_panel.o
obj-$(CONFIG_EXYNOS_DECON_MDNIE_LITE) += mdnie_lite.o mdnie_tuning.o
obj-$(CONFIG_PANEL_AID_DIMMING) += dimming_core.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E3HA0)	+= s6e3ha0k_mipi_lcd.o s6e3ha0k_lcd_ctrl.o dynamic_aid.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E3HA2K)	+= s6e3ha2k_mipi_lcd.o s6e3ha2k_lcd_ctrl.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E3HF2)	+= s6e3hf2_mipi_lcd.o s6e3hf2_lcd_ctrl.o
obj-$(CONFIG_PANEL_S6E3FA2_DYNAMIC) += s6e3fa2_lcd_ctrl.o
obj-$(CONFIG_PANEL_S6E3FA3_DYNAMIC) += s6e3fa3_lcd_ctrl.o
obj-$(CONFIG_PANEL_S6D7AA0_DYNAMIC) += s6d7aa0_lcd_ctrl.o
obj-$(CONFIG_PANEL_S6D7AA0X62_DYNAMIC) += s6d7aa0x62_lcd_ctrl.o
obj-$(CONFIG_PANEL_EA8064G_DYNAMIC) += ea8064g_lcd_ctrl.o
obj-$(CONFIG_PANEL_LTM184HL01) += ltm184hl01_lcd_ctrl.o
obj-$(CONFIG_PANEL_LAGO_DUMMY) += lago_dummy_lcd_ctrl.o
obj-$(CONFIG_PANEL_S6E3AA2_DYNAMIC) += ea8061_lcd_ctrl.o

obj-$(CONFIG_EXYNOS_DECON_LCD_S6E3FA0)	+= s6e3fa0_mipi_lcd.o s6e3fa0_lcd_ctrl.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E3FA2)	+= s6e3fa2_mipi_lcd.o s6e3fa2_lcd_ctrl.o
obj-$(CONFIG_EXYNOS_DECON_LCD_S6E3FA3)	+= s6e3fa3_mipi_lcd.o s6e3fa3_lcd_ctrl.o
