ccflags-y += -DSTK_BUS_I2C
ccflags-y += -DSTK_GPIO_MTK
ccflags-y += -DSTK_MTK
ccflags-y += -DSTK_RETRY_I2C
obj-$(CONFIG_INPUT_STK501XX) += stk501xx.o
stk-src += stk501xx.c
stk-objs := $(stk-src:.c=.o)
