# hs14 code for SR-AL6528A-01-271 by zhangziyi at 2022/10/12 start
# hs14 code for SR-AL6528A-01-282|SR-AL6528A-01-292 by xiongxiaoliang at 2022/10/10 start
ifeq ($(CONFIG_MTK_FINGERPRINT_SUPPORT), y)
obj-$(CONFIG_SILEAD_FP)                += silead/
# hs14 code added for SR-AL6528A-01-272 by Wentao at 2022/10/09 start
obj-$(CONFIG_FINGERPRINT_FOCALTECH)    += focaltech/
# hs14 code added for SR-AL6528A-01-272 by Wentao at 2022/10/09 end
obj-$(CONFIG_CDFINGER_FP)              += cdfinger/
obj-$(CONFIG_FINGER_O22)               += fingerprint_sysfs.o
endif
# hs14 code for SR-AL6528A-01-282|SR-AL6528A-01-292 by xiongxiaoliang at 2022/10/10 end
# hs14 code for SR-AL6528A-01-271 by zhangziyi at 2022/10/12 end
