dtb-y += mt6757_j7maxlte_swa_ins_00.dtb
dtb-y += mt6757_j7maxlte_swa_ins_01.dtb
dtb-y += mt6757_j7maxlte_swa_ins_02.dtb
dtb-y += mt6757_j7maxlte_swa_ins_05.dtb

always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb*
