
obj-$(CONFIG_TOUCHSCREEN_ILI9881H) +=   ilitek_plat_qcom.o \
					ilitek_spi.o \
					ilitek_main.o \
					ilitek_ic.o \
					ilitek_touch.o \
					ilitek_mp.o \
					ilitek_fw.o \
					ilitek_node.o
