# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_MEDIATEK_MT6338_AUXADC) += mt6338-auxadc.o
obj-$(CONFIG_MEDIATEK_MT635X_AUXADC) += mt635x-auxadc.o
obj-$(CONFIG_MEDIATEK_MT6375_AUXADC) += mt6375-auxadc.o
obj-$(CONFIG_MEDIATEK_MT6681_AUXADC) += mt6681-auxadc.o
obj-$(CONFIG_DEVICE_MODULES_MEDIATEK_MT6577_AUXADC) += mt6577_auxadc.o
obj-$(CONFIG_MEDIATEK_SPMI_PMIC_ADC) += mtk-spmi-pmic-adc.o
obj-$(CONFIG_MEDIATEK_SPMI_TIA_ADC) += mtk-spmi-tia-adc.o
obj-$(CONFIG_MEDIATEK_MT6362_ADC) += mt6362-adc.o
obj-$(CONFIG_MEDIATEK_MT6375_ADC) += mt6375-adc.o
obj-$(CONFIG_RT9490_ADC) += rt9490-adc.o
