# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the kernel USB device drivers.
#

# Object files in subdirectories

obj-$(CONFIG_DEVICE_MODULES_USB_MTU3)		+= mtu3/

obj-$(CONFIG_DEVICE_MODULES_USB_SS_FUNCTIONS)	+= ss_function/

