/*
 * linux/drivers/video/fbdev/exynos/panel/s6e3hae/s6e3hae.h
 *
 * Header file for S6E3HAE Dimming Driver
 *
 * Copyright (c) 2016 Samsung Electronics
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#ifndef __S6E3HAE_H__
#define __S6E3HAE_H__

#include <linux/types.h>
#include <linux/kernel.h>
#include "../panel_drv.h"
#ifdef CONFIG_SUPPORT_DDI_FLASH
#include "../panel_poc.h"
#endif
/*
 * OFFSET ==> OFS means N-param - 1
 * <example>
 * XXX 1st param => S6E3HAE_XXX_OFS (0)
 * XXX 2nd param => S6E3HAE_XXX_OFS (1)
 * XXX 36th param => S6E3HAE_XXX_OFS (35)
 */

#undef CONFIG_PANEL_VRR_BRIDGE

#define AID_INTERPOLATION

#define S6E3HAE_IRC_ONOFF_OFS	(0)
#define S6E3HAE_IRC_VALUE_OFS	(10)
#define S6E3HAE_IRC_VALUE_LEN	(33)

#define S6E3HAE_ADDR_OFS	(0)
#define S6E3HAE_ADDR_LEN	(1)
#define S6E3HAE_DATA_OFS	(S6E3HAE_ADDR_OFS + S6E3HAE_ADDR_LEN)

#define S6E3HAE_GAMMA_REG		0xB2
#define S6E3HAE_GAMMA_OFS		0x27
#define S6E3HAE_GAMMA_LEN		84

#define S6E3HAE_GAMMA_FLASH_REG		0x6E
#define S6E3HAE_GAMMA_FLASH_OFS		0
#define S6E3HAE_GAMMA_FLASH_LEN		70

#define S6E3HAE_DATE_REG			0xA1
#define S6E3HAE_DATE_OFS			4
#define S6E3HAE_DATE_LEN			(PANEL_DATE_LEN)

#define S6E3HAE_COORDINATE_REG		0xA1
#define S6E3HAE_COORDINATE_OFS		0
#define S6E3HAE_COORDINATE_LEN		(PANEL_COORD_LEN)

#define S6E3HAE_ID_REG				0x04
#define S6E3HAE_ID_OFS				0
#define S6E3HAE_ID_LEN				(PANEL_ID_LEN)

#define S6E3HAE_CODE_REG			0xD6
#define S6E3HAE_CODE_OFS			0
#define S6E3HAE_CODE_LEN			(PANEL_CODE_LEN)

#define S6E3HAE_ELVSS_REG			0xB5
#define S6E3HAE_ELVSS_OFS			0
#define S6E3HAE_ELVSS_LEN			23

#define S6E3HAE_ELVSS_TEMP_0_REG		0xB5
#define S6E3HAE_ELVSS_TEMP_0_OFS		74
#define S6E3HAE_ELVSS_TEMP_0_LEN		1

#define S6E3HAE_ELVSS_TEMP_1_REG		0xB5
#define S6E3HAE_ELVSS_TEMP_1_OFS		75
#define S6E3HAE_ELVSS_TEMP_1_LEN		1

#define S6E3HAE_OCTA_ID_REG			0xA1
#define S6E3HAE_OCTA_ID_OFS			11
#define S6E3HAE_OCTA_ID_LEN			(PANEL_OCTA_ID_LEN)

#define S6E3HAE_COPR_SPI_REG			0x5A
#define S6E3HAE_COPR_SPI_OFS			0
#define S6E3HAE_COPR_SPI_LEN			(COPR_V6_SPI_RX_SIZE)

#define S6E3HAE_COPR_DSI_REG			0x5A
#define S6E3HAE_COPR_DSI_OFS			0
#define S6E3HAE_COPR_DSI_LEN			(COPR_V6_DSI_RX_SIZE)

#define S6E3HAE_COPR_CTRL_REG			0xE1
#define S6E3HAE_COPR_CTRL_OFS			0
#define S6E3HAE_COPR_CTRL_LEN			(COPR_V6_CTRL_REG_SIZE)

#define S6E3HAE_CHIP_ID_REG				0xD6
#define S6E3HAE_CHIP_ID_OFS				0
#define S6E3HAE_CHIP_ID_LEN				5

#define S6E3HAE_AOR_MANUAL_ONOFF_REG	(0x98)
#define S6E3HAE_AOR_MANUAL_ONOFF_OFS	(0x19F)
#define S6E3HAE_AOR_MANUAL_ONOFF_LEN	(1)

#define S6E3HAE_AOR_MANUAL_VALUE_REG	(0x98)
#define S6E3HAE_AOR_MANUAL_VALUE_OFS	(0x1A0)
#define S6E3HAE_AOR_MANUAL_VALUE_LEN	(2)

#define S6E3HAE_VTOTAL_NS_0_REG		(0xB1)
#define S6E3HAE_VTOTAL_NS_0_OFS		(0x2B)
#define S6E3HAE_VTOTAL_NS_0_LEN		(2)

#define S6E3HAE_VTOTAL_NS_1_REG		(0xB1)
#define S6E3HAE_VTOTAL_NS_1_OFS		(0x3D)
#define S6E3HAE_VTOTAL_NS_1_LEN		(2)

#define S6E3HAE_VTOTAL_HS_0_REG		(0xB1)
#define S6E3HAE_VTOTAL_HS_0_OFS		(0x43)
#define S6E3HAE_VTOTAL_HS_0_LEN		(2)

#define S6E3HAE_VTOTAL_HS_1_REG		(0xB1)
#define S6E3HAE_VTOTAL_HS_1_OFS		(0x55)
#define S6E3HAE_VTOTAL_HS_1_LEN		(2)

#define S6E3HAE_VFP_OPT_NS_REG		(0xB1)
#define S6E3HAE_VFP_OPT_NS_OFS		(0x3F)
#define S6E3HAE_VFP_OPT_NS_LEN		(2)

#define S6E3HAE_VFP_OPT_HS_REG		(0xB1)
#define S6E3HAE_VFP_OPT_HS_OFS		(0x57)
#define S6E3HAE_VFP_OPT_HS_LEN		(2)

#define S6E3HAE_VINT_REG			0xF4
#define S6E3HAE_VINT_OFS			4
#define S6E3HAE_VINT_LEN			1

#define S6E3HAE_ELVSS_T_REG			0xB5
#define S6E3HAE_ELVSS_T_OFS			2
#define S6E3HAE_ELVSS_T_LEN			1

#define S6E3HAE_FLASH_LOADED_REG	(0x91)
#define S6E3HAE_FLASH_LOADED_OFS	(0x40)
#define S6E3HAE_FLASH_LOADED_LEN	1

#define S6E3HAE_IRC_REG				(0x92)
#define S6E3HAE_IRC_OFS				(S6E3HAE_IRC_VALUE_OFS)
#define S6E3HAE_IRC_LEN				(S6E3HAE_IRC_VALUE_LEN)

/* for panel dump */
#define S6E3HAE_RDDPM_REG			0x0A
#define S6E3HAE_RDDPM_OFS			0
#define S6E3HAE_RDDPM_LEN			(PANEL_RDDPM_LEN)

#define S6E3HAE_RDDSM_REG			0x0E
#define S6E3HAE_RDDSM_OFS			0
#define S6E3HAE_RDDSM_LEN			(PANEL_RDDSM_LEN)

#define S6E3HAE_ERR_REG				0xE9
#define S6E3HAE_ERR_OFS				0
#define S6E3HAE_ERR_LEN				5

#define S6E3HAE_ERR_FG_REG			0xEE
#define S6E3HAE_ERR_FG_OFS			0
#define S6E3HAE_ERR_FG_LEN			1

#define S6E3HAE_DSI_ERR_REG			0x05
#define S6E3HAE_DSI_ERR_OFS			0
#define S6E3HAE_DSI_ERR_LEN			1

#define S6E3HAE_SELF_DIAG_REG			0x0F
#define S6E3HAE_SELF_DIAG_OFS			0
#define S6E3HAE_SELF_DIAG_LEN			1

#define S6E3HAE_SELF_MASK_CHECKSUM_REG		0x14
#define S6E3HAE_SELF_MASK_CHECKSUM_OFS		0
#define S6E3HAE_SELF_MASK_CHECKSUM_LEN		2

#define S6E3HAE_SELF_MASK_CRC_REG		0x7F
#define S6E3HAE_SELF_MASK_CRC_OFS	6
#define S6E3HAE_SELF_MASK_CRC_LEN		4

#ifdef CONFIG_SUPPORT_DDI_CMDLOG
#define S6E3HAE_CMDLOG_REG			0x9C
#define S6E3HAE_CMDLOG_OFS			0
#define S6E3HAE_CMDLOG_LEN			0x80
#endif

#ifdef CONFIG_SUPPORT_DDI_FLASH
#define S6E3HAE_POC_CHKSUM_REG		0xEC
#define S6E3HAE_POC_CHKSUM_OFS		0
#define S6E3HAE_POC_CHKSUM_LEN		(PANEL_POC_CHKSUM_LEN)

#define S6E3HAE_POC_CTRL_REG		0xEB
#define S6E3HAE_POC_CTRL_OFS		0
#define S6E3HAE_POC_CTRL_LEN		(PANEL_POC_CTRL_LEN)

#define S6E3HAE_POC_DATA_REG		0xFB
#define S6E3HAE_POC_DATA_OFS		(12)
#define S6E3HAE_POC_DATA_LEN		(1)
#endif

#ifdef CONFIG_SUPPORT_GRAM_CHECKSUM
#define S6E3HAE_GRAM_CHECKSUM_REG	0xAF
#define S6E3HAE_GRAM_CHECKSUM_OFS	0
#define S6E3HAE_GRAM_CHECKSUM_LEN	1
#define S6E3HAE_GRAM_CHECKSUM_VALID_1	0x2B
#define S6E3HAE_GRAM_CHECKSUM_VALID_2	0x2B
#endif

#define S6E3HAE_MCD_RESISTANCE_REG			0xCD
#define S6E3HAE_MCD_RESISTANCE_OFS			2
#define S6E3HAE_MCD_RESISTANCE_LEN			1

#ifdef CONFIG_SUPPORT_CCD_TEST
#define S6E3HAE_CCD_STATE_REG				0xCD
#define S6E3HAE_CCD_STATE_OFS				0
#define S6E3HAE_CCD_STATE_LEN				1
#endif

#define S6E3HAE_SSR_ONOFF_REG				0xF6
#define S6E3HAE_SSR_ONOFF_OFS				0x08
#define S6E3HAE_SSR_ONOFF_LEN				1

#define S6E3HAE_SSR_STATE_REG				0xFB
#define S6E3HAE_SSR_STATE_OFS				0x23
#define S6E3HAE_SSR_STATE_LEN				1

#define S6E3HAE_SSR_TEST_LEN				(S6E3HAE_SSR_ONOFF_LEN + S6E3HAE_SSR_STATE_LEN)

#define S6E3HAE_ECC_TEST_REG				0xF8
#define S6E3HAE_ECC_TEST_OFS				0x02
#define S6E3HAE_ECC_TEST_LEN				3

#define S6E3HAE_DECODER_TEST_REG			0x14
#define S6E3HAE_DECODER_TEST_OFS			0
#define S6E3HAE_DECODER_TEST_LEN			2

#define S6E3HAE_SPSRAM_GAMMA_REG			0x6E
#define S6E3HAE_SPSRAM_GAMMA_OFS			0
#define S6E3HAE_SPSRAM_GAMMA_LEN			70

#ifdef CONFIG_SUPPORT_GRAYSPOT_TEST
#define S6E3HAE_GRAYSPOT_CAL_1_REG			0x94
#define S6E3HAE_GRAYSPOT_CAL_1_OFS			0x18
#define S6E3HAE_GRAYSPOT_CAL_1_LEN			1
#define S6E3HAE_GRAYSPOT_CAL_2_REG			0x94
#define S6E3HAE_GRAYSPOT_CAL_2_OFS			0x1A
#define S6E3HAE_GRAYSPOT_CAL_2_LEN			1
#endif

#ifdef CONFIG_SUPPORT_MAFPC
#define S6E3HAE_MAFPC_REG					0x87
#define S6E3HAE_MAFPC_OFS					0
#define S6E3HAE_MAFPC_LEN					1

#define S6E3HAE_MAFPC_FLASH_REG				0xFE
#define S6E3HAE_MAFPC_FLASH_OFS				0x09
#define S6E3HAE_MAFPC_FLASH_LEN				1

#define S6E3HAE_MAFPC_CRC_REG				0x14
#define S6E3HAE_MAFPC_CRC_OFS				0
#define S6E3HAE_MAFPC_CRC_LEN				2

#define S6E3HAE_MAFPC_ENA_REG				0
#define S6E3HAE_MAFPC_VBP_REG				2

#define S6E3HAE_MAFPC_SCALE_MAX				75

#define S6E3HAE_MAFPC_ENABLE				0x51
#define S6E3HAE_MAFPC_CTRL_CMD_OFFSET		6
#endif

#ifdef CONFIG_SUPPORT_DDI_FLASH
/* MCD */
#define S6E3HAE_FLASH_MCD_ADDR	(POC_MCD_PARTITION)
#define S6E3HAE_FLASH_MCD1_R_OFS	(0)
#define S6E3HAE_FLASH_MCD1_R_LEN	(1)
#define S6E3HAE_FLASH_MCD2_R_OFS	(S6E3HAE_FLASH_MCD1_R_OFS + S6E3HAE_FLASH_MCD1_R_LEN)
#define S6E3HAE_FLASH_MCD2_R_LEN	(1)
/* DUMMY 2byte */
#define S6E3HAE_FLASH_MCD1_L_OFS	(S6E3HAE_FLASH_MCD2_R_OFS + S6E3HAE_FLASH_MCD2_R_LEN + 2)
#define S6E3HAE_FLASH_MCD1_L_LEN	(1)
#define S6E3HAE_FLASH_MCD2_L_OFS	(S6E3HAE_FLASH_MCD1_L_OFS + S6E3HAE_FLASH_MCD1_L_LEN)
#define S6E3HAE_FLASH_MCD2_L_LEN	(1)
#define S6E3HAE_FLASH_MCD_LEN	(S6E3HAE_FLASH_MCD2_L_OFS + S6E3HAE_FLASH_MCD2_L_LEN)
#endif /* CONFIG_SUPPORT_DDI_FLASH */

#ifdef CONFIG_SUPPORT_GM2_FLASH
#define S6E3HAE_GM2_FLASH_VBIAS1_ADDR	(POC_GM2_VBIAS_PARTITION)
#define S6E3HAE_GM2_FLASH_VBIAS1_COL	(14)
#define S6E3HAE_GM2_FLASH_VBIAS1_ROW	(6)
#define S6E3HAE_GM2_FLASH_VBIAS1_OFS	(0)
#define S6E3HAE_GM2_FLASH_VBIAS1_LEN	(S6E3HAE_GM2_FLASH_VBIAS1_COL * S6E3HAE_GM2_FLASH_VBIAS1_ROW)

#define S6E3HAE_GM2_FLASH_VBIAS_CHECKSUM_ADDR	(POC_GM2_VBIAS_PARTITION)
#define S6E3HAE_GM2_FLASH_VBIAS_CHECKSUM_OFS	(S6E3HAE_GM2_FLASH_VBIAS1_LEN)
#define S6E3HAE_GM2_FLASH_VBIAS_CHECKSUM_LEN	(2)

#define S6E3HAE_GM2_FLASH_VBIAS_MAGICNUM_ADDR	(POC_GM2_VBIAS_PARTITION)
#define S6E3HAE_GM2_FLASH_VBIAS_MAGICNUM_OFS	(S6E3HAE_GM2_FLASH_VBIAS1_LEN + S6E3HAE_GM2_FLASH_VBIAS_CHECKSUM_LEN)
#define S6E3HAE_GM2_FLASH_VBIAS_MAGICNUM_LEN	(1)


#define S6E3HAE_GM2_FLASH_VBIAS2_ADDR	(POC_GM2_VBIAS_PARTITION)
#define S6E3HAE_GM2_FLASH_VBIAS2_COL	(2)
#define S6E3HAE_GM2_FLASH_VBIAS2_ROW	(1)
#define S6E3HAE_GM2_FLASH_VBIAS2_OFS	(S6E3HAE_GM2_FLASH_VBIAS1_LEN + S6E3HAE_GM2_FLASH_VBIAS_CHECKSUM_LEN + S6E3HAE_GM2_FLASH_VBIAS_MAGICNUM_LEN)
#define S6E3HAE_GM2_FLASH_VBIAS2_LEN	(S6E3HAE_GM2_FLASH_VBIAS2_COL * S6E3HAE_GM2_FLASH_VBIAS2_ROW)

#define S6E3HAE_GM2_FLASH_VBIAS_TOTAL_SIZE (S6E3HAE_GM2_FLASH_VBIAS1_LEN \
	+ S6E3HAE_GM2_FLASH_VBIAS_CHECKSUM_LEN + S6E3HAE_GM2_FLASH_VBIAS_MAGICNUM_LEN + S6E3HAE_GM2_FLASH_VBIAS2_LEN)

#endif

#ifdef CONFIG_EXYNOS_DECON_MDNIE_LITE
#define NR_S6E3HAE_MDNIE_REG	(3)

#define S6E3HAE_MDNIE_0_REG		(0xDF)
#define S6E3HAE_MDNIE_0_OFS		(0)
#define S6E3HAE_MDNIE_0_LEN		(224)

#define S6E3HAE_MDNIE_1_REG		(0xDE)
#define S6E3HAE_MDNIE_1_OFS		(S6E3HAE_MDNIE_0_OFS + S6E3HAE_MDNIE_0_LEN)
#define S6E3HAE_MDNIE_1_LEN		(196)

#define S6E3HAE_MDNIE_2_REG		(0xDD)
#define S6E3HAE_MDNIE_2_OFS		(S6E3HAE_MDNIE_1_OFS + S6E3HAE_MDNIE_1_LEN)
#define S6E3HAE_MDNIE_2_LEN		(21)
#define S6E3HAE_MDNIE_LEN		(S6E3HAE_MDNIE_0_LEN + S6E3HAE_MDNIE_1_LEN + S6E3HAE_MDNIE_2_LEN)

#define S6E3HAE_SCR_CR_OFS	(31)
#define S6E3HAE_SCR_WR_OFS	(49)
#define S6E3HAE_SCR_WG_OFS	(51)
#define S6E3HAE_SCR_WB_OFS	(53)
#define S6E3HAE_NIGHT_MODE_OFS	(S6E3HAE_SCR_CR_OFS)
#define S6E3HAE_NIGHT_MODE_LEN	(24)
#define S6E3HAE_COLOR_LENS_OFS	(S6E3HAE_SCR_CR_OFS)
#define S6E3HAE_COLOR_LENS_LEN	(24)

#define S6E3HAE_TRANS_MODE_OFS	(17)
#define S6E3HAE_TRANS_MODE_LEN	(1)
#endif /* CONFIG_EXYNOS_DECON_MDNIE_LITE */

#define MIN_S6E3HAE_FPS_DIV_COUNT (1)
#define MAX_S6E3HAE_FPS_DIV_COUNT (12)

#define MTP		(0xFF)

#define S6E3HAE_NR_GLUT_POINT (32)
#define S6E3HAE_GLUT_LEN (144)

#define S6E3HAE_SSR_ENABLE_VALUE	0xC4
#define S6E3HAE_SSR_ENABLE_MASK		0xFF
#define S6E3HAE_SSR_STATE_VALUE		0x10
#define S6E3HAE_SSR_STATE_MASK		0xFF

#define S6E3HAE_ECC_ENABLE_VALUE	0x00
#define S6E3HAE_ECC_ENABLE_MASK		0xFF

#define S6E3HAE_FLASH_LOADED_VALUE	0x00

enum {
	GAMMA_MODE2_MAPTBL,
	GAMMA_MODE2_LT_81_MAPTBL,
	GAMMA_MODE2_EXIT_LPM_MAPTBL,
	TSET_MAPTBL,
#ifdef CONFIG_SUPPORT_XTALK_MODE
	VGH_MAPTBL,
#endif
#ifdef CONFIG_SUPPORT_HMD
	/* HMD MAPTBL */
	HMD_GAMMA_MAPTBL,
	HMD_AOR_MAPTBL,
	HMD_ELVSS_MAPTBL,
#endif /* CONFIG_SUPPORT_HMD */
	SYNC_CONTROL_MAPTBL,
	VINT_MAPTBL,
	VINT_VRR_120HZ_MAPTBL,
	ACL_OPR_MAPTBL,
	IRC_MAPTBL,
	IRC_MODE_0_MAPTBL,
	IRC_MODE_1_MAPTBL,
	DSC_MAPTBL,
	PPS_MAPTBL,
	SCALER_MAPTBL,
	CASET_MAPTBL,
	PASET_MAPTBL,
	/* default */
	AOR_MANUAL_ONOFF_MAPTBL,
	AOR_MANUAL_VALUE_MAPTBL,
	OSC_MAPTBL,
	FPS_MAPTBL,
	VFP_MAPTBL,
	TE_TIMING_MAPTBL,
	FPS_LFD_OFF_MAPTBL,
	LPM_NIT_MAPTBL,
	LPM_WRDISBV_MAPTBL,
	LPM_AOR_OFF_MAPTBL,
#ifdef CONFIG_SUPPORT_GRAYSPOT_TEST
	GRAYSPOT_CAL_1_MAPTBL,
	GRAYSPOT_CAL_2_MAPTBL,
#endif
#ifdef CONFIG_SUPPORT_GRAM_CHECKSUM
	VDDM_MAPTBL,
	GRAM_IMG_MAPTBL,
	GRAM_INV_IMG_MAPTBL,
#endif
	SET_FFC_MAPTBL,
	POC_ONOFF_MAPTBL,
	MCD_RESISTANCE_MAPTBL,
	GAMMA_INTER_CONTROL_MAPTBL,
#ifdef CONFIG_SUPPORT_MAFPC
	MAFPC_ENA_MAPTBL,
	MAFPC_VBP_MAPTBL,
	MAFPC_CTRL_MAPTBL,
	MAFPC_SCALE_MAPTBL,
#endif
	POC_COMP_MAPTBL,
	DBV_MAPTBL,
	HBM_CYCLE_MAPTBL,
	DIMMING_FRAME_INIT_MAPTBL,
	DIMMING_FRAME_MAPTBL,
	DIMMING_TRANSITION_MAPTBL,
	DIA_ONOFF_MAPTBL,
	WACOM_SYNC_MAPTBL,
	LFD_MIN_MAPTBL,
	LFD_MAX_MAPTBL,
	LFD_FRAME_INSERTION_ONOFF_MAPTBL,
	LFD_3C_UPDATE_MAPTBL,
	LFD_FRAME_INSERTION_1_MAPTBL,
	LFD_FRAME_INSERTION_2_MAPTBL,
	LFD_FRAME_INSERTION_3_MAPTBL,
	LFD_MCA_DITHER_MAPTBL,
	TE_FRAME_SEL_MAPTBL,
	LFD_FRAME_SEL_MAPTBL,
	LPM_LFD_MIN_MAPTBL,
	LPM_LFD_MAX_MAPTBL,
	LPM_LTPS_MAPTBL,
#ifdef CONFIG_SUPPORT_BRIGHTDOT_TEST
	BRIGHTDOT_AOR_MAPTBL,
#endif
	GAMMA_SELECT_MAPTBL,
	GAMMA_MTP_MAPTBL,
	GLUT_CTRL_MAPTBL,
	GLUT_MAPTBL,
	MAX_MAPTBL,
};

enum {
#ifdef CONFIG_EXYNOS_DECON_LCD_COPR
	READ_COPR_SPI,
	READ_COPR_DSI,
#endif
	READ_ID,
	READ_COORDINATE,
	READ_CODE,
	READ_ELVSS,
	READ_ELVSS_TEMP_0,
	READ_ELVSS_TEMP_1,
	READ_DATE,
	READ_OCTA_ID,
	READ_CHIP_ID,
	/* for brightness debugging */
	READ_GAMMA_120HS,
	READ_GAMMA_120HS_HBM,
	READ_GAMMA_FLASH_120HS,
	READ_GAMMA_FLASH_120HS_HBM,
	READ_VINT,
	READ_ELVSS_T,
	READ_FLASH_LOADED,
	READ_IRC,
	READ_RDDPM,
	READ_RDDSM,
	READ_ERR,
	READ_ERR_FG,
	READ_DSI_ERR,
	READ_SELF_DIAG,
	READ_SELF_MASK_CHECKSUM,
	READ_SELF_MASK_CRC,
#ifdef CONFIG_SUPPORT_DDI_CMDLOG
	READ_CMDLOG,
#endif
#ifdef CONFIG_SUPPORT_DDI_FLASH
	READ_POC_CHKSUM,
	READ_POC_CTRL,
	READ_POC_DATA,
	READ_FLASH_MCD,
#endif
#ifdef CONFIG_SUPPORT_GRAM_CHECKSUM
	READ_GRAM_CHECKSUM,
#endif
	READ_MCD_RESISTANCE,
#ifdef CONFIG_SUPPORT_CCD_TEST
	READ_CCD_STATE,
#endif
	READ_SSR_ONOFF,
	READ_SSR_STATE,
	READ_ECC_TEST,
	READ_DECODER_TEST,
#ifdef CONFIG_SUPPORT_GRAYSPOT_TEST
	READ_GRAYSPOT_CAL_1,
	READ_GRAYSPOT_CAL_2,
#endif
#ifdef CONFIG_SUPPORT_MAFPC
	READ_MAFPC,
	READ_MAFPC_FLASH,

	READ_MAFPC_CRC,
#endif
	READ_SPSRAM_GAMMA_120HS,
};

enum {
#ifdef CONFIG_EXYNOS_DECON_LCD_COPR
	RES_COPR_SPI,
	RES_COPR_DSI,
#endif
	RES_ID,
	RES_COORDINATE,
	RES_CODE,
	RES_ELVSS,
	RES_ELVSS_TEMP_0,
	RES_ELVSS_TEMP_1,
	RES_DATE,
	RES_OCTA_ID,
	RES_CHIP_ID,
	/* for brightness debugging */
	RES_GAMMA_120HS,
	RES_GAMMA_120HS_HBM,
	RES_GAMMA_FLASH_120HS,
	RES_GAMMA_FLASH_120HS_HBM,
	RES_VINT,
	RES_ELVSS_T,
	RES_FLASH_LOADED,
	RES_IRC,
	RES_RDDPM,
	RES_RDDSM,
	RES_ERR,
	RES_ERR_FG,
	RES_DSI_ERR,
	RES_SELF_DIAG,
#ifdef CONFIG_SUPPORT_DDI_CMDLOG
	RES_CMDLOG,
#endif
#ifdef CONFIG_SUPPORT_GRAM_CHECKSUM
	RES_GRAM_CHECKSUM,
#endif
	RES_MCD_RESISTANCE,
#ifdef CONFIG_SUPPORT_CCD_TEST
	RES_CCD_STATE,
	RES_CCD_CHKSUM_PASS,
#endif
	RES_SSR_TEST,
	RES_ECC_TEST,
	RES_DECODER_TEST,
#ifdef CONFIG_SUPPORT_GRAYSPOT_TEST
	RES_GRAYSPOT_CAL_1,
	RES_GRAYSPOT_CAL_2,
#endif
	RES_SELF_MASK_CHECKSUM,
	RES_SELF_MASK_CRC,
#ifdef CONFIG_SUPPORT_MAFPC
	RES_MAFPC,
	RES_MAFPC_FLASH,
	RES_MAFPC_CRC,
#endif
	RES_SPSRAM_GAMMA_120HS_0,
	RES_SPSRAM_GAMMA_120HS_1,
	RES_SPSRAM_GAMMA_120HS_2,
	RES_SPSRAM_GAMMA_120HS_3,
	RES_SPSRAM_GAMMA_120HS_4,
	RES_SPSRAM_GAMMA_120HS_5,
	RES_SPSRAM_GAMMA_120HS_6,
	RES_SPSRAM_GAMMA_120HS_7,
	RES_SPSRAM_GAMMA_120HS_8,
	RES_SPSRAM_GAMMA_120HS_9,
	RES_SPSRAM_GAMMA_120HS_10,
	RES_SPSRAM_GAMMA_120HS_11,
};

static u8 S6E3HAE_ID[S6E3HAE_ID_LEN];
static u8 S6E3HAE_COORDINATE[S6E3HAE_COORDINATE_LEN];
static u8 S6E3HAE_CODE[S6E3HAE_CODE_LEN];
static u8 S6E3HAE_ELVSS[S6E3HAE_ELVSS_LEN];
static u8 S6E3HAE_ELVSS_TEMP_0[S6E3HAE_ELVSS_TEMP_0_LEN];
static u8 S6E3HAE_ELVSS_TEMP_1[S6E3HAE_ELVSS_TEMP_1_LEN];
static u8 S6E3HAE_DATE[S6E3HAE_DATE_LEN];
static u8 S6E3HAE_OCTA_ID[S6E3HAE_OCTA_ID_LEN];
/* for brightness debugging */
static u8 S6E3HAE_GAMMA_120HS[S6E3HAE_GAMMA_LEN];
static u8 S6E3HAE_GAMMA_120HS_HBM[S6E3HAE_GAMMA_LEN];
static u8 S6E3HAE_GAMMA_FLASH_120HS[S6E3HAE_GAMMA_FLASH_LEN];
static u8 S6E3HAE_GAMMA_FLASH_120HS_HBM[S6E3HAE_GAMMA_FLASH_LEN];

static u8 S6E3HAE_VINT[S6E3HAE_VINT_LEN];
static u8 S6E3HAE_ELVSS_T[S6E3HAE_ELVSS_T_LEN];
static u8 S6E3HAE_FLASH_LOADED[S6E3HAE_FLASH_LOADED_LEN];
static u8 S6E3HAE_IRC[S6E3HAE_IRC_LEN];

#ifdef CONFIG_EXYNOS_DECON_LCD_COPR
static u8 S6E3HAE_COPR_SPI[S6E3HAE_COPR_SPI_LEN];
static u8 S6E3HAE_COPR_DSI[S6E3HAE_COPR_DSI_LEN];
#endif

static u8 S6E3HAE_CHIP_ID[S6E3HAE_CHIP_ID_LEN];
static u8 S6E3HAE_RDDPM[S6E3HAE_RDDPM_LEN];
static u8 S6E3HAE_RDDSM[S6E3HAE_RDDSM_LEN];
static u8 S6E3HAE_ERR[S6E3HAE_ERR_LEN];
static u8 S6E3HAE_ERR_FG[S6E3HAE_ERR_FG_LEN];
static u8 S6E3HAE_DSI_ERR[S6E3HAE_DSI_ERR_LEN];
static u8 S6E3HAE_SELF_DIAG[S6E3HAE_SELF_DIAG_LEN];
#ifdef CONFIG_SUPPORT_DDI_CMDLOG
static u8 S6E3HAE_CMDLOG[S6E3HAE_CMDLOG_LEN];
#endif

#ifdef CONFIG_SUPPORT_GRAM_CHECKSUM
static u8 S6E3HAE_GRAM_CHECKSUM[S6E3HAE_GRAM_CHECKSUM_LEN];
#endif
static u8 S6E3HAE_MCD_RESISTANCE[S6E3HAE_MCD_RESISTANCE_LEN];
#ifdef CONFIG_SUPPORT_CCD_TEST
static u8 S6E3HAE_CCD_STATE[S6E3HAE_CCD_STATE_LEN];
static u8 S6E3HAE_CCD_CHKSUM_PASS[S6E3HAE_CCD_STATE_LEN] = { 0x00 };
#endif
static u8 S6E3HAE_SSR_TEST[S6E3HAE_SSR_ONOFF_LEN + S6E3HAE_SSR_STATE_LEN];
static u8 S6E3HAE_ECC_TEST[S6E3HAE_ECC_TEST_LEN];
static u8 S6E3HAE_DECODER_TEST[S6E3HAE_DECODER_TEST_LEN];

#ifdef CONFIG_SUPPORT_GRAYSPOT_TEST
static u8 S6E3HAE_GRAYSPOT_CAL_1[S6E3HAE_GRAYSPOT_CAL_1_LEN];
static u8 S6E3HAE_GRAYSPOT_CAL_2[S6E3HAE_GRAYSPOT_CAL_2_LEN];
#endif
static u8 S6E3HAE_SELF_MASK_CHECKSUM[S6E3HAE_SELF_MASK_CHECKSUM_LEN];
static u8 S6E3HAE_SELF_MASK_CRC[S6E3HAE_SELF_MASK_CRC_LEN];

#ifdef CONFIG_SUPPORT_MAFPC
static u8 S6E3HAE_MAFPC[S6E3HAE_MAFPC_LEN];
static u8 S6E3HAE_MAFPC_FLASH[S6E3HAE_MAFPC_FLASH_LEN];
static u8 S6E3HAE_MAFPC_CRC[S6E3HAE_MAFPC_CRC_LEN];
#endif
static u8 S6E3HAE_SPSRAM_GAMMA_120HS_0[S6E3HAE_SPSRAM_GAMMA_LEN];
static u8 S6E3HAE_SPSRAM_GAMMA_120HS_1[S6E3HAE_SPSRAM_GAMMA_LEN];
static u8 S6E3HAE_SPSRAM_GAMMA_120HS_2[S6E3HAE_SPSRAM_GAMMA_LEN];
static u8 S6E3HAE_SPSRAM_GAMMA_120HS_3[S6E3HAE_SPSRAM_GAMMA_LEN];
static u8 S6E3HAE_SPSRAM_GAMMA_120HS_4[S6E3HAE_SPSRAM_GAMMA_LEN];
static u8 S6E3HAE_SPSRAM_GAMMA_120HS_5[S6E3HAE_SPSRAM_GAMMA_LEN];
static u8 S6E3HAE_SPSRAM_GAMMA_120HS_6[S6E3HAE_SPSRAM_GAMMA_LEN];
static u8 S6E3HAE_SPSRAM_GAMMA_120HS_7[S6E3HAE_SPSRAM_GAMMA_LEN];
static u8 S6E3HAE_SPSRAM_GAMMA_120HS_8[S6E3HAE_SPSRAM_GAMMA_LEN];
static u8 S6E3HAE_SPSRAM_GAMMA_120HS_9[S6E3HAE_SPSRAM_GAMMA_LEN];
static u8 S6E3HAE_SPSRAM_GAMMA_120HS_10[S6E3HAE_SPSRAM_GAMMA_LEN];
static u8 S6E3HAE_SPSRAM_GAMMA_120HS_11[S6E3HAE_SPSRAM_GAMMA_LEN];

static struct rdinfo s6e3hae_rditbl[] = {
	[READ_ID] = RDINFO_INIT(id, DSI_PKT_TYPE_RD, S6E3HAE_ID_REG, S6E3HAE_ID_OFS, S6E3HAE_ID_LEN),
	[READ_COORDINATE] = RDINFO_INIT(coordinate, DSI_PKT_TYPE_RD, S6E3HAE_COORDINATE_REG, S6E3HAE_COORDINATE_OFS, S6E3HAE_COORDINATE_LEN),
	[READ_CODE] = RDINFO_INIT(code, DSI_PKT_TYPE_RD, S6E3HAE_CODE_REG, S6E3HAE_CODE_OFS, S6E3HAE_CODE_LEN),
	[READ_ELVSS] = RDINFO_INIT(elvss, DSI_PKT_TYPE_RD, S6E3HAE_ELVSS_REG, S6E3HAE_ELVSS_OFS, S6E3HAE_ELVSS_LEN),
	[READ_ELVSS_TEMP_0] = RDINFO_INIT(elvss_temp_0, DSI_PKT_TYPE_RD, S6E3HAE_ELVSS_TEMP_0_REG, S6E3HAE_ELVSS_TEMP_0_OFS, S6E3HAE_ELVSS_TEMP_0_LEN),
	[READ_ELVSS_TEMP_1] = RDINFO_INIT(elvss_temp_1, DSI_PKT_TYPE_RD, S6E3HAE_ELVSS_TEMP_1_REG, S6E3HAE_ELVSS_TEMP_1_OFS, S6E3HAE_ELVSS_TEMP_1_LEN),
	[READ_DATE] = RDINFO_INIT(date, DSI_PKT_TYPE_RD, S6E3HAE_DATE_REG, S6E3HAE_DATE_OFS, S6E3HAE_DATE_LEN),
	[READ_OCTA_ID] = RDINFO_INIT(octa_id, DSI_PKT_TYPE_RD, S6E3HAE_OCTA_ID_REG, S6E3HAE_OCTA_ID_OFS, S6E3HAE_OCTA_ID_LEN),
	/* for brightness debugging */
	[READ_GAMMA_120HS] = RDINFO_INIT(gamma_120hs, DSI_PKT_TYPE_RD, S6E3HAE_GAMMA_REG, S6E3HAE_GAMMA_OFS, S6E3HAE_GAMMA_LEN),
	[READ_GAMMA_120HS_HBM] = RDINFO_INIT(gamma_120hs_hbm, DSI_PKT_TYPE_RD, S6E3HAE_GAMMA_REG, S6E3HAE_GAMMA_OFS, S6E3HAE_GAMMA_LEN),
	[READ_GAMMA_FLASH_120HS] = RDINFO_INIT(gamma_flash_120hs, DSI_PKT_TYPE_RD, S6E3HAE_GAMMA_FLASH_REG, S6E3HAE_GAMMA_FLASH_OFS, S6E3HAE_GAMMA_FLASH_LEN),
	[READ_GAMMA_FLASH_120HS_HBM] = RDINFO_INIT(gamma_flash_120hs_hbm, DSI_PKT_TYPE_RD, S6E3HAE_GAMMA_FLASH_REG, S6E3HAE_GAMMA_FLASH_OFS, S6E3HAE_GAMMA_FLASH_LEN),
	[READ_VINT] = RDINFO_INIT(vint, DSI_PKT_TYPE_RD, S6E3HAE_VINT_REG, S6E3HAE_VINT_OFS, S6E3HAE_VINT_LEN),
	[READ_ELVSS_T] = RDINFO_INIT(elvss_t, DSI_PKT_TYPE_RD, S6E3HAE_ELVSS_T_REG, S6E3HAE_ELVSS_T_OFS, S6E3HAE_ELVSS_T_LEN),
	[READ_FLASH_LOADED] = RDINFO_INIT(flash_loaded, DSI_PKT_TYPE_RD, S6E3HAE_FLASH_LOADED_REG, S6E3HAE_FLASH_LOADED_OFS, S6E3HAE_FLASH_LOADED_LEN),
	[READ_IRC] = RDINFO_INIT(irc, DSI_PKT_TYPE_RD, S6E3HAE_IRC_REG, S6E3HAE_IRC_OFS, S6E3HAE_IRC_LEN),
#ifdef CONFIG_EXYNOS_DECON_LCD_COPR
	[READ_COPR_SPI] = RDINFO_INIT(copr_spi, SPI_PKT_TYPE_RD, S6E3HAE_COPR_SPI_REG, S6E3HAE_COPR_SPI_OFS, S6E3HAE_COPR_SPI_LEN),
	[READ_COPR_DSI] = RDINFO_INIT(copr_dsi, DSI_PKT_TYPE_RD, S6E3HAE_COPR_DSI_REG, S6E3HAE_COPR_DSI_OFS, S6E3HAE_COPR_DSI_LEN),
#endif
	[READ_CHIP_ID] = RDINFO_INIT(chip_id, DSI_PKT_TYPE_RD, S6E3HAE_CHIP_ID_REG, S6E3HAE_CHIP_ID_OFS, S6E3HAE_CHIP_ID_LEN),
	[READ_RDDPM] = RDINFO_INIT(rddpm, DSI_PKT_TYPE_RD, S6E3HAE_RDDPM_REG, S6E3HAE_RDDPM_OFS, S6E3HAE_RDDPM_LEN),
	[READ_RDDSM] = RDINFO_INIT(rddsm, DSI_PKT_TYPE_RD, S6E3HAE_RDDSM_REG, S6E3HAE_RDDSM_OFS, S6E3HAE_RDDSM_LEN),
	[READ_ERR] = RDINFO_INIT(err, DSI_PKT_TYPE_RD, S6E3HAE_ERR_REG, S6E3HAE_ERR_OFS, S6E3HAE_ERR_LEN),
	[READ_ERR_FG] = RDINFO_INIT(err_fg, DSI_PKT_TYPE_RD, S6E3HAE_ERR_FG_REG, S6E3HAE_ERR_FG_OFS, S6E3HAE_ERR_FG_LEN),
	[READ_DSI_ERR] = RDINFO_INIT(dsi_err, DSI_PKT_TYPE_RD, S6E3HAE_DSI_ERR_REG, S6E3HAE_DSI_ERR_OFS, S6E3HAE_DSI_ERR_LEN),
	[READ_SELF_DIAG] = RDINFO_INIT(self_diag, DSI_PKT_TYPE_RD, S6E3HAE_SELF_DIAG_REG, S6E3HAE_SELF_DIAG_OFS, S6E3HAE_SELF_DIAG_LEN),
#ifdef CONFIG_SUPPORT_DDI_CMDLOG
	[READ_CMDLOG] = RDINFO_INIT(cmdlog, DSI_PKT_TYPE_RD, S6E3HAE_CMDLOG_REG, S6E3HAE_CMDLOG_OFS, S6E3HAE_CMDLOG_LEN),
#endif
#ifdef CONFIG_SUPPORT_GRAM_CHECKSUM
	[READ_GRAM_CHECKSUM] = RDINFO_INIT(gram_checksum, DSI_PKT_TYPE_RD, S6E3HAE_GRAM_CHECKSUM_REG, S6E3HAE_GRAM_CHECKSUM_OFS, S6E3HAE_GRAM_CHECKSUM_LEN),
#endif
	[READ_MCD_RESISTANCE] = RDINFO_INIT(mcd_resistance, DSI_PKT_TYPE_RD, S6E3HAE_MCD_RESISTANCE_REG, S6E3HAE_MCD_RESISTANCE_OFS, S6E3HAE_MCD_RESISTANCE_LEN),
#ifdef CONFIG_SUPPORT_CCD_TEST
	[READ_CCD_STATE] = RDINFO_INIT(ccd_state, DSI_PKT_TYPE_RD, S6E3HAE_CCD_STATE_REG, S6E3HAE_CCD_STATE_OFS, S6E3HAE_CCD_STATE_LEN),
#endif
	[READ_SSR_ONOFF] = RDINFO_INIT(ssr_onoff, DSI_PKT_TYPE_RD, S6E3HAE_SSR_ONOFF_REG, S6E3HAE_SSR_ONOFF_OFS, S6E3HAE_SSR_ONOFF_LEN),
	[READ_SSR_STATE] = RDINFO_INIT(ssr_state, DSI_PKT_TYPE_RD, S6E3HAE_SSR_STATE_REG, S6E3HAE_SSR_STATE_OFS, S6E3HAE_SSR_STATE_LEN),
	[READ_ECC_TEST] = RDINFO_INIT(ecc_test, DSI_PKT_TYPE_RD, S6E3HAE_ECC_TEST_REG, S6E3HAE_ECC_TEST_OFS, S6E3HAE_ECC_TEST_LEN),
	[READ_DECODER_TEST] = RDINFO_INIT(decoder_test, DSI_PKT_TYPE_RD, S6E3HAE_DECODER_TEST_REG, S6E3HAE_DECODER_TEST_OFS, S6E3HAE_DECODER_TEST_LEN),
#ifdef CONFIG_SUPPORT_GRAYSPOT_TEST
	[READ_GRAYSPOT_CAL_1] = RDINFO_INIT(grayspot_cal_1, DSI_PKT_TYPE_RD, S6E3HAE_GRAYSPOT_CAL_1_REG, S6E3HAE_GRAYSPOT_CAL_1_OFS, S6E3HAE_GRAYSPOT_CAL_1_LEN),
	[READ_GRAYSPOT_CAL_2] = RDINFO_INIT(grayspot_cal_2, DSI_PKT_TYPE_RD, S6E3HAE_GRAYSPOT_CAL_2_REG, S6E3HAE_GRAYSPOT_CAL_2_OFS, S6E3HAE_GRAYSPOT_CAL_2_LEN),
#endif
	[READ_SELF_MASK_CHECKSUM] = RDINFO_INIT(self_mask_checksum, DSI_PKT_TYPE_RD, S6E3HAE_SELF_MASK_CHECKSUM_REG, S6E3HAE_SELF_MASK_CHECKSUM_OFS, S6E3HAE_SELF_MASK_CHECKSUM_LEN),
	[READ_SELF_MASK_CRC] = RDINFO_INIT(self_mask_crc, DSI_PKT_TYPE_RD, S6E3HAE_SELF_MASK_CRC_REG, S6E3HAE_SELF_MASK_CRC_OFS, S6E3HAE_SELF_MASK_CRC_LEN),
#ifdef CONFIG_SUPPORT_MAFPC
	[READ_MAFPC] = RDINFO_INIT(mafpc, DSI_PKT_TYPE_RD, S6E3HAE_MAFPC_REG, S6E3HAE_MAFPC_OFS, S6E3HAE_MAFPC_LEN),
	[READ_MAFPC_FLASH] = RDINFO_INIT(mafpc_flash, DSI_PKT_TYPE_RD, S6E3HAE_MAFPC_FLASH_REG, S6E3HAE_MAFPC_FLASH_OFS, S6E3HAE_MAFPC_FLASH_LEN),
	[READ_MAFPC_CRC] = RDINFO_INIT(mafpc_crc, DSI_PKT_TYPE_RD, S6E3HAE_MAFPC_CRC_REG, S6E3HAE_MAFPC_CRC_OFS, S6E3HAE_MAFPC_CRC_LEN),
#endif
	[READ_SPSRAM_GAMMA_120HS] = RDINFO_INIT(spsram_gamma_120hs, DSI_PKT_TYPE_RD, S6E3HAE_SPSRAM_GAMMA_REG, S6E3HAE_SPSRAM_GAMMA_OFS, S6E3HAE_SPSRAM_GAMMA_LEN),
};

static DEFINE_RESUI(id, &s6e3hae_rditbl[READ_ID], 0);
static DEFINE_RESUI(coordinate, &s6e3hae_rditbl[READ_COORDINATE], 0);
static DEFINE_RESUI(code, &s6e3hae_rditbl[READ_CODE], 0);
static DEFINE_RESUI(elvss, &s6e3hae_rditbl[READ_ELVSS], 0);
static DEFINE_RESUI(elvss_temp_0, &s6e3hae_rditbl[READ_ELVSS_TEMP_0], 0);
static DEFINE_RESUI(elvss_temp_1, &s6e3hae_rditbl[READ_ELVSS_TEMP_1], 0);

static DEFINE_RESUI(date, &s6e3hae_rditbl[READ_DATE], 0);
static DEFINE_RESUI(octa_id, &s6e3hae_rditbl[READ_OCTA_ID], 0);
/* for brightness debugging */
static DEFINE_RESUI(gamma_120hs, &s6e3hae_rditbl[READ_GAMMA_120HS], 0);
static DEFINE_RESUI(gamma_120hs_hbm, &s6e3hae_rditbl[READ_GAMMA_120HS_HBM], 0);
static DEFINE_RESUI(gamma_flash_120hs, &s6e3hae_rditbl[READ_GAMMA_FLASH_120HS], 0);
static DEFINE_RESUI(gamma_flash_120hs_hbm, &s6e3hae_rditbl[READ_GAMMA_FLASH_120HS_HBM], 0);

static DEFINE_RESUI(vint, &s6e3hae_rditbl[READ_VINT], 0);
static DEFINE_RESUI(elvss_t, &s6e3hae_rditbl[READ_ELVSS_T], 0);
static DEFINE_RESUI(flash_loaded, &s6e3hae_rditbl[READ_FLASH_LOADED], 0);
static DEFINE_RESUI(irc, &s6e3hae_rditbl[READ_IRC], 0);
#ifdef CONFIG_EXYNOS_DECON_LCD_COPR
static DEFINE_RESUI(copr_spi, &s6e3hae_rditbl[READ_COPR_SPI], 0);
static DEFINE_RESUI(copr_dsi, &s6e3hae_rditbl[READ_COPR_DSI], 0);
#endif
static DEFINE_RESUI(chip_id, &s6e3hae_rditbl[READ_CHIP_ID], 0);
static DEFINE_RESUI(rddpm, &s6e3hae_rditbl[READ_RDDPM], 0);
static DEFINE_RESUI(rddsm, &s6e3hae_rditbl[READ_RDDSM], 0);
static DEFINE_RESUI(err, &s6e3hae_rditbl[READ_ERR], 0);
static DEFINE_RESUI(err_fg, &s6e3hae_rditbl[READ_ERR_FG], 0);
static DEFINE_RESUI(dsi_err, &s6e3hae_rditbl[READ_DSI_ERR], 0);
static DEFINE_RESUI(self_diag, &s6e3hae_rditbl[READ_SELF_DIAG], 0);

#ifdef CONFIG_SUPPORT_DDI_CMDLOG
static DEFINE_RESUI(cmdlog, &s6e3hae_rditbl[READ_CMDLOG], 0);
#endif

#ifdef CONFIG_SUPPORT_GRAM_CHECKSUM
static DEFINE_RESUI(gram_checksum, &s6e3hae_rditbl[READ_GRAM_CHECKSUM], 0);
#endif
#ifdef CONFIG_SUPPORT_CCD_TEST
static DEFINE_RESUI(ccd_state, &s6e3hae_rditbl[READ_CCD_STATE], 0);
#endif
static struct res_update_info RESUI(ssr_test)[] = {
	{
		.offset = 0,
		.rditbl = &s6e3hae_rditbl[READ_SSR_ONOFF],
	}, {
		.offset = S6E3HAE_SSR_ONOFF_LEN,
		.rditbl = &s6e3hae_rditbl[READ_SSR_STATE],
	},
};
static DEFINE_RESUI(ecc_test, &s6e3hae_rditbl[READ_ECC_TEST], 0);
static DEFINE_RESUI(decoder_test, &s6e3hae_rditbl[READ_DECODER_TEST], 0);

#ifdef CONFIG_SUPPORT_GRAYSPOT_TEST
static DEFINE_RESUI(grayspot_cal_1, &s6e3hae_rditbl[READ_GRAYSPOT_CAL_1], 0);
static DEFINE_RESUI(grayspot_cal_2, &s6e3hae_rditbl[READ_GRAYSPOT_CAL_2], 0);
#endif

static DEFINE_RESUI(mcd_resistance, &s6e3hae_rditbl[READ_MCD_RESISTANCE], 0);
static DEFINE_RESUI(self_mask_checksum, &s6e3hae_rditbl[READ_SELF_MASK_CHECKSUM], 0);
static DEFINE_RESUI(self_mask_crc, &s6e3hae_rditbl[READ_SELF_MASK_CRC], 0);

#ifdef CONFIG_SUPPORT_MAFPC
static DEFINE_RESUI(mafpc, &s6e3hae_rditbl[READ_MAFPC], 0);
static DEFINE_RESUI(mafpc_flash, &s6e3hae_rditbl[READ_MAFPC_FLASH], 0);
static DEFINE_RESUI(mafpc_crc, &s6e3hae_rditbl[READ_MAFPC_CRC], 0);
#endif
static DEFINE_RESUI(spsram_gamma_120hs, &s6e3hae_rditbl[READ_SPSRAM_GAMMA_120HS], 0);

static struct resinfo s6e3hae_restbl[] = {
	[RES_ID] = RESINFO_INIT(id, S6E3HAE_ID, RESUI(id)),
	[RES_COORDINATE] = RESINFO_INIT(coordinate, S6E3HAE_COORDINATE, RESUI(coordinate)),
	[RES_CODE] = RESINFO_INIT(code, S6E3HAE_CODE, RESUI(code)),
	[RES_ELVSS] = RESINFO_INIT(elvss, S6E3HAE_ELVSS, RESUI(elvss)),
	[RES_ELVSS_TEMP_0] = RESINFO_INIT(elvss_temp_0, S6E3HAE_ELVSS_TEMP_0, RESUI(elvss_temp_0)),
	[RES_ELVSS_TEMP_1] = RESINFO_INIT(elvss_temp_1, S6E3HAE_ELVSS_TEMP_1, RESUI(elvss_temp_1)),
	[RES_DATE] = RESINFO_INIT(date, S6E3HAE_DATE, RESUI(date)),
	[RES_OCTA_ID] = RESINFO_INIT(octa_id, S6E3HAE_OCTA_ID, RESUI(octa_id)),
	/* for brightness debugging */
	[RES_GAMMA_120HS] = RESINFO_INIT(gamma_120hs, S6E3HAE_GAMMA_120HS, RESUI(gamma_120hs)),
	[RES_GAMMA_120HS_HBM] = RESINFO_INIT(gamma_120hs_hbm, S6E3HAE_GAMMA_120HS_HBM, RESUI(gamma_120hs_hbm)),
	[RES_GAMMA_FLASH_120HS] = RESINFO_INIT(gamma_flash_120hs, S6E3HAE_GAMMA_FLASH_120HS, RESUI(gamma_flash_120hs)),
	[RES_GAMMA_FLASH_120HS_HBM] = RESINFO_INIT(gamma_flash_120hs_hbm, S6E3HAE_GAMMA_FLASH_120HS_HBM, RESUI(gamma_flash_120hs_hbm)),
	[RES_VINT] = RESINFO_INIT(vint, S6E3HAE_VINT, RESUI(vint)),
	[RES_ELVSS_T] = RESINFO_INIT(elvss_t, S6E3HAE_ELVSS_T, RESUI(elvss_t)),
	[RES_FLASH_LOADED] = RESINFO_INIT(flash_loaded, S6E3HAE_FLASH_LOADED, RESUI(flash_loaded)),
	[RES_IRC] = RESINFO_INIT(irc, S6E3HAE_IRC, RESUI(irc)),
#ifdef CONFIG_EXYNOS_DECON_LCD_COPR
	[RES_COPR_SPI] = RESINFO_INIT(copr_spi, S6E3HAE_COPR_SPI, RESUI(copr_spi)),
	[RES_COPR_DSI] = RESINFO_INIT(copr_dsi, S6E3HAE_COPR_DSI, RESUI(copr_dsi)),
#endif
	[RES_CHIP_ID] = RESINFO_INIT(chip_id, S6E3HAE_CHIP_ID, RESUI(chip_id)),
	[RES_RDDPM] = RESINFO_INIT(rddpm, S6E3HAE_RDDPM, RESUI(rddpm)),
	[RES_RDDSM] = RESINFO_INIT(rddsm, S6E3HAE_RDDSM, RESUI(rddsm)),
	[RES_ERR] = RESINFO_INIT(err, S6E3HAE_ERR, RESUI(err)),
	[RES_ERR_FG] = RESINFO_INIT(err_fg, S6E3HAE_ERR_FG, RESUI(err_fg)),
	[RES_DSI_ERR] = RESINFO_INIT(dsi_err, S6E3HAE_DSI_ERR, RESUI(dsi_err)),
	[RES_SELF_DIAG] = RESINFO_INIT(self_diag, S6E3HAE_SELF_DIAG, RESUI(self_diag)),
#ifdef CONFIG_SUPPORT_DDI_CMDLOG
	[RES_CMDLOG] = RESINFO_INIT(cmdlog, S6E3HAE_CMDLOG, RESUI(cmdlog)),
#endif
#ifdef CONFIG_SUPPORT_GRAM_CHECKSUM
	[RES_GRAM_CHECKSUM] = RESINFO_INIT(gram_checksum, S6E3HAE_GRAM_CHECKSUM, RESUI(gram_checksum)),
#endif
	[RES_MCD_RESISTANCE] = RESINFO_INIT(mcd_resistance, S6E3HAE_MCD_RESISTANCE, RESUI(mcd_resistance)),
#ifdef CONFIG_SUPPORT_CCD_TEST
	[RES_CCD_STATE] = RESINFO_INIT(ccd_state, S6E3HAE_CCD_STATE, RESUI(ccd_state)),
	[RES_CCD_CHKSUM_PASS] = {
		.name = "ccd_chksum_pass",
		.type = CMD_TYPE_RES,
		.state = RES_UNINITIALIZED,
		.data = S6E3HAE_CCD_CHKSUM_PASS,
		.dlen = ARRAY_SIZE(S6E3HAE_CCD_CHKSUM_PASS),
		.resui = NULL,
		.nr_resui = 0,
	},
#endif
	[RES_SSR_TEST] = RESINFO_INIT(ssr_test, S6E3HAE_SSR_TEST, RESUI(ssr_test)),
	[RES_ECC_TEST] = RESINFO_INIT(ecc_test, S6E3HAE_ECC_TEST, RESUI(ecc_test)),
	[RES_DECODER_TEST] = RESINFO_INIT(decoder_test, S6E3HAE_DECODER_TEST, RESUI(decoder_test)),
#ifdef CONFIG_SUPPORT_GRAYSPOT_TEST
	[RES_GRAYSPOT_CAL_1] = RESINFO_INIT(grayspot_cal_1, S6E3HAE_GRAYSPOT_CAL_1, RESUI(grayspot_cal_1)),
	[RES_GRAYSPOT_CAL_2] = RESINFO_INIT(grayspot_cal_2, S6E3HAE_GRAYSPOT_CAL_2, RESUI(grayspot_cal_2)),
#endif
	[RES_SELF_MASK_CHECKSUM] = RESINFO_INIT(self_mask_checksum, S6E3HAE_SELF_MASK_CHECKSUM, RESUI(self_mask_checksum)),
	[RES_SELF_MASK_CRC] = RESINFO_INIT(self_mask_crc, S6E3HAE_SELF_MASK_CRC, RESUI(self_mask_crc)),
#ifdef CONFIG_SUPPORT_MAFPC
	[RES_MAFPC] = RESINFO_INIT(mafpc, S6E3HAE_MAFPC, RESUI(mafpc)),
	[RES_MAFPC_FLASH] = RESINFO_INIT(mafpc_flash, S6E3HAE_MAFPC_FLASH, RESUI(mafpc_flash)),
	[RES_MAFPC_CRC] = RESINFO_INIT(mafpc_crc, S6E3HAE_MAFPC_CRC, RESUI(mafpc_crc)),
#endif
	[RES_SPSRAM_GAMMA_120HS_0] = RESINFO_INIT(spsram_gamma_120hs_0, S6E3HAE_SPSRAM_GAMMA_120HS_0, RESUI(spsram_gamma_120hs)),
	[RES_SPSRAM_GAMMA_120HS_1] = RESINFO_INIT(spsram_gamma_120hs_1, S6E3HAE_SPSRAM_GAMMA_120HS_1, RESUI(spsram_gamma_120hs)),
	[RES_SPSRAM_GAMMA_120HS_2] = RESINFO_INIT(spsram_gamma_120hs_2, S6E3HAE_SPSRAM_GAMMA_120HS_2, RESUI(spsram_gamma_120hs)),
	[RES_SPSRAM_GAMMA_120HS_3] = RESINFO_INIT(spsram_gamma_120hs_3, S6E3HAE_SPSRAM_GAMMA_120HS_3, RESUI(spsram_gamma_120hs)),
	[RES_SPSRAM_GAMMA_120HS_4] = RESINFO_INIT(spsram_gamma_120hs_4, S6E3HAE_SPSRAM_GAMMA_120HS_4, RESUI(spsram_gamma_120hs)),
	[RES_SPSRAM_GAMMA_120HS_5] = RESINFO_INIT(spsram_gamma_120hs_5, S6E3HAE_SPSRAM_GAMMA_120HS_5, RESUI(spsram_gamma_120hs)),
	[RES_SPSRAM_GAMMA_120HS_6] = RESINFO_INIT(spsram_gamma_120hs_6, S6E3HAE_SPSRAM_GAMMA_120HS_6, RESUI(spsram_gamma_120hs)),
	[RES_SPSRAM_GAMMA_120HS_7] = RESINFO_INIT(spsram_gamma_120hs_7, S6E3HAE_SPSRAM_GAMMA_120HS_7, RESUI(spsram_gamma_120hs)),
	[RES_SPSRAM_GAMMA_120HS_8] = RESINFO_INIT(spsram_gamma_120hs_8, S6E3HAE_SPSRAM_GAMMA_120HS_8, RESUI(spsram_gamma_120hs)),
	[RES_SPSRAM_GAMMA_120HS_9] = RESINFO_INIT(spsram_gamma_120hs_9, S6E3HAE_SPSRAM_GAMMA_120HS_9, RESUI(spsram_gamma_120hs)),
	[RES_SPSRAM_GAMMA_120HS_10] = RESINFO_INIT(spsram_gamma_120hs_10, S6E3HAE_SPSRAM_GAMMA_120HS_10, RESUI(spsram_gamma_120hs)),
	[RES_SPSRAM_GAMMA_120HS_11] = RESINFO_INIT(spsram_gamma_120hs_11, S6E3HAE_SPSRAM_GAMMA_120HS_11, RESUI(spsram_gamma_120hs)),
};

enum {
	DUMP_RDDPM = 0,
	DUMP_RDDPM_SLEEP_IN,
	DUMP_RDDSM,
	DUMP_ERR,
	DUMP_ERR_FG,
	DUMP_DSI_ERR,
	DUMP_SELF_DIAG,
	DUMP_SELF_MASK_CRC,
#ifdef CONFIG_SUPPORT_DDI_CMDLOG
	DUMP_CMDLOG,
#endif
#ifdef CONFIG_SUPPORT_MAFPC
	DUMP_MAFPC,
	DUMP_MAFPC_FLASH,
#endif
	DUMP_SSR,
	DUMP_ECC,
	DUMP_FLASH_LOADED,
};

__visible_for_testing int show_rddpm(struct dumpinfo *info);
__visible_for_testing int show_rddpm_before_sleep_in(struct dumpinfo *info);
__visible_for_testing int show_rddsm(struct dumpinfo *info);
__visible_for_testing int show_err(struct dumpinfo *info);
__visible_for_testing int show_err_fg(struct dumpinfo *info);
__visible_for_testing int show_dsi_err(struct dumpinfo *info);
__visible_for_testing int show_self_diag(struct dumpinfo *info);
#ifdef CONFIG_SUPPORT_DDI_CMDLOG
__visible_for_testing int show_cmdlog(struct dumpinfo *info);
#endif
__visible_for_testing int show_self_mask_crc(struct dumpinfo *info);
#ifdef CONFIG_SUPPORT_MAFPC
__visible_for_testing int show_mafpc_log(struct dumpinfo *info);
__visible_for_testing int show_mafpc_flash_log(struct dumpinfo *info);
#endif
__visible_for_testing int show_ssr_err(struct dumpinfo *info);
__visible_for_testing int show_ecc_err(struct dumpinfo *info);
__visible_for_testing int show_flash_loaded(struct dumpinfo *info);

static struct dumpinfo s6e3hae_dmptbl[] = {
	[DUMP_RDDPM] = DUMPINFO_INIT(rddpm, &s6e3hae_restbl[RES_RDDPM], show_rddpm),
	[DUMP_RDDPM_SLEEP_IN] = DUMPINFO_INIT(rddpm, &s6e3hae_restbl[RES_RDDPM], show_rddpm_before_sleep_in),
	[DUMP_RDDSM] = DUMPINFO_INIT(rddsm, &s6e3hae_restbl[RES_RDDSM], show_rddsm),
	[DUMP_ERR] = DUMPINFO_INIT(err, &s6e3hae_restbl[RES_ERR], show_err),
	[DUMP_ERR_FG] = DUMPINFO_INIT(err_fg, &s6e3hae_restbl[RES_ERR_FG], show_err_fg),
	[DUMP_DSI_ERR] = DUMPINFO_INIT(dsi_err, &s6e3hae_restbl[RES_DSI_ERR], show_dsi_err),
	[DUMP_SELF_DIAG] = DUMPINFO_INIT(self_diag, &s6e3hae_restbl[RES_SELF_DIAG], show_self_diag),
#ifdef CONFIG_SUPPORT_DDI_CMDLOG
	[DUMP_CMDLOG] = DUMPINFO_INIT(cmdlog, &s6e3hae_restbl[RES_CMDLOG], show_cmdlog),
#endif
	[DUMP_SELF_MASK_CRC] = DUMPINFO_INIT(self_mask_crc, &s6e3hae_restbl[RES_SELF_MASK_CRC], show_self_mask_crc),
#ifdef CONFIG_SUPPORT_MAFPC
	[DUMP_MAFPC] = DUMPINFO_INIT(mafpc, &s6e3hae_restbl[RES_MAFPC], show_mafpc_log),
	[DUMP_MAFPC_FLASH] = DUMPINFO_INIT(mafpc_flash, &s6e3hae_restbl[RES_MAFPC_FLASH], show_mafpc_flash_log),
#endif
	[DUMP_SSR] = DUMPINFO_INIT(ssr, &s6e3hae_restbl[RES_SSR_TEST], show_ssr_err),
	[DUMP_ECC] = DUMPINFO_INIT(ecc, &s6e3hae_restbl[RES_ECC_TEST], show_ecc_err),
	[DUMP_FLASH_LOADED] = DUMPINFO_INIT(flash_loaded, &s6e3hae_restbl[RES_FLASH_LOADED], show_flash_loaded),
};

/* use according to adaptive_control sysfs */
enum {
	S6E3HAE_ACL_OPR_0,
	S6E3HAE_ACL_OPR_1,
	S6E3HAE_ACL_OPR_2,
	S6E3HAE_ACL_OPR_3,
	MAX_S6E3HAE_ACL_OPR
};

enum {
	S6E3HAE_AID_2_CYCLE,
	S6E3HAE_AID_4_CYCLE,
	MAX_S6E3HAE_AID_CYCLE,
};

enum {
	S6E3HAE_SCALER_OFF,
	S6E3HAE_SCALER_x1_78,
	S6E3HAE_SCALER_x4,
	MAX_S6E3HAE_SCALER,
};

static u32 S6E3HAE_SCALER_1440[] = {
	[S6E3HAE_SCALER_OFF] = 1440,
	[S6E3HAE_SCALER_x1_78] = 1080,
	[S6E3HAE_SCALER_x4] = 720,
};

/* Variable Refresh Rate */
enum {
	S6E3HAE_VRR_MODE_NS,
	S6E3HAE_VRR_MODE_HS,
	MAX_S6E3HAE_VRR_MODE,
};

enum {
	/* 60NS BASED VRR */
	S6E3HAE_VRR_60NS,
	/* 48NS BASED VRR */
	S6E3HAE_VRR_48NS,
	/* 120HS BASED VRR */
	S6E3HAE_VRR_120HS,
	S6E3HAE_VRR_60HS_120HS_TE_HW_SKIP_1,
	S6E3HAE_VRR_30HS_120HS_TE_HW_SKIP_3,
	S6E3HAE_VRR_24HS_120HS_TE_HW_SKIP_4,
	S6E3HAE_VRR_10HS_120HS_TE_HW_SKIP_11,
	/* 96HS BASED VRR */
	S6E3HAE_VRR_96HS,
	S6E3HAE_VRR_48HS_96HS_TE_HW_SKIP_1,
	MAX_S6E3HAE_VRR,
};

enum {
	S6E3HAE_RESOL_1440x3088,
	S6E3HAE_RESOL_1080x2316,
	S6E3HAE_RESOL_720x1544,
};

enum {
	/* RESOLUTION : WQHD */
	/* 60NS BASED DISPLAY_MODE */
	S6E3HAE_DISPLAY_MODE_1440x3088_60NS,
	/* 48NS BASED DISPLAY_MODE */
	S6E3HAE_DISPLAY_MODE_1440x3088_48NS,
	/* 120HS BASED DISPLAY_MODE */
	S6E3HAE_DISPLAY_MODE_1440x3088_120HS,
	S6E3HAE_DISPLAY_MODE_1440x3088_60HS_120HS_TE_HW_SKIP_1,
	S6E3HAE_DISPLAY_MODE_1440x3088_30HS_120HS_TE_HW_SKIP_3,
	S6E3HAE_DISPLAY_MODE_1440x3088_24HS_120HS_TE_HW_SKIP_4,
	S6E3HAE_DISPLAY_MODE_1440x3088_10HS_120HS_TE_HW_SKIP_11,
	/* 96HS BASED DISPLAY_MODE */
	S6E3HAE_DISPLAY_MODE_1440x3088_96HS,
	S6E3HAE_DISPLAY_MODE_1440x3088_48HS_96HS_TE_HW_SKIP_1,

	/* RESOLUTION : FHD */
	/* 60NS BASED DISPLAY_MODE */
	S6E3HAE_DISPLAY_MODE_1080x2316_60NS,
	/* 48NS BASED DISPLAY_MODE */
	S6E3HAE_DISPLAY_MODE_1080x2316_48NS,
	/* 120HS BASED DISPLAY_MODE */
	S6E3HAE_DISPLAY_MODE_1080x2316_120HS,
	S6E3HAE_DISPLAY_MODE_1080x2316_60HS_120HS_TE_HW_SKIP_1,
	S6E3HAE_DISPLAY_MODE_1080x2316_30HS_120HS_TE_HW_SKIP_3,
	S6E3HAE_DISPLAY_MODE_1080x2316_24HS_120HS_TE_HW_SKIP_4,
	S6E3HAE_DISPLAY_MODE_1080x2316_10HS_120HS_TE_HW_SKIP_11,
	/* 96HS BASED DISPLAY_MODE */
	S6E3HAE_DISPLAY_MODE_1080x2316_96HS,
	S6E3HAE_DISPLAY_MODE_1080x2316_48HS_96HS_TE_HW_SKIP_1,

	/* RESOLUTION : HD */
	/* 60NS BASED DISPLAY_MODE */
	S6E3HAE_DISPLAY_MODE_720x1544_60NS,
	/* 48NS BASED DISPLAY_MODE */
	S6E3HAE_DISPLAY_MODE_720x1544_48NS,
	/* 120HS BASED DISPLAY_MODE */
	S6E3HAE_DISPLAY_MODE_720x1544_120HS,
	S6E3HAE_DISPLAY_MODE_720x1544_60HS_120HS_TE_HW_SKIP_1,
	S6E3HAE_DISPLAY_MODE_720x1544_30HS_120HS_TE_HW_SKIP_3,
	S6E3HAE_DISPLAY_MODE_720x1544_24HS_120HS_TE_HW_SKIP_4,
	S6E3HAE_DISPLAY_MODE_720x1544_10HS_120HS_TE_HW_SKIP_11,
	/* 96HS BASED DISPLAY_MODE */
	S6E3HAE_DISPLAY_MODE_720x1544_96HS,
	S6E3HAE_DISPLAY_MODE_720x1544_48HS_96HS_TE_HW_SKIP_1,
	MAX_S6E3HAE_DISPLAY_MODE,
};

enum {
	S6E3HAE_VRR_KEY_REFRESH_RATE,
	S6E3HAE_VRR_KEY_REFRESH_MODE,
	S6E3HAE_VRR_KEY_TE_SW_SKIP_COUNT,
	S6E3HAE_VRR_KEY_TE_HW_SKIP_COUNT,
	MAX_S6E3HAE_VRR_KEY,
};

static u32 S6E3HAE_VRR_FPS[MAX_S6E3HAE_VRR][MAX_S6E3HAE_VRR_KEY] = {
	[S6E3HAE_VRR_60NS] = { 60, VRR_NORMAL_MODE, 0, 0 },
	[S6E3HAE_VRR_48NS] = { 48, VRR_NORMAL_MODE, 0, 0 },
	[S6E3HAE_VRR_120HS] = { 120, VRR_HS_MODE, 0, 0 },
	[S6E3HAE_VRR_60HS_120HS_TE_HW_SKIP_1] = { 120, VRR_HS_MODE, 0, 1 },
	[S6E3HAE_VRR_30HS_120HS_TE_HW_SKIP_3] = { 120, VRR_HS_MODE, 0, 3 },
	[S6E3HAE_VRR_24HS_120HS_TE_HW_SKIP_4] = { 120, VRR_HS_MODE, 0, 4 },
	[S6E3HAE_VRR_10HS_120HS_TE_HW_SKIP_11] = { 120, VRR_HS_MODE, 0, 11 },
	[S6E3HAE_VRR_96HS] = { 96, VRR_HS_MODE, 0, 0 },
	[S6E3HAE_VRR_48HS_96HS_TE_HW_SKIP_1] = { 96, VRR_HS_MODE, 0, 1 },
};

enum {
	S6E3HAE_VRR_LFD_SCALABILITY_NONE,
	S6E3HAE_VRR_LFD_SCALABILITY_1,
	S6E3HAE_VRR_LFD_SCALABILITY_2,
	S6E3HAE_VRR_LFD_SCALABILITY_3,
	S6E3HAE_VRR_LFD_SCALABILITY_4,
	S6E3HAE_VRR_LFD_SCALABILITY_5,
	S6E3HAE_VRR_LFD_SCALABILITY_6,
	MAX_S6E3HAE_VRR_LFD_SCALABILITY,
};

#define S6E3HAE_VRR_LFD_SCALABILITY_MIN (S6E3HAE_VRR_LFD_SCALABILITY_1)
#define S6E3HAE_VRR_LFD_SCALABILITY_DEF (S6E3HAE_VRR_LFD_SCALABILITY_5)
#define S6E3HAE_VRR_LFD_SCALABILITY_MAX (S6E3HAE_VRR_LFD_SCALABILITY_6)

static u32 S6E3HAE_VRR_LFD_MIN_FREQ[MAX_S6E3HAE_VRR_LFD_SCALABILITY][MAX_S6E3HAE_VRR] = {
	/* scalability default - same as 5 */
	[S6E3HAE_VRR_LFD_SCALABILITY_NONE] = {
		[S6E3HAE_VRR_60NS] = 30,
		[S6E3HAE_VRR_48NS] = 48,
		[S6E3HAE_VRR_120HS] = 1,
		[S6E3HAE_VRR_60HS_120HS_TE_HW_SKIP_1] = 40,
		[S6E3HAE_VRR_30HS_120HS_TE_HW_SKIP_3] = 1,
		[S6E3HAE_VRR_24HS_120HS_TE_HW_SKIP_4] = 1,
		[S6E3HAE_VRR_10HS_120HS_TE_HW_SKIP_11] = 1,
		[S6E3HAE_VRR_96HS] = 1,
		[S6E3HAE_VRR_48HS_96HS_TE_HW_SKIP_1] = 32,
	},
	[S6E3HAE_VRR_LFD_SCALABILITY_1] = {
		[S6E3HAE_VRR_60NS] = 60,
		[S6E3HAE_VRR_48NS] = 48,
		[S6E3HAE_VRR_120HS] = 120,
		[S6E3HAE_VRR_60HS_120HS_TE_HW_SKIP_1] = 60,
		[S6E3HAE_VRR_30HS_120HS_TE_HW_SKIP_3] = 30,
		[S6E3HAE_VRR_24HS_120HS_TE_HW_SKIP_4] = 24,
		[S6E3HAE_VRR_10HS_120HS_TE_HW_SKIP_11] = 10,
		[S6E3HAE_VRR_96HS] = 96,
		[S6E3HAE_VRR_48HS_96HS_TE_HW_SKIP_1] = 48,
	},
	[S6E3HAE_VRR_LFD_SCALABILITY_2] = {
		[S6E3HAE_VRR_60NS] = 30,
		[S6E3HAE_VRR_48NS] = 48,
		[S6E3HAE_VRR_120HS] = 60,
		[S6E3HAE_VRR_60HS_120HS_TE_HW_SKIP_1] = 60,
		[S6E3HAE_VRR_30HS_120HS_TE_HW_SKIP_3] = 30,
		[S6E3HAE_VRR_24HS_120HS_TE_HW_SKIP_4] = 24,
		[S6E3HAE_VRR_10HS_120HS_TE_HW_SKIP_11] = 10,
		[S6E3HAE_VRR_96HS] = 48,
		[S6E3HAE_VRR_48HS_96HS_TE_HW_SKIP_1] = 48,
	},
	[S6E3HAE_VRR_LFD_SCALABILITY_3] = {
		[S6E3HAE_VRR_60NS] = 30,
		[S6E3HAE_VRR_48NS] = 48,
		[S6E3HAE_VRR_120HS] = 30,
		[S6E3HAE_VRR_60HS_120HS_TE_HW_SKIP_1] = 40,
		[S6E3HAE_VRR_30HS_120HS_TE_HW_SKIP_3] = 30,
		[S6E3HAE_VRR_24HS_120HS_TE_HW_SKIP_4] = 24,
		[S6E3HAE_VRR_10HS_120HS_TE_HW_SKIP_11] = 10,
		[S6E3HAE_VRR_96HS] = 24,
		[S6E3HAE_VRR_48HS_96HS_TE_HW_SKIP_1] = 32,
	},
	[S6E3HAE_VRR_LFD_SCALABILITY_4] = {
		[S6E3HAE_VRR_60NS] = 30,
		[S6E3HAE_VRR_48NS] = 48,
		[S6E3HAE_VRR_120HS] = 24,
		[S6E3HAE_VRR_60HS_120HS_TE_HW_SKIP_1] = 40,
		[S6E3HAE_VRR_30HS_120HS_TE_HW_SKIP_3] = 30,
		[S6E3HAE_VRR_24HS_120HS_TE_HW_SKIP_4] = 24,
		[S6E3HAE_VRR_10HS_120HS_TE_HW_SKIP_11] = 10,
		[S6E3HAE_VRR_96HS] = 24,
		[S6E3HAE_VRR_48HS_96HS_TE_HW_SKIP_1] = 32,
	},
	[S6E3HAE_VRR_LFD_SCALABILITY_5] = {
		[S6E3HAE_VRR_60NS] = 30,
		[S6E3HAE_VRR_48NS] = 48,
		[S6E3HAE_VRR_120HS] = 1,
		[S6E3HAE_VRR_60HS_120HS_TE_HW_SKIP_1] = 40,
		[S6E3HAE_VRR_30HS_120HS_TE_HW_SKIP_3] = 1,
		[S6E3HAE_VRR_24HS_120HS_TE_HW_SKIP_4] = 1,
		[S6E3HAE_VRR_10HS_120HS_TE_HW_SKIP_11] = 1,
		[S6E3HAE_VRR_96HS] = 1,
		[S6E3HAE_VRR_48HS_96HS_TE_HW_SKIP_1] = 32,
	},
	[S6E3HAE_VRR_LFD_SCALABILITY_6] = {
		[S6E3HAE_VRR_60NS] = 30,
		[S6E3HAE_VRR_48NS] = 48,
		[S6E3HAE_VRR_120HS] = 1,
		[S6E3HAE_VRR_60HS_120HS_TE_HW_SKIP_1] = 1,
		[S6E3HAE_VRR_30HS_120HS_TE_HW_SKIP_3] = 1,
		[S6E3HAE_VRR_24HS_120HS_TE_HW_SKIP_4] = 1,
		[S6E3HAE_VRR_10HS_120HS_TE_HW_SKIP_11] = 1,
		[S6E3HAE_VRR_96HS] = 1,
		[S6E3HAE_VRR_48HS_96HS_TE_HW_SKIP_1] = 1,
	},
};

static u32 S6E3HAE_LPM_LFD_MIN_FREQ[MAX_S6E3HAE_VRR_LFD_SCALABILITY] = {
	/* scalability default */
	[S6E3HAE_VRR_LFD_SCALABILITY_NONE] = 1,
	[S6E3HAE_VRR_LFD_SCALABILITY_1] = 30,
	[S6E3HAE_VRR_LFD_SCALABILITY_2] = 30,
	[S6E3HAE_VRR_LFD_SCALABILITY_3] = 30,
	[S6E3HAE_VRR_LFD_SCALABILITY_4] = 30,
	[S6E3HAE_VRR_LFD_SCALABILITY_5] = 1,
	[S6E3HAE_VRR_LFD_SCALABILITY_6] = 1,
};

enum {
	S6E3HAE_RAINBOW_B0_FLASH_ADDR_ID_LT_E3,
	S6E3HAE_RAINBOW_B0_FLASH_ADDR_ID_LT_E5,
	S6E3HAE_RAINBOW_B0_FLASH_ADDR_ID_LT_E8,
	S6E3HAE_RAINBOW_B0_FLASH_ADDR_ID_GTE_E8,
	MAX_S6E3HAE_RAINBOW_B0_FLASH_ADDR_ID,
};

enum {
	S6E3HAE_AOR_MANUAL_OFF,
	S6E3HAE_AOR_MANUAL_ON,
	MAX_S6E3HAE_AOR_MANUAL
};

enum {
	S6E3HAE_96HS_MODE_OFF,
	S6E3HAE_96HS_MODE_ON,
	MAX_S6E3HAE_96HS_MODE
};

enum {
	S6E3HAE_GAMMA_MTP_0,
	S6E3HAE_GAMMA_MTP_1,
	S6E3HAE_GAMMA_MTP_2,
	S6E3HAE_GAMMA_MTP_3,
	S6E3HAE_GAMMA_MTP_4,
	S6E3HAE_GAMMA_MTP_5,
	S6E3HAE_GAMMA_MTP_6,
	S6E3HAE_GAMMA_MTP_7,
	S6E3HAE_GAMMA_MTP_8,
	MAX_S6E3HAE_GAMMA_MTP,
};

enum {
	/**
	 * the order of S6E3HAE_VRR_LFD_FRAME_IDX enum
	 * could be mearningful. so don't change the order.
	 */
	S6E3HAE_VRR_LFD_FRAME_IDX_HS_BEGIN,
	S6E3HAE_VRR_LFD_FRAME_IDX_120_HS = S6E3HAE_VRR_LFD_FRAME_IDX_HS_BEGIN,
	S6E3HAE_VRR_LFD_FRAME_IDX_96_HS,
	S6E3HAE_VRR_LFD_FRAME_IDX_60_HS,
	S6E3HAE_VRR_LFD_FRAME_IDX_48_HS,
	S6E3HAE_VRR_LFD_FRAME_IDX_32_HS,
	S6E3HAE_VRR_LFD_FRAME_IDX_30_HS,
	S6E3HAE_VRR_LFD_FRAME_IDX_24_HS,
	S6E3HAE_VRR_LFD_FRAME_IDX_10_HS,
	S6E3HAE_VRR_LFD_FRAME_IDX_1_HS,
	S6E3HAE_VRR_LFD_FRAME_IDX_HS_END = S6E3HAE_VRR_LFD_FRAME_IDX_1_HS,
	S6E3HAE_VRR_LFD_FRAME_IDX_NS_BEGIN,
	S6E3HAE_VRR_LFD_FRAME_IDX_60_NS = S6E3HAE_VRR_LFD_FRAME_IDX_NS_BEGIN,
	S6E3HAE_VRR_LFD_FRAME_IDX_48_NS,
	S6E3HAE_VRR_LFD_FRAME_IDX_30_NS,
	S6E3HAE_VRR_LFD_FRAME_IDX_NS_END = S6E3HAE_VRR_LFD_FRAME_IDX_30_NS,
	MAX_S6E3HAE_VRR_LFD_FRAME_IDX,
};

static u32 S6E3HAE_VRR_LFD_FRAME_IDX_VAL[MAX_S6E3HAE_VRR_LFD_FRAME_IDX] = {
	[S6E3HAE_VRR_LFD_FRAME_IDX_120_HS] = 120,
	[S6E3HAE_VRR_LFD_FRAME_IDX_96_HS] = 96,
	[S6E3HAE_VRR_LFD_FRAME_IDX_60_HS] = 60,
	[S6E3HAE_VRR_LFD_FRAME_IDX_48_HS] = 48,
	[S6E3HAE_VRR_LFD_FRAME_IDX_32_HS] = 32,
	[S6E3HAE_VRR_LFD_FRAME_IDX_30_HS] = 30,
	[S6E3HAE_VRR_LFD_FRAME_IDX_24_HS] = 24,
	[S6E3HAE_VRR_LFD_FRAME_IDX_10_HS] = 10,
	[S6E3HAE_VRR_LFD_FRAME_IDX_1_HS] = 1,
	[S6E3HAE_VRR_LFD_FRAME_IDX_60_NS] = 60,
	[S6E3HAE_VRR_LFD_FRAME_IDX_48_NS] = 48,
	[S6E3HAE_VRR_LFD_FRAME_IDX_30_NS] = 30,
};

#if defined(__PANEL_NOT_USED_VARIABLE__)
static u32 S6E3HAE_VRR_MODE[] = {
	[S6E3HAE_VRR_MODE_NS] = VRR_NORMAL_MODE,
	[S6E3HAE_VRR_MODE_HS] = VRR_HS_MODE,
};
#endif

enum {
	DDI_REV_EVT0 = 0,
	DDI_REV_EVT0_OSC,
	DDI_REV_EVT1,
	MAX_DDI_REV
};

enum {
	S6E3HAE_SMOOTH_DIM_USE = 0,
	S6E3HAE_SMOOTH_DIM_NOT_USE,
	MAX_S6E3HAE_SMOOTH_DIM,
};

enum {
	HS_CLK_1362 = 0,
	HS_CLK_1328,
	HS_CLK_1368,
	MAX_HS_CLK
};

#ifdef CONFIG_DYNAMIC_MIPI
__visible_for_testing void dynamic_mipi_set_ffc(struct maptbl *tbl, u8 *dst);
#endif
__visible_for_testing int init_common_table(struct maptbl *);
__visible_for_testing int get_s6e3hae_96hs_mode(int vrr);
__visible_for_testing int find_s6e3hae_vrr(struct panel_vrr *vrr);
__visible_for_testing int getidx_s6e3hae_lfd_frame_idx(int fps, int mode);
__visible_for_testing int get_s6e3hae_lfd_min_freq(u32 scalability, u32 vrr_fps_index);
__visible_for_testing int s6e3hae_get_vrr_lfd_min_div_count(struct panel_info *panel_data);
__visible_for_testing int s6e3hae_get_vrr_lfd_max_div_count(struct panel_info *panel_data);
__visible_for_testing DECLARE_REDIRECT_MOCKABLE(s6e3hae_get_vrr_lfd_max_freq, RETURNS(int), PARAMS(struct panel_info *));
__visible_for_testing DECLARE_REDIRECT_MOCKABLE(s6e3hae_get_vrr_lfd_min_freq, RETURNS(int), PARAMS(struct panel_info *));
__visible_for_testing int getidx_s6e3hae_vrr_mode(int mode);
__visible_for_testing int generate_brt_step_table(struct brightness_table *brt_tbl);
#ifdef CONFIG_EXYNOS_DECON_MDNIE_LITE
__visible_for_testing int getidx_common_maptbl(struct maptbl *);
#endif
__visible_for_testing int init_gamma_mtp_table(struct maptbl *tbl);
#if defined(__PANEL_NOT_USED_FUNCTION__)
__visible_for_testing void dump_s32_arr(char *buf, u32 buflen, s32 *arr, u32 len);
#endif
#if defined(CONFIG_MCD_PANEL_LPM) && defined(CONFIG_SUPPORT_AOD_BL)
__visible_for_testing int init_aod_dimming_table(struct maptbl *tbl);
#endif
#ifdef CONFIG_SUPPORT_HMD
__visible_for_testing int init_gamma_mode2_hmd_brt_table(struct maptbl *tbl);
__visible_for_testing int getidx_gamma_mode2_hmd_brt_table(struct maptbl *tbl);
#endif
__visible_for_testing int init_gamma_mode2_brt_table(struct maptbl *tbl);
__visible_for_testing int getidx_gamma_mode2_brt_table(struct maptbl *);
__visible_for_testing int getidx_vrr_brt_table(struct maptbl *tbl);
__visible_for_testing int getidx_dimming_frame_table(struct maptbl *tbl);
__visible_for_testing int getidx_acl_opr_table(struct maptbl *);
__visible_for_testing int getidx_dia_onoff_table(struct maptbl *tbl);
__visible_for_testing int getidx_irc_mode_table(struct maptbl *tbl);

__visible_for_testing bool is_panel_state_not_lpm(struct panel_device *panel);

#ifdef CONFIG_SUPPORT_XTALK_MODE
__visible_for_testing int getidx_vgh_table(struct maptbl *);
#endif
__visible_for_testing int getidx_dsc_table(struct maptbl *);
__visible_for_testing int getidx_resolution_table(struct maptbl *);
__visible_for_testing int getidx_vrr_fps_table(struct maptbl *);
__visible_for_testing int getidx_aor_manual_onoff_table(struct maptbl *tbl);
__visible_for_testing int getidx_aor_manual_value_table(struct maptbl *tbl);

__visible_for_testing int init_lpm_brt_table(struct maptbl *tbl);
__visible_for_testing int getidx_lpm_brt_table(struct maptbl *);
__visible_for_testing int getidx_lpm_fps_table(struct maptbl *tbl);

__visible_for_testing int getidx_vrr_mode_table(struct maptbl *);
__visible_for_testing int getidx_lfd_frame_insertion_table(struct maptbl *tbl);

#ifdef CONFIG_EXYNOS_DECON_MDNIE_LITE
__visible_for_testing void copy_dummy_maptbl(struct maptbl *tbl, u8 *dst);
#endif
__visible_for_testing void copy_common_maptbl(struct maptbl *, u8 *);
__visible_for_testing void copy_gamma_mode2_brt_maptbl(struct maptbl *tbl, u8 *dst);
__visible_for_testing void copy_tset_maptbl(struct maptbl *, u8 *);
#ifdef CONFIG_SUPPORT_GRAYSPOT_TEST
__visible_for_testing void copy_grayspot_cal_1_maptbl(struct maptbl *tbl, u8 *dst);
__visible_for_testing void copy_grayspot_cal_2_maptbl(struct maptbl *tbl, u8 *dst);
#endif
__visible_for_testing void copy_lfd_min_maptbl(struct maptbl *tbl, u8 *dst);
__visible_for_testing void copy_lfd_max_maptbl(struct maptbl *tbl, u8 *dst);

#ifdef CONFIG_EXYNOS_DECON_LCD_COPR
__visible_for_testing void copy_copr_maptbl(struct maptbl *, u8 *);
#endif

#ifdef CONFIG_SUPPORT_GRAM_CHECKSUM
__visible_for_testing int s6e3hae_getidx_vddm_table(struct maptbl *);
__visible_for_testing int s6e3hae_getidx_gram_img_pattern_table(struct maptbl *tbl);
#endif

#ifdef CONFIG_SUPPORT_MAFPC
__visible_for_testing int getidx_mafpc_enable_maptbl(struct maptbl *tbl);
__visible_for_testing void copy_mafpc_enable_maptbl(struct maptbl *tbl, u8 *dst);
__visible_for_testing void copy_mafpc_ctrl_maptbl(struct maptbl *tbl, u8 *dst);
__visible_for_testing int get_mafpc_scale_index(struct mafpc_device *mafpc, struct panel_device *panel);
__visible_for_testing void copy_mafpc_scale_maptbl(struct maptbl *tbl, u8 *dst);
#endif
#ifdef CONFIG_EXYNOS_DECON_MDNIE_LITE
__visible_for_testing int init_color_blind_table(struct maptbl *tbl);
__visible_for_testing int getidx_mdnie_scenario_maptbl(struct maptbl *tbl);
__visible_for_testing int getidx_mdnie_hdr_maptbl(struct maptbl *tbl);
__visible_for_testing int getidx_mdnie_trans_mode_maptbl(struct maptbl *tbl);
__visible_for_testing int init_mdnie_night_mode_table(struct maptbl *tbl);
__visible_for_testing int getidx_mdnie_night_mode_maptbl(struct maptbl *tbl);
__visible_for_testing int init_mdnie_color_lens_table(struct maptbl *tbl);
__visible_for_testing int getidx_color_lens_maptbl(struct maptbl *tbl);
__visible_for_testing int init_color_coordinate_table(struct maptbl *);
__visible_for_testing int init_sensor_rgb_table(struct maptbl *tbl);
__visible_for_testing int getidx_adjust_ldu_maptbl(struct maptbl *tbl);
__visible_for_testing int getidx_color_coordinate_maptbl(struct maptbl *tbl);
__visible_for_testing void copy_scr_white_maptbl(struct maptbl *tbl, u8 *dst);
__visible_for_testing int getidx_trans_maptbl(struct pkt_update_info *pktui);
__visible_for_testing int getidx_mdnie_maptbl(struct pkt_update_info *pktui, int offset);
__visible_for_testing int getidx_mdnie_0_maptbl(struct pkt_update_info *pktui);
__visible_for_testing int getidx_mdnie_1_maptbl(struct pkt_update_info *pktui);
__visible_for_testing int getidx_mdnie_2_maptbl(struct pkt_update_info *pktui);
__visible_for_testing int getidx_mdnie_scr_white_maptbl(struct pkt_update_info *pktui);
__visible_for_testing void update_current_scr_white(struct maptbl *tbl, u8 *dst);
#endif /* CONFIG_EXYNOS_DECON_MDNIE_LITE */
__visible_for_testing int do_gamma_flash_checksum(struct panel_device *panel, void *data, u32 len);
#ifdef CONFIG_SUPPORT_SSR_TEST
__visible_for_testing int s6e3hae_ssr_test(struct panel_device *panel, void *data, u32 len);
#endif
#ifdef CONFIG_SUPPORT_ECC_TEST
__visible_for_testing int s6e3hae_ecc_test(struct panel_device *panel, void *data, u32 len);
#endif
#ifdef CONFIG_SUPPORT_PANEL_DECODER_TEST
__visible_for_testing int s6e3hae_decoder_test(struct panel_device *panel, void *data, u32 len);
#endif
__visible_for_testing bool is_panel_mres_updated(struct panel_device *panel);
__visible_for_testing bool is_panel_mres_updated_bigger(struct panel_device *panel);

static inline bool is_id_lt_81(struct panel_device *panel)
{
	if (!panel)
		return false;

	return ((panel->panel_data.id[2] & 0xFF) < 0x81) ? true : false;
}

static inline bool is_id_lt_90(struct panel_device *panel)
{
	if (!panel)
		return false;

	return ((panel->panel_data.id[2] & 0xFF) < 0x90) ? true : false;
}
__visible_for_testing bool is_support_lpm_lfd(struct panel_device *panel);
__visible_for_testing bool is_support_lfd(struct panel_device *panel);
__visible_for_testing bool is_first_set_bl(struct panel_device *panel);
__visible_for_testing bool is_wait_vsync_needed(struct panel_device *panel);
__visible_for_testing bool is_96hs_based_fps(struct panel_device *panel);

#ifdef CONFIG_SUPPORT_BRIGHTDOT_TEST
__visible_for_testing int s6e3hae_getidx_brightdot_aor_table(struct maptbl *tbl);
__visible_for_testing bool s6e3hae_is_brightdot_enabled(struct panel_device *panel);
#endif

__visible_for_testing int s6e3hae_getidx_ffc_table(struct maptbl *tbl);
#endif /* __S6E3HAE_H__ */
