# SIA PA object

#zhangsen1
ifeq ($(CONFIG_SND_SOC_SIA8159),y)

snd-soc-sia8159-objs := \
		sipa.o \
		sipa_regmap.o \
		sipa_aux_dev_if.o \
		sipa_91xx.o \
		sipa_parameter.o\
		sipa_tuning_misc.o\
 		sipa_tuning_if.o


obj-y += snd-soc-sia8159.o
endif
#zhangsen1
