/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) Samsung Electronics Co., Ltd.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 */

#include <linux/module.h>
#include "../panel_debug.h"
#include "../panel_function.h"
#include "oled_common.h"
#include "oled_common_cond.h"
#include "oled_common_dump.h"
#if IS_ENABLED(CONFIG_USDM_PANEL_SELF_DISPLAY)
#include "oled_common_aod.h"
#endif
#if IS_ENABLED(CONFIG_USDM_MDNIE)
#include "oled_common_mdnie.h"
#endif
#include "oled_function.h"

struct pnobj_func oled_function_table[MAX_OLED_FUNCTION] = {
	[OLED_MAPTBL_INIT_DEFAULT] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_INIT_DEFAULT, oled_maptbl_init_default),
	[OLED_MAPTBL_GETIDX_DEFAULT] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_GETIDX_DEFAULT, oled_maptbl_getidx_default),
	[OLED_MAPTBL_GETIDX_GM2_BRT] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_GETIDX_GM2_BRT, oled_maptbl_getidx_gm2_brt),
	[OLED_MAPTBL_COPY_DEFAULT] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_COPY_DEFAULT, oled_maptbl_copy_default),
	[OLED_MAPTBL_COPY_TSET] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_COPY_TSET, oled_maptbl_copy_tset),
	[OLED_MAPTBL_COPY_DUMMY] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_COPY_DUMMY, oled_maptbl_copy_dummy),
#ifdef CONFIG_USDM_PANEL_COPR
	[OLED_MAPTBL_COPY_COPR] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_COPY_COPR, oled_maptbl_copy_copr),
#endif
#if IS_ENABLED(CONFIG_USDM_PANEL_SELF_DISPLAY)
	[OLED_MAPTBL_GETIDX_AOD_SELF_MODE_POS] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_GETIDX_AOD_SELF_MODE_POS, oled_maptbl_getidx_aod_self_mode_pos),
	[OLED_MAPTBL_COPY_AOD_DIGITAL_POS] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_COPY_AOD_DIGITAL_POS, oled_maptbl_copy_aod_digital_pos),
	[OLED_MAPTBL_COPY_AOD_TIME] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_COPY_AOD_TIME, oled_maptbl_copy_aod_time),
	[OLED_MAPTBL_COPY_AOD_TIMER_RATE] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_COPY_AOD_TIMER_RATE, oled_maptbl_copy_aod_timer_rate),
	[OLED_MAPTBL_COPY_AOD_TIMER_RATE_HOP] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_COPY_AOD_TIMER_RATE_HOP, oled_maptbl_copy_aod_timer_rate_hop),
	[OLED_MAPTBL_COPY_AOD_SELF_MOVE_ON_CTRL] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_COPY_AOD_SELF_MOVE_ON_CTRL, oled_maptbl_copy_aod_self_move_on_ctrl),
	[OLED_MAPTBL_COPY_AOD_ANALOG_POS] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_COPY_AOD_ANALOG_POS, oled_maptbl_copy_aod_analog_pos),
	[OLED_MAPTBL_COPY_AOD_ANALOG_EN] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_COPY_AOD_ANALOG_EN, oled_maptbl_copy_aod_analog_en),
	[OLED_MAPTBL_COPY_AOD_DIGITAL_EN] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_COPY_AOD_DIGITAL_EN, oled_maptbl_copy_aod_digital_en),
	[OLED_MAPTBL_COPY_AOD_SELF_MOVE_RESET] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_COPY_AOD_SELF_MOVE_RESET, oled_maptbl_copy_aod_self_move_reset),
	[OLED_MAPTBL_COPY_AOD_ICON_CTRL] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_COPY_AOD_ICON_CTRL, oled_maptbl_copy_aod_icon_ctrl),
	[OLED_MAPTBL_COPY_AOD_DIGITAL_COLOR] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_COPY_AOD_DIGITAL_COLOR, oled_maptbl_copy_aod_digital_color),
	[OLED_MAPTBL_COPY_AOD_DIGITAL_UN_WIDTH] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_COPY_AOD_DIGITAL_UN_WIDTH, oled_maptbl_copy_aod_digital_un_width),
	[OLED_MAPTBL_COPY_AOD_PARTIAL_MODE] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_COPY_AOD_PARTIAL_MODE, oled_maptbl_copy_aod_partial_mode),
	[OLED_MAPTBL_COPY_AOD_PARTIAL_AREA] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_COPY_AOD_PARTIAL_AREA, oled_maptbl_copy_aod_partial_area),
	[OLED_MAPTBL_COPY_AOD_PARTIAL_HLPM] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_COPY_AOD_PARTIAL_HLPM, oled_maptbl_copy_aod_partial_hlpm),
#ifdef SUPPORT_NORMAL_SELF_MOVE
	[OLED_MAPTBL_GETIDX_AOD_SELF_PATTERN] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_GETIDX_AOD_SELF_PATTERN, oled_maptbl_getidx_aod_self_pattern),
	[OLED_MAPTBL_COPY_AOD_SELF_MOVE_PATTERN] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_COPY_AOD_SELF_MOVE_PATTERN, oled_maptbl_copy_aod_self_move_pattern),
#endif
#endif /* CONFIG_USDM_PANEL_SELF_DISPLAY */
#if IS_ENABLED(CONFIG_USDM_MDNIE)
	[OLED_MAPTBL_GETIDX_MDNIE_SCENARIO_MODE] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_GETIDX_MDNIE_SCENARIO_MODE, oled_maptbl_getidx_mdnie_scenario_mode),
#ifdef CONFIG_USDM_PANEL_HMD
	[OLED_MAPTBL_GETIDX_MDNIE_HMD] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_GETIDX_MDNIE_HMD, oled_maptbl_getidx_mdnie_hmd),
#endif
	[OLED_MAPTBL_GETIDX_MDNIE_HDR] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_GETIDX_MDNIE_HDR, oled_maptbl_getidx_mdnie_hdr),
	[OLED_MAPTBL_GETIDX_MDNIE_TRANS_MODE] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_GETIDX_MDNIE_TRANS_MODE, oled_maptbl_getidx_mdnie_trans_mode),
	[OLED_MAPTBL_GETIDX_MDNIE_NIGHT_MODE] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_GETIDX_MDNIE_NIGHT_MODE, oled_maptbl_getidx_mdnie_night_mode),
	[OLED_MAPTBL_GETIDX_COLOR_LENS] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_GETIDX_COLOR_LENS, oled_maptbl_getidx_color_lens),
	[OLED_MAPTBL_COPY_SCR_WHITE] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_COPY_SCR_WHITE, oled_maptbl_copy_scr_white),
	[OLED_MAPTBL_COPY_SCR_WHITE_ANTI_GLARE] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_COPY_SCR_WHITE_ANTI_GLARE, oled_maptbl_copy_scr_white_anti_glare),
	[OLED_MAPTBL_COPY_SCR_CR] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_COPY_SCR_CR, oled_maptbl_copy_scr_cr),
#ifdef CONFIG_USDM_MDNIE_AFC
	[OLED_MAPTBL_COPY_AFC] = __PNOBJ_FUNC_INITIALIZER(OLED_MAPTBL_COPY_AFC, oled_maptbl_copy_afc),
#endif
#endif /* CONFIG_USDM_MDNIE */
	[OLED_COND_IS_PANEL_DISPLAY_MODE_CHANGED] = __PNOBJ_FUNC_INITIALIZER(OLED_COND_IS_PANEL_DISPLAY_MODE_CHANGED, oled_cond_is_panel_display_mode_changed),
	[OLED_COND_IS_PANEL_REFRESH_RATE_CHANGED] = __PNOBJ_FUNC_INITIALIZER(OLED_COND_IS_PANEL_REFRESH_RATE_CHANGED, oled_cond_is_panel_refresh_rate_changed),
	[OLED_COND_IS_PANEL_REFRESH_MODE_CHANGED] = __PNOBJ_FUNC_INITIALIZER(OLED_COND_IS_PANEL_REFRESH_MODE_CHANGED, oled_cond_is_panel_refresh_mode_changed),
	[OLED_COND_IS_PANEL_REFRESH_MODE_NS] = __PNOBJ_FUNC_INITIALIZER(OLED_COND_IS_PANEL_REFRESH_MODE_NS, oled_cond_is_panel_refresh_mode_ns),
	[OLED_COND_IS_PANEL_REFRESH_MODE_HS] = __PNOBJ_FUNC_INITIALIZER(OLED_COND_IS_PANEL_REFRESH_MODE_HS, oled_cond_is_panel_refresh_mode_hs),
	[OLED_COND_IS_PANEL_STATE_LPM] = __PNOBJ_FUNC_INITIALIZER(OLED_COND_IS_PANEL_STATE_LPM, oled_cond_is_panel_state_lpm),
	[OLED_COND_IS_PANEL_STATE_NOT_LPM] = __PNOBJ_FUNC_INITIALIZER(OLED_COND_IS_PANEL_STATE_NOT_LPM, oled_cond_is_panel_state_not_lpm),
	[OLED_COND_IS_FIRST_SET_BL] = __PNOBJ_FUNC_INITIALIZER(OLED_COND_IS_FIRST_SET_BL, oled_cond_is_first_set_bl),
	[OLED_COND_IS_PANEL_MRES_UPDATED] = __PNOBJ_FUNC_INITIALIZER(OLED_COND_IS_PANEL_MRES_UPDATED, oled_cond_is_panel_mres_updated),
	[OLED_COND_IS_PANEL_MRES_UPDATED_BIGGER] = __PNOBJ_FUNC_INITIALIZER(OLED_COND_IS_PANEL_MRES_UPDATED_BIGGER, oled_cond_is_panel_mres_updated_bigger),
	[OLED_COND_IS_ACL_PWRSAVE_ON] = __PNOBJ_FUNC_INITIALIZER(OLED_COND_IS_ACL_PWRSAVE_ON, oled_cond_is_acl_pwrsave_on),
	[OLED_DUMP_SHOW_EXPECTS] = __PNOBJ_FUNC_INITIALIZER(OLED_DUMP_SHOW_EXPECTS, oled_dump_show_expects),
	[OLED_DUMP_SHOW_RESOURCE] = __PNOBJ_FUNC_INITIALIZER(OLED_DUMP_SHOW_RESOURCE, oled_dump_show_resource),
	[OLED_DUMP_SHOW_RESOURCE_AND_PANIC] = __PNOBJ_FUNC_INITIALIZER(OLED_DUMP_SHOW_RESOURCE_AND_PANIC, oled_dump_show_resource_and_panic),
	[OLED_DUMP_SHOW_RDDPM] = __PNOBJ_FUNC_INITIALIZER(OLED_DUMP_SHOW_RDDPM, oled_dump_show_rddpm),
	[OLED_DUMP_SHOW_RDDPM_BEFORE_SLEEP_IN] = __PNOBJ_FUNC_INITIALIZER(OLED_DUMP_SHOW_RDDPM_BEFORE_SLEEP_IN, oled_dump_show_rddpm_before_sleep_in),
	[OLED_DUMP_SHOW_RDDSM] = __PNOBJ_FUNC_INITIALIZER(OLED_DUMP_SHOW_RDDSM, oled_dump_show_rddsm),
	[OLED_DUMP_SHOW_ERR] = __PNOBJ_FUNC_INITIALIZER(OLED_DUMP_SHOW_ERR, oled_dump_show_err),
	[OLED_DUMP_SHOW_ERR_FG] = __PNOBJ_FUNC_INITIALIZER(OLED_DUMP_SHOW_ERR_FG, oled_dump_show_err_fg),
	[OLED_DUMP_SHOW_DSI_ERR] = __PNOBJ_FUNC_INITIALIZER(OLED_DUMP_SHOW_DSI_ERR, oled_dump_show_dsi_err),
	[OLED_DUMP_SHOW_SELF_DIAG] = __PNOBJ_FUNC_INITIALIZER(OLED_DUMP_SHOW_SELF_DIAG, oled_dump_show_self_diag),
#ifdef CONFIG_USDM_DDI_CMDLOG
	[OLED_DUMP_SHOW_CMDLOG] = __PNOBJ_FUNC_INITIALIZER(OLED_DUMP_SHOW_CMDLOG, oled_dump_show_cmdlog),
#endif
	[OLED_DUMP_SHOW_SSR_ERR] = __PNOBJ_FUNC_INITIALIZER(OLED_DUMP_SHOW_SSR_ERR, oled_dump_show_ssr_err),
	[OLED_DUMP_SHOW_ECC_ERR] = __PNOBJ_FUNC_INITIALIZER(OLED_DUMP_SHOW_ECC_ERR, oled_dump_show_ecc_err),
	[OLED_DUMP_SHOW_FLASH_LOADED] = __PNOBJ_FUNC_INITIALIZER(OLED_DUMP_SHOW_FLASH_LOADED, oled_dump_show_flash_loaded),
#ifdef CONFIG_USDM_PANEL_MAFPC
	[OLED_DUMP_SHOW_MAFPC_LOG] = __PNOBJ_FUNC_INITIALIZER(OLED_DUMP_SHOW_MAFPC_LOG, oled_dump_show_mafpc_log),
	[OLED_DUMP_SHOW_MAFPC_FLASH_LOG] = __PNOBJ_FUNC_INITIALIZER(OLED_DUMP_SHOW_MAFPC_FLASH_LOG, oled_dump_show_mafpc_flash_log),
	[OLED_DUMP_SHOW_ABC_CRC_LOG] = __PNOBJ_FUNC_INITIALIZER(OLED_DUMP_SHOW_ABC_CRC_LOG, oled_dump_show_abc_crc_log),
#endif
	[OLED_DUMP_SHOW_SELF_MASK_CRC] = __PNOBJ_FUNC_INITIALIZER(OLED_DUMP_SHOW_SELF_MASK_CRC, oled_dump_show_self_mask_crc),
};
EXPORT_SYMBOL(oled_function_table);

static int __init oled_function_init(void)
{
	int ret;

	ret = panel_function_insert_array(oled_function_table,
			ARRAY_SIZE(oled_function_table));
	if (ret < 0)
		panel_err("failed to insert oled_function_table\n");

	return 0;
}

static void __exit oled_function_exit(void)
{
}

module_init(oled_function_init)
module_exit(oled_function_exit)

MODULE_DESCRIPTION("oled_function driver");
MODULE_LICENSE("GPL");
