# Makefile for the focaltech touchscreen drivers.


obj-$(CONFIG_TOUCHSCREEN_FTS_1695)	+=  focaltech_core.o
obj-$(CONFIG_TOUCHSCREEN_FTS_1695)	+=  focaltech_ex_fun.o
obj-$(CONFIG_TOUCHSCREEN_FTS_1695)	+=  focaltech_ex_mode.o
obj-$(CONFIG_TOUCHSCREEN_FTS_1695)	+=  focaltech_gesture.o
obj-$(CONFIG_TOUCHSCREEN_FTS_1695)	+=  focaltech_esdcheck.o
obj-$(CONFIG_TOUCHSCREEN_FTS_1695)   +=  focaltech_point_report_check.o
obj-$(CONFIG_TOUCHSCREEN_FTS_1695)   +=  focaltech_test/

obj-$(CONFIG_TOUCHSCREEN_FTS_1695)   +=  focaltech_i2c.o
obj-$(CONFIG_TOUCHSCREEN_FTS_1695)	+=  focaltech_flash.o
obj-$(CONFIG_TOUCHSCREEN_FTS_1695)   +=  focaltech_flash/
# HS60 add for SR-ZQL1695-01000000583 by liufurong at 20190724 start
obj-$(CONFIG_TOUCHSCREEN_FTS_1695)	+=  fts_sec.o
# HS60 add for SR-ZQL1695-01000000583 by liufurong at 20190724 end
