obj-$(CONFIG_SEC_DEBUG)			+= test_builder_pattern.o \
					   test_erase_unique_info.o

obj-$(CONFIG_SEC_LOG_BUF)		+= test_sec_log_buf.o
obj-$(CONFIG_SEC_REBOOT_CMD)		+= test_sec_reboot_cmd.o
obj-$(CONFIG_SEC_UPLOAD_CAUSE)		+= test_sec_upload_cause.o
obj-$(CONFIG_SEC_CRASHKEY)		+= test_sec_crashkey.o
obj-$(CONFIG_SEC_CRASHKEY_LONG)		+= test_sec_crashkey_long.o
obj-$(CONFIG_SEC_DEBUG_REGION)		+= test_sec_debug_region.o
obj-$(CONFIG_SEC_FORCE_ERR)		+= test_sec_force_err.o
