# SPDX-License-Identifier: GPL-2.0
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/clocksource

ccflags-y += -I$(srctree)/drivers/clocksource

obj-$(CONFIG_DEVICE_MODULES_MTK_TIMER)		+= timer-mediatek.o
