obj-$(CONFIG_SOC_EXYNOS2100) += gud-exynos2100/
obj-$(CONFIG_SOC_S5E9925) += gud-s5e9925/
obj-$(CONFIG_SOC_S5E8825) += gud-s5e8825/
obj-$(CONFIG_SOC_S5E9935) += gud-s5e9935/
obj-$(CONFIG_SOC_S5E8535) += gud-s5e8535/
obj-$(CONFIG_SOC_S5E8835) += gud-s5e8835/
