
ifeq ($(CONFIG_MACH_CORE3_W),y)
obj-y += sensor_power_core3.o
else ifeq ($(CONFIG_MACH_GRANDNEOVE3G),y)
obj-y += sensor_power_grandneo.o
else ifeq ($(CONFIG_MACH_YOUNG23GDTV),y)
obj-y += sensor_power_young2dtv.o
else ifeq ($(CONFIG_MACH_VIVALTO3MVE3G_LTN),y)
obj-y += sensor_power_vivalto3mve3g.o
else ifeq ($(CONFIG_MACH_GOYAVE3G_SWA),y)
obj-y += sensor_power_goyave3g_swa.o
else ifeq ($(CONFIG_MACH_GOYAVE3G_SEA),y)
obj-y += sensor_power_goyave3gsea.o
else ifeq ($(CONFIG_MACH_GOYAVEWIFI_SEA_XTC),y)
obj-y += sensor_power_goyave3gsea.o
else ifeq ($(CONFIG_MACH_GOYAVE3G),y)
obj-y += sensor_power_goyave3g.o
else ifeq ($(CONFIG_MACH_GOYAVEWIFI),y)
obj-y += sensor_power_goyave3g.o
else ifeq ($(CONFIG_MACH_VIVALTO5MVE3G),y)
obj-y += sensor_power_pikeavivaltove.o
else ifeq ($(CONFIG_MACH_J13G),y)
obj-y += sensor_power_j13g.o
else
obj-y += sensor_power.o
endif
