
ifeq ($(CONFIG_MACH_COREPRIMELITE),y)
obj-y += sensor_power_coreprimelite.o
else ifeq ($(CONFIG_MACH_TSHARK2TABE),y)
obj-y += sensor_power_tshark2tabe.o
else ifeq ($(CONFIG_MACH_GRANDPRIMEVE3G),y)
obj-y += sensor_power_grandprime3g_ve.o
else ifeq ($(CONFIG_MACH_COREPRIMEVE3G),y)
obj-y += sensor_power_coreprime3g_ve.o
else ifeq ($(CONFIG_MACH_J23G),y)
obj-y += sensor_power_J2_3G.o
else
obj-y += sensor_power.o
endif
