
ccflags-y := -Iinclude/drm -Idrivers/gpu/drm/msm -Idrivers/gpu/drm/msm/dsi-staging -Idrivers/gpu/drm/msm/dp
ccflags-y += -I$(srctree)/drivers/gpu/drm/msm
ccflags-y += -I$(srctree)/drivers/gpu/drm/msm/sde
ccflags-y += -I$(srctree)/drivers/clk/qcom
ccflags-y += -I$(srctree)/drivers/gpu/drm/msm/samsung_lego

obj-y  += ss_dsi_panel_HX83102_TV104WUM.o
obj-y  += ss_buck_isl98609_i2c.o