#ifndef __DT_BINDINGS__SEC_LOG_BUF_H__
#define __DT_BINDINGS__SEC_LOG_BUF_H__

#define SEC_LOG_BUF_STRATEGY_BUILTIN 	0
#define SEC_LOG_BUF_STRATEGY_KPROBE	1
#define SEC_LOG_BUF_STRATEGY_CONSOLE	2
#define SEC_LOG_BUF_STRATEGY_VH_PRINTK_STORE	3
#define SEC_LOG_BUF_NR_STRATEGIES	(SEC_LOG_BUF_STRATEGY_VH_PRINTK_STORE + 1)

#endif	/* __DT_BINDINGS__SEC_LOG_BUF_H__ */
