subdir-ccflags-y += -Idrivers/marvell/marvell-telephony/include
subdir-ccflags-y += -DEXPORT_SYMTAB

obj-m += ccinetdev/

obj-m += cidatastub/

obj-m += cidatatty/

obj-m += cimodemtty/

obj-m += citty/

obj-m += cp_load/

obj-m += diag/

obj-m += errorhandler/

obj-m += hwmap/

obj-m += shmem/

obj-m += usim_event/
