# SPDX-License-Identifier: GPL-2.0
# COPYRIGHT(C) 2023 Samsung Electronics Co., Ltd. All Right Reserved.

# TODO: remove the below sub-makefile after lego is enabled.
gta9p_dir		:= $(srctree)/$(src)
include $(gta9p_dir)/without_lego.mk
