# SPDX-License-Identifier: GPL-2.0
# COPYRIGHT(C) 2023 Samsung Electronics Co., Ltd. All Right Reserved.

# TODL: remove the below sub-makefile after lego is enabled.
a05s_dir		:= $(srctree)/$(src)
include $(a05s_dir)/without_lego.mk
