#
# Makefile for IIO proximity sensors
#

# When adding new entries keep the list in alphabetical order
obj-$(CONFIG_AS3935)		+= as3935.o
obj-$(CONFIG_SENSORS_STK3013_IIO)		+= stk3013.o
obj-$(CONFIG_SENSORS_CM36672P_IIO)	+= cm36672p.o