dtb-y += q6q_kor_singlex_w00_r10.dtbo
dtb-y += q6q_kor_singlex_w00_r09.dtbo
dtb-y += q6q_kor_singlex_w00_r08.dtbo
dtb-y += q6q_kor_singlex_w00_r04.dtbo
# SPDX-License-Identifier: GPL-2.0
# COPYRIGHT(C) 2023 Samsung Electronics Co., Ltd. All Right Reserved.

# TODO: if lego is not avaiable then uncomment the following sub-makefile
# q6q_dir		:= $(srctree)/$(src)
# include $(q6q_dir)/without_lego.mk
