ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include/
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/sda/include
ccflags-y += -I$(srctree)/kernel/

obj-$(CONFIG_MTK_CACHE_PARITY_CHECK) += cache-parity.o
obj-$(CONFIG_MTK_DBGTOP) += dbgtop-drm.o
obj-$(CONFIG_MTK_IRQ_DBG) += irq-dbg.o
obj-$(CONFIG_MTK_BUS_PARITY_CHECK) += bus-parity.o
obj-$(CONFIG_MTK_SYSTRACKER_WATCHPOINT) += systracker.o
obj-$(CONFIG_MTK_BUS_PARITY_CHECK) += dbg_error_flag.o
obj-$(CONFIG_MTK_LAST_BUS) += last_bus.o
obj-$(CONFIG_MTK_BTM_SUPPORT) += btm/
