obj-$(CONFIG_EXYNOS_FMP_SIMULATOR) += fmp_simulator-core.o
fmp_simulator-core-$(CONFIG_EXYNOS_FIPS_SIMULATOR) += fmp_simulator.o \
						fmp_fips_main.o \
						fmp_fips_fops.o \
						fmp_fips_cipher.o \
						fmp_test.o
