# SPRD Audio Memory Manager Support
SPRD_SOUND_TREE                         := sound/soc/sprd/
subdir-ccflags-y                        += -I$(SPRD_SOUND_TREE)/include/

obj-$(CONFIG_SPRD_AUDIO_VOICE_TRIGGER)  += voice_trigger_node.o
