#SPRD CODEC

SPRD_SOUND_TREE := sound/soc/sprd/
ccflags-y += -I$(SPRD_SOUND_TREE)/codec/sprd

snd-soc-sprd-codec-ump9620-objs   := sprd-codec.o sprd-audio-power.o  sprd-headset-ump9620.o
obj-$(CONFIG_SND_SOC_SPRD_CODEC_UMP9620)        += snd-soc-sprd-codec-ump9620.o
