# SPDX-License-Identifier: GPL-2.0
dtb-y += mt6739.dtb
dtb-y += mt6739_a01core_cis_ser_00.dtb
dtb-y += mt6739_a01core_cis_ser_01.dtb
dtb-y += mt6739_a01core_cis_ser_02.dtb
dtb-y += mt6739_a01core_cis_ser_03.dtb
dtb-y += mt6739_a01core_cis_ser_04.dtb

always            := $(dtb-y)
clean-files       := *.dtb*
