
obj-$(CONFIG_ARCH_MSM8610)	+= sec_dct_msm_a_family.o
obj-$(CONFIG_ARCH_MSM8960)	+= sec_dct_msm_a_family.o
obj-$(CONFIG_ARCH_MSM8930)	+= sec_dct_msm_a_family.o
obj-$(CONFIG_ARCH_APQ8064)	+= sec_dct_msm_a_family.o

obj-$(CONFIG_ARCH_MSM8226)	+= sec_dct_msm_b_family.o
obj-$(CONFIG_ARCH_MSM8916)	+= sec_dct_msm_b_family.o
obj-$(CONFIG_ARCH_MSM8974)	+= sec_dct_msm_b_family.o
obj-$(CONFIG_ARCH_APQ8084)	+= sec_dct_msm_b_family.o