#
# Copyright (c) 2022 Samsung Electronics Co., Ltd.
#		http://www.samsung.com
#
# Licensed under GPLv2
#

vra-objs := pablo-vra-core.o

obj-$(CONFIG_VIDEO_EXYNOS_CAMERA_POSTPROCESS_VRA)	+= vra.o
vra-$(CONFIG_CAMERA_PP_VRA_V6_0_0_OBJ)	+= pablo-hw-api-vra-v6_0_0.o
