#
# panel object
# namd : ss_dsi_panel_"DDI NAME"_"PANEL NAME".c
#
obj-y  += ss_dsi_panel_S6E3HA6_AMB577MQ01.o
obj-y  += ss_dsi_smart_dimming_S6E3HA6_AMB577MQ01.o
obj-y  += ss_dsi_active_clk_S6E3HA6.o

# POC FLASH
# SDM660 Branch use ss_ddi_poc_common, so panel poc file is not use any more.
# obj-$(CONFIG_SUPPORT_POC_FLASH) += ss_dsi_poc_S6E3HA6_AMB577MQ01.o
