# +S96818AA1-1936,shenwenlei.wt,add,2023/07/10,GC7272 Add headphone cable recognition function
ifeq ($(CONFIG_TOUCHSCREEN_GC7272),y)
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/GC7272
endif
# -S96818AA1-1936,shenwenlei.wt,add,2023/07/10,GC7272 Add headphone cable recognition function
obj-$(CONFIG_MTK_ACCDET) := accdet.o

