# SPDX-License-Identifier: GPL-2.0
dtb-y += exynos7904-m30lte_swa_open_00.dtb
dtb-y += exynos7904-m30lte_swa_open_01.dtb
dtb-y += exynos7904-m30lte_swa_open_03.dtb
dtb-y += exynos7904-m30lte_swa_open_04.dtb

always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb*
