# SPDX-License-Identifier: GPL-2.0
dtb-y += exynos7884-j7topelte_usa_00.dtb
dtb-y += exynos7884-j7topelte_usa_01.dtb
dtb-y += exynos7884-j7topelte_usa_05.dtb
dtb-y += exynos7884-j7topelte_usa_06.dtb
dtb-y += exynos7884-j7topelte_usa_07.dtb

always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb*
