# SPDX-License-Identifier: GPL-2.0
dtb-y += exynos8895-dreamlte_kor_05.dtb
dtb-y += exynos8895-dreamlte_kor_07.dtb
dtb-y += exynos8895-dreamlte_kor_09.dtb
dtb-y += exynos8895-dreamlte_kor_10.dtb
dtb-y += exynos8895-dreamlte_kor_11.dtb

always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb*
