#
# Makefile for the Novatek NT36xxx touchscreen driver.
#

# Each configuration option enables a list of files.
# Tab A7 T618 code for SR-AX6189A-01-148 by suyurui at 2021/12/22 start
obj-$(CONFIG_TOUCHSCREEN_NT36XXX_HOSTDL_SPI_OT9) += nt36xxx.o nt36xxx_fw_update.o nt36xxx_ext_proc.o nt36xxx_mp_ctrlram.o nt36xxx_sec_fn.o
# Tab A7 T618 code for SR-AX6189A-01-148 by suyurui at 2021/12/22 start