#
# Makefile for BTS.
#

obj-$(CONFIG_EXYNOS5433_BTS)    += bts-exynos5433.o
obj-$(CONFIG_EXYNOS7420_BTS)    += cal_bts.o bts-exynos7420.o
obj-$(CONFIG_EXYNOS7580_BTS)    += cal_bts_7580.o bts-exynos7580.o
