#
# Makefile for BTS.
#

obj-$(CONFIG_EXYNOS8890_BTS)    += cal_bts8890.o bts-exynos8890.o
obj-$(CONFIG_EXYNOS7870_BTS)    += cal_bts7870.o bts-exynos7870.o
obj-$(CONFIG_EXYNOS7570_BTS)    += cal_bts7570.o bts-exynos7570.o
