#
# Makefile for SAMSUNG Radio driver based s6xx
# FM radio.
#
obj-$(CONFIG_RADIO_S610)	+= fm_s5exxxx.o
fm_s5exxxx-objs		:= radio-s610.o \
				fm_low.o \
				fm_ctrl.o \
				fm_rds.o

obj-$(CONFIG_RADIO_S621)	+= fm_s5exxxx.o
fm_s5exxxx-objs		:= radio-s610.o \
				fm_low.o \
				fm_ctrl.o \
				fm_rds.o