# SPDX-License-Identifier: GPL-2.0-only

ccflags-y += -I$(srctree)/drivers/dma/mediatek

obj-$(CONFIG_DEVICE_MODULES_MTK_UART_APDMA) += mtk-uart-apdma.o
obj-$(CONFIG_DEVICE_MODULES_MTK_CQDMA) += mtk-cqdma.o
