dtb-y += kalamap-v2-dm2q_chn_hkx_w00_r11.dtb
kalamap-v2-dm2q_chn_hkx_w00_r11-dtbs += ../../../vendor/qcom/kalamap-v2.dtb dm2q_chn_hkx_w00_r11.dtbo
dtb-y += kalamap-dm2q_chn_hkx_w00_r11.dtb
kalamap-dm2q_chn_hkx_w00_r11-dtbs += ../../../vendor/qcom/kalamap.dtb dm2q_chn_hkx_w00_r11.dtbo
dtb-y += kalama-v2-dm2q_chn_hkx_w00_r11.dtb
kalama-v2-dm2q_chn_hkx_w00_r11-dtbs += ../../../vendor/qcom/kalama-v2.dtb dm2q_chn_hkx_w00_r11.dtbo
dtb-y += kalama-dm2q_chn_hkx_w00_r11.dtb
kalama-dm2q_chn_hkx_w00_r11-dtbs += ../../../vendor/qcom/kalama.dtb dm2q_chn_hkx_w00_r11.dtbo
kalama-overlays-dtb-y += dm2q_chn_hkx_w00_r11.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
dtb-y += kalamap-v2-dm2q_chn_hkx_w00_r08.dtb
kalamap-v2-dm2q_chn_hkx_w00_r08-dtbs += ../../../vendor/qcom/kalamap-v2.dtb dm2q_chn_hkx_w00_r08.dtbo
dtb-y += kalamap-dm2q_chn_hkx_w00_r08.dtb
kalamap-dm2q_chn_hkx_w00_r08-dtbs += ../../../vendor/qcom/kalamap.dtb dm2q_chn_hkx_w00_r08.dtbo
dtb-y += kalama-v2-dm2q_chn_hkx_w00_r08.dtb
kalama-v2-dm2q_chn_hkx_w00_r08-dtbs += ../../../vendor/qcom/kalama-v2.dtb dm2q_chn_hkx_w00_r08.dtbo
dtb-y += kalama-dm2q_chn_hkx_w00_r08.dtb
kalama-dm2q_chn_hkx_w00_r08-dtbs += ../../../vendor/qcom/kalama.dtb dm2q_chn_hkx_w00_r08.dtbo
kalama-overlays-dtb-y += dm2q_chn_hkx_w00_r08.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
dtb-y += kalamap-v2-dm2q_chn_hkx_w00_r06.dtb
kalamap-v2-dm2q_chn_hkx_w00_r06-dtbs += ../../../vendor/qcom/kalamap-v2.dtb dm2q_chn_hkx_w00_r06.dtbo
dtb-y += kalamap-dm2q_chn_hkx_w00_r06.dtb
kalamap-dm2q_chn_hkx_w00_r06-dtbs += ../../../vendor/qcom/kalamap.dtb dm2q_chn_hkx_w00_r06.dtbo
dtb-y += kalama-v2-dm2q_chn_hkx_w00_r06.dtb
kalama-v2-dm2q_chn_hkx_w00_r06-dtbs += ../../../vendor/qcom/kalama-v2.dtb dm2q_chn_hkx_w00_r06.dtbo
dtb-y += kalama-dm2q_chn_hkx_w00_r06.dtb
kalama-dm2q_chn_hkx_w00_r06-dtbs += ../../../vendor/qcom/kalama.dtb dm2q_chn_hkx_w00_r06.dtbo
kalama-overlays-dtb-y += dm2q_chn_hkx_w00_r06.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
dtb-y += kalamap-v2-dm2q_chn_hkx_w00_r05.dtb
kalamap-v2-dm2q_chn_hkx_w00_r05-dtbs += ../../../vendor/qcom/kalamap-v2.dtb dm2q_chn_hkx_w00_r05.dtbo
dtb-y += kalamap-dm2q_chn_hkx_w00_r05.dtb
kalamap-dm2q_chn_hkx_w00_r05-dtbs += ../../../vendor/qcom/kalamap.dtb dm2q_chn_hkx_w00_r05.dtbo
dtb-y += kalama-v2-dm2q_chn_hkx_w00_r05.dtb
kalama-v2-dm2q_chn_hkx_w00_r05-dtbs += ../../../vendor/qcom/kalama-v2.dtb dm2q_chn_hkx_w00_r05.dtbo
dtb-y += kalama-dm2q_chn_hkx_w00_r05.dtb
kalama-dm2q_chn_hkx_w00_r05-dtbs += ../../../vendor/qcom/kalama.dtb dm2q_chn_hkx_w00_r05.dtbo
kalama-overlays-dtb-y += dm2q_chn_hkx_w00_r05.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
dtb-y += kalamap-v2-dm2q_chn_hkx_w00_r04.dtb
kalamap-v2-dm2q_chn_hkx_w00_r04-dtbs += ../../../vendor/qcom/kalamap-v2.dtb dm2q_chn_hkx_w00_r04.dtbo
dtb-y += kalamap-dm2q_chn_hkx_w00_r04.dtb
kalamap-dm2q_chn_hkx_w00_r04-dtbs += ../../../vendor/qcom/kalamap.dtb dm2q_chn_hkx_w00_r04.dtbo
dtb-y += kalama-v2-dm2q_chn_hkx_w00_r04.dtb
kalama-v2-dm2q_chn_hkx_w00_r04-dtbs += ../../../vendor/qcom/kalama-v2.dtb dm2q_chn_hkx_w00_r04.dtbo
dtb-y += kalama-dm2q_chn_hkx_w00_r04.dtb
kalama-dm2q_chn_hkx_w00_r04-dtbs += ../../../vendor/qcom/kalama.dtb dm2q_chn_hkx_w00_r04.dtbo
kalama-overlays-dtb-y += dm2q_chn_hkx_w00_r04.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
dtb-y += kalamap-v2-dm2q_chn_hkx_w00_r03.dtb
kalamap-v2-dm2q_chn_hkx_w00_r03-dtbs += ../../../vendor/qcom/kalamap-v2.dtb dm2q_chn_hkx_w00_r03.dtbo
dtb-y += kalamap-dm2q_chn_hkx_w00_r03.dtb
kalamap-dm2q_chn_hkx_w00_r03-dtbs += ../../../vendor/qcom/kalamap.dtb dm2q_chn_hkx_w00_r03.dtbo
dtb-y += kalama-v2-dm2q_chn_hkx_w00_r03.dtb
kalama-v2-dm2q_chn_hkx_w00_r03-dtbs += ../../../vendor/qcom/kalama-v2.dtb dm2q_chn_hkx_w00_r03.dtbo
dtb-y += kalama-dm2q_chn_hkx_w00_r03.dtb
kalama-dm2q_chn_hkx_w00_r03-dtbs += ../../../vendor/qcom/kalama.dtb dm2q_chn_hkx_w00_r03.dtbo
kalama-overlays-dtb-y += dm2q_chn_hkx_w00_r03.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
dtb-y += kalamap-v2-dm2q_chn_hkx_w00_r02.dtb
kalamap-v2-dm2q_chn_hkx_w00_r02-dtbs += ../../../vendor/qcom/kalamap-v2.dtb dm2q_chn_hkx_w00_r02.dtbo
dtb-y += kalamap-dm2q_chn_hkx_w00_r02.dtb
kalamap-dm2q_chn_hkx_w00_r02-dtbs += ../../../vendor/qcom/kalamap.dtb dm2q_chn_hkx_w00_r02.dtbo
dtb-y += kalama-v2-dm2q_chn_hkx_w00_r02.dtb
kalama-v2-dm2q_chn_hkx_w00_r02-dtbs += ../../../vendor/qcom/kalama-v2.dtb dm2q_chn_hkx_w00_r02.dtbo
dtb-y += kalama-dm2q_chn_hkx_w00_r02.dtb
kalama-dm2q_chn_hkx_w00_r02-dtbs += ../../../vendor/qcom/kalama.dtb dm2q_chn_hkx_w00_r02.dtbo
kalama-overlays-dtb-y += dm2q_chn_hkx_w00_r02.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
dtb-y += kalamap-v2-dm2q_chn_hkx_w00_r01.dtb
kalamap-v2-dm2q_chn_hkx_w00_r01-dtbs += ../../../vendor/qcom/kalamap-v2.dtb dm2q_chn_hkx_w00_r01.dtbo
dtb-y += kalamap-dm2q_chn_hkx_w00_r01.dtb
kalamap-dm2q_chn_hkx_w00_r01-dtbs += ../../../vendor/qcom/kalamap.dtb dm2q_chn_hkx_w00_r01.dtbo
dtb-y += kalama-v2-dm2q_chn_hkx_w00_r01.dtb
kalama-v2-dm2q_chn_hkx_w00_r01-dtbs += ../../../vendor/qcom/kalama-v2.dtb dm2q_chn_hkx_w00_r01.dtbo
dtb-y += kalama-dm2q_chn_hkx_w00_r01.dtb
kalama-dm2q_chn_hkx_w00_r01-dtbs += ../../../vendor/qcom/kalama.dtb dm2q_chn_hkx_w00_r01.dtbo
kalama-overlays-dtb-y += dm2q_chn_hkx_w00_r01.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
dtb-y += kalamap-v2-dm2q_chn_hkx_w00_r00.dtb
kalamap-v2-dm2q_chn_hkx_w00_r00-dtbs += ../../../vendor/qcom/kalamap-v2.dtb dm2q_chn_hkx_w00_r00.dtbo
dtb-y += kalamap-dm2q_chn_hkx_w00_r00.dtb
kalamap-dm2q_chn_hkx_w00_r00-dtbs += ../../../vendor/qcom/kalamap.dtb dm2q_chn_hkx_w00_r00.dtbo
dtb-y += kalama-v2-dm2q_chn_hkx_w00_r00.dtb
kalama-v2-dm2q_chn_hkx_w00_r00-dtbs += ../../../vendor/qcom/kalama-v2.dtb dm2q_chn_hkx_w00_r00.dtbo
dtb-y += kalama-dm2q_chn_hkx_w00_r00.dtb
kalama-dm2q_chn_hkx_w00_r00-dtbs += ../../../vendor/qcom/kalama.dtb dm2q_chn_hkx_w00_r00.dtbo
kalama-overlays-dtb-y += dm2q_chn_hkx_w00_r00.dtbo # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
kalama-overlays-dtb-y += ../../../vendor/qcom/kalama.dtb ../../../vendor/qcom/kalama-v2.dtb ../../../vendor/qcom/kalamap.dtb ../../../vendor/qcom/kalamap-v2.dtb # ADDED BY LEGO AUTOMATICALLY: DO NOT SUBMIT
# SPDX-License-Identifier: GPL-2.0


# add-overlay defines the target with following naming convention:
# <base>-<board>-dtbs = base.dtb board.dtbo
#
# Combined dtb target is also generated using the fdt_overlay tool.
# dtb-y += <base>-<board>.dtb

add-overlays = $(foreach o,$1,$(foreach b,$2,$(eval $(basename $(notdir $b))-$(basename $o)-dtbs = $b $o) $(basename $(notdir $b))-$(basename $o).dtb))

# kalama-dtb-y is list of DTBs to install when doing non-overlay build
# kalama-overlays-dtb-y is list of DTBs and DTBOs to install when doing overlay-supported build
# see DTB_TYPES from scripts/Makefile.dtbinst and install_dtbs from build.config.msm.com

# KALAMA BASE DTB
#QCOM_DTB := ../../../vendor/qcom
#SEC_KALAMA_BASE_DTB := $(QCOM_DTB)/kalama.dtb $(QCOM_DTB)/kalamap.dtb

# DM2Q
#SEC_DM2Q_BOARDS := \
#	kalama-sec.dm2q.overlay.00.dtbo

#kalama-dtb-$(CONFIG_ARCH_KALAMA) += \
#    $(call add-overlays, $(SEC_DM2Q_BOARDS),$(SEC_KALAMA_BASE_DTB))
#kalama-overlays-dtb-$(CONFIG_ARCH_KALAMA) += $(SEC_DM2Q_BOARDS) $(SEC_KALAMA_BASE_DTB)
#dtb-y += $(kalama-dtb-y)

always-y        := $(dtb-y)
subdir-y        := $(dts-dirs)

clean-files := *.dtb *.reverse.dts *.dtbo
