#
# Makefile for the input misc drivers.
#

# Each configuration option enables a list of files.
#Tab A8 code for AX6300DEV-457 by mayuhang at 2021/9/18 start
obj-$(CONFIG_INPUT_HX9031A) += hx9031a.o
#Tab A8 code for AX6300DEV-457 by mayuhang at 2021/9/18 end
