exynos-drm-kunit-y := dpu_kunit_helper.o
exynos-drm-kunit-$(CONFIG_DRM_SAMSUNG_KUNIT_TEST_DSIM_BIST) +=		\
						dpu_kunit_dsim_bist.o
exynos-drm-kunit-$(CONFIG_DRM_SAMSUNG_KUNIT_TEST_DECON_COLORMAP) +=	\
						dpu_kunit_decon_colormap.o
exynos-drm-kunit-$(CONFIG_DRM_SAMSUNG_KUNIT_TEST_DPU_DMA) +=		\
						dpu_kunit_dma_buf.o
obj-$(CONFIG_DRM_SAMSUNG_KUNIT_TEST) += exynos-drm-kunit.o
