#
# for huaqin sim tray status check
#

# HS03 code for SR-SL6215-01-233 by sunxunou at 2021/08/02 start
obj-$(CONFIG_HQ_SIM_TRAY_CHECK) += sim_tray.o
# HS03 code for SR-SL6215-01-233 by sunxunou at 2021/08/02 emd
