#
# for huaqin sim tray status check
#

# Huaqin add for ZQL1830-235 by liunianliang at 2018/07/05 start
obj-$(CONFIG_HQ_SIM_TRAY_CHECK) += sim_tray.o
# Huaqin add for ZQL1830-235 by liunianliang at 2018/07/05 end
