
obj-$(CONFIG_SENSORS_CORE)		+= sensors_core.o
obj-$(CONFIG_SENSORS_GP2A002S)	+= gp2a.o
obj-$(CONFIG_SENSORS_GP2A030)		+= gp2ap030.o
obj-$(CONFIG_SENSORS_BMA2X2)	+= bma2x2_driver.o bst_sensor_common.o      
obj-$(CONFIG_SENSORS_BMM050)	+= bmm050_driver.o bmm050.o

