obj-y   +=  tpd_control.o
obj-y   +=  tpd_button.o
obj-y   +=  tpd_debug.o
obj-y   +=  tpd_default.o
obj-y   +=  tpd_misc.o
obj-y   +=  tpd_setting.o

obj-$(CONFIG_TOUCHSCREEN_ILI7806S_TOUCH) += ilitek_touch/
obj-$(CONFIG_TOUCHSCREEN_CHIPONE) += chipone/
obj-$(CONFIG_TOUCHSCREEN_JADARD_CHIPSET) += jdchipset/
obj-$(CONFIG_TOUCHSCREEN_NT36xxx_HOSTDL_SPI) += novatek_touch/
obj-$(CONFIG_TOUCHSCREEN_FTS) += focaltech_touch_ax3565/
obj-$(CONFIG_TOUCHSCREEN_HIMAX_OT8) += hxchipset_ot8/
obj-$(CONFIG_TOUCHSCREEN_HIMAX_CHIPSET) += hxchipset/
#hs03s_NM code for SR-AL5625-01-644 by fengzhigang at 20220414 start
obj-$(CONFIG_TOUCHSCREEN_GALAXYCORE_CHIPSET) += galaxycore/
#hs03s_NM code for SR-AL5625-01-644 by fengzhigang at 20220414 end
# hs04 code for SR-AL6398A-01-178 by huangzhongjie at 2022/07/07 start
obj-$(CONFIG_TOUCHSCREEN_JADARD_CHIPSET_M04) += M04/jdchipset/
obj-$(CONFIG_TOUCHSCREEN_GALAXYCORE_CHIPSET_M04) += M04/galaxycore/
# hs04 code for SR-AL6398A-01-178 by huangzhongjie at 2022/07/07 end
# hs04 code for SR-AL6398A-01-664 by hehaoran5 at 2022/07/13 start
obj-$(CONFIG_TOUCHSCREEN_CHIPONE_CHIPSET_M04) += M04/chipone/
# hs04 code for SR-AL6398A-01-664 by hehaoran5 at 2022/07/13 end