subdir-ccflags-y += -I$(src)
# ========== SharkL/TSharkL configuration begin ===========
#ifeq ($(CONFIG_FB_SCX35L), y)
obj-y := sprd_interface.o sprd_dispc.o
obj-y += sprd_dsi.o sprd_mipi.o
obj-y += sprd_main.o
obj-y += lcd_mipi_driver.o
#endif

#obj-$(CONFIG_FB_SCX35L) += dsi_1_21a/
#obj-$(CONFIG_FB_SCX35L) += shark/
obj-y += dsi_1_21a/
obj-y += shark/
# ========== SharkL/TSharkL configuration end ============

# This file is used for creating file node


