#
# for huaqin misc info
#
# Tab A9 code for SR-AX6739A-01-348 by Niebingling at 20230506 start
obj-$(CONFIG_HQ_SIM_TRAY_CHECK) += sim_tray.o
# Tab A9 code for SR-AX6739A-01-348 by Niebingling at 20230506 end